VermilionCity_House1_MapScripts::
	.byte 0

VermilionCity_House1_EventScript_Fisher::
	msgbox VermilionCity_House1_Text_FishingDude, MSGBOX_NPC
	end
VermilionCity_House1_EventScript_Photo::
	msgbox VermilionCity_House1_Text_Photo, MSGBOX_NPC
	end
VermilionCity_House1_Text_FishingDude:
	.string "Je suis le\n"
	.string "PÊCHEUR\p"
	.string "DUDE, l'aîné\n"
	.string "des FRÈRES\p"
	.string "PÊCHEURS.\n"
	.string "As-tu rencontré le\p"
	.string "GURU DE LA PÊCHE à\n"
	.string "LAC COLÈRE ?\p"
	.string "Il est un maître\n"
	.string "pêcheur !$"

VermilionCity_House1_Text_Photo:
	.string "C'est une photo de gens qui pêchent…\p"
	.string "Ils passent un bon moment…$"
