OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "Quand un combat POKéMON commence, celui à\n"
	.string "gauche de la liste sort en\p"
	.string "premier. Alors, quand tu as plus\n"
	.string "de POKéMON dans ton équipe, essaie\l"
	.string "de changer l'ordre de tes POKéMON.\p"
	.string "Ça pourrait te donner un avantage.$"

