SafariZoneGate_MapScripts::
	.byte 0

SafariZoneGate_EventScript_Trigger::
	setflag FLAG_VISITED_SAFARI_ZONE_GATE
	setvar VAR_SAFARI_ZONE_GATE_STATE, 3
	end

SafariZoneGate_EventScript_BackupTrigger::
	setflag FLAG_VISITED_SAFARI_ZONE_GATE
	setvar VAR_TEMP_0, 1
	end

SafariZoneGate_EventScript_WorkerM::
	lock
	faceplayer
	msgbox SafariZone_Text_ForeignFeeling, MSGBOX_DEFAULT
	closemessage
	release
	end

SafariZoneGate_EventScript_Silent::
	lock
	faceplayer
	msgbox SafariZone_Text_SilentNPC, MSGBOX_DEFAULT
	closemessage
	release
	end

SafariZoneGate_EventScript_Kangaskhan::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_KANGASKHAN, CRY_MODE_NORMAL
	msgbox SafariZone_Text_Kangaskhan, MSGBOX_DEFAULT
	waitmoncry
	release
	end

SafariZoneGate_EventScript_Engineer::
	lock
	faceplayer
	msgbox SafariZone_Text_JigglypuffTrainer, MSGBOX_DEFAULT
	closemessage
	release
	end

SafariZoneGate_EventScript_Girl::
	lock
	faceplayer
	msgbox SafariZone_Text_FirstCatch, MSGBOX_DEFAULT
	closemessage
	release
	end

SafariZoneGate_EventScript_SlowpokeLady::
	lock
	faceplayer
	msgbox SafariZone_Text_SlowpokeFan, MSGBOX_DEFAULT
	closemessage
	release
	end


SafariZone_Text_ForeignFeeling:
	.string "PARC SAFARI...\n"
	.string "On se croirait dans un pays\l"
	.string "étranger.\p"
	.string "Ça suscite un sentiment étrange.$"

SafariZone_Text_SilentNPC:
	.string "..................\p"
	.string "(Je ne suis pas bavard.)$"

SafariZone_Text_Kangaskhan:
	.string "KANGOUREX : ..................$"

SafariZone_Text_JigglypuffTrainer:
	.string "Ce PARC SAFARI est génial !\n"
	.string "Je n'ai fait que courir après des POKéMON !\p"
	.string "Ça a contrarié mon RONDOUDOU, par contre.$"

SafariZone_Text_FirstCatch:
	.string "J'ai toujours voulu attraper mon premier\n"
	.string "POKéMON à la ZONE SAFARI.$"

SafariZone_Text_SlowpokeFan:
	.string "Il y a plein de POKéMON au choix,\n"
	.string "mais rien ne bat la mignonnerie du\l"
	.string "RAMOLOSS.\p"
	.string "On me dit souvent que je lui ressemble !$"

SafariZone_Text_CustomSystem:
	.string "Tu pourrais penser qu'il existe\n"
	.string "un système sophistiqué pour\l"
	.string "personnaliser le PARC SAFARI, non ?\p"
	.string "La vraie vérité, c'est que…$"

SafariZone_Text_Sign:
	.string "PARC SAFARI\n"
	.string "Ici, tout est palpitant.\p"
	.string "N'hésitez pas à venir vivre\n"
	.string "l'aventure sauvage !$"


SafariZoneGate_EventScript_IncenseClerk::
	goto_if_set FLAG_FINITE_TMS, SafariZoneGate_EventScript_IncenseClerkFinite
	lock
	faceplayer
	message gText_HowMayIServeYou
	waitmessage
	pokemart SafariZoneGate_Pokemart_Incenses
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	release
	end

	.align 2
SafariZoneGate_Pokemart_Incenses:
	.2byte ITEM_SEA_INCENSE
	.2byte ITEM_LAX_INCENSE
	.2byte ITEM_NONE
	release
	end


SafariZoneGate_EventScript_IncenseClerkFinite::
	lock
	faceplayer
	message gText_HowMayIServeYou
	waitmessage
	pokemart SafariZoneGate_Pokemart_Incenses2
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	release
	end

	.align 2
SafariZoneGate_Pokemart_Incenses2:
	.2byte ITEM_TM_HIDDEN_POWER
	.2byte ITEM_TM_SECRET_POWER
	.2byte ITEM_SEA_INCENSE
	.2byte ITEM_LAX_INCENSE
	.2byte ITEM_NONE
	release
	end

SafariZoneGate_EventScript_VitaminGuru::
	lock
	faceplayer
	message SafariZoneGate_Text_VitaminGuruSellWhatYouNeed
	waitmessage
	pokemart SafariZoneGate_Pokemart_VitaminGuru
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	release
	end

	.align 2
SafariZoneGate_Pokemart_VitaminGuru:
	.2byte ITEM_PROTEIN
	.2byte ITEM_IRON
	.2byte ITEM_CARBOS
	.2byte ITEM_ZINC
	.2byte ITEM_CALCIUM
	.2byte ITEM_HP_UP
	.2byte ITEM_NONE
	release
	end


SafariZoneGate_Text_VitaminGuruSellWhatYouNeed:
	.string "Je suis le GOURU DE L'ÉNERGIE ! Je vais tout donner\n"
	.string "et te vendre ce dont tu as besoin !$"

