BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
	.string "Ce dont un DRESSEUR\p"
	.string "a besoin… La connaissance…\n"
	.string "La stratégie… La chance…\l"
	.string "Le cran… L'esprit… Le\l"
	.string "courage… Et l'habileté… Eh\l"
	.string "bien, je suis prêt\l"
	.string "sur tous les plans\l"
	.string "! Je serai imbattable\p"
	.string "dans chaque bâtiment\n"
	.string "! Hein ?\p"
	.string "Les POKéMON ?\n"
	.string "C'est quoi ?$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
	.string "Tu connais les AS DU\n"
	.string "PARADIS ?\p"
	.string "C'est comme ça que SCOTT appelle les sept\n"
	.string "DRESSEURS spéciaux qui dirigent les sept\l"
	.string "installations de la ZONE DE COMBAT.$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
	.string "À la TOUR DE COMBAT, une fille\n"
	.string "plus âgée m'a dit que j'avais beaucoup\l"
	.string "de talent pour les combats ! J'aime\p"
	.string "plus les CONCOURS POKéMON ! Mais je\p"
	.string "ne suis pas douée aux CONCOURS\p"
	.string "! Avoir du talent et aimer\n"
	.string "quelque chose, ce n'est pas pareil.$"

