FortreeCity_House3_MapScripts::
	.byte 0

FortreeCity_House3_EventScript_Maniac::
	msgbox FortreeCity_House3_Text_MetStevenHadAmazingPokemon, MSGBOX_NPC
	end

FortreeCity_House3_EventScript_SchoolKidM::
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
	end

FortreeCity_House3_Text_MetStevenHadAmazingPokemon:
	.string "En parlant de POKéDEX,\n"
	.string "je me suis souvenu\p"
	.string "de quelque chose.\n"
	.string "J'ai rencontré ce\p"
	.string "DRESSEUR, PIERRE, quand\n"
	.string "je cherchais des\p"
	.string "pierres rares.\n"
	.string "Il est vraiment passionné\p"
	.string "par les minéraux.\n"
	.string "Un type intéressant !$"

FortreeCity_House3_Text_OhYouHavePokedex:
	.string "C'est quoi cet objet que tu as là ?\p"
	.string "… … … … … …\p"
	.string "Oh, ça s'appelle un POKéDEX ?\n"
	.string "C'est vraiment génial !$"

