FuchsiaCity_House1_MapScripts::
	.byte 0

FuchsiaCity_House1_EventScript_BillsOlderSister::
	msgbox FuchsiaCity_House1_Text_BillsOlderSister, MSGBOX_NPC
	end

FuchsiaCity_House1_EventScript_Youngster::
	msgbox FuchsiaCity_House1_Text_Youngster, MSGBOX_NPC
	end

FuchsiaCity_House1_Text_BillsOlderSister:
	.string "Mon grand-père est chez mon frère BILL\n"
	.string "sur le CAP BRUN.$"

FuchsiaCity_House1_Text_Youngster:
	.string "J'ai vu ces POKéMON bizarres et lents\n"
	.string "sur la PISTE CYCLABLE.$"

