AquaHideout_UnusedRubyMap3_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, AquaHideout_UnusedRubyMap3_OnTransition
	.byte 0

AquaHideout_UnusedRubyMap3_OnTransition::
	end

AquaHideout_UnusedRubyMap3_BonslyMunchEvo::
	msgbox AquaHideout_UnusedRubyMap3_BonslyMunchEvo_Text, MSGBOX_NPC
	end

AquaHideout_UnusedRubyMap3_BonslyMunchEvo_Text:
	.string "Tu as vu ces étranges arbres qui bougent ?\n"
	.string "Ce sont des POKéMON nommés\l"
	.string "SIMULARBRE ! Tu le savais ?\p"
	.string "C'est un POKéMON qui se déguise\n"
	.string "en petit arbre.\p"
	.string "Et il y a aussi MANZAI, qui fait\n"
	.string "la même chose… mais n'a pas l'air aussi\l"
	.string "réaliste, je crois.\p"
	.string "D'ailleurs, je les ai vus évoluer\n"
	.string "en essayant d'imiter d'autres SIMULARBRE.\p"
	.string "C'est comme ça qu'ils évoluent ?\p"
	.string "Si je ne me trompe pas, MIME JR. évolue\n"
	.string "aussi en IMITANT d'autres POKéMON.\p"
	.string "Très différent de mon LOUDMINI, qui\n"
	.string "a évolué par AMITIÉ, tu ne trouves pas ?$"
