gText_ApprenticeChallenge0::
	.string "Euh… Je suis l'apprenti nº {STR_VAR_2} de {STR_VAR_1}.\n"
	.string "Snif… Cette tension me gagne…$"

gText_ApprenticeChallenge1::
	.string "Je suis l'apprenti n° {STR_VAR_2} de {STR_VAR_1} !\n"
	.string "Nous voilà !$"

gText_ApprenticeChallenge2::
	.string "Je suis l'apprenti no {STR_VAR_2} de {STR_VAR_1} !\n"
	.string "Accepte mon défi !$"

gText_ApprenticeChallenge3::
	.string "Euh… Je suis l'apprenti nº {STR_VAR_2} de {STR_VAR_1}…\n"
	.string "Tu crois que quelqu'un comme moi peut gagner ?$"

gText_ApprenticeChallenge4::
	.string "Je suis l'apprenti no {STR_VAR_2} de {STR_VAR_1} !\n"
	.string "Je te laisse me défier !$"

gText_ApprenticeChallenge5::
	.string "Je suis terriblement occupé, mais je suis\n"
	.string "le n° {STR_VAR_2} apprenti de {STR_VAR_1}.$"

gText_ApprenticeChallenge6::
	.string "Je suis le n° {STR_VAR_2} apprenti de {STR_VAR_1}.\n"
	.string "Enchanté !$"

gText_ApprenticeChallenge7::
	.string "Je suis l'apprenti n° {STR_VAR_2} de {STR_VAR_1}.\n"
	.string "Puis-je commencer ?$"

gText_ApprenticeChallenge8::
	.string "Aïe ! Je suis le n° {STR_VAR_2} apprenti de {STR_VAR_1} !\n"
	.string "Je ferai de mon mieux !$"

gText_ApprenticeChallenge9::
	.string "Yeehaw ! Je suis le n° {STR_VAR_2} apprenti de {STR_VAR_1} !\n"
	.string "Aux armes !$"

gText_ApprenticeChallenge10::
	.string "Je suis le 1 000e apprenti de {STR_VAR_1} !\n"
	.string "En fait, je suis le n° {STR_VAR_2} ! C'est parti !$"

gText_ApprenticeChallenge11::
	.string "Ouais, je suis le n° {STR_VAR_2} apprenti de {STR_VAR_1} !\n"
	.string "On va tout déchirer !$"

gText_ApprenticeChallenge12::
	.string "Youpi-youhou ! Je suis ce qu'on appelle\n"
	.string "l'apprenti no {STR_VAR_2} de {STR_VAR_1} !$"

gText_ApprenticeChallenge13::
	.string "Toux ! Je suis le n° {STR_VAR_2} apprenti de {STR_VAR_1}.\n"
	.string "Ravi de te rencontrer ! Toux !$"

gText_ApprenticeChallenge14::
	.string "C'est stressant…\n"
	.string "Je suis l'apprenti no {STR_VAR_2} de {STR_VAR_1}.$"

gText_ApprenticeChallenge15::
	.string "Je suis le n° {STR_VAR_2} apprenti de {STR_VAR_1},\n"
	.string "et ce n'est pas un mensonge.$"

gText_ApprenticePleaseTeach0::
	.string "Tu es… {PLAYER} ?\n"
	.string "Oh ! Snif…\p"
	.string "sanglote…\n"
	.string "Oh ! P-pardon…\p"
	.string "Je suis si nerveux,\n"
	.string "je ne peux\p"
	.string "pas m'empêcher\n"
	.string "de pleurer…\p"
	.string "Je suis {STR_VAR_1}.\n"
	.string "Aide-moi, {PLAYER} !$"

gText_ApprenticeRejectTeaching0::
	.string "Oh… M-mais…\n"
	.string "Snif… Waaaaaaah !\p"
	.string "S'il te plaît !\n"
	.string "Je t'en supplie, s'il te plaît !$"

gText_ApprenticeWhichLevelMode0::
	.string "Oh, vraiment ?\n"
	.string "Tu veux bien\p"
	.string "? Génial !\n"
	.string "Formidable ! Awoooh\p"
	.string "! Oh… Je\n"
	.string "suis désolé… Je\p"
	.string "suis si heureux\n"
	.string "que je pleure…$"

gText_ApprenticeLevelModeThanks0::
	.string "{STR_VAR_1} ?\n"
	.string "Waaaaah !\p"
	.string "Oh ! Je suis désolé !\n"
	.string "Tu m'as rendu heureux en choisissant\l"
	.string "le niveau pour moi, et ça m'a fait pleurer…\p"
	.string "Snif…\n"
	.string "Merci beaucoup !\l"
	.string "Parle-moi encore !$"

gText_ApprenticePleaseTeach1::
	.string "Waouh ! Tu es\n"
	.string "{PLAYER}, n'est-ce pas ?\p"
	.string "Tu es terriblement fort,\n"
	.string "non ? Je suis\p"
	.string "{STR_VAR_1} ! Enchanté !\n"
	.string "Tu veux te battre\l"
	.string "avec moi ?$"

gText_ApprenticeRejectTeaching1::
	.string "Pourquoi ?\n"
	.string "Oh, s'il te plaît ? Je t'en supplie ?\l"
	.string "Sois mon professeur, je t'en prie !$"

gText_ApprenticeWhichLevelMode1::
	.string "Youpi ! Génial !\p"
	.string "La première chose que je voulais te demander\n"
	.string "concerne la TOUR DE COMBAT !\p"
	.string "Les salles NORMAL et DIFFICILE…\n"
	.string "Laquelle serait parfaite pour moi ?$"

gText_ApprenticeLevelModeThanks1::
	.string "{STR_VAR_1}, hein ? C'est vrai !\n"
	.string "Je vais faire de mon mieux\p"
	.string "! Si on se recroise ici,\n"
	.string "apprends-moi autre chose, professeur !$"

gText_ApprenticePleaseTeach2::
	.string "Euh… Tu es {PLAYER} ? Je\n"
	.string "m'appelle {STR_VAR_1}. Je veux devenir DRESSEUR\p"
	.string "POKéMON, mais je ne sais pas\n"
	.string "quoi faire… Alors j'ai pensé te\p"
	.string "demander conseil parce que tu\n"
	.string "es si célèbre. {PLAYER}, pourrais-tu\p"
	.string "me donner des conseils ?$"

gText_ApprenticeRejectTeaching2::
	.string "Oh, mais…\p"
	.string "Je veux vraiment devenir un DRESSEUR\n"
	.string "de POKéMON !\p"
	.string "S'il te plaît, peux-tu répondre à mes questions ?$"

gText_ApprenticeWhichLevelMode2::
	.string "Merci !\n"
	.string "Voici ma première question tout de suite !\p"
	.string "La TOUR DE COMBAT a deux niveaux,\n"
	.string "NORMAL et DIFFICILE, n'est-ce pas ?\p"
	.string "Quel niveau penses-tu qui me\n"
	.string "convient le mieux ?$"

gText_ApprenticeLevelModeThanks2::
	.string "Oh, le défi {STR_VAR_1} ?\n"
	.string "Compris ! Si j'ai une\p"
	.string "autre question, je reviendrai ici\n"
	.string "pour tes conseils !$"

gText_ApprenticePleaseTeach3::
	.string "Oh ? Hein ? Tu es…\n"
	.string "Non, ce n'est pas possible.\p"
	.string "Il n'y a aucune chance que quelqu'un\n"
	.string "comme moi puisse rencontrer {PLAYER}.\p"
	.string "…Tu es vraiment {PLAYER} ?\n"
	.string "Je n'arrive pas à croire que je te parle !\p"
	.string "Quand quelque chose d'aussi bien arrive,\n"
	.string "seulement des choses terribles vont m'arriver\l"
	.string "maintenant, j'en suis sûr…\p"
	.string "…Je suis désolé…\n"
	.string "Je suis… {STR_VAR_1}…\p"
	.string "Il n'y a rien de spécial chez moi\n"
	.string "dont je puisse être fier…\p"
	.string "Je ne devrais même pas parler de\n"
	.string "moi car tu vas oublier…\p"
	.string "J'avais ce rêve que si je te rencontrais\n"
	.string "jamais, {PLAYER}, peut-être que je pourrais te\l"
	.string "demander des conseils en tant que DRESSEUR.\p"
	.string "Mais je ne pense pas que tu\n"
	.string "accepterais.\p"
	.string "…Ou seras-tu assez gentil pour me\n"
	.string "donner des conseils ?$"

gText_ApprenticeRejectTeaching3::
	.string "Je le savais…\p"
	.string "Ça devait arriver\n"
	.string "parce que je suis\p"
	.string "un vrai nobody\n"
	.string "ennuyeux…\p"
	.string "Mais j'ai pensé\n"
	.string "que peut-être…\p"
	.string "{PLAYER}{KUN},\n"
	.string "merci quand même.$"

gText_ApprenticeWhichLevelMode3::
	.string "Vraiment ? Je n'arrive\n"
	.string "pas à y croire !\l"
	.string "Je n'arrive\p"
	.string "pas à croire\n"
	.string "que tu vas me\p"
	.string "conseiller !\n"
	.string "Je… Je suis si heureux…\p"
	.string "Que devrais-je demander\n"
	.string "à mon {STR_VAR_1} ?$"

gText_ApprenticeLevelModeThanks3::
	.string "{STR_VAR_1} ? D'accord !\n"
	.string "Mais tu crois vraiment\l"
	.string "que quelqu'un comme moi\p"
	.string "aurait une chance ?\n"
	.string "Je vais essayer\p"
	.string "quand même !\n"
	.string "Merci, {PLAYER}{KUN} !$"

gText_ApprenticePleaseTeach4::
	.string "Oh ! Tu es\p"
	.string "{PLAYER}{KUN},\n"
	.string "n'est-ce pas ?\p"
	.string "J'ai entendu que\n"
	.string "tu es fort en\p"
	.string "POKéMON !\p"
	.string "Je suis {STR_VAR_1} !\n"
	.string "Je serai ton ami !\l"
	.string "{PLAYER}{KUN},\p"
	.string "donne-moi un\n"
	.string "conseil !$"

gText_ApprenticeRejectTeaching4::
	.string "Hein ? Pourquoi tu refuses ?\n"
	.string "C'est moi qui te demande !\l"
	.string "Tu dois y réfléchir !$"

gText_ApprenticeWhichLevelMode4::
	.string "OK, il y a un truc.\n"
	.string "Je veux que tu décides pour moi.\p"
	.string "Tu sais que la TOUR DE COMBAT a\n"
	.string "des salles NORMAL et DIFFICILE ?\p"
	.string "Laquelle tu crois qui me conviendrait,\n"
	.string "{PLAYER}{KUN} ?$"

gText_ApprenticeLevelModeThanks4::
	.string "OK, {STR_VAR_1} me convient ?\n"
	.string "Merci !\p"
	.string "Sachant que c'est toi qui as décidé,\n"
	.string "{PLAYER}{KUN}, je ne serai pas trop déçu si\l"
	.string "je perds.\p"
	.string "OK, je compterai encore sur tes conseils.\n"
	.string "Salut !$"

gText_ApprenticePleaseTeach5::
	.string "Oh, salut ! {PLAYER}{KUN} !\n"
	.string "Je te connais parce que tu es célèbre !\l"
	.string "Appelle-moi {STR_VAR_1} ! Enchanté !\p"
	.string "Je suis TRIATHLÈTE, alors je reste en forme\n"
	.string "même en élevant des POKéMON.\p"
	.string "Je suis aussi impliqué dans d'autres choses\n"
	.string "comme le travail, les siestes, la danse de salon…\p"
	.string "Être aussi occupé, ce n'est pas si facile pour\n"
	.string "moi de devenir un bon DRESSEUR.\p"
	.string "Alors, j'ai une proposition !\p"
	.string "Il doit y avoir une raison pour laquelle on s'est rencontrés.\n"
	.string "Alors, {PLAYER}{KUN}, que dirais-tu de partager ta\l"
	.string "sagesse avec moi de temps en temps ?$"

gText_ApprenticeRejectTeaching5::
	.string "Oh, mais s'il te plaît ?\n"
	.string "Un type comme moi a besoin de quelqu'un\l"
	.string "comme toi, {PLAYER}{KUN} !\p"
	.string "Honnêtement, j'ai besoin de tes conseils !$"

gText_ApprenticeWhichLevelMode5::
	.string "Merci ! C'est plus comme ça\n"
	.string "! Alors, commençons par une\p"
	.string "facile ! Tu connais les\n"
	.string "deux parcours de la TOUR\l"
	.string "DE COMBAT, non ? NORMAL\p"
	.string "et DIFFICILE. Moi qui suis\n"
	.string "occupé, lequel devrais-je choisir ?$"

gText_ApprenticeLevelModeThanks5::
	.string "{STR_VAR_1}, hein ? OK, j'ai compris.\n"
	.string "Je trouverai le temps et je tenterai !\p"
	.string "…Oups, je ferais mieux d'aller travailler !\n"
	.string "Merci ! À bientôt !$"

gText_ApprenticePleaseTeach6::
	.string "Pas possible ! Uh-uh !\n"
	.string "Tu es peut-être le vrai {PLAYER} ?\p"
	.string "A-hah ! Génial ! Je suis {STR_VAR_1},\n"
	.string "ravi de te rencontrer !\p"
	.string "{PLAYER}, tu es très fort,\n"
	.string "n'est-ce pas ?\p"
	.string "Tout le monde parle de toi !\p"
	.string "Oh ! Je viens d'avoir une super idée !\n"
	.string "Je vais demander des conseils, {PLAYER} !\l"
	.string "Je suis sûr que ça me rendra plus fort !\p"
	.string "C'est pas une super idée ?\n"
	.string "S'il te plaît, je veux ton conseil !$"

gText_ApprenticeRejectTeaching6::
	.string "Ahahaha, tu peux faire semblant d'être méchant,\n"
	.string "mais tu ne me trompes pas !\l"
	.string "Tu es sympa au fond, n'est-ce pas ?$"

gText_ApprenticeWhichLevelMode6::
	.string "Yay ! Je\n"
	.string "savais que tu\p"
	.string "aurais un grand cœur,\n"
	.string "{PLAYER} !\p"
	.string "Que devrais-je te\n"
	.string "demander en premier ?\p"
	.string "…Oh, j'ai pensé\n"
	.string "à quelque chose !\p"
	.string "Quelle capacité pour\n"
	.string "mon {STR_VAR_1} ?$"

gText_ApprenticeLevelModeThanks6::
	.string "Oh-oh-oh !\n"
	.string "{STR_VAR_1}, tu dis !\l"
	.string "Merci pour une réponse vraiment cool !\p"
	.string "Je crois que c'est à peu près tout ce que je voulais\n"
	.string "te demander aujourd'hui.\p"
	.string "On se retrouve ici, d'accord ?\n"
	.string "Merci !$"

gText_ApprenticePleaseTeach7::
	.string "Je vous demande\n"
	.string "pardon, mais…\p"
	.string "Êtes-vous\n"
	.string "{PLAYER} ?\p"
	.string "Je suis\n"
	.string "{STR_VAR_1},\p"
	.string "et je suis\p"
	.string "ravi de\n"
	.string "faire votre\p"
	.string "connaissance,\n"
	.string "{PLAYER}{KUN} !$"

gText_ApprenticeRejectTeaching7::
	.string "Oh… !\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "…Je dois m'être évanoui de choc.\n"
	.string "Je suis désolé, j'ai dû mal entendre.\p"
	.string "S'il te plaît ! Dis que tu\n"
	.string "m'accepteras comme apprenti !$"

gText_ApprenticeWhichLevelMode7::
	.string "Oh… Je suis ravie ! Je\p"
	.string "ne veux pas te faire perdre\n"
	.string "ton temps, alors conseille-moi sur ceci.\p"
	.string "Je prévois de relever bientôt le\n"
	.string "défi de la TOUR DE COMBAT.\p"
	.string "Cependant, il y a deux niveaux…\p"
	.string "Lequel me conviendrait le mieux\n"
	.string "? NORMAL ou DIFFICILE ?$"

gText_ApprenticeLevelModeThanks7::
	.string "{STR_VAR_1}, c'est ton choix !\n"
	.string "Je vois. Je vais faire de mon mieux !\p"
	.string "Merci, {PLAYER}.\n"
	.string "J'espère pouvoir encore compter sur toi.\l"
	.string "Prends soin de toi !$"

gText_ApprenticePleaseTeach8::
	.string "Eek ! Eek !\n"
	.string "{PLAYER} !\l"
	.string "Tu m'as parlé !\p"
	.string "Je… Je suis\n"
	.string "comblée de joie !\p"
	.string "Moi ! Je m'appelle\n"
	.string "{STR_VAR_1} !\p"
	.string "Je viens de\n"
	.string "devenir DRESSEUR !\p"
	.string "Je suis ravie de te\n"
	.string "rencontrer, {PLAYER} !$"

gText_ApprenticeRejectTeaching8::
	.string "Waaaah !\n"
	.string "{PLAYER} m'a refusé…\l"
	.string "C'est… C'est une expérience inestimable !\p"
	.string "{PLAYER}, s'il te plaît ! Je veux entendre\n"
	.string "une réponse affirmative cette fois !\p"
	.string "Je t'en supplie, guide-moi !$"

gText_ApprenticeWhichLevelMode8::
	.string "Hieeeeh ! {PLAYER} a dit oui\n"
	.string "! {PLAYER} a dit oui !\p"
	.string "Je ne pourrai pas dormir ce\n"
	.string "soir… Merci infiniment ! Alors, voici\p"
	.string "ma question ! À la TOUR\p"
	.string "DE COMBAT, qu'est-ce qui me\n"
	.string "convient, NORMAL ou DIFFICILE ?$"

gText_ApprenticeLevelModeThanks8::
	.string "{STR_VAR_1} ! Parfaitement compris !\n"
	.string "Je comprends parfaitement !\l"
	.string "Je suis follement ravi !\p"
	.string "J'espère que tu voudras bien m'apprendre\n"
	.string "encore d'autres choses une autre fois.$"

gText_ApprenticePleaseTeach9::
	.string "Waouh ! Tu pourrais être…\n"
	.string "Serait-ce… {PLAYER}{KUN} ?!\l"
	.string "Ce DRESSEUR si fort et célèbre ?\l"
	.string "Eh bien, bonjour, ne suis-je pas le plus chanceux !\p"
	.string "Bonjour, je m'appelle {STR_VAR_1} !\p"
	.string "Je suis à la recherche\n"
	.string "d'un professeur POKéMON.\p"
	.string "Et avec un timing impeccablement bon,\n"
	.string "voilà que tu arrives, {PLAYER}{KUN} !\p"
	.string "Alors, voilà, {PLAYER}{KUN} !\n"
	.string "Laisse-moi devenir ton apprenti !$"

gText_ApprenticeRejectTeaching9::
	.string "Gwaaaah !\n"
	.string "Tu es vraiment cool et coriace…\p"
	.string "Ne sois pas comme ça, s'il te plaît.\n"
	.string "Je t'en supplie !$"

gText_ApprenticeWhichLevelMode9::
	.string "Oh, oui ! C'est une solide réponse !\n"
	.string "Excellente, je dirais !\p"
	.string "Alors, un premier conseil\n"
	.string "sur la TOUR DE COMBAT ?\p"
	.string "Si j'y allais, qu'est-ce qui serait mieux ?\n"
	.string "NORMAL ou DIFFICILE ?$"

gText_ApprenticeLevelModeThanks9::
	.string "Ah oui, {STR_VAR_1}, c'est ça !\n"
	.string "OK, nickel !\l"
	.string "Je vais montrer ce que je vaux, genre !\p"
	.string "D'accord, je te prends comme mentor !\n"
	.string "Adios !$"

gText_ApprenticePleaseTeach10::
	.string "Oh, hé, {PLAYER}{KUN},\n"
	.string "c'est ça ?\p"
	.string "La police te cherchait !\n"
	.string "… … …\p"
	.string "Bien sûr je mens !\n"
	.string "Moi, je suis {STR_VAR_1}.\l"
	.string "Malgré mon apparence,\p"
	.string "je suis un\n"
	.string "DRESSEUR sérieux !\p"
	.string "{PLAYER}{KUN},\n"
	.string "donne-moi un conseil !$"

gText_ApprenticeRejectTeaching10::
	.string "Si tu vas être aussi froid,\n"
	.string "je vais te montrer ce que je sais faire !\p"
	.string "Ouah ! Ouah ! Ouah !\n"
	.string "Hic !\p"
	.string "Hahaha, c'était mes FAUSSES LARMES !\p"
	.string "Allez, tu veux bien être\n"
	.string "mon maître POKéMON ?$"

gText_ApprenticeWhichLevelMode10::
	.string "Yippee !\n"
	.string "Je t'achèterai un\p"
	.string "bateau pour ça !\n"
	.string "Bien sûr je\p"
	.string "mens encore !\n"
	.string "Mais… Merci,\p"
	.string "maître !\n"
	.string "Tu es le meilleur,\p"
	.string "{PLAYER}{KUN} !$"

gText_ApprenticeLevelModeThanks10::
	.string "OK, donc {STR_VAR_1} est mieux !\n"
	.string "Je vais à l'autre niveau, alors !\p"
	.string "Je plaisante !\n"
	.string "J'obéirai à ton enseignement, maître !\p"
	.string "Merci, maître !\n"
	.string "J'espère que tu continueras à m'enseigner !$"

gText_ApprenticePleaseTeach11::
	.string "A-H-O-Y !\n"
	.string "Et ça fait ahoy, et ça veut dire salut !\p"
	.string "Je suis {STR_VAR_1}, le MARIN qui rappe\n"
	.string "c'est moi !\p"
	.string "À ton tour, parle-moi un peu de\n"
	.string "toi, essaie !\p"
	.string "Uh-huh, uh-huh !\n"
	.string "{PLAYER}{KUN}, c'est ton nom,\l"
	.string "et les POKéMON, c'est ton jeu !\p"
	.string "Et tu es à un âge délicat\n"
	.string "où le monde entier est ta scène !\p"
	.string "Bref, je veux juste dire,\n"
	.string "que tu es le dixième DRESSEUR\l"
	.string "à qui je parle aujourd'hui.\p"
	.string "Faisons-en une célébration !\n"
	.string "Deviens mon mentor pour commémorer !$"

gText_ApprenticeRejectTeaching11::
	.string "Mais !\n"
	.string "Tu dois travailler avec moi !\p"
	.string "Ne fais pas le difficile !\n"
	.string "Deviens mon mentor, s'il te plaît !$"

gText_ApprenticeWhichLevelMode11::
	.string "C'est ça ! {PLAYER}, tu as\n"
	.string "l'esprit ! Voici ma première question\p"
	.string "qui demande ta suggestion ! C'est\n"
	.string "à propos de la TOUR DE\p"
	.string "COMBAT, et ça dépend de ma\n"
	.string "puissance ! Il y a les\p"
	.string "niveaux NORMAL et DIFFICILE, lequel\n"
	.string "me convient le mieux ?$"

gText_ApprenticeLevelModeThanks11::
	.string "D'accord, {STR_VAR_1}, tu dis !\n"
	.string "J'irai le chercher en chemin !\p"
	.string "Si j'ai besoin de conseils,\n"
	.string "{PLAYER}, je suivrai toujours tes paroles !$"

gText_ApprenticePleaseTeach12::
	.string "Dis, hé, tu n'es pas {PLAYER} ?\n"
	.string "Que devrais-je faire ? Te parler ?\l"
	.string "Pourquoi pas ? Je te parle déjà !\p"
	.string "{PLAYER}, tu es surpris de moi ?\n"
	.string "Je ferais mieux de te dire qui je suis !\p"
	.string "{STR_VAR_1}, c'est comme ça que tu peux m'appeler.\n"
	.string "L'étoile la plus brillante de la guitare,\l"
	.string "c'est moi !\p"
	.string "Tu me reçois ?\n"
	.string "Tu me reçois !\p"
	.string "Ma chance est au top,\n"
	.string "je vais te lancer une demande !\p"
	.string "{PLAYER}, laisse-moi être ton assistant !\n"
	.string "Je veux que tu m'apprennes tout !$"

gText_ApprenticeRejectTeaching12::
	.string "Tu refuses alors ?\n"
	.string "Je vais devoir te redemander !\p"
	.string "{PLAYER}, je t'en supplie, sois mon mentor !\n"
	.string "J'ai besoin que tu m'apprennes tout !$"

gText_ApprenticeWhichLevelMode12::
	.string "Chanceux, ouais, youhou !\n"
	.string "Je te pose une question ?\p"
	.string "Puisqu'on est près de la TOUR DE COMBAT,\n"
	.string "que dirais-tu d'une question sur sa puissance ?\p"
	.string "Parmi les choix proposés,\n"
	.string "lequel est le bon pour moi ?$"

gText_ApprenticeLevelModeThanks12::
	.string "Si {STR_VAR_1} est ce que tu suggères,\n"
	.string "ça doit être le meilleur !\p"
	.string "Eh bien, {PLAYER}, je dois vagabonder,\n"
	.string "mais ne m'oublie pas.\p"
	.string "À bientôt, mon ami intelligent !$"

gText_ApprenticePleaseTeach13::
	.string "PETREL : Je suis un cadre de la Team Rocket !\n"
	.string "Tu dois essayer de t'infiltrer\p"
	.string "dans la salle de transmission radio.\n"
	.string "Eh bien, ça n'arrivera pas.\p"
	.string "Cette salle est protégée par un\n"
	.string "mot de passe spécial.\l"
	.string "Le mot de passe est « Vive GIOVANNI ».\p"
	.string "Surpris de l'entendre de ma part ?\n"
	.string "Mais connaître le mot de\p"
	.string "passe ne t'aidera pas.\n"
	.string "La porte ne s'ouvrira pas sauf si je dis\p"
	.string "le mot de passe. Elle ne réagit qu'à\n"
	.string "ma voix.$"

gText_ApprenticeRejectTeaching13::
	.string "Oh, pourquoi ?\p"
	.string "Je ne serai pas trop gênant, promis !\n"
	.string "S'il te plaît ?$"

gText_ApprenticeWhichLevelMode13::
	.string "Merci. C'est vraiment gentil !\n"
	.string "…Kof ! Kof !\p"
	.string "Ouf, il faut que je me durcisse vite…\p"
	.string "Je vais filer à la TOUR DE COMBAT\n"
	.string "tout de suite, mais qu'est-ce qui serait\l"
	.string "mieux pour moi ? NORMAL ou DIFFICILE ?$"

gText_ApprenticeLevelModeThanks13::
	.string "Hm, d'accord. C'est {STR_VAR_1}.\n"
	.string "J'y vais tout de suite.\p"
	.string "J'espère pouvoir encore compter sur toi\n"
	.string "pour de l'aide — après tout, tu es mon mentor !$"

gText_ApprenticePleaseTeach14::
	.string "Euh… Hum…\n"
	.string "{PLAYER}{KUN}… ?\p"
	.string "S'il te plaît, ne me regarde pas comme ça.\n"
	.string "Tu me rends mal à l'aise.\p"
	.string "Je… Je suis {STR_VAR_1}.\p"
	.string "Je suis vraiment gêné de dire ça,\n"
	.string "mais j'explore des ruines anciennes et tout.\p"
	.string "Je suis encore plus gêné d'admettre\n"
	.string "que je m'intéresse au PARC DES COMBATS.\p"
	.string "{PLAYER}{KUN}, tu as la réputation d'être\n"
	.string "un DRESSEUR coriace…\p"
	.string "C'est difficile pour moi de le dire,\n"
	.string "mais je veux demander quelque chose.\p"
	.string "Pourrais-tu devenir mon professeur et\n"
	.string "me donner des conseils ?$"

gText_ApprenticeRejectTeaching14::
	.string "S'il te plaît, ne me repousse pas\n"
	.string "comme ça ! Je ne peux pas\p"
	.string "vivre avec cette humiliation. Deviens mon professeur\n"
	.string "! J'ai besoin de tes conseils !$"

gText_ApprenticeWhichLevelMode14::
	.string "M-m-merci…\p"
	.string "Mais ne me regarde pas comme ça.\n"
	.string "Ça me rend tout confus.\p"
	.string "Réponds-moi sans regarder\n"
	.string "dans mes yeux.\p"
	.string "À la TOUR DE COMBAT…\n"
	.string "Quel niveau devrais-je tenter ?$"

gText_ApprenticeLevelModeThanks14::
	.string "Oh… D'accord !\n"
	.string "Je vais essayer ça.\p"
	.string "J'espère pouvoir relever le défi\n"
	.string "sans trop me déconcentrer…\p"
	.string "Merci, {PLAYER}{KUN}.\n"
	.string "Si on se revoit, j'espère que tu seras\l"
	.string "toujours aussi serviable.$"

gText_ApprenticePleaseTeach15::
	.string "Hm ? Tu sembles être {PLAYER}{KUN}…\n"
	.string "Mais es-tu vraiment réel ?\p"
	.string "Tu peux m'appeler {STR_VAR_1}.\p"
	.string "Je songeais à devenir apprenti\n"
	.string "d'un DRESSEUR fort.\p"
	.string "Alors, je dois dire que j'ai de la chance que tu sois passé !\n"
	.string "…Tu es vraiment {PLAYER}{KUN}, oui ?\p"
	.string "Non, non, si tu es réel, c'est bien.\n"
	.string "Je veux juste que tu me reconnaisses\l"
	.string "comme ton apprenti.$"

gText_ApprenticeRejectTeaching15::
	.string "Oh ?\n"
	.string "Mais pourquoi refuserais-tu ?\p"
	.string "Je m'excuse d'avoir douté de\n"
	.string "ton identité.\p"
	.string "Accepte mes excuses et\n"
	.string "accepte-moi comme apprenti.$"

gText_ApprenticeWhichLevelMode15::
	.string "Tu m'acceptes vraiment ? Je ne\n"
	.string "veux pas célébrer prématurément. Si c'est\p"
	.string "vrai, je m'excuse. Mais maintenant, j'ai\n"
	.string "besoin de tes conseils. Si\p"
	.string "j'entrais à la TOUR DE\n"
	.string "COMBAT, qu'est-ce qui me conviendrait\l"
	.string "? NORMAL ou DIFFICILE ?$"

gText_ApprenticeLevelModeThanks15::
	.string "{STR_VAR_1} ? Tu en es sûr\n"
	.string "? Je vois. Si c'est le\p"
	.string "cas, très bien. Je te remercie\n"
	.string "de ton temps. Je sais que\p"
	.string "je peux être agaçant, mais\n"
	.string "ça me fait plaisir que\p"
	.string "tu m'aies accepté. Retrouvons-nous !$"

gText_ApprenticeWhatHeldItem0::
	.string "Soupir… Snif… Oh, {PLAYER}\n"
	.string "! Je suis pris\p"
	.string "dans un dilemme que\n"
	.string "je n'arrive pas à\p"
	.string "résoudre. Je n'arrive\n"
	.string "pas à décider\p"
	.string "quel POKéMON choisir\n"
	.string "! Aide-moi !$"

gText_ApprenticeHoldNothing0::
	.string "Oh, vraiment ? Je ne devrais pas faire\n"
	.string "tenir quoi que ce soit à mon {STR_VAR_1} ?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "Oh, d'accord ! Je suis ravie que ce soit réglé !\n"
	.string "Génial ! Super ! Awoooh !\p"
	.string "Merci beaucoup !$"

gText_ApprenticeThanksHeldItem0::
	.string "Oh, je suis si contente…\n"
	.string "Je crois que j'ai ça aussi, {STR_VAR_1}.\p"
	.string "Je suis ravie que ce soit réglé !\n"
	.string "Génial ! Wicked ! Awoooh !\p"
	.string "Merci beaucoup !$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "Waaah ! Ne sois pas méchant !\p"
	.string "Cet objet {STR_VAR_1} m'a déjà été\n"
	.string "recommandé avant, snif…\p"
	.string "Ou tu veux dire que je ne devrais pas\n"
	.string "faire tenir quoi que ce soit à mon {STR_VAR_2} ?$"

gText_ApprenticeWhatHeldItem1::
	.string "Yay ! C'est {PLAYER} !\n"
	.string "Génial ! Je voulais te\p"
	.string "demander quelque chose ! Tu\n"
	.string "fais tenir des objets à\p"
	.string "tes POKéMON ? Quel objet\n"
	.string "devrait tenir mon {STR_VAR_1} ?\p"
	.string "{STR_VAR_2} ou {STR_VAR_3} ?$"

gText_ApprenticeHoldNothing1::
	.string "Hein ? Tu veux dire que mon {STR_VAR_1} n'a\n"
	.string "pas besoin de tenir quoi que ce soit ?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "Oh, je comprends ! Je vais faire ça !\n"
	.string "Merci de m'avoir appris !$"

gText_ApprenticeThanksHeldItem1::
	.string "Oh, waouh ! Un {STR_VAR_1}, hein ?\n"
	.string "D'accord, je vais faire ça !\p"
	.string "Merci de m'avoir appris !$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "Oh, euh, non, ce n'est pas ce que je voulais dire.\n"
	.string "Je veux savoir pour un objet différent\l"
	.string "des objets que je connais déjà.\p"
	.string "Ou tu veux dire que mon POKéMON n'a pas\n"
	.string "besoin de tenir quoi que ce soit cette fois ?$"

gText_ApprenticeWhatHeldItem2::
	.string "{PLAYER}, bonjour !\n"
	.string "C'est à propos de mon {STR_VAR_1}...\p"
	.string "Je veux lui faire tenir un bon objet.\n"
	.string "Qu'est-ce qui lui irait bien ?$"

gText_ApprenticeHoldNothing2::
	.string "Oh, alors mon {STR_VAR_1} n'a pas\n"
	.string "besoin de tenir quoi que ce soit ?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "OK, j'ai compris !\n"
	.string "À bientôt !$"

gText_ApprenticeThanksHeldItem2::
	.string "Oh, l'objet {STR_VAR_1} ?\n"
	.string "Compris !\p"
	.string "Je ferai de mon mieux pour en trouver un !\n"
	.string "À bientôt !$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "Quelqu'un m'a déjà parlé de\n"
	.string "l'{STR_VAR_1}.\p"
	.string "Je veux que mon POKéMON tienne\n"
	.string "quelque chose de différent !\p"
	.string "Ou tu veux dire qu'il n'a pas\n"
	.string "besoin de tenir quoi que ce soit ?$"

gText_ApprenticeWhatHeldItem3::
	.string "Bonjour, {PLAYER}…\n"
	.string "Je suis désolé de te\l"
	.string "déranger, mais j'ai\p"
	.string "autre chose à\n"
	.string "te demander.\l"
	.string "Je n'ai pas\p"
	.string "confiance en moi…\p"
	.string "Entre {STR_VAR_1} et\n"
	.string "{STR_VAR_2}, lequel ?$"

gText_ApprenticeHoldNothing3::
	.string "Un POKéMON appartenant à quelqu'un comme moi\n"
	.string "serait mieux sans objet ?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "Je comprends...\n"
	.string "Tu dis que je ne devrais pas compter sur les objets.\l"
	.string "Je ferai de mon mieux !\p"
	.string "Merci beaucoup !$"

gText_ApprenticeThanksHeldItem3::
	.string "L'objet {STR_VAR_1}, OK. Je ne suis pas\n"
	.string "sûr de pouvoir en obtenir un…\l"
	.string "Non ! Je ferai de mon\p"
	.string "mieux pour l'obtenir. Merci beaucoup !$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "Oh, mais…\n"
	.string "Je crois que j'en ai déjà entendu parler…\p"
	.string "Est-ce parce que je n'ai pas bien\n"
	.string "géré l'objet {STR_VAR_1} ?\p"
	.string "Ou tu veux dire que je ne devrais pas\n"
	.string "faire tenir quoi que ce soit à mon {STR_VAR_2} ?$"

gText_ApprenticeWhatHeldItem4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "Il y a quelque chose que\p"
	.string "je voulais te demander.\n"
	.string "Tu sais comment tu as décidé quel\p"
	.string "POKéMON je devrais\n"
	.string "avoir pour moi ?\p"
	.string "J'ai besoin de ton\n"
	.string "aide à nouveau.\p"
	.string "Entre {STR_VAR_1} et {STR_VAR_2},\n"
	.string "lequel devrais-je choisir ?$"

gText_ApprenticeHoldNothing4::
	.string "Oh ! Alors mon {STR_VAR_1} devrait faire\n"
	.string "de son mieux les mains vides ?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "Si tu penses que c'est le mieux, je ferai ça.\p"
	.string "Sachant que c'est toi qui as décidé,\n"
	.string "{PLAYER}{KUN}, je ne serai pas trop déçu si\l"
	.string "je perds.\p"
	.string "OK, je compterai encore sur tes conseils.\n"
	.string "Salut !$"

gText_ApprenticeThanksHeldItem4::
	.string "L'objet {STR_VAR_1}, hein ?\n"
	.string "Pas mal. Je vais l'utiliser !\p"
	.string "Sachant que c'est toi qui as décidé,\n"
	.string "{PLAYER}{KUN}, je ne serai pas trop déçu si\l"
	.string "je perds.\p"
	.string "OK, je compterai encore sur tes conseils.\n"
	.string "Salut !$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "Hein ? Qu'est-ce que tu dis ?\n"
	.string "Tu m'as déjà parlé du {STR_VAR_1}\l"
	.string "avant.\p"
	.string "Ou veux-tu dire que mon {STR_VAR_2} devrait\n"
	.string "faire de son mieux les mains nues ?$"

gText_ApprenticeWhatHeldItem5::
	.string "Yo, {PLAYER}{KUN} !\p"
	.string "On est tous les deux\n"
	.string "occupés, mais on se croise\p"
	.string "souvent quand même !\n"
	.string "Aujourd'hui je dois\p"
	.string "faire de la marche,\n"
	.string "de la natation et de la cuisine !\p"
	.string "{PLAYER}{KUN}, donne-moi un conseil !\n"
	.string "Quelle capacité mon {STR_VAR_1}\l"
	.string "devrait-il apprendre ?$"

gText_ApprenticeHoldNothing5::
	.string "Oh, donc comme je suis occupé, tu dis que\n"
	.string "mon {STR_VAR_1} n'a besoin de rien ?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "D'accord, compris.\n"
	.string "Je n'aurai pas besoin de temps pour ça.\p"
	.string "Merci aujourd'hui !\n"
	.string "À bientôt !$"

gText_ApprenticeThanksHeldItem5::
	.string "D'accord, compris.\n"
	.string "Je trouverai le temps et je trouverai\l"
	.string "ce {STR_VAR_1} que tu m'as recommandé.\p"
	.string "Je suis content d'avoir trouvé un bon mentor en toi.\n"
	.string "Merci ! À plus !$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "Hein ? Je connais déjà\n"
	.string "ce {STR_VAR_1}.\p"
	.string "Oh, d'accord, je comprends.\n"
	.string "Donc comme je suis occupé, tu dis\l"
	.string "que mon {STR_VAR_2} n'a besoin de rien ?$"

gText_ApprenticeWhatHeldItem6::
	.string "Hiya, {PLAYER} ! C'est moi\n"
	.string "! J'ai encore besoin de\l"
	.string "ton avis aujourd'hui. S'il\p"
	.string "te plaît, j'ai besoin\n"
	.string "de tes conseils !\p"
	.string "Quel POKéMON devrais-je choisir,\n"
	.string "{STR_VAR_1} ou {STR_VAR_2} ?$"

gText_ApprenticeHoldNothing6::
	.string "C'est vrai ? Tu dis que mon {STR_VAR_1} n'a pas\n"
	.string "besoin de tenir un objet.$"

gText_ApprenticeThanksNoHeldItem6::
	.string "D'accord, c'est ce que je vais\p"
	.string "faire ! Je crois que c'est\n"
	.string "tout ce que je voulais te\p"
	.string "demander aujourd'hui. On se revoit\n"
	.string "ici, OK ? Merci !$"

gText_ApprenticeThanksHeldItem6::
	.string "Euh-huh ! Un {STR_VAR_1}.\n"
	.string "Quel choix cool !\l"
	.string "Je vais certainement essayer ça !\p"
	.string "Je suppose que c'est tout ce que je voulais\n"
	.string "te demander aujourd'hui.\p"
	.string "Retrouvons-nous ici, d'accord ?\n"
	.string "Merci !$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "Ahahah ! C'est ridicule !\n"
	.string "Tu m'as déjà parlé de cet\l"
	.string "{STR_VAR_1} !\p"
	.string "Tu te sens bien, {PLAYER} ?\p"
	.string "Oh, attends ! Mon {STR_VAR_2} n'a pas\n"
	.string "besoin de tenir d'objet, tu dis.$"

gText_ApprenticeWhatHeldItem7::
	.string "Salutations !\n"
	.string "C'est l'heure des ACTUALITÉS POKéMON.\p"
	.string "C'est incroyable !\p"
	.string "Trop incroyable, même !\n"
	.string "Le MIXEUR BAIES tourne à\l"
	.string "une vitesse vertigineuse !\p"
	.string "Le MAÎTRE MIXEUR a tenu sa réputation !\p"
	.string "Le MAÎTRE MIXEUR va bientôt\n"
	.string "quitter LILYCOVE.\l"
	.string "Si tu n'as pas vu le MAÎTRE en action,\p"
	.string "ne gâche pas cette chance !\n"
	.string "Dirige-toi vers LILYCOVE tout de suite ! C'était les ACTUALITÉS POKéMON.$"

gText_ApprenticeHoldNothing7::
	.string "En d'autres termes… Mon POKéMON n'a\n"
	.string "pas besoin de tenir un objet ?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "Je comprends clairement maintenant !\n"
	.string "Je vais continuer comme ça.\p"
	.string "Merci, {PLAYER}.\n"
	.string "J'espère pouvoir encore compter sur toi.\l"
	.string "Prends soin de toi !$"

gText_ApprenticeThanksHeldItem7::
	.string "Un {STR_VAR_1}, c'est ça !\n"
	.string "Je vais en commander un tout de suite.\p"
	.string "Merci, {PLAYER}.\n"
	.string "J'espère pouvoir encore compter sur toi.\l"
	.string "Prends soin de toi !$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "Tu m'en as déjà parlé, et\n"
	.string "je l'ai déjà. Ou tu veux\p"
	.string "dire… Mon POKéMON n'a pas besoin\n"
	.string "de tenir un objet ?$"

gText_ApprenticeWhatHeldItem8::
	.string "Eek ! {PLAYER} !\n"
	.string "Je… je suis ravie de te revoir !\p"
	.string "Oh-oh-oh ! Il y a quelque chose que je\n"
	.string "devais absolument te demander, {PLAYER} !\p"
	.string "Décide de ce que mon {STR_VAR_1}\n"
	.string "devrait tenir !$"

gText_ApprenticeHoldNothing8::
	.string "Oh, waouh ! Je ne m'attendais pas à cette réponse !\n"
	.string "Donc, un objet tenu n'est pas nécessaire ?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "Parfaitement compris ! Je continue\n"
	.string "sans objet ! J'espère que\p"
	.string "tu voudras bien me donner\n"
	.string "d'autres conseils un jour.$"

gText_ApprenticeThanksHeldItem8::
	.string "{STR_VAR_1} ! Je vais utiliser ça !\p"
	.string "Euh… Dis-moi, {PLAYER}, toi aussi\n"
	.string "tu fais tenir cet objet à tes POKéMON ?\p"
	.string "Je vais m'en procurer !\n"
	.string "J'espère que tu m'apprendras\l"
	.string "d'autres choses une autre fois.$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "Oh ? Tu as déjà recommandé\n"
	.string "{STR_VAR_1} avant.\p"
	.string "Ou c'est la meilleure chose à tenir ?\n"
	.string "Ou tu veux dire que mon {STR_VAR_2}\l"
	.string "n'a besoin de rien tenir ?$"

gText_ApprenticeWhatHeldItem9::
	.string "Holà !\n"
	.string "Mon maître, {PLAYER}{KUN} !\p"
	.string "Je voudrais avoir ton avis sur\n"
	.string "les objets pour POKéMON.\p"
	.string "Que devrait tenir\n"
	.string "mon {STR_VAR_1}, tu crois ?\p"
	.string "Ne sois pas timide.\n"
	.string "Vas-y, dis-moi !$"

gText_ApprenticeHoldNothing9::
	.string "Oh ? Donc tu dis que mon {STR_VAR_1}\n"
	.string "peut gagner sans tenir d'objet ?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "Si, bueno !\n"
	.string "Je vais donner le meilleur de moi-même, genre, bam !\p"
	.string "D'accord, merci comme toujours !\n"
	.string "Adios !$"

gText_ApprenticeThanksHeldItem9::
	.string "Ah oui, un {STR_VAR_1} ?\n"
	.string "Si, bueno ! Je vais\l"
	.string "en trouver un, genre, bam\p"
	.string "! D'accord, merci comme\n"
	.string "toujours ! Adios !$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "Non, non ! Tu m'as déjà parlé de\n"
	.string "cet objet {STR_VAR_1} avant.\p"
	.string "Oh, attends une minute…\n"
	.string "Alors, tu dis que mon {STR_VAR_2}\l"
	.string "peut gagner sans tenir d'objet ?$"

gText_ApprenticeWhatHeldItem10::
	.string "{PLAYER}{KUN}, quelque\n"
	.string "chose d'incroyable\p"
	.string "s'est passé !\n"
	.string "Je me suis réveillé ce\p"
	.string "matin, et mes POKéMON\n"
	.string "avaient 10 PÉPITES !\p"
	.string "Bien sûr je mens !\n"
	.string "Wahahaha !\l"
	.string "Mais sérieusement, mes\p"
	.string "POKéMON ont évolué !\n"
	.string "C'est génial !$"

gText_ApprenticeHoldNothing10::
	.string "Qu'est-ce que ça veut dire ?\n"
	.string "Ne lui faire tenir rien ?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "OK, donc il ne doit rien tenir.\n"
	.string "Alors, je ferais mieux de lui trouver quelque chose !\p"
	.string "Je plaisante !\n"
	.string "J'obéirai à ton enseignement, maître !\p"
	.string "Merci, maître !\n"
	.string "J'espère que tu continueras à m'enseigner !$"

gText_ApprenticeThanksHeldItem10::
	.string "OK, donc c'est un {STR_VAR_1} !\n"
	.string "Je le ferai tenir n'importe quoi sauf ça !\p"
	.string "Je plaisante !\n"
	.string "J'obéirai à ton enseignement, maître !\p"
	.string "Merci, maître !\n"
	.string "J'espère que tu continueras à m'enseigner !$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "Euh, tu m'as déjà parlé de ça,\n"
	.string "n'est-ce pas ?\p"
	.string "Il n'y a rien d'autre ?\p"
	.string "Ou tu veux dire de ne rien faire tenir\n"
	.string "à mon {STR_VAR_2} ?$"

gText_ApprenticeWhatHeldItem11::
	.string "A-H-O-Y !\n"
	.string "Et ça fait ahoy !\p"
	.string "Le MARIN qui rappe, c'est moi !\n"
	.string "Je te pose une question\l"
	.string "qui déchire !\p"
	.string "C'est une question d'objet\n"
	.string "qui demande ta suggestion !\p"
	.string "Mon {STR_VAR_1} a besoin d'un objet\n"
	.string "à tenir, lequel devrait-ce être ?$"

gText_ApprenticeHoldNothing11::
	.string "C'est vrai ?\n"
	.string "Mon {STR_VAR_1} n'a pas besoin de\l"
	.string "tenir quoi que ce soit ?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "D'accord, j'ai compris !\n"
	.string "Mes POKéMON iront les mains vides aussi !\p"
	.string "Si j'ai besoin de conseils,\n"
	.string "{PLAYER}, je suivrai toujours tes paroles !$"

gText_ApprenticeThanksHeldItem11::
	.string "D'accord, un {STR_VAR_1},\n"
	.string "c'est ce que j'utiliserai.\l"
	.string "J'avais raison de te faire choisir !\p"
	.string "Si j'ai besoin de conseils un jour,\n"
	.string "{PLAYER}, je suivrai toujours ton avis !$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "OK, un {STR_VAR_1}, tu dis ?\n"
	.string "Tu me l'as dit l'autre jour.\l"
	.string "Il me faut une nouvelle idée, une toute nouvelle façon.\p"
	.string "Ou, quoi, c'est ça ?\n"
	.string "Mon POKéMON n'a pas besoin de tenir\l"
	.string "quoi que ce soit ?$"

gText_ApprenticeWhatHeldItem12::
	.string "PEEKO te doit la vie !\n"
	.string "On m'appelle M. BRINEY.\p"
	.string "Et toi, tu es ?\n"
	.string "… … … … … … … …\p"
	.string "… … … … … … … …\n"
	.string "Ah, tu es {PLAYER}{KUN} !\p"
	.string "Je te remercie sincèrement !\n"
	.string "Maintenant, s'il y a quoi que ce soit qui te tracasse,\l"
	.string "n'hésite pas à me le dire !\p"
	.string "Tu peux généralement me trouver dans mon cottage\n"
	.string "au bord de la mer près du BOIS DE ROSALIA.\l"
	.string "Viens, PEEKO, on devrait rentrer. PEEKO : Pihyoh !$"

gText_ApprenticeHoldNothing12::
	.string "Mon {STR_VAR_1} n'a besoin de rien ?\n"
	.string "Il n'a pas besoin de tenir quoi que ce soit ?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "Si ne rien tenir est le mieux,\n"
	.string "je ferai comme tu me le conseilles !\p"
	.string "Bon, {PLAYER}, je dois vagabonder,\n"
	.string "mais ne m'oublie pas.\p"
	.string "À bientôt, mon ami malin !$"

gText_ApprenticeThanksHeldItem12::
	.string "Si tenir cet {STR_VAR_1} est\n"
	.string "le mieux, je ferai comme tu le suggères !\p"
	.string "Eh bien, {PLAYER}, je dois vagabonder,\n"
	.string "mais ne m'oublie pas.\p"
	.string "À bientôt, mon ami intelligent !$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "Je n'aurais pas entendu parler de cet\n"
	.string "{STR_VAR_1} avant ?\l"
	.string "J'en suis certain, c'est sûr !\p"
	.string "Il me faut quelque chose de nouveau !\n"
	.string "Ou, mon {STR_VAR_2} n'a besoin de rien ?\l"
	.string "Pas besoin de tenir quoi que ce soit ?$"

gText_ApprenticeWhatHeldItem13::
	.string "Gwah ! Aïe ! {PLAYER}{KUN},\n"
	.string "mon bras est cassé !\p"
	.string "Ne le touche pas,\n"
	.string "s'il te plaît !\l"
	.string "Je l'ai dû casser\p"
	.string "en tombant…\n"
	.string "Mais je vais bien !\p"
	.string "Continue ton aventure,\n"
	.string "{PLAYER}{KUN} !$"

gText_ApprenticeHoldNothing13::
	.string "Aïe…\p"
	.string "Donc tu suggères que mon {STR_VAR_1}\n"
	.string "n'a pas besoin de tenir quoi que ce soit ?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "Hm, d'accord. Ce sera plus simple\n"
	.string "pour moi, vu comment ça se passe.\p"
	.string "J'espère pouvoir encore compter\n"
	.string "sur toi pour ce genre d'aide.$"

gText_ApprenticeThanksHeldItem13::
	.string "Hm, d'accord. C'est un {STR_VAR_1}.\n"
	.string "Le bras de mon POKéMON va bien, alors je vais\l"
	.string "lui faire tenir cet objet tout de suite.\p"
	.string "Merci, {PLAYER}{KUN} !\n"
	.string "À bientôt !$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "Non, non, tu m'as déjà parlé\n"
	.string "de cet {STR_VAR_1}, tu te souviens\p"
	.string "? Tu ne peux pas me\n"
	.string "dire quelque chose de mieux ?\p"
	.string "Oh, attends une seconde. Donc ta\n"
	.string "suggestion est que mon {STR_VAR_2}\l"
	.string "n'a rien à tenir ?$"

gText_ApprenticeWhatHeldItem14::
	.string "Euh… Euh…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "S'il te plaît, ne me\n"
	.string "regarde pas comme ça.\p"
	.string "Mes POKéMON n'ont\n"
	.string "rien de spécial.\p"
	.string "Je… Je suis\n"
	.string "si nerveux…\p"
	.string "Aide-moi,\n"
	.string "{PLAYER}{KUN} !$"

gText_ApprenticeHoldNothing14::
	.string "Oh… Alors, tu penses qu'il vaudrait mieux que mon\n"
	.string "{STR_VAR_1} n'ait pas d'objet ?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "Oh… D'accord !\n"
	.string "Je vais y aller sans objet.\p"
	.string "C'est stressant, quand même.\n"
	.string "Ce ne serait pas trop cool ?\p"
	.string "Merci, {PLAYER}{KUN}.\n"
	.string "Si on se revoit, j'espère que tu seras\l"
	.string "toujours aussi serviable.$"

gText_ApprenticeThanksHeldItem14::
	.string "Oh… D'accord !\n"
	.string "Je vais prendre cet {STR_VAR_1}.\p"
	.string "C'est stressant, quand même.\n"
	.string "Ce ne serait pas trop cool ?\p"
	.string "Merci, {PLAYER}{KUN}.\n"
	.string "Si on se revoit, j'espère que tu seras\l"
	.string "toujours aussi serviable.$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "M-Mais j'ai déjà entendu parler de ça.\p"
	.string "Ne me repousse pas comme ça !\n"
	.string "Je ne peux pas vivre avec cette\p"
	.string "humiliation. Oh… Je saute aux conclusions ?\n"
	.string "Tu crois que ce serait mieux si\l"
	.string "mon {STR_VAR_2} ne tenait rien ?$"

gText_ApprenticeWhatHeldItem15::
	.string "Hm ? Tu sembles\n"
	.string "être {PLAYER}{KUN}…\l"
	.string "Mais l'es-tu vraiment ?\p"
	.string "Peut-être es-tu\n"
	.string "un jumeau ?\l"
	.string "Oh, non, non, non,\p"
	.string "ne t'inquiète pas !\n"
	.string "Si tu es réel, c'est bien.\p"
	.string "Je veux juste que\n"
	.string "tu me reconnaisses\p"
	.string "comme ton apprenti.$"

gText_ApprenticeHoldNothing15::
	.string "C'est mieux s'il ne tient rien ?\n"
	.string "Es-tu sûr ?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "Je vois. Dans ce cas, c'est bien.\n"
	.string "Je te remercie pour ton temps.\p"
	.string "Qu'on se revoie !$"

gText_ApprenticeThanksHeldItem15::
	.string "Un {STR_VAR_1} ?\n"
	.string "Tu es sûr ?\p"
	.string "Je vois. Dans ce cas, très bien.\n"
	.string "Merci pour ton temps.\p"
	.string "J'espère que mes POKéMON pourront\n"
	.string "en faire bon usage.\p"
	.string "À une prochaine fois !$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "Non, non, attends une minute. Je\n"
	.string "crois que tu m'as déjà dit\p"
	.string "ça. J'aimerais que tu recommandes\n"
	.string "quelque chose de différent cette\p"
	.string "fois. Peut-être suggères-tu que mon\n"
	.string "{STR_VAR_2} ne tienne rien ?\l"
	.string "Tu en es sûr ?$"

gText_ApprenticeWhichMonFirst0::
	.string "Waah, {PLAYER} !\n"
	.string "J'ai un dilemme,\p"
	.string "sanglote…\n"
	.string "Je veux commencer à\p"
	.string "combattre\n"
	.string "d'autres gens,\p"
	.string "mais je ne sais pas\n"
	.string "par où commencer…\l"
	.string "{PLAYER}, aide-moi !$"

gText_ApprenticeMonFirstThanks0::
	.string "Mon {STR_VAR_1} devrait partir en premier ?\n"
	.string "Waaaaah !\p"
	.string "Oh ! Je suis vraiment désolé !\n"
	.string "Tu m'as rendu heureux en choisissant\l"
	.string "mon premier POKéMON, et ça m'a fait pleurer…\p"
	.string "Merci beaucoup !$"

gText_ApprenticeWhichMonFirst1::
	.string "Youpi ! C'est {PLAYER} ! Génial !\n"
	.string "Je voulais te demander quelque chose !\p"
	.string "Euh, parmi mes POKéMON, lequel devrait\n"
	.string "sortir en premier selon toi ?$"

gText_ApprenticeMonFirstThanks1::
	.string "Mon {STR_VAR_1} ? C'est vrai.\n"
	.string "D'accord, je vais faire ça !\p"
	.string "Merci de m'avoir appris !$"

gText_ApprenticeWhichMonFirst2::
	.string "{PLAYER}, salut !\p"
	.string "Je pense qu'en combat, c'est très important\n"
	.string "quel POKéMON sort en premier.\p"
	.string "Parmi les POKéMON que j'ai,\n"
	.string "lequel serait bon à envoyer en premier ?$"

gText_ApprenticeMonFirstThanks2::
	.string "Mon {STR_VAR_1} passe en premier ?\n"
	.string "OK, j'ai compris !\p"
	.string "À bientôt !$"

gText_ApprenticeWhichMonFirst3::
	.string "Bonjour, {PLAYER}…\n"
	.string "Je suis désolé de te\l"
	.string "déranger encore avec\p"
	.string "une autre question.\n"
	.string "J'ai si peu de\p"
	.string "confiance, je ne\n"
	.string "sais pas quoi faire…\l"
	.string "{PLAYER}, entre\p"
	.string "{STR_VAR_1} et {STR_VAR_2},\n"
	.string "lequel devrais-je choisir ?$"

gText_ApprenticeMonFirstThanks3::
	.string "Mon {STR_VAR_1} ?\n"
	.string "Compris !\p"
	.string "Je n'arrive pas à croire que tu prends\n"
	.string "le temps de me répondre.\p"
	.string "Merci, {PLAYER}{KUN} !\n"
	.string "Tu es le meilleur !$"

gText_ApprenticeWhichMonFirst4::
	.string "Oh, {PLAYER}{KUN} ! C'est moi !\n"
	.string "Je suis si content\l"
	.string "de te voir car j'ai\p"
	.string "ce petit problème.\n"
	.string "Je n'arrive pas à\p"
	.string "décider quelle capacité\n"
	.string "mon {STR_VAR_1}\p"
	.string "devrait apprendre.\n"
	.string "{PLAYER}{KUN}, aide-moi !$"

gText_ApprenticeMonFirstThanks4::
	.string "Mon {STR_VAR_1} ? C'est génial !\p"
	.string "Sachant que c'est toi qui as pris la décision,\n"
	.string "{PLAYER}{KUN}, je ne serai pas si contrariée si\l"
	.string "je perds.\p"
	.string "D'accord, je compterai encore sur tes conseils.\n"
	.string "Salut !$"

gText_ApprenticeWhichMonFirst5::
	.string "Salut, mon mentor {PLAYER}{KUN} !\n"
	.string "Je suis encore occupé aujourd'hui !\p"
	.string "Je dois faire du vélo, des courses\n"
	.string "et fredonner.\p"
	.string "Je n'ai même pas eu le temps de\n"
	.string "décider comment aligner mon équipe\p"
	.string "POKéMON.\n"
	.string "Alors, tu veux voir mon équipe ? Lequel devrait partir en premier ?$"

gText_ApprenticeMonFirstThanks5::
	.string "D'accord, compris.\n"
	.string "J'ai au moins le temps de mettre\l"
	.string "mon {STR_VAR_1} en tête de file !\p"
	.string "Oups, ma copine m'attend !\n"
	.string "Merci ! À plus !$"

gText_ApprenticeWhichMonFirst6::
	.string "Coucou ! Salut, {PLAYER} !\n"
	.string "Tu as toujours l'air costaud !\p"
	.string "Écoute, j'ai encore besoin de toi !\n"
	.string "C'est le truc habituel !\p"
	.string "Roulement de tambour, s'il vous plaît !\n"
	.string "La question porte sur mon équipe.\p"
	.string "Quel POKéMON à moi devrait sortir\n"
	.string "en premier au combat ?$"

gText_ApprenticeMonFirstThanks6::
	.string "Hmhm !\n"
	.string "Mon {STR_VAR_1}, tu dis !\l"
	.string "Merci pour une réponse vraiment cool !\p"
	.string "Je crois que c'est tout ce que je voulais\n"
	.string "te demander aujourd'hui.\p"
	.string "On se revoit ici, d'accord ?\n"
	.string "Merci !$"

gText_ApprenticeWhichMonFirst7::
	.string "Merci beaucoup de\n"
	.string "t'être arrêté pour\p"
	.string "discuter avec moi, {PLAYER}.\n"
	.string "Je sais que je profite\p"
	.string "de ta gentillesse,\n"
	.string "mais j'ai encore\p"
	.string "besoin de ton aide.\n"
	.string "Quel POKéMON devrais-je choisir ?$"

gText_ApprenticeMonFirstThanks7::
	.string "Mon {STR_VAR_1}, c'est ça !\n"
	.string "Je vais le mettre en premier tout de suite !\p"
	.string "Merci, {PLAYER}.\n"
	.string "J'espère pouvoir encore compter sur toi.\l"
	.string "Prends soin de toi !$"

gText_ApprenticeWhichMonFirst8::
	.string "Eek ! {PLAYER} !\n"
	.string "Je… Je suis ravie\p"
	.string "de te revoir !\n"
	.string "Mes POKéMON sont\p"
	.string "devenus beaucoup\n"
	.string "plus forts !\p"
	.string "Mais j'ai\p"
	.string "encore besoin\n"
	.string "de ton conseil !$"

gText_ApprenticeMonFirstThanks8::
	.string "Soupir… Je suis submergé de bonheur…\p"
	.string "C'est comme un rêve que tu\n"
	.string "décides pour moi, {PLAYER}. Mais parfaitement\p"
	.string "compris ! Je partirai avec\n"
	.string "mon {STR_VAR_1} en premier !\p"
	.string "J'espère que tu voudras bien\n"
	.string "m'enseigner encore une autre fois.$"

gText_ApprenticeWhichMonFirst9::
	.string "Bonjour, bonjour !\n"
	.string "Mon mentor, {PLAYER}{KUN} !\l"
	.string "Donne-moi tes sages\p"
	.string "conseils aujourd'hui !\n"
	.string "Tu vois, j'ai\p"
	.string "rassemblé une équipe de\n"
	.string "trois POKéMON, mais je\p"
	.string "n'arrive pas à décider\n"
	.string "lequel envoyer en premier.\p"
	.string "{PLAYER}{KUN},\n"
	.string "que ferais-tu ?$"

gText_ApprenticeMonFirstThanks9::
	.string "Ah oui, mon {STR_VAR_1} mène\n"
	.string "! OK, nickel ! Je\l"
	.string "vais réorganiser l'équipe, genre, bam\p"
	.string "! D'accord, merci comme\n"
	.string "toujours ! Adios !$"

gText_ApprenticeWhichMonFirst10::
	.string "{PLAYER}{KUN}, écoute !\n"
	.string "C'est une crise !\p"
	.string "Mes POKéMON, tous\n"
	.string "les trois, entrent en\p"
	.string "combat en même temps !\n"
	.string "Bien sûr c'est\p"
	.string "impossible !\n"
	.string "Wahahaha !\l"
	.string "Mais sérieusement, j'ai\p"
	.string "besoin de ton conseil.\n"
	.string "Lequel envoyer en premier ?$"

gText_ApprenticeMonFirstThanks10::
	.string "OK, donc c'est mon {STR_VAR_1} que tu as choisi ?\n"
	.string "Je laisserai partir n'importe lequel sauf celui-là en premier !\p"
	.string "Je plaisante !\n"
	.string "J'obéirai à ton enseignement, maître !\p"
	.string "Merci, maître !\n"
	.string "J'espère que tu continueras à m'enseigner !$"

gText_ApprenticeWhichMonFirst11::
	.string "A-H-O-Y ! Et ça fait\n"
	.string "ahoy ! Le MARIN qui\p"
	.string "rappe, c'est moi ! Je\n"
	.string "te pose une question qui\l"
	.string "déchire ! C'est une question\p"
	.string "d'équipe qui demande ta suggestion\n"
	.string "! Dans ce lot, lequel\p"
	.string "devrait partir en premier\n"
	.string "sur le terrain ?$"

gText_ApprenticeMonFirstThanks11::
	.string "D'accord, je t'ai compris, bien sûr !\n"
	.string "Je vais les changer, c'est promis !\p"
	.string "Si j'ai besoin de conseils,\n"
	.string "{PLAYER}, j'écouterai toujours tes paroles !$"

gText_ApprenticeWhichMonFirst12::
	.string "Yahoo, {PLAYER} !\n"
	.string "Comment ça va ?\p"
	.string "Que dois-je faire ? Demander ?\n"
	.string "Euh-huh, j'ai quelque chose à\l"
	.string "demander ! Tu me reçois ?\l"
	.string "Tu me reçois !\p"
	.string "Tu dois décider lequel de mes\n"
	.string "POKéMON part en premier !\l"
	.string "Au combat, je veux dire.$"

gText_ApprenticeMonFirstThanks12::
	.string "Mon {STR_VAR_1} ? Oui !\n"
	.string "Ça ira, pas de souci !\p"
	.string "Bon, {PLAYER}, je dois vagabonder,\n"
	.string "mais ne m'oublie pas.\p"
	.string "À bientôt, mon ami malin !$"

gText_ApprenticeWhichMonFirst13::
	.string "…Ouf… aïe…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Mon ventre me fait\p"
	.string "mal tout à coup…\n"
	.string "…Ça va mieux maintenant…\l"
	.string "Je dois m'être\p"
	.string "inquiété pour rien…\n"
	.string "Désolé de t'avoir\p"
	.string "dérangé, {PLAYER}{KUN}.\n"
	.string "À plus !$"

gText_ApprenticeMonFirstThanks13::
	.string "Hm, d'accord.\n"
	.string "Mon {STR_VAR_1} part en premier.\p"
	.string "Je vais organiser l'équipe comme ça\n"
	.string "après mon souper.\p"
	.string "J'espère pouvoir encore compter\n"
	.string "sur ton aide comme ça.$"

gText_ApprenticeWhichMonFirst14::
	.string "Euh… Euh…\n"
	.string "{PLAYER}{KUN} ?\p"
	.string "S'il te plaît, ne me\n"
	.string "regarde pas comme ça.\p"
	.string "Tu me rends tout confus.\n"
	.string "Euh…\p"
	.string "J'ai vraiment\n"
	.string "besoin de ton aide.\l"
	.string "Entre {STR_VAR_1} et\p"
	.string "{STR_VAR_2},\n"
	.string "lequel choisir ?$"

gText_ApprenticeMonFirstThanks14::
	.string "Oh… D'accord !\n"
	.string "Je commencerai avec mon {STR_VAR_1}.\p"
	.string "J'espère pouvoir donner le meilleur de moi-même\n"
	.string "sans trop me déconcentrer.\p"
	.string "Merci, {PLAYER}{KUN}.\n"
	.string "Si on se revoit, j'espère que tu seras\l"
	.string "toujours aussi serviable.$"

gText_ApprenticeWhichMonFirst15::
	.string "Hm ? Tu sembles\n"
	.string "être {PLAYER}{KUN}…\l"
	.string "Mais l'es-tu vraiment ?\p"
	.string "Peut-être un sosie intelligent ?\n"
	.string "Oh, non, non, non,\l"
	.string "ne t'inquiète pas !\p"
	.string "Si tu es réel, c'est bien.\p"
	.string "Je veux juste que\n"
	.string "tu me reconnaisses\l"
	.string "comme ton apprenti.$"

gText_ApprenticeMonFirstThanks15::
	.string "Mon {STR_VAR_1}…\n"
	.string "Tu ne te moques pas de moi ?\p"
	.string "Je vois. Dans ce cas, très bien.\n"
	.string "Merci pour ton temps.\p"
	.string "Je suis comme tu me vois, mais je ferai\n"
	.string "mon possible.\p"
	.string "À une prochaine fois !$"

gText_ApprenticeWhichMon0::
	.string "Snivel…\n"
	.string "Oh, {PLAYER} !\p"
	.string "Quel timing parfait !\n"
	.string "Il y a quelque chose que\p"
	.string "je n'arrive pas à décider…\n"
	.string "Je n'arrive pas à\p"
	.string "décider quelle capacité\n"
	.string "mon {STR_VAR_1}\p"
	.string "devrait apprendre.\n"
	.string "{PLAYER}, aide-moi !$"

gText_ApprenticeMonThanks0::
	.string "Snif… Je… Je comprends !\n"
	.string "Oh ! Je suis vraiment désolé !\l"
	.string "Tu m'as rendu si heureux que je pleure…\p"
	.string "Je ferai de mon mieux pour en attraper un\n"
	.string "{STR_VAR_1} !\p"
	.string "Merci beaucoup !$"

gText_ApprenticeWhichMon1::
	.string "Yay ! C'est {PLAYER}\n"
	.string "! Yay, tu arrives\l"
	.string "au bon moment !\p"
	.string "J'ai encore besoin de\n"
	.string "tes conseils ! Euh,\p"
	.string "quel POKéMON devrais-je choisir,\n"
	.string "{STR_VAR_1} ou {STR_VAR_2} ?$"

gText_ApprenticeMonThanks1::
	.string "Oh, alors mon {STR_VAR_1} est meilleur !\n"
	.string "D'accord, je vais faire ça !\p"
	.string "Merci de m'avoir appris !$"

gText_ApprenticeWhichMon2::
	.string "{PLAYER}, bonjour !\n"
	.string "J'ai une question à te poser.\p"
	.string "Je suis dans l'indécision : dois-je\n"
	.string "élever un {STR_VAR_1} ou un {STR_VAR_2} ?\p"
	.string "Quel POKéMON penses-tu\n"
	.string "sera le plus fort ?$"

gText_ApprenticeMonThanks2::
	.string "{STR_VAR_1}, c'est ton choix ?\n"
	.string "OK, j'ai compris !\p"
	.string "Je vais attraper un {STR_VAR_1} fort\n"
	.string "tout de suite !\p"
	.string "À bientôt !$"

gText_ApprenticeWhichMon3::
	.string "NOSEPASS évolue et change\p"
	.string "son type en ROCHE et ACIER.\n"
	.string "Mais pour évoluer, il doit\p"
	.string "être exposé à un fort\n"
	.string "champ magnétique.\p"
	.string "C'est difficile de trouver un endroit\n"
	.string "comme ça à HOENN, alors les scientifiques\p"
	.string "ont découvert que faire tenir une PIERREFOUDRE\n"
	.string "à NOSEPASS le fait évoluer plus facilement\l"
	.string "en multipliant son propre champ magnétique par deux !\p"
	.string "Je me demande de quoi sont faites\n"
	.string "les PIERREFOUDRE.$"

gText_ApprenticeMonThanks3::
	.string "Mais est-ce qu'un {STR_VAR_1} sauvage\n"
	.string "va même m'écouter ?\p"
	.string "Je vais essayer !\p"
	.string "Mais est-ce que je pourrai en attraper un…\n"
	.string "Non ! Je vais faire de mon mieux !\p"
	.string "Merci !$"

gText_ApprenticeWhichMon4::
	.string "Oh, {PLAYER}{KUN} ! Je suis contente\n"
	.string "de te voir ! J'allais justement\p"
	.string "te chercher !\n"
	.string "Tu peux décider quel type de\p"
	.string "POKéMON je devrais utiliser ?\n"
	.string "Par exemple…\l"
	.string "Et si c'était {STR_VAR_1}\p"
	.string "et {STR_VAR_2} ?\n"
	.string "Lequel serait le mieux ?$"

gText_ApprenticeMonThanks4::
	.string "{STR_VAR_1} ? C'est super !\p"
	.string "Sachant que c'est toi qui as pris la décision,\n"
	.string "{PLAYER}{KUN}, je ne serai pas trop déçu si\l"
	.string "je perds.\p"
	.string "D'accord, je compterai encore sur tes conseils.\n"
	.string "Salut !$"

gText_ApprenticeWhichMon5::
	.string "Si ce n'est pas {PLAYER}{KUN}\n"
	.string "! Comment ça va ?\p"
	.string "Je suis encore occupé comme toujours !\n"
	.string "Je veux bien faire avec\l"
	.string "les POKéMON aussi,\p"
	.string "mais je n'ai pas le temps de m'entraîner.\n"
	.string "{PLAYER}{KUN}, donne-moi un conseil !\p"
	.string "Quelle capacité mon {STR_VAR_1}\n"
	.string "devrait-il apprendre ?$"

gText_ApprenticeMonThanks5::
	.string "D'accord, compris.\n"
	.string "Je trouverai le temps et j'attraperai\l"
	.string "ce {STR_VAR_1} que tu m'as recommandé.\p"
	.string "Je suis content d'avoir trouvé un bon mentor en toi.\n"
	.string "Merci ! À plus !$"

gText_ApprenticeWhichMon6::
	.string "Oh !\n"
	.string "Yay, c'est {PLAYER} !\p"
	.string "Je n'ai pas perdu de\n"
	.string "temps à me vanter auprès\p"
	.string "de mes amis de\n"
	.string "t'avoir rencontré !\p"
	.string "J'ai besoin de puiser dans\n"
	.string "ton esprit à nouveau !\p"
	.string "Quelle capacité\n"
	.string "mon {STR_VAR_1}\l"
	.string "devrait-il apprendre ?$"

gText_ApprenticeMonThanks6::
	.string "Ahhh !\n"
	.string "{STR_VAR_1}, tu dis !\l"
	.string "Merci pour une réponse vraiment cool !\p"
	.string "Je crois que c'est tout ce que je voulais\n"
	.string "te demander aujourd'hui.\p"
	.string "On se revoit ici, d'accord ?\n"
	.string "Merci !$"

gText_ApprenticeWhichMon7::
	.string "Oh, c'est toi, {PLAYER} ?\n"
	.string "Je suis ravi de te revoir !\p"
	.string "Depuis que je suis devenu ton apprenti,\n"
	.string "ma confiance a fleuri.\p"
	.string "Je pense que je suis prêt à élever un POKéMON\n"
	.string "à moi !\p"
	.string "{PLAYER}, puis-je t'imposer de choisir\n"
	.string "quel POKéMON je devrais élever ?\p"
	.string "Les choix sont les POKéMON\n"
	.string "{STR_VAR_1} ou {STR_VAR_2}…\l"
	.string "Quel POKéMON me convient ?$"

gText_ApprenticeMonThanks7::
	.string "Un {STR_VAR_1}, c'est ça !\n"
	.string "J'en trouverai un tout de suite !\p"
	.string "Merci, {PLAYER}.\n"
	.string "J'espère pouvoir encore compter sur toi.\l"
	.string "Prends soin de toi !$"

gText_ApprenticeWhichMon8::
	.string "Eek ! {PLAYER} ! On se revoit !\n"
	.string "Je… Je suis ravie !\p"
	.string "Oh-oh-oh, je sais !\n"
	.string "Je ne dois pas rater cette occasion !\p"
	.string "Puis-je te demander une énorme\n"
	.string "faveur, {PLAYER} ? Choisis un\p"
	.string "POKéMON pour moi !\n"
	.string "Décide lequel serait le mieux, {STR_VAR_1} ou {STR_VAR_2} !$"

gText_ApprenticeMonThanks8::
	.string "Wow ! Tu as décidé pour moi !\n"
	.string "Un {STR_VAR_1}, c'est ce que j'élèverai\l"
	.string "au mieux de mes capacités.\p"
	.string "J'espère que tu voudras bien\n"
	.string "m'enseigner encore une autre fois.$"

gText_ApprenticeWhichMon9::
	.string "Hé, hé ! Mon mentor,\n"
	.string "{PLAYER}{KUN} ! Salut, je te\p"
	.string "cherchais pour avoir encore de\n"
	.string "tes sages conseils ! Quel\p"
	.string "type de POKéMON me conviendrait,\n"
	.string "un {STR_VAR_1} ou {STR_VAR_2}\p"
	.string "? Ne sois pas\n"
	.string "timide. Dis-le franchement !$"

gText_ApprenticeMonThanks9::
	.string "Ah oui, un {STR_VAR_1}, c'est ça\n"
	.string "! OK, nickel ! Je vais\l"
	.string "en attraper un dans une BALL,\p"
	.string "genre, direct ! D'accord, merci\n"
	.string "comme toujours ! Adios !$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}{KUN},\n"
	.string "écoute\p"
	.string "! Grande\n"
	.string "nouvelle !\p"
	.string "J'ai attrapé un\n"
	.string "POKéMON mirage !\l"
	.string "Bien sûr je mens !\p"
	.string "Wahahaha !\n"
	.string "Mais\l"
	.string "sérieusement, j'ai\p"
	.string "attrapé un\n"
	.string "POKéMON rare !$"

gText_ApprenticeMonThanks10::
	.string "OK, donc c'est {STR_VAR_1} que tu as choisi ?\n"
	.string "Je prendrai l'autre sorte, alors !\p"
	.string "Je plaisante !\n"
	.string "J'obéirai à ton enseignement, maître !\p"
	.string "Merci, maître !\n"
	.string "J'espère que tu continueras à m'enseigner !$"

gText_ApprenticeWhichMon11::
	.string "A-H-O-Y !\n"
	.string "Et ça épelle ahoy !\p"
	.string "Le MARIN rappeur,\n"
	.string "c'est moi !\p"
	.string "Tu te souviens sûrement\n"
	.string "de qui je suis ?\p"
	.string "Aujourd'hui, j'ai\n"
	.string "attrapé un\l"
	.string "gros poisson !$"

gText_ApprenticeMonThanks11::
	.string "{STR_VAR_1}, tu dis, hé hé !\n"
	.string "Je vais m'en trouver un tout de suite !\p"
	.string "Si j'ai besoin de conseils,\n"
	.string "{PLAYER}, j'écouterai toujours tes paroles !$"

gText_ApprenticeWhichMon12::
	.string "Oh, waouh, si ce\p"
	.string "n'est pas {PLAYER} !\n"
	.string "Que devrais-je faire ?\p"
	.string "Demander ton conseil ?\n"
	.string "Pourquoi pas ? Je\l"
	.string "te parle déjà !\l"
	.string "Ça fait longtemps !\p"
	.string "{PLAYER}, quelle\n"
	.string "capacité mon {STR_VAR_1}\l"
	.string "devrait-il apprendre ?$"

gText_ApprenticeMonThanks12::
	.string "Si ce {STR_VAR_1} est le meilleur,\n"
	.string "je ferai comme tu me le conseilles !\p"
	.string "Bon, {PLAYER}, je dois vagabonder,\n"
	.string "mais ne m'oublie pas.\p"
	.string "À bientôt, mon ami malin !$"

gText_ApprenticeWhichMon13::
	.string "Oh, salut,\n"
	.string "{PLAYER}{KUN}…\p"
	.string "J'ai un horrible\n"
	.string "mal de tête…\p"
	.string "Je dois m'être\n"
	.string "trop inquiété pour\p"
	.string "le genre de\n"
	.string "POKéMON à choisir…\l"
	.string "{PLAYER}{KUN}, aide-moi !$"

gText_ApprenticeMonThanks13::
	.string "Hm, un {STR_VAR_1}, d'accord.\n"
	.string "J'irai en chercher un quand j'irai mieux.\p"
	.string "J'espère pouvoir encore compter sur toi\n"
	.string "pour de l'aide comme ça.$"

gText_ApprenticeWhichMon14::
	.string "Euh… Euh…\n"
	.string "{PLAYER}{KUN}… ?\p"
	.string "S'il te plaît, ne me\n"
	.string "regarde pas comme ça.\l"
	.string "Je suis tout confus…\p"
	.string "Euh…\n"
	.string "J'ai besoin de ton aide.\p"
	.string "Entre {STR_VAR_1} et\n"
	.string "{STR_VAR_2}, lequel ?$"

gText_ApprenticeMonThanks14::
	.string "Oh… D'accord !\n"
	.string "Je vais faire de mon mieux avec un {STR_VAR_1}.\p"
	.string "J'espère pouvoir donner le meilleur de moi-même\n"
	.string "sans trop me déconcentrer.\p"
	.string "Merci, {PLAYER}{KUN}.\n"
	.string "Si on se revoit, j'espère que tu seras\l"
	.string "toujours aussi serviable.$"

gText_ApprenticeWhichMon15::
	.string "Hm ? Tu sembles\n"
	.string "être {PLAYER}{KUN}…\p"
	.string "Mais es-tu\n"
	.string "vraiment réel ?\l"
	.string "Non, non, si tu es\p"
	.string "réel, c'est bien.\p"
	.string "Je veux juste que\n"
	.string "tu me reconnaisses\l"
	.string "comme ton apprenti.$"

gText_ApprenticeMonThanks15::
	.string "{STR_VAR_1} ?\n"
	.string "Tu es sûr ?\p"
	.string "Je vois. Dans ce cas, très bien.\n"
	.string "Merci pour ton temps.\p"
	.string "J'espère que c'est quelque chose que même moi\n"
	.string "je pourrai gérer avec aplomb.\p"
	.string "À une prochaine fois !$"

gText_ApprenticeWhichMove0::
	.string "Waaah ! Oh, {PLAYER} !\n"
	.string "Snif… Hic…\p"
	.string "J'ai un dilemme !\n"
	.string "Je n'arrive pas à choisir une\l"
	.string "capacité pour mon {STR_VAR_1}…\p"
	.string "S'il te plaît, {PLAYER}.\n"
	.string "Tu peux choisir pour moi ?\p"
	.string "Pour mon {STR_VAR_1}, quelle capacité\n"
	.string "serait le meilleur choix : {STR_VAR_2}\l"
	.string "ou {STR_VAR_3} ?$"

gText_ApprenticeMoveThanks0::
	.string "{STR_VAR_1} ?\n"
	.string "Waaaaah !\p"
	.string "Oh ! Je suis désolé, {PLAYER} !\n"
	.string "Tu m'as rendu si heureux en choisissant\l"
	.string "ce mouvement que je pleure…\p"
	.string "Snif…\n"
	.string "Merci beaucoup !$"

gText_ApprenticeWhichMove1::
	.string "Yay ! Salut, {PLAYER} !\n"
	.string "J'ai encore besoin de tes conseils !\p"
	.string "Je veux apprendre une attaque cool\n"
	.string "à mon {STR_VAR_1}.\p"
	.string "J'hésite entre les attaques\n"
	.string "{STR_VAR_2} ou {STR_VAR_3}.\l"
	.string "Qu'est-ce que tu recommandes ?$"

gText_ApprenticeMoveThanks1::
	.string "{STR_VAR_1} est mieux ? Je suppose !\n"
	.string "D'accord, je vais choisir ça !\p"
	.string "Si on se revoit ici, enseigne-moi\n"
	.string "autre chose, mentor !$"

gText_ApprenticeWhichMove2::
	.string "{PLAYER}, bonjour !\n"
	.string "C'est à propos de mon {STR_VAR_1}, mais je\l"
	.string "suis inquiet pour ses attaques.\p"
	.string "Tu vois, ce sont les attaques {STR_VAR_2}\n"
	.string "et {STR_VAR_3}.\p"
	.string "Laquelle est la plus forte et la meilleure\n"
	.string "pour mon {STR_VAR_1} ?$"

gText_ApprenticeMoveThanks2::
	.string "{STR_VAR_1} est ton choix ?\n"
	.string "OK, compris ! Je vais\p"
	.string "aller apprendre {STR_VAR_1} à mon\n"
	.string "POKéMON tout de suite\p"
	.string "! À bientôt !$"

gText_ApprenticeWhichMove3::
	.string "Ohhh, {PLAYER}…\n"
	.string "Je suis désespéré, vraiment !\p"
	.string "J'ai décidé d'élever un POKéMON,\n"
	.string "mais maintenant je n'arrive même pas à décider\l"
	.string "quelle capacité lui apprendre…\p"
	.string "Je sais que ça ne veut rien dire\n"
	.string "pour toi, {PLAYER}.\p"
	.string "Mais ça compte beaucoup pour moi…\p"
	.string "S'il te plaît, {PLAYER}, pourrais-tu choisir\n"
	.string "une capacité pour mon {STR_VAR_1} ?\p"
	.string "Si tu pouvais même choisir entre\n"
	.string "{STR_VAR_2} et {STR_VAR_3}…$"

gText_ApprenticeMoveThanks3::
	.string "Je comprends !\p"
	.string "Mais sera-t-il même prêt à apprendre\n"
	.string "{STR_VAR_1} pour moi...\l"
	.string "Non ! Je ferai de mon mieux !\p"
	.string "Merci !$"

gText_ApprenticeWhichMove4::
	.string "Oh, {PLAYER}{KUN} !\n"
	.string "J'espérais te\p"
	.string "voir aussi !\n"
	.string "Je me demandais quelle\p"
	.string "capacité serait\n"
	.string "appropriée pour\p"
	.string "mon {STR_VAR_1}.\n"
	.string "{PLAYER}{KUN},\l"
	.string "que ferais-tu ?$"

gText_ApprenticeMoveThanks4::
	.string "{STR_VAR_1} ? C'est super !\p"
	.string "Sachant que c'est toi qui as pris la décision,\n"
	.string "{PLAYER}{KUN}, je ne serai pas trop déçu si\l"
	.string "je perds.\p"
	.string "D'accord, je compterai encore sur tes conseils.\n"
	.string "Salut !$"

gText_ApprenticeWhichMove5::
	.string "Comment les choses peuvent-elles être\n"
	.string "si chargées ?\l"
	.string "Hé, si ce n'est pas {PLAYER}{KUN} !\p"
	.string "Comment ça va ?\n"
	.string "Depuis ce matin, j'ai fait mon jogging,\p"
	.string "ma natation et ma cuisine !\p"
	.string "Tu ne croirais pas à quel point je suis occupé !\n"
	.string "Je n'arrive même pas à décider quelle\p"
	.string "capacité mon {STR_VAR_1} devrait apprendre !\n"
	.string "{STR_VAR_2} a l'air bien, hein ?\p"
	.string "Mais {STR_VAR_3} est pas mal aussi.\n"
	.string "{PLAYER}{KUN}, donne-moi un bon conseil ! Quelle capacité serait bien pour moi ?$"

gText_ApprenticeMoveThanks5::
	.string "D'accord, j'ai compris.\n"
	.string "Je vais libérer du temps dans mon emploi du temps et\l"
	.string "enseigner cette capacité.\p"
	.string "Je suis content d'avoir trouvé un bon mentor en toi.\n"
	.string "Merci ! À bientôt !$"

gText_ApprenticeWhichMove6::
	.string "Oh ! Quelle chance\n"
	.string "! On se revoit,\l"
	.string "{PLAYER} ! J'ai encore\p"
	.string "besoin de ton avis\n"
	.string "aujourd'hui. Roulement de tambour\p"
	.string "! Quelle capacité pour\n"
	.string "mon {STR_VAR_1}, {STR_VAR_2}\l"
	.string "ou {STR_VAR_3} ?$"

gText_ApprenticeMoveThanks6::
	.string "Ahhh !\n"
	.string "{STR_VAR_1}, tu dis !\l"
	.string "Merci pour une réponse vraiment cool !\p"
	.string "Je crois que c'est tout ce que je voulais\n"
	.string "te demander aujourd'hui.\p"
	.string "On se revoit ici, d'accord ?\n"
	.string "Merci !$"

gText_ApprenticeWhichMove7::
	.string "Oh, bonjour, {PLAYER}. J'espère que tu\n"
	.string "vas bien ? J'ai encore\p"
	.string "besoin de tes conseils. C'est\n"
	.string "à propos de mon cher\p"
	.string "{STR_VAR_1}. Quelle serait la capacité\n"
	.string "idéale pour mon adorable {STR_VAR_1}\l"
	.string "? {STR_VAR_2} ou {STR_VAR_3} ?$"

gText_ApprenticeMoveThanks7::
	.string "{STR_VAR_1}, c'est noté !\n"
	.string "Je vais lui apprendre tout de suite !\p"
	.string "Merci, {PLAYER}.\n"
	.string "J'espère pouvoir compter sur toi.\l"
	.string "Prends soin de toi !$"

gText_ApprenticeWhichMove8::
	.string "Eek ! {PLAYER}\n"
	.string "! Je t'ai revu !\p"
	.string "Je… Je suis\n"
	.string "comblée de joie !\p"
	.string "Chaque fois\n"
	.string "que j'ai\p"
	.string "besoin, tu\n"
	.string "es toujours\p"
	.string "là pour moi !\n"
	.string "Merci, {PLAYER} !$"

gText_ApprenticeMoveThanks8::
	.string "Oh-oh-oh ! Merci !\n"
	.string "{STR_VAR_1}, c'est ça !\l"
	.string "Parfaitement compris !\p"
	.string "J'espère que tu voudras bien m'enseigner\n"
	.string "encore quelque chose une autre fois.$"

gText_ApprenticeWhichMove9::
	.string "Hola, {PLAYER}{KUN}, bueno ! J'espère\n"
	.string "encore un peu de tes\l"
	.string "sages conseils aujourd'hui ! Quelle\p"
	.string "serait la meilleure capacité pour\n"
	.string "mon {STR_VAR_1} ? Ça devrait\p"
	.string "être quelque chose qui me\n"
	.string "fait gagner comme ça\p"
	.string "! Ce serait {STR_VAR_2}\n"
	.string "? Ou {STR_VAR_3} ?$"

gText_ApprenticeMoveThanks9::
	.string "Ah oui, {STR_VAR_1}, c'est ça\n"
	.string "! Si, bueno ! Je\l"
	.string "vais l'apprendre, genre, boum\p"
	.string "! D'accord, merci comme\n"
	.string "toujours ! Adios !$"

gText_ApprenticeWhichMove10::
	.string "{PLAYER}{KUN}, c'est\p"
	.string "complètement fou !\n"
	.string "Mon POKéMON !\p"
	.string "Il a appris\n"
	.string "six capacités !\p"
	.string "Bien sûr je mens !\n"
	.string "Wahahaha !\l"
	.string "Ce n'est pas\p"
	.string "un mensonge !\n"
	.string "Il a appris une\p"
	.string "nouvelle capacité !\n"
	.string "C'est génial, non ?$"

gText_ApprenticeMoveThanks10::
	.string "OK, donc c'est {STR_VAR_1} que tu as choisi ?\n"
	.string "Je choisirai une autre attaque, alors !\p"
	.string "Je plaisante !\n"
	.string "J'obéirai à ton enseignement, maître !\p"
	.string "Merci, maître !\n"
	.string "J'espère que tu continueras à m'enseigner !$"

gText_ApprenticeWhichMove11::
	.string "A-H-O-Y !\n"
	.string "Et ça épelle ahoy !\p"
	.string "Le MARIN rappeur,\n"
	.string "c'est moi !\p"
	.string "Je suis toujours\n"
	.string "au top, ne\p"
	.string "me demande\n"
	.string "pas pourquoi.\l"
	.string "À plus, {PLAYER}{KUN} !$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}, tu dis, hé hé !\n"
	.string "Je vais l'enseigner tout de suite !\p"
	.string "Si j'ai besoin de conseils,\n"
	.string "{PLAYER}, j'écouterai toujours tes paroles !$"

gText_ApprenticeWhichMove12::
	.string "Oh, ouaisah, si ce\p"
	.string "n'est pas {PLAYER} !\n"
	.string "Que devrais-je faire ?\p"
	.string "Demander ton conseil ?\n"
	.string "Pourquoi pas ? Je\p"
	.string "te parle déjà !\n"
	.string "{PLAYER}, tu en as marre de moi ?\p"
	.string "Nah, pas possible.\n"
	.string "Quelle capacité mon {STR_VAR_1}\l"
	.string "devrait-il apprendre ?$"

gText_ApprenticeMoveThanks12::
	.string "Si ce {STR_VAR_1} est le meilleur,\n"
	.string "je ferai comme tu me le conseilles !\p"
	.string "Bon, {PLAYER}, je dois vagabonder,\n"
	.string "mais ne m'oublie pas.\p"
	.string "À bientôt, mon ami malin !$"

gText_ApprenticeWhichMove13::
	.string "Gahack ! Gaah !\n"
	.string "Oh, {PLAYER}{KUN}…\p"
	.string "J'ai ce maudit rhume…\n"
	.string "Je veux choisir une\p"
	.string "capacité pour\n"
	.string "mon POKéMON\p"
	.string "mais je n'arrive\n"
	.string "pas à me concentrer…\l"
	.string "{PLAYER}{KUN}, aide-moi !$"

gText_ApprenticeMoveThanks13::
	.string "Hm, {STR_VAR_1}, d'accord. Toussot !\n"
	.string "J'irai l'enseigner quand j'irai mieux.\p"
	.string "J'espère pouvoir encore compter sur toi\n"
	.string "pour de l'aide comme ça.$"

gText_ApprenticeWhichMove14::
	.string "Euh… Euh…\n"
	.string "{PLAYER}{KUN}… ?\p"
	.string "S'il te plaît, ne me\n"
	.string "regarde pas comme ça.\l"
	.string "Je suis tout confus…\p"
	.string "Euh…\n"
	.string "J'ai vraiment\l"
	.string "besoin de ton aide.\p"
	.string "Entre {STR_VAR_1} et\n"
	.string "{STR_VAR_2},\l"
	.string "lequel choisir ?$"

gText_ApprenticeMoveThanks14::
	.string "Oh… D'accord !\n"
	.string "Je vais essayer cette {STR_VAR_1}.\p"
	.string "J'espère pouvoir enseigner cette attaque…\n"
	.string "C'est tellement stressant…\p"
	.string "Merci, {PLAYER}{KUN}.\n"
	.string "Si on se revoit, j'espère que tu seras\l"
	.string "toujours aussi serviable.$"

gText_ApprenticeWhichMove15::
	.string "Hm ? Tu sembles\n"
	.string "être {PLAYER}{KUN}…\p"
	.string "Mais es-tu vraiment réel ?\n"
	.string "Peut-être es-tu une\p"
	.string "de ces imitations\n"
	.string "populaires ?\p"
	.string "Non, non, si tu es\n"
	.string "réel, c'est bien.\p"
	.string "Je veux juste que\p"
	.string "tu me reconnaisses\n"
	.string "comme ton apprenti.$"

gText_ApprenticeMoveThanks15::
	.string "{STR_VAR_1} ? Tu n'as aucun\n"
	.string "doute ? Je vois. Si\p"
	.string "c'est le cas, très bien.\n"
	.string "Je te remercie de ton\p"
	.string "temps. J'espère que c'est quelque\n"
	.string "chose que même mes POKéMON\p"
	.string "peuvent apprendre. Retrouvons-nous !$"

gText_ApprenticePickWinSpeech0::
	.string "Oh… {PLAYER} ?\n"
	.string "C'est {PLAYER} !\l"
	.string "Oh ! Snif… sanglote…\p"
	.string "Écoute, s'il\n"
	.string "te plaît !\p"
	.string "Je… Quand je combats,\n"
	.string "je suis si nerveux,\p"
	.string "je ne sais pas quelle\n"
	.string "capacité utiliser…\l"
	.string "{PLAYER}, aide-moi !$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "Génial ! Wicked\n"
	.string "! Awoooh !\p"
	.string "C'est vraiment\n"
	.string "cool !\p"
	.string "Oh… Je suis\n"
	.string "désolé…\p"
	.string "Je suis si heureux,\n"
	.string "je pleure…\p"
	.string "Merci,\n"
	.string "{PLAYER}{KUN} !$"

gText_ApprenticePickWinSpeech1::
	.string "Youpi ! C'est {PLAYER} ! Salut !\n"
	.string "Je voulais te demander quelque chose !\p"
	.string "Je veux dire quelque chose de cool quand\n"
	.string "je gagne un combat.\p"
	.string "Tu as une phrase cool à\n"
	.string "me recommander ?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1} Oh, waouh !\p"
	.string "C'est trop cool !\n"
	.string "D'accord, je dirai ça\p"
	.string "! Merci de m'avoir\n"
	.string "tout appris, {PLAYER}{KUN}\l"
	.string "! Je vais\p"
	.string "devenir un DRESSEUR\n"
	.string "comme toi !$"

gText_ApprenticePickWinSpeech2::
	.string "{PLAYER}, bonjour ! Mon POKéMON et\p"
	.string "moi sommes prêts à tout, sauf\n"
	.string "pour une chose. Je pense\p"
	.string "qu'il me faudrait quelque chose\n"
	.string "à crier quand je gagne.\p"
	.string "Tu pourrais trouver quelque chose\n"
	.string "de bien à dire ?$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1} …Cool ! Je\p"
	.string "vais utiliser ça !\n"
	.string "Je vais aller me\p"
	.string "battre partout. Qui sait,\n"
	.string "peut-être qu'un jour je\p"
	.string "me battrai contre toi,\n"
	.string "{PLAYER}. La prochaine fois,\p"
	.string "retrouvons-nous sur un terrain\n"
	.string "de combat !$"

gText_ApprenticePickWinSpeech3::
	.string "Bonjour, {PLAYER}…\n"
	.string "Je suis désolé\p"
	.string "de t'embêter,\n"
	.string "mais je suis désespéré…\l"
	.string "Même quand…\p"
	.string "Même quand je gagne,\n"
	.string "je n'ai personne\p"
	.string "à qui me vanter.\p"
	.string "{PLAYER}, sois\n"
	.string "mon ami !$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "C'est inspirant…\p"
	.string "Euh… Est-ce que\n"
	.string "quelqu'un comme moi\p"
	.string "a le droit\p"
	.string "de dire ça ?\n"
	.string "Non ! Je vais faire\p"
	.string "de mon mieux !\p"
	.string "{PLAYER}, merci\n"
	.string "pour tout !\l"
	.string "Adieu, mon mentor !$"

gText_ApprenticePickWinSpeech4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "Il y a quelque chose que\p"
	.string "je veux que tu entendes.\n"
	.string "Je sais que je n'ai\p"
	.string "pas toujours l'air\n"
	.string "nice ou poli…\p"
	.string "Quand je gagne, je suis content.\n"
	.string "Quand je perds, je suis contrarié.\l"
	.string "C'est normal, non ?\p"
	.string "Mais je veux devenir plus fort.\n"
	.string "Alors, combattons !$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1} Pas mal ! Oui, je\p"
	.string "vais choisir ça ! Je vais\n"
	.string "prendre la route et faire\p"
	.string "ce que je peux avec\n"
	.string "ce que tu m'as enseigné\l"
	.string "dans ma tête et mon\p"
	.string "cœur. Désolé d'avoir été si\n"
	.string "insistant avec toi ! La\p"
	.string "prochaine fois, on se bat,\n"
	.string "OK ? À plus !$"

gText_ApprenticePickWinSpeech5::
	.string "Oh, je n'arrive pas à croire\n"
	.string "à quel point je suis occupé !\p"
	.string "Oh, hé, je te cherchais, {PLAYER}{KUN}.\n"
	.string "Tu vas bien comme d'habitude ?\p"
	.string "Les choses n'ont pas changé pour moi.\n"
	.string "J'ai de la course, des combats et de la cartographie\p"
	.string "à faire. Pourquoi suis-je si occupé ?\n"
	.string "Mais même si je suis occupé, ce serait impoli\l"
	.string "de partir après une victoire sans dire un mot.\p"
	.string "Alors, quelle serait une phrase cool pour\n"
	.string "souligner ma classe quand j'ai fini\l"
	.string "et que je m'en vais ? {PLAYER}{KUN}, aide-moi !$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "D'accord, compris.\n"
	.string "Je trouverai le temps de dire ça !\p"
	.string "Honnêtement, je suis content d'avoir\n"
	.string "rencontré un bon mentor comme toi.\p"
	.string "Je vais trouver le temps pour me\n"
	.string "lancer dans les combats.\p"
	.string "Merci pour tout, {PLAYER}{KUN} !\n"
	.string "Il faudra qu'on se batte un jour !$"

gText_ApprenticePickWinSpeech6::
	.string "J'ai encore de la chance ! {PLAYER}\n"
	.string "! Je suis content de te voir\l"
	.string "! Comme d'habitude, j'ai besoin de tes\p"
	.string "conseils ! Roulement de tambour, s'il\n"
	.string "vous plaît ! Ma dernière question\p"
	.string "est… Si je gagne un combat\n"
	.string "et veux le terminer avec un\l"
	.string "geste stylé, que dois-je dire ?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "C'est… C'est\n"
	.string "fabuleux !\p"
	.string "C'est digne et cool\n"
	.string "! Je le réclame !\p"
	.string "…Écoute, je pense que\n"
	.string "je deviens pas mal\p"
	.string "à ça, non ?\p"
	.string "Merci, {PLAYER}{KUN} !\n"
	.string "Tu es un\p"
	.string "super mentor !$"

gText_ApprenticePickWinSpeech7::
	.string "Oh, {PLAYER}.\n"
	.string "Je suis si\p"
	.string "content de\n"
	.string "t'avoir\p"
	.string "rencontré !\p"
	.string "Je n'ai plus\n"
	.string "de soucis\p"
	.string "concernant\n"
	.string "mes POKéMON.\p"
	.string "Merci pour\n"
	.string "tout, {PLAYER} !$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "Ah ! Ce dicton !\n"
	.string "Il me rafraîchit\p"
	.string "et me fait me\p"
	.string "sentir renaître !\n"
	.string "Je dois\p"
	.string "l'utiliser\n"
	.string "tout de suite !\p"
	.string "Merci,\n"
	.string "{PLAYER}{KUN} !$"

gText_ApprenticePickWinSpeech8::
	.string "Eek ! J'ai repéré {PLAYER} !\n"
	.string "Je… Je suis ravie de te voir !\p"
	.string "Oh-oh-oh ! Il y a quelque\n"
	.string "chose que je devais\p"
	.string "te demander !\n"
	.string "Un petit conseil de\p"
	.string "ta part, {PLAYER} !\n"
	.string "Quelle capacité\p"
	.string "mon {STR_VAR_1}\n"
	.string "devrait-il apprendre ?$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "Ouuaaaah !\n"
	.string "Je vais dire ça ?!\l"
	.string "Je… Je suis\p"
	.string "fou de joie !\n"
	.string "M-merci !\p"
	.string "Je n'ai plus rien\n"
	.string "à te demander.\p"
	.string "Adieu,\n"
	.string "{PLAYER}{KUN} !\p"
	.string "Tu es le meilleur\n"
	.string "mentor !$"

gText_ApprenticePickWinSpeech9::
	.string "Hola, bueno !\n"
	.string "{PLAYER}{KUN} !\p"
	.string "Tu sais, j'ai\n"
	.string "envie de vagabonder\p"
	.string "et combattre\n"
	.string "où je peux.\p"
	.string "Mais avant ça, j'ai\n"
	.string "besoin de\l"
	.string "ton conseil !$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1} Mh-mh, c'est mignon ! Si,\p"
	.string "bueno ! Je vais essayer\n"
	.string "de dire ça, genre, ham\l"
	.string "! Et maintenant, c'est l'heure\p"
	.string "de dire au revoir !\n"
	.string "Merci pour plein de choses\p"
	.string "! Offre-moi un combat un\n"
	.string "jour, OK ? Adios !$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}{KUN},\p"
	.string "gros problème !\n"
	.string "Quand je gagne un\p"
	.string "combat, je me vante\n"
	.string "pendant au moins\p"
	.string "une heure !\n"
	.string "Mais aujourd'hui\p"
	.string "j'ai perdu…\n"
	.string "Je suis trop triste\l"
	.string "pour me vanter !$"

gText_ApprenticeWinSpeechThanks10::
	.string "Ma femme adore le POKéMON EVOLI.\p"
	.string "Elle connaît toutes les façons dont ils peuvent\n"
	.string "évoluer. Comme, en TENANT une PIERRE EAU,\p"
	.string "ou une PIERRE PLANTE.\n"
	.string "Oui, TENIR, pas utiliser !\p"
	.string "Tu le savais ? Moi pas.\n"
	.string "Ou être HEUREUX pendant le jour ou la nuit.\p"
	.string "Ou être mignon en utilisant une\n"
	.string "capacité de type FÉE !\p"
	.string "…\n"
	.string "Tu sais où sont les EVOLI ?\p"
	.string "Peut-être que je devrais\p"
	.string "en capturer un pour elle.\n"
	.string "Elle va adorer !$"

gText_ApprenticePickWinSpeech11::
	.string "A-H-O-Y ! Et ça fait ahoy\n"
	.string "! Le MARIN qui rappe,\p"
	.string "c'est moi ! Ce sera\n"
	.string "ma dernière question, ne pleure\l"
	.string "pas ! C'est une question\p"
	.string "de réplique qui demande ta\n"
	.string "suggestion ! Si je gagne\p"
	.string "un match, que puis-je dire\n"
	.string "de façon vraiment cool ?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "Parfait ! C'est ce\n"
	.string "que j'utiliserai.\p"
	.string "J'avais raison de\n"
	.string "te faire choisir !\p"
	.string "Et maintenant, je\n"
	.string "pense qu'il est temps\p"
	.string "de dire au revoir.\n"
	.string "Merci,\l"
	.string "{PLAYER}{KUN} !$"

gText_ApprenticePickWinSpeech12::
	.string "Oh, ouais,\n"
	.string "{PLAYER} !\p"
	.string "Je t'ai retrouvé\n"
	.string "aujourd'hui !\p"
	.string "Que devrais-je faire\n"
	.string "? Te redemander ?\l"
	.string "Pourquoi pas ? Je\l"
	.string "te demande déjà !\p"
	.string "Bref, {PLAYER}, tu\n"
	.string "en as marre de moi ?\l"
	.string "Nah, pas possible.\p"
	.string "Écoute-moi !$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "D'accord, d'accord !\n"
	.string "Je vais utiliser ça parce que c'est trop cool !\p"
	.string "Je n'ai plus rien à te demander.\n"
	.string "Il ne reste qu'à te dire au revoir.\p"
	.string "Mais peut-être qu'un jour on se reverra,\n"
	.string "l'un destiné à être vaincu.\p"
	.string "Mais vraiment, il est temps de dire adieu.\p"
	.string "Bon, {PLAYER}, je dois vagabonder librement,\n"
	.string "mais ne m'oublie pas !\p"
	.string "Prends soin de toi, {PLAYER} !\n"
	.string "Je t'aime !$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}, j'ai fini…\n"
	.string "Mon nez ne s'arrête\p"
	.string "pas de couler…\n"
	.string "J'essayais de trouver\p"
	.string "quelque chose de cool à dire\n"
	.string "quand je gagne\p"
	.string "un combat, mais…\n"
	.string "Je n'arrive à rien !\p"
	.string "{PLAYER}{KUN},\n"
	.string "donne-moi un conseil !$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "… … …C'est bien.\n"
	.string "Non, c'est\l"
	.string "inspirant !\p"
	.string "Ça me fait\n"
	.string "verser\p"
	.string "des larmes\n"
	.string "de joie !\p"
	.string "Merci,\n"
	.string "{PLAYER}{KUN} !$"

gText_ApprenticePickWinSpeech14::
	.string "Euh… Hum…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "S'il te plaît, ne me regarde pas\n"
	.string "comme ça. Tu me rends nerveux.\p"
	.string "J'ai… encore besoin de tes conseils.\n"
	.string "Ce sera le dernier, promis…\p"
	.string "C'est vraiment embarrassant de\n"
	.string "demander, mais si je gagne un\l"
	.string "combat ? Que devrais-je dire ?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1} Oh… D'accord ! J'essaierai\p"
	.string "de dire ça ! Je\n"
	.string "serai peut-être trop nerveux… Merci,\l"
	.string "{PLAYER}{KUN}. Je dois te dire\p"
	.string "au revoir. J'obéirai à\n"
	.string "tout ce que tu\p"
	.string "m'as enseigné, {PLAYER}{KUN}, et\n"
	.string "ferai de mon mieux.$"

gText_ApprenticePickWinSpeech15::
	.string "Hm ? Tu sembles\n"
	.string "être {PLAYER}{KUN}…\l"
	.string "Mais l'es-tu vraiment ?\p"
	.string "Peut-être une POUPEE\n"
	.string "{PLAYER} intelligente ?\l"
	.string "Oh, non, non, non,\p"
	.string "ne t'inquiète pas !\n"
	.string "Si tu es réel, c'est bien.\p"
	.string "Je veux juste que\p"
	.string "tu me reconnaisses\n"
	.string "comme ton apprenti.$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "… … … … … …\n"
	.string "Quand je gagne un match…\p"
	.string "{STR_VAR_1}\p"
	.string "…Tu es sérieux ?\p"
	.string "Je vois. Si tu es\n"
	.string "sérieux, c'est bien.\p"
	.string "Je te remercie\n"
	.string "pour ton temps.\p"
	.string "J'espère que moi aussi\n"
	.string "je pourrai un jour\p"
	.string "mettre ce dicton en pratique.\n"
	.string "Mais pour l'instant,\p"
	.string "je dois y aller.\n"
	.string "À plus !$"
