BattleDome_Text_Potential1::
	.string "Le meilleur candidat au titre de champion !$"

BattleDome_Text_Potential2::
	.string "Une équipe sûrement finaliste.$"

BattleDome_Text_Potential3::
	.string "Un finisseur probable du top trois.$"

BattleDome_Text_Potential4::
	.string "Un candidat à la première place.$"

BattleDome_Text_Potential5::
	.string "Une équipe au potentiel de premier ordre.$"

BattleDome_Text_Potential6::
	.string "L'équipe surprise de ce tournoi.$"

BattleDome_Text_Potential7::
	.string "Une équipe au-dessus de la moyenne.$"

BattleDome_Text_Potential8::
	.string "L'équipe moyenne de ce tournoi.$"

BattleDome_Text_Potential9::
	.string "Une équipe au potentiel moyen.$"

BattleDome_Text_Potential10::
	.string "Une équipe en dessous de la moyenne.$"

BattleDome_Text_Potential11::
	.string "Une équipe en quête de sa première victoire.$"

BattleDome_Text_Potential12::
	.string "Une victoire rendra cette équipe fière.$"

BattleDome_Text_Potential13::
	.string "Dans l'ensemble, une équipe faible.$"

BattleDome_Text_Potential14::
	.string "Une équipe au potentiel très faible.$"

BattleDome_Text_Potential15::
	.string "Une équipe peu susceptible de gagner le tournoi.$"

BattleDome_Text_Potential16::
	.string "L'équipe la moins susceptible de gagner.$"

BattleDome_Text_PotentialDomeAceTucker::
	.string "La superstar parfaite et invincible !$"

BattleDome_Text_StyleRiskDisaster::
	.string "Prêt à risquer la catastrophe totale parfois.$"

BattleDome_Text_StyleEndureLongBattles::
	.string "Doué pour endurer de longs combats.$"

BattleDome_Text_StyleVariesTactics::
	.string "Varie ses tactiques selon l'adversaire.$"

BattleDome_Text_StyleToughWinningPattern::
	.string "A un schéma de victoire solide.$"

BattleDome_Text_StyleUsesVeryRareMove::
	.string "Utilise parfois une capacité très rare.$"

BattleDome_Text_StyleUsesStartlingMoves::
	.string "Utilise des capacités déconcertantes et perturbatrices.$"

BattleDome_Text_StyleConstantlyWatchesHP::
	.string "Surveille constamment les PV en combat.$"

BattleDome_Text_StyleStoresAndLoosesPower::
	.string "Bon pour stocker puis relâcher de la puissance.$"

BattleDome_Text_StyleEnfeeblesFoes::
	.string "Habile à affaiblir les adversaires.$"

BattleDome_Text_StylePrefersLuckTactics::
	.string "Privilégie les tactiques basées sur la chance.$"

BattleDome_Text_StyleRegalAtmosphere::
	.string "Attaque avec une atmosphère royale.$"

BattleDome_Text_StylePowerfulLowPPMoves::
	.string "Attaque avec des capacités puissantes à faible PP.$"

BattleDome_Text_StyleEnfeebleThenAttack::
	.string "Habile à affaiblir, puis attaquer.$"

BattleDome_Text_StyleBattlesWhileEnduring::
	.string "Combat en encaissant toutes les attaques.$"

BattleDome_Text_StyleUpsetsFoesEmotionally::
	.string "Habile à contrarier émotionnellement les ennemis.$"

BattleDome_Text_StyleStrongAndStraightforward::
	.string "Utilise des capacités fortes et directes.$"

BattleDome_Text_StyleAggressivelyStrongMoves::
	.string "Utilise agressivement des attaques puissantes.$"

BattleDome_Text_StyleCleverlyDodgesAttacks::
	.string "Combat en esquivant habilement les attaques.$"

BattleDome_Text_StyleUsesUpsettingMoves::
	.string "Doué pour utiliser des attaques déstabilisantes.$"

BattleDome_Text_StyleUsesPopularMoves::
	.string "Utilise beaucoup de capacités populaires.$"

BattleDome_Text_StyleHasPowerfulComboMoves::
	.string "A des capacités pour des combos puissants.$"

BattleDome_Text_StyleUsesHighProbabilityMoves::
	.string "Utilise des attaques à haute probabilité.$"

BattleDome_Text_StyleAggressivelySpectacularMoves::
	.string "Utilise agressivement des capacités spectaculaires.$"

BattleDome_Text_StyleEmphasizesOffenseOverDefense::
	.string "Privilégie l'attaque plutôt que la défense.$"

BattleDome_Text_StyleEmphasizesDefenseOverOffense::
	.string "Privilégie la défense plutôt que l'attaque.$"

BattleDome_Text_StyleAttacksQuicklyStrongMoves::
	.string "Attaque rapidement avec des capacités fortes.$"

BattleDome_Text_StyleUsesAddedEffectMoves::
	.string "Utilise souvent des capacités à effets secondaires.$"

BattleDome_Text_StyleUsesBalancedMixOfMoves::
	.string "Utilise un mélange équilibré de capacités.$"

BattleDome_Text_StyleSampleMessage1::
	.string "Ceci est le message d'exemple 1.$"

BattleDome_Text_StyleSampleMessage2::
	.string "Ceci est le message d'exemple 2.$"

BattleDome_Text_StyleSampleMessage3::
	.string "Ceci est le message d'exemple 3.$"

BattleDome_Text_StyleSampleMessage4::
	.string "Ceci est le message d'exemple 4.$"

BattleDome_Text_EmphasizesHPAndAtk::
	.string "Privilégie les PV et l'ATTAQUE.$"

BattleDome_Text_EmphasizesHPAndDef::
	.string "Privilégie les PV et la DÉFENSE.$"

BattleDome_Text_EmphasizesHPAndSpeed::
	.string "Privilégie les PV et la VITESSE.$"

BattleDome_Text_EmphasizesHPAndSpAtk::
	.string "Met l'accent sur les PV et l'ATQ. SPÉ.$"

BattleDome_Text_EmphasizesHPAndSpDef::
	.string "Met l'accent sur les PV et la DEF. SPÉ.$"

BattleDome_Text_EmphasizesAtkAndDef::
	.string "Met l'accent sur l'ATTAQUE et la DÉFENSE.$"

BattleDome_Text_EmphasizesAtkAndSpeed::
	.string "Met l'accent sur l'ATTAQUE et la VITESSE.$"

BattleDome_Text_EmphasizesAtkAndSpAtk::
	.string "Privilégie l'ATTAQUE et l'ATTAQUE SPÉC.$"

BattleDome_Text_EmphasizesAtkAndSpDef::
	.string "Privilégie l'ATTAQUE et la DÉF. SPÉC.$"

BattleDome_Text_EmphasizesDefAndSpeed::
	.string "Met l'accent sur la DÉFENSE et la VITESSE.$"

BattleDome_Text_EmphasizesDefAndSpAtk::
	.string "Privilégie la DÉFENSE et l'ATTAQUE SPÉC.$"

BattleDome_Text_EmphasizesDefAndSpDef::
	.string "Privilégie la DÉFENSE et la DÉF. SPÉC.$"

BattleDome_Text_EmphasizesSpeedAndSpAtk::
	.string "Privilégie la VITESSE et l'ATTAQUE SPÉC.$"

BattleDome_Text_EmphasizesSpeedAndSpDef::
	.string "Privilégie la VITESSE et la DÉF. SPÉC.$"

BattleDome_Text_EmphasizesSpAtkAndSpDef::
	.string "Met l'accent sur l'ATQ. SPÉ. et la DÉF. SPÉ.$"

BattleDome_Text_EmphasizesHP::
	.string "Privilégie les PV.$"

BattleDome_Text_EmphasizesAtk::
	.string "Privilégie l'ATTAQUE.$"

BattleDome_Text_EmphasizesDef::
	.string "Privilégie la DEFENSE.$"

BattleDome_Text_EmphasizesSpeed::
	.string "Privilégie la VITESSE.$"

BattleDome_Text_EmphasizesSpAtk::
	.string "Privilégie l'ATQ. SPÉ.$"

BattleDome_Text_EmphasizesSpDef::
	.string "Privilégie la DÉF. SPÉ.$"

BattleDome_Text_NeglectsHPAndAtk::
	.string "Néglige les PV et l'ATTAQUE.$"

BattleDome_Text_NeglectsHPAndDef::
	.string "Néglige les PV et la DÉFENSE.$"

BattleDome_Text_NeglectsHPAndSpeed::
	.string "Néglige les PV et la VITESSE.$"

BattleDome_Text_NeglectsHPAndSpAtk::
	.string "Néglige les PV et l'ATQ. SPÉ.$"

BattleDome_Text_NeglectsHPAndSpDef::
	.string "Néglige les PV et la DEF. SPÉ.$"

BattleDome_Text_NeglectsAtkAndDef::
	.string "Néglige l'ATTAQUE et la DÉFENSE.$"

BattleDome_Text_NeglectsAtkAndSpeed::
	.string "Néglige l'ATTAQUE et la VITESSE.$"

BattleDome_Text_NeglectsAtkAndSpAtk::
	.string "Néglige l'ATTAQUE et l'ATQ. SPÉ.$"

BattleDome_Text_NeglectsAtkAndSpDef::
	.string "Néglige l'ATTAQUE et la DÉF. SPÉC.$"

BattleDome_Text_NeglectsDefAndSpeed::
	.string "Néglige la DÉFENSE et la VITESSE.$"

BattleDome_Text_NeglectsDefAndSpAtk::
	.string "Néglige la DÉFENSE et l'ATTAQUE SPÉC.$"

BattleDome_Text_NeglectsDefAndSpDef::
	.string "Néglige la DÉFENSE et la DÉF. SPÉC.$"

BattleDome_Text_NeglectsSpeedAndSpAtk::
	.string "Néglige la VITESSE et l'ATQ. SPÉ.$"

BattleDome_Text_NeglectsSpeedAndSpDef::
	.string "Néglige la VITESSE et la DEF. SPÉ.$"

BattleDome_Text_NeglectsSpAtkAndSpDef::
	.string "Néglige l'ATTAQUE SPÉC. et la DÉF. SPÉC.$"

BattleDome_Text_NeglectsHP::
	.string "Néglige les PV.$"

BattleDome_Text_NeglectsAtk::
	.string "Néglige ATTAQUE.$"

BattleDome_Text_NeglectsDef::
	.string "Néglige la DEFENSE.$"

BattleDome_Text_NeglectsSpeed::
	.string "Néglige VITESSE.$"

BattleDome_Text_NeglectsSpAtk::
	.string "Néglige l'ATQ. SPÉ.$"

BattleDome_Text_NeglectsSpDef::
	.string "Néglige la DEF. SPÉ.$"

BattleDome_Text_RaisesMonsWellBalanced::
	.string "Élève les POKéMON de façon équilibrée.$"

BattleDome_Text_LetTheBattleBegin::
	.string "Que le combat commence !$"

BattleDome_Text_TrainerWonUsingMove::
	.string "{STR_VAR_1} a gagné en utilisant {STR_VAR_2} !$"

BattleDome_Text_TrainerBecameChamp::
	.string "{STR_VAR_1} est devenu le champion !$"

BattleDome_Text_TrainerWonByDefault::
	.string "{STR_VAR_1} a gagné par forfait !$"

BattleDome_Text_TrainerWonOutrightByDefault::
	.string "{STR_VAR_1} a gagné par forfait !$"

BattleDome_Text_TrainerWonNoMoves::
	.string "{STR_VAR_1} a gagné sans utiliser de capacité !$"

BattleDome_Text_TrainerWonOutrightNoMoves::
	.string "{STR_VAR_1} a gagné sans utiliser aucune capacité !$"

BattleDome_Text_Round1Match1::
	.string "Tour 1, Match 1$"

BattleDome_Text_Round1Match2::
	.string "Tour 1, Match 2$"

BattleDome_Text_Round1Match3::
	.string "Tour 1, Match 3$"

BattleDome_Text_Round1Match4::
	.string "Tour 1, Match 4$"

BattleDome_Text_Round1Match5::
	.string "Tour 1, Match 5$"

BattleDome_Text_Round1Match6::
	.string "Tour 1, Match 6$"

BattleDome_Text_Round1Match7::
	.string "Tour 1, Match 7$"

BattleDome_Text_Round1Match8::
	.string "Tour 1, Match 8$"

BattleDome_Text_Round2Match1::
	.string "Tour 2, Match 1$"

BattleDome_Text_Round2Match2::
	.string "Tour 2, Match 2$"

BattleDome_Text_Round2Match3::
	.string "Tour 2, Match 3$"

BattleDome_Text_Round2Match4::
	.string "Tour 2, Match 4$"

BattleDome_Text_SemifinalMatch1::
	.string "Demi-finale 1$"

BattleDome_Text_SemifinalMatch2::
	.string "Demi-finale 2$"

BattleDome_Text_FinalMatch::
	.string "Match final$"
