FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Je te souhaite la bienvenue au PARC DE COMBAT :\n"
	.string "ARÈNE !\p"
	.string "Je suis ton guide pour le Tournoi KO !$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "Maintenant, veux-tu relever le défi\n"
	.string "d'un Tournoi KO ?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "Nous attendons ton défi\n"
	.string "une autre fois !$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "Dans la TENTE DE COMBAT : ARÈNE, nous\n"
	.string "organisons le Tournoi KO Fixe.\p"
	.string "Tous les participants entrent avec une équipe de\n"
	.string "trois POKéMON.\p"
	.string "Les trois POKéMON doivent être alignés\n"
	.string "dans l'ordre où ils apparaîtront.\p"
	.string "Pendant le combat, les POKéMON apparaîtront\n"
	.string "un par un dans l'ordre prédéfini.\p"
	.string "Une fois qu'un POKéMON entre en combat, il doit\n"
	.string "rester sur le terrain jusqu'à la fin du match.\p"
	.string "Si un match reste indécis après\n"
	.string "trois tours, il passe au jugement.\p"
	.string "Si tu souhaites interrompre ton défi,\n"
	.string "sauvegarde la partie.\p"
	.string "Si tu ne sauvegardes pas, tu ne pourras pas\n"
	.string "continuer ton défi.\p"
	.string "Si tu réussis à battre\n"
	.string "trois DRESSEURS d'affilée,\l"
	.string "nous te remettrons un beau prix.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Avant de t'emmener à la TENTE DE COMBAT,\n"
	.string "je dois sauvegarder. Ça te va ?$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Nous proposons deux niveaux de défi,\n"
	.string "Niveau 50 et Niveau Libre.\l"
	.string "Lequel choisis-tu ?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Très bien, choisis tes\n"
	.string "trois POKéMON, s'il te plaît.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Mon cher challenger ! Tu\p"
	.string "n'as pas les trois POKéMON\n"
	.string "requis pour l'entrée. Ils ne\p"
	.string "doivent pas non plus tenir\n"
	.string "des objets identiques. Les\p"
	.string "ŒUFS{STR_VAR_1} ne sont pas\p"
	.string "admis. Quand tu seras\n"
	.string "prêt, reviens nous voir.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Mon cher\p"
	.string "challenger !\n"
	.string "Tu n'as pas les\p"
	.string "trois POKéMON\n"
	.string "requis pour\p"
	.string "l'entrée.\n"
	.string "Pour être admis,\p"
	.string "tu dois apporter\p"
	.string "trois POKéMON\n"
	.string "différents.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "Je vais maintenant te conduire\n"
	.string "à la TENTE DE COMBAT.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Mon cher challenger ! Tu\p"
	.string "n'as pas sauvegardé avant\n"
	.string "de quitter, n'est-ce pas\p"
	.string "? C'est malheureux, mais\n"
	.string "cela a entraîné ta\l"
	.string "disqualification de ton défi.\p"
	.string "Tu peux, bien sûr,\n"
	.string "recommencer un nouveau défi.$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "Comme c'est splendide ! Tu as battu\n"
	.string "trois DRESSEURS d'affilée !$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "Patientez pendant l'enregistrement.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Pour commémorer ta série de 3 victoires,\n"
	.string "nous t'offrons ce prix.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} a reçu le prix\n"
	.string "{STR_VAR_1}.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "Oh ?\n"
	.string "Ton SAC semble être plein.\p"
	.string "Je t'invite à faire de la place et\n"
	.string "à revenir chercher ton lot.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "Merci beaucoup d'avoir participé !\p"
	.string "Patientez pendant que je sauvegarde la partie.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "Nous attendons ton défi\n"
	.string "une autre fois !$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "Nous attendions votre arrivée avec\n"
	.string "impatience. Avant de vous conduire\p"
	.string "à la TENTE DE COMBAT,\n"
	.string "je dois sauvegarder. Patientez.$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Je t'accueille à la TENTE DE COMBAT :\n"
	.string "PALAIS !\p"
	.string "Ici, la confiance du DRESSEUR envers\n"
	.string "ses POKéMON est mise à l'épreuve.$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "Veux-tu relever le défi de la\n"
	.string "TENTE DE COMBAT : PALAIS ?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "Dans la TENTE DE COMBAT : PALAIS,\n"
	.string "il y a une règle cruciale à respecter.\l"
	.string "Les DRESSEURS ne sont\p"
	.string "autorisés qu'à échanger\n"
	.string "leurs POKéMON.\p"
	.string "Les DRESSEURS sont autrement interdits de\n"
	.string "commander leurs POKéMON.\p"
	.string "Les POKéMON doivent se comporter selon\n"
	.string "leur nature et combattre seuls.\p"
	.string "Tu dois faire confiance à tes\n"
	.string "POKéMON et veiller sur eux.\p"
	.string "Si tu obtiens l'honneur de battre\n"
	.string "trois DRESSEURS d'affilée,\l"
	.string "nous te remettrons un prix.\p"
	.string "Si tu veux interrompre ton\n"
	.string "défi, sauvegarde la partie.\p"
	.string "Si tu ne sauvegardes pas avant d'interrompre,\n"
	.string "tu seras disqualifié.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "Quand tu auras fortifié ton cœur\n"
	.string "et tes POKéMON, tu devras revenir.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Il y a deux niveaux de difficulté,\n"
	.string "Niveau 50 et Niveau Libre.\l"
	.string "Lequel choisis-tu comme défi ?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Soupir…\p"
	.string "Tu n'as pas les\n"
	.string "trois POKéMON\p"
	.string "requis pour\n"
	.string "le défi.\p"
	.string "Pour entrer, tu\n"
	.string "dois fournir trois\p"
	.string "POKéMON différents.\p"
	.string "Reviens quand\n"
	.string "tu seras prêt !$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Soupir…\p"
	.string "Tu n'as pas les\n"
	.string "trois POKéMON\p"
	.string "requis pour\n"
	.string "le défi.\p"
	.string "Pour entrer, tu\n"
	.string "dois fournir trois\p"
	.string "POKéMON différents.\p"
	.string "Reviens quand\n"
	.string "tu seras prêt !$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Bien. Maintenant, tu dois choisir\n"
	.string "tes trois POKéMON.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Je dois sauvegarder avant de t'emmener\n"
	.string "à la TENTE DE COMBAT. Ça te va ?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "Bien.\n"
	.string "Maintenant, suis-moi.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "Je me sens privilégié d'avoir vu\n"
	.string "les exploits de tes POKéMON.\p"
	.string "Les résultats seront enregistrés.\n"
	.string "Je te demande d'attendre un instant.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "Pour une série de 3 victoires...\p"
	.string "Les liens entre ton cœur et tes POKéMON\n"
	.string "semblent solides et sincères.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "Ton exploit sera enregistré.\n"
	.string "Je dois te demander d'attendre un instant.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Pour ta série de 3 victoires,\n"
	.string "nous te remettons ce prix.$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "Bienvenue au PARC DE COMBAT :\n"
	.string "USINE !\p"
	.string "Je suis ton guide pour le Tournoi\n"
	.string "Échange-Combat.$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "Veux-tu relever le défi\n"
	.string "du Combat Échange ?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "Ici, à la TENTE DE COMBAT : USINE,\n"
	.string "nous organisons des événements Échange de Combat\l"
	.string "utilisant des POKéMON de location.\p"
	.string "D'abord, on te prêtera trois\n"
	.string "POKéMON spécialement pour cet événement.\p"
	.string "Avec les POKéMON de location fournis,\n"
	.string "tu dois mener un COMBAT SIMPLE.\p"
	.string "Si tu gagnes, tu es autorisé à échanger\n"
	.string "un de tes POKéMON de location.\p"
	.string "Répète ce cycle de combat et\n"
	.string "d'échange--si tu gagnes trois fois\l"
	.string "d'affilée, tu gagneras un beau prix.\p"
	.string "Si tu veux interrompre ton\n"
	.string "défi, sauvegarde la partie.\p"
	.string "Si tu ne sauvegardes pas avant d'interrompre,\n"
	.string "tu seras disqualifié.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "Nous attendons ta prochaine visite avec impatience.$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "Quel niveau veux-tu affronter ?\n"
	.string "Niveau 50 ou Niveau 100 ?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Avant de commencer ton défi,\n"
	.string "je dois sauvegarder les données. Ça te va ?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "OK, je garderai tes POKéMON en\n"
	.string "sécurité pendant que tu concours.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "Par ici, s'il vous plaît.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "Merci d'avoir participé !\p"
	.string "Je te rendrai tes POKéMON en échange\n"
	.string "de nos POKéMON de location.\p"
	.string "Je dois aussi sauvegarder les résultats de l'événement.\n"
	.string "Patientez.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "Je te rendrai tes POKéMON en échange\n"
	.string "de nos POKéMON de location.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "Félicitations !\n"
	.string "Tu as gagné trois matchs d'affilée !\p"
	.string "Je te rendrai tes POKéMON en échange\n"
	.string "de nos POKéMON de location.\p"
	.string "Je dois aussi sauvegarder tes résultats.\n"
	.string "Patientez.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "En reconnaissance de ta série de 3 victoires,\n"
	.string "nous t'offrons ce prix.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "Oh ?\n"
	.string "Tu n'as pas l'air d'avoir de place pour ça.\p"
	.string "Fais de la place dans ton SAC et\n"
	.string "fais-le moi savoir.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "On t'attendait !\p"
	.string "Avant de reprendre ton défi,\n"
	.string "je dois sauvegarder.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Je suis désolé de te dire ça, mais tu n'as\n"
	.string "pas sauvegardé avant d'arrêter de jouer la dernière fois.\p"
	.string "En conséquence, tu as été disqualifié\n"
	.string "de ton défi.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "Nous te rendrons tes POKéMON personnels.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} a reçu le prix\n"
	.string "{STR_VAR_1}.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "Les règles de l'Échange de Combat sont affichées.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "Quel titre veux-tu lire ?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "Dans un événement Échange de Combat, tu ne peux\n"
	.string "utiliser que trois POKéMON.\p"
	.string "Que tu loues ou échanges, ton équipe ne peut\n"
	.string "pas avoir deux POKéMON identiques ou\l"
	.string "plus.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "Tu ne peux échanger des POKéMON qu'avec\n"
	.string "le DRESSEUR que tu viens de battre.\p"
	.string "Tu ne peux échanger que les POKéMON\n"
	.string "utilisés par le DRESSEUR vaincu.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "Après chaque combat gagné, tu peux\n"
	.string "échanger contre un des POKéMON vaincus\l"
	.string "de ton adversaire.\p"
	.string "Tu ne pourras pas échanger de POKéMON\n"
	.string "avec le troisième DRESSEUR de l'épreuve.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "Il y a deux points\n"
	.string "clés à connaître\p"
	.string "lors d'un échange de POKéMON.\n"
	.string "D'abord, lors d'un échange,\l"
	.string "tu ne peux pas vérifier\p"
	.string "les stats du POKéMON de l'autre.\n"
	.string "Deuxièmement, certains\l"
	.string "POKéMON n'évoluent\p"
	.string "qu'en étant échangés.\n"
	.string "N'oublie pas ça !$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "Les POKéMON de la TENTE DE COMBAT :\n"
	.string "USINE sont tous en location.\p"
	.string "Tous les POKéMON loués sont au\n"
	.string "Niveau 50.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "Les règles de la TENTE DE COMBAT\n"
	.string "de VERGOYON sont affichées.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "Quel titre veux-tu lire ?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "Ici, au TENTE DE COMBAT MYOKARA,\n"
	.string "les POKéMON doivent penser et se\l"
	.string "battre tout seuls. Contrairement à\p"
	.string "la nature, les POKéMON qui\n"
	.string "vivent avec les gens se\l"
	.string "comportent différemment selon leur nature.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "Selon sa nature, un POKéMON\n"
	.string "peut préférer attaquer quoi qu'il arrive.\p"
	.string "Un autre POKéMON peut préférer se protéger\n"
	.string "de tout mal.\p"
	.string "Un autre encore peut aimer contrarier ou\n"
	.string "dérouter ses ennemis.\p"
	.string "Selon sa nature, un POKéMON\n"
	.string "aura des capacités favorites qu'il maîtrise\l"
	.string "bien.\p"
	.string "Il peut aussi détester certaines capacités\n"
	.string "qu'il a du mal à utiliser.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "Il y a des capacités offensives qui infligent\n"
	.string "des dégâts directs à l'ennemi.\p"
	.string "Il y a des capacités défensives utilisées\n"
	.string "pour se préparer aux attaques ennemies ou\l"
	.string "pour soigner les PV, etc.\p"
	.string "Il y a aussi d'autres capacités un peu étranges\n"
	.string "qui peuvent affaiblir les ennemis avec\l"
	.string "des problèmes de stats incluant poison et\l"
	.string "paralysie.\p"
	.string "Les POKéMON envisageront d'utiliser des capacités\n"
	.string "dans ces trois catégories.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "Quand il n'est pas sous\n"
	.string "les ordres de son DRESSEUR,\l"
	.string "un POKéMON peut être\p"
	.string "incapable d'utiliser\n"
	.string "efficacement\p"
	.string "certaines capacités.\n"
	.string "Fais confiance à la\l"
	.string "nature de ton POKéMON !$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "Selon sa nature, un POKéMON peut\n"
	.string "commencer à utiliser des attaques qui ne correspondent pas à\l"
	.string "sa nature quand il est en difficulté.\p"
	.string "Si un POKéMON se comporte bizarrement\n"
	.string "dans une situation critique, observe-le attentivement.$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "Dans ce PARC DE COMBAT, les niveaux de\n"
	.string "tous les POKéMON seront ajustés au\l"
	.string "Niveau 50.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "La TENTE DE COMBAT : PALAIS\n"
	.string "affiche ses règles.$"
