PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "PAPA : Salut, {PLAYER} !\p"
	.string "Je viens de recevoir une BAIE très rare.\n"
	.string "Je voudrais que tu l'aies.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "Si tu vois des BAIES pousser dans\n"
	.string "un sol fertile, n'hésite pas à les prendre.\p"
	.string "Mais assure-toi de planter une BAIE\n"
	.string "au même endroit. C'est la courtoisie de base.\p"
	.string "Tiens, je vais partager ça avec toi.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "À te voir, tu dois être un DRESSEUR,\n"
	.string "n'est-ce pas ?\p"
	.string "Les DRESSEURS font souvent tenir\n"
	.string "des BAIES à leurs POKéMON.\p"
	.string "C'est à toi de décider si tu veux cultiver\n"
	.string "des BAIES ou les utiliser.$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "J'ai arrosé les plantes chaque jour.\n"
	.string "Elles ont produit plein de fleurs.\p"
	.string "Et elles m'ont donné plein de BAIES aussi.\p"
	.string "Tiens !\n"
	.string "Tu peux l'avoir !$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "Je vais essayer très fort de faire pousser\n"
	.string "des BAIES de différentes couleurs.\p"
	.string "J'espère que tu feras de ton mieux aussi !$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "Je me demande quelles BAIES\n"
	.string "je vais chercher aujourd'hui ?$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "J'adore utiliser la machine BROYE-BAIE,\n"
	.string "alors je collectionne les BAIES.\p"
	.string "Je t'en donne une, si tu veux.$"

Route114_Text_TryBerryCrushWithFriends:
	.string "Tu devrais essayer le BROYEUR DE BAIES\n"
	.string "avec tes amis.$"

Route114_Text_FunToThinkAboutBerries:
	.string "Quelle BAIE devrait être plantée ?\n"
	.string "Faut-il utiliser ou garder les BAIES ?\p"
	.string "C'est amusant d'y réfléchir.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "Les BAIES poussent en absorbant la lumière du soleil.\p"
	.string "Nous aidons les BAIES à pousser en les\n"
	.string "arrosant régulièrement.\p"
	.string "C'est une expression d'amour, non ?$"

Route120_Text_YesYouUnderstand:
	.string "Oui, oui.\n"
	.string "Tu comprends ce que je veux dire.\p"
	.string "Tu devrais prendre ceci.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Oh… Mais il est important de se faire\n"
	.string "sa propre opinion, je suppose…\p"
	.string "Tu peux prendre ceci.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "Je pense que cette BAIE est rare.\n"
	.string "J'espère que tu l'élèveras avec amour.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "J'irai chercher plus de BAIES\n"
	.string "chez le MAÎTRE DES BAIES.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "Quand on y réfléchit bien…\p"
	.string "De la même façon que les costumes me vont parfaitement,\n"
	.string "une brise fraîche convient à la mer.\p"
	.string "Et toi, une BAIE te va à merveille…\p"
	.string "Pourquoi donc ?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "Au fond…\p"
	.string "C'est parce que tu es un DRESSEUR !$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "Au fond...\p"
	.string "La simplicité digne me convient,\n"
	.string "et les {POKEBLOCK}S conviennent parfaitement aux POKéMON.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "Tu peux m'appeler le MAÎTRE DES BAIES.\p"
	.string "Je rêve de remplir le monde de\n"
	.string "belles fleurs, alors j'élève des BAIES\l"
	.string "et je les distribue à tout le monde.\p"
	.string "Tu mérites d'en avoir une !$"

Route123_BerryMastersHouse_Text_YoureDeservingOfMulch:
	.string "ENGRAIS MIRACLE peut faire pousser n'importe quel\n"
	.string "arbre à BAIES instantanément. Essaie-le\l"
	.string "sur la BAIE du jour !$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Pourquoi être avare ?\n"
	.string "Prends-en un autre !$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "N'oublie pas de visiter la boutique de fleurs\n"
	.string "JOLI PÉTALE près de KANTEBLA.\p"
	.string "Que les fleurs remplissent le monde !$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "J'ai fini pour aujourd'hui.\n"
	.string "Reviens un autre jour.\p"
	.string "Que les fleurs remplissent le monde !$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "La façon dont mon mari cultive les BAIES,\n"
	.string "oh, c'est le meilleur du monde.\p"
	.string "Il me rend fière, c'est sûr.\p"
	.string "Au fait, mon enfant, as-tu entendu\n"
	.string "un bon dicton récemment ?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "Ah ! Quelle remarque remarquable !\n"
	.string "Inspirante, elle l'est !\p"
	.string "Je veux que tu prennes ceci.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Oh ! C'est un bon dicton.\n"
	.string "Tu es vraiment remarquable.\p"
	.string "Je veux te donner ça.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "Nos quatre petits-enfants devraient surpasser\n"
	.string "mon mari.\p"
	.string "La joie ne quitte jamais ma vie !$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "Bonjour !\p"
	.string "Ceci est la boutique de fleurs JOLI PÉTALE.\n"
	.string "Des fleurs partout dans le monde !$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, veux-tu en savoir plus\n"
	.string "sur les BAIES ?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "Comment tu t'appelles ?\p"
	.string "{PLAYER}{KUN}.\n"
	.string "C'est un joli prénom.\p"
	.string "{PLAYER}{KUN}, veux-tu en apprendre\n"
	.string "plus sur les BAIES ?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "Les BAIES poussent sur des arbres qui\n"
	.string "prospèrent uniquement dans un sol meuble et fertile.\p"
	.string "Si tu prends des BAIES, assure-toi d'en\n"
	.string "replanter une dans le sol fertile.\p"
	.string "Une BAIE plantée va bientôt germer,\n"
	.string "pousser, fleurir magnifiquement,\l"
	.string "puis produire à nouveau des BAIES.\p"
	.string "Je veux voir le monde entier rempli\n"
	.string "de belles fleurs.\l"
	.string "C'est mon rêve.\p"
	.string "Aide-moi, {PLAYER}{KUN}. Plante des BAIES\n"
	.string "et apporte plus de fleurs au monde.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "Les fleurs apportent tant de bonheur\n"
	.string "aux gens, n'est-ce pas ?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "Bonjour !\p"
	.string "Plus on accorde d'attention aux fleurs,\n"
	.string "plus elles s'épanouissent magnifiquement.\p"
	.string "Tu vas aimer t'occuper des fleurs. J'en suis\n"
	.string "sûr. Tu peux prendre ceci.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "Pendant que les plantes de BAIES\n"
	.string "poussent, arrose-les avec le\p"
	.string "SEAU WAILMER.\p"
	.string "Oh, autre chose.\n"
	.string "Si tu ne cueilles pas les BAIES\l"
	.string "pendant un moment, elles tombent\p"
	.string "au sol. Mais elles repoussent.\n"
	.string "C'est pas génial ? C'est comme si elles avaient la volonté de vivre.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "J'essaie d'être comme mes grandes sœurs.\n"
	.string "Je fais pousser des fleurs aussi !\p"
	.string "Tiens !\n"
	.string "C'est pour toi !$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "Un POKéMON peut manger une BAIE pour\n"
	.string "se soigner, ou tu peux la faire\p"
	.string "tenir à un POKéMON. Dans une\n"
	.string "région lointaine que j'ai visitée, ils\l"
	.string "avaient une machine qui mélange différentes\l"
	.string "BAIES et fait des bonbons pour\p"
	.string "POKéMON. Je veux des bonbons aussi.$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Salut, comment tu t'appelles ? …\p"
	.string "… … … … … …\n"
	.string "… … OK. C'est sympa !\p"
	.string "Je m'appelle KIRI. Maman et papa\p"
	.string "m'ont donné ce nom pour que\n"
	.string "je grandisse en bonne santé et\l"
	.string "au cœur chaleureux. C'était leur souhait.\p"
	.string "Tu peux en prendre un.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "KIRI te donnera aussi cette BAIE !\n"
	.string "Je l'aime vraiment beaucoup !$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "Je me demande quel genre de souhait\n"
	.string "est inclus dans ton nom.$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Le printemps, l'été, l'automne et l'hiver.\p"
	.string "Si tu es né au printemps, tu aimes\n"
	.string "le printemps, et si tu es né en\l"
	.string "été, tu aimes l'été ?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "Ensuite KIRI est née en automne,\n"
	.string "alors j'adore l'automne !\p"
	.string "Quelle saison préfères-tu ?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Oh…\n"
	.string "Ça n'a pas d'importance…\p"
	.string "Il y a tant de choses que je veux savoir…$"
