gText_Birch_Welcome::
	.string "Salut ! Désolé de t'avoir fait attendre !\p"
	.string "Bienvenue dans le monde des POKéMON !\p"
	.string "Je m'appelle CHEN.\p"
	.string "On m'appelle le PROFESSEUR\n"
	.string "POKéMON.\p$"

gText_Birch_Pokemon::
	.string "Voici ce qu'on appelle un « POKéMON ».\p"
	.string "\n$"

gText_Birch_MainSpeech::
	.string "Ce monde est peuplé de créatures\n"
	.string "que l'on appelle POKéMON.\p"
	.string "Les humains et les POKéMON vivent\n"
	.string "ensemble, en s'entraidant.\p"
	.string "Certains jouent avec les POKéMON,\n"
	.string "d'autres combattent avec eux.\p"
	.string "Mais on ne sait pas encore tout\n"
	.string "sur les POKéMON.\p"
	.string "Il reste tant de mystères\n"
	.string "à élucider. C'est pour ça que j'étudie\l"
	.string "les POKéMON chaque jour.\p$"

gText_Birch_AndYouAre::
	.string "Et toi, tu es ?$"

gText_Birch_BoyOrGirl::
	.string "Es-tu un garçon ?\n"
	.string "Ou une fille ?$"

gText_Birch_Difficulty::
	.string "Aha…\p"
	.string "Et… Comment penses-tu que cette\n"
	.string "aventure va se passer ?$"

gText_Birch_LockDifficulty::
	.string "Si tu veux changer la DIFFICULTÉ,\n"
	.string "ouvre le MENU OPTIONS et\l"
	.string "change-la depuis là.\p"
	.string "Tu peux aussi la verrouiller.\n"
	.string "Veux-tu verrouiller la\l"
	.string "DIFFICULTÉ choisie ?\p"
	.string "Cela ne pourra plus être changé.$"

gText_Birch_Challenge::
	.string "Oh, vraiment ?\p"
	.string "Très bien, c'est noté…\n"
	.string "Attends-tu des DÉFIS\l"
	.string "dans ton voyage ?\p"
	.string "Et comment t'appelles-tu ?$"

gText_Birch_WhatsYourName::
	.string "Alors, tu as dit que tu t'appelais\n"
	.string "comment ?$"

gText_Birch_SoItsPlayer::
	.string "Oh ! Alors tu es {PLAYER}{KUN} ?$"

gText_Birch_YourePlayer::
	.string "{PLAYER}{KUN}, es-tu prêt ?\p"
	.string "Ta propre aventure est sur\n"
	.string "le point de commencer.\p$"

gText_Birch_AreYouReady::
	.string "Tu vivras des moments joyeux et\n"
	.string "des défis difficiles.\p"
	.string "Un monde de rêves et d'aventures\n"
	.string "avec les POKéMON t'attend ! Allons-y !\p"
	.string "On se reverra plus tard !\p$"
