BerryBlender_Text_BlendWithTheBlendMaster:
	.string "MAÎTRE DU MIXAGE : En effet, c'est moi !\n"
	.string "Le MAÎTRE DU MIXAGE, c'est moi !\p"
	.string "Mixe avec moi, et tu verras\n"
	.string "la maîtrise que j'apporte au mixage !$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "MAÎTRE MIXEUR : Hmmm ! Alors, tu veux\n"
	.string "voir ma maîtrise en action ?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "Hmmm ! Alors, tu es trop\p"
	.string "occupé maintenant, je vois ! Mais\p"
	.string "ne crains rien ! Je serai\n"
	.string "là toute la journée ! Reviens\l"
	.string "vite de ton errance !$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "Hmm !\p"
	.string "Tu n'as pas une seule BAIE !\p"
	.string "Je resterai ici toute la journée !\n"
	.string "Reviens vite avec des BAIES !$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "Bien sûr !\n"
	.string "Bien sûr !\p"
	.string "Au fait…\n"
	.string "Tu sais comment mélanger des {POKEBLOCK}S\l"
	.string "à partir de BAIES ?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "Hmmm ! Ah, mais c'est un processus\p"
	.string "simple ! Quand la flèche du MIXEUR\p"
	.string "arrive sur ton marqueur, appuie sur\n"
	.string "le bouton A. C'est tout ce\p"
	.string "que tu as à faire. Quand\p"
	.string "tu verras avec quelle précision j'appuie\n"
	.string "sur le bouton A, tu comprendras.$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "Très bien !\p"
	.string "Commençons, alors !\p"
	.string "Tous ensemble avec le MAÎTRE MIXEUR,\n"
	.string "mixons des BAIES !$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "Hmmm !\p"
	.string "On dirait que tu n'as pas obtenu\n"
	.string "la BOÎTE {POKEBLOCK} !\p"
	.string "Je serai là toute la journée !\n"
	.string "Obtiens la BOÎTE {POKEBLOCK} et dépêche-toi de revenir !$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "Hmm ! Ta BOÎTE POKéBLOCS semble\p"
	.string "pleine ! Je serai là toute\p"
	.string "la journée ! Utilise des\n"
	.string "POKéBLOCS et reviens vite !$"

BerryBlender_Text_WhoaAwesome:
	.string "Ouah !\n"
	.string "Génial !$"

BerryBlender_Text_WickedlyFast:
	.string "Terriblement rapide !$"

BerryBlender_Text_WhatAnExpert:
	.string "Quel expert !$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "Quand j'ai mixé avec le MAÎTRE,\n"
	.string "nous avons fait d'incroyables {POKEBLOCK}S !$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "Des yeux qui suivent la flèche avec\n"
	.string "une intensité mécanique…\p"
	.string "Une main qui appuie sur le bouton A\n"
	.string "avec une précision horlogère…\p"
	.string "Posséder ces qualités fait\n"
	.string "du MAÎTRE DU MIXEUR un vrai grand.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "Le MAÎTRE DU MIXAGE est censé perfectionner\n"
	.string "ses talents au fond des montagnes.\p"
	.string "Parfois, il vient à JADIELLE\n"
	.string "pour mélanger des BAIES toute la journée.$"
