CableClub_Text_WelcomeWhichCableClubService:
	.string "Bienvenue au CLUB POKéMON CÂBLE\n"
	.string "CLUB.\p"
	.string "Lequel de nos services souhaites-tu\n"
	.string "utiliser ?$"

CableClub_Text_WhichService:
	.string "Quel service souhaites-tu\n"
	.string "utiliser ?$"

CableClub_Text_TradeUsingLinkCable::
	.string "Échange des POKéMON avec un autre joueur\n"
	.string "via un câble Game Link GBA.$"

CableClub_Text_BattleUsingLinkCable::
	.string "Tu peux combattre un autre DRESSEUR\n"
	.string "avec un câble Game Link GBA.$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "Tu peux utiliser le COIN ENREGISTREMENT\n"
	.string "avec d'autres via un câble Game Link GBA.$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "Fermer ce menu.$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "Pour un COMBAT DOUBLE, tu dois\n"
	.string "avoir au moins deux POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "Pour échanger, tu dois avoir au\n"
	.string "moins deux POKéMON avec toi.$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "Un POKéMON tenant la BAIE\n"
	.string "{STR_VAR_1} ne peut pas être échangé.$"

gText_PleaseWaitForLink::
	.string "Patientez.\n"
	.string "… … Bouton B : Annuler$"

gText_ConfirmLinkWhenPlayersReady::
	.string "Quand tous les joueurs sont prêts…\n"
	.string "Bouton A : Confirmer\l"
	.string "Bouton B : Annuler$"

gText_ConfirmStartLinkWithXPlayers::
	.string "Lancer la connexion avec {STR_VAR_1} joueurs.\n"
	.string "Bouton A : Confirmer\l"
	.string "Bouton B : Annuler$"

gText_AwaitingLinkup::
	.string "En attente de connexion…\n"
	.string "… … Bouton B : Annuler$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "Ta progression doit être sauvegardée avant\n"
	.string "de te connecter. Est-ce OK de sauvegarder ?$"

CableClub_Text_PleaseEnter:
	.string "Entrez, s'il vous plaît.$"

CableClub_Text_DirectYouToYourRoom:
	.string "Je vais maintenant te conduire à ta chambre.$"

Text_SomeoneIsNotReadyToLink:
	.string "Quelqu'un n'est pas prêt à se connecter.\p"
	.string "Reviens quand tout le monde\n"
	.string "aura fait les préparatifs.$"

Text_LinkErrorPleaseReset:
	.string "Désolé, erreur de connexion…\n"
	.string "Réinitialise et réessaie.$"

Text_PlayersMadeDifferentSelections:
	.string "Les partenaires de lien semblent avoir\n"
	.string "fait des sélections différentes.$"

CableClub_Text_PleaseVisitAgain:
	.string "Revenez nous voir.$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "Le nombre de participants est\n"
	.string "incorrect.$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "Le mode COMBAT SIMPLE ne peut pas être\n"
	.string "joué par {STR_VAR_1} joueurs.$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "Le mode COMBAT DOUBLE ne peut pas être\n"
	.string "joué par {STR_VAR_1} joueurs.$"

CableClub_Text_NeedFourPlayers:
	.string "Il faut quatre joueurs pour jouer\n"
	.string "à ce Mode Combat.$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "Confirme le nombre de\n"
	.string "joueurs et recommence.$"

Text_TerminateLinkConfirmation:
	.string "La connexion sera interrompue si tu\n"
	.string "quittes la salle. Est-ce OK ?$"

Text_TerminateLinkPleaseWait:
	.string "Fin de la connexion…\n"
	.string "Tu seras escorté hors de\l"
	.string "la salle. Patientez.$"

CableClub_Text_TooBusyToNotice:
	.string "Ce DRESSEUR est trop occupé pour\n"
	.string "remarquer…$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "Super ! J'ai pu voir la CARTE\n"
	.string "DRESSEUR de {STR_VAR_1} !$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "Oui ! J'ai pu voir la\n"
	.string "CARTE DRESSEUR de {STR_VAR_1} !\p"
	.string "C'est une carte {STR_VAR_2} !$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "Prenez place et commencez\n"
	.string "votre combat.$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "Prends place et commence\n"
	.string "ton échange.$"

RecordCorner_Text_ThanksForComing:
	.string "Merci d'être venu.$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "Les données de la CARTE D'ASSO\n"
	.string "seront écrasées.$"

CableClub_Text_HopeToSeeYouAgain:
	.string "J'espère te revoir bientôt !$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "Je suis vraiment désolé.\p"
	.string "Nous ne sommes pas encore prêts à échanger\n"
	.string "avec des DRESSEURS d'une autre\l"
	.string "région lointaine...$"

CableClub_Text_OtherTrainerNotReady:
	.string "L'autre DRESSEUR n'est pas prêt.$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "Tu as au moins un POKéMON\n"
	.string "qui ne peut pas être pris.$"

RecordCorner_Text_TakeSeatAndWait:
	.string "Prends place et attends, s'il te plaît.$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "{STR_VAR_1} a envoyé\n"
	.string "un {STR_VAR_2}.$"

CableClub_Text_CantMixWithJapaneseGame:
	.string "Désolé, il y a une erreur de\p"
	.string "transmission. Tu ne peux pas mélanger les\n"
	.string "enregistrements avec les jeux Rubis ou Saphir\p"
	.string "japonais. De plus, tu ne peux pas\n"
	.string "mélanger les enregistrements entre Émeraude japonaise et\l"
	.string "Rubis ou Saphir étrangers en même temps.$"

CableClub_Text_AdapterNotConnected:
	.string "L'Adaptateur Sans Fil n'est pas\n"
	.string "connecté correctement.$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "Les participants sont priés de se rendre\n"
	.string "au comptoir d'accueil.$"

@ Unused
CableClub_Text_Hello:
	.string "Bonjour !$"

@ Unused
CableClub_Text_PleaseWait:
	.string "Veuillez patienter.$"

CableClub_Text_YouMayTradeHere::
	.string "Tu peux échanger tes POKéMON ici\n"
	.string "avec un autre DRESSEUR.$"

CableClub_Text_YouMayBattleHere::
	.string "Tu peux combattre avec tes amis\n"
	.string "ici.$"

CableClub_Text_CanMakeBerryPowder::
	.string "Deux à cinq DRESSEURS peuvent faire\n"
	.string "de la POUDRE DE BAIES ensemble.$"

CableClub_Text_CanMixRecords::
	.string "Les données de deux à quatre joueurs\n"
	.string "peuvent être mélangées.$"

@ Unused
CableClub_Text_GuideToVariousServices:
	.string "Un guide des divers services\n"
	.string "du CLUB SANS FIL.$"

CableClub_Text_CancelSelectedItem::
	.string "Annule l'objet sélectionné dans le MENU.$"

@ Unused
CableClub_Text_WhichBattleMode:
	.string "Quel mode de combat préfères-tu ?$"

@ Unused
CableClub_Text_ReturnsToPreviousStep:
	.string "Retourne à l'étape précédente.$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "Pour utiliser le service BROYEUR DE BAIES,\n"
	.string "tu dois avoir au moins une BAIE.$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "Pour entrer dans la SALLE UNION, tu dois\n"
	.string "avoir au moins deux POKéMON.$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "Aucun POKéMON tenant la BAIE {STR_VAR_1}\n"
	.string "ne peut entrer dans la SALLE UNION.$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "C'est la SALLE UNION du CLUB\n"
	.string "SANS FIL POKéMON.\p"
	.string "Malheureusement, ton adaptateur sans fil\n"
	.string "n'est pas correctement connecté.\p"
	.string "Reviens nous voir.$"

@ Unused
CableClub_Text_OhExcuseMe:
	.string "Oh…\n"
	.string "Excuse-moi !$"

CableClub_Text_PlayerIsWaiting:
	.string "On dirait que {STR_VAR_1} est en train de jouer\n"
	.string "en ce moment.\l"
	.string "Vas-y !$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "Je peux t'expliquer les règles du jeu,\n"
	.string "si tu veux.\p"
	.string "Quel jeu dois-je décrire ?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "« POKéMON JUMP »\p"
	.string "Fais sauter\n"
	.string "ton POKéMON\p"
	.string "par-dessus la corde\n"
	.string "FOUET LIANES avec\p"
	.string "le bouton A.\n"
	.string "Seuls les mini POKéMON\p"
	.string "d'environ 70 cm\n"
	.string "ou moins peuvent\p"
	.string "participer.\n"
	.string "Amuse-toi bien !$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "« DODRIO CUEILLE-BAIES » Commande les\p"
	.string "trois têtes de DODRIO pour attraper\n"
	.string "les BAIES qui tombent. Appuie à\p"
	.string "droite, en haut ou à\n"
	.string "gauche sur la croix pour\p"
	.string "déplacer les têtes. Pour jouer,\n"
	.string "il te faut un DODRIO.$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "Si tu veux jouer,\n"
	.string "dis-le au vieil homme à côté de moi.$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "Salut, bienvenue !\n"
	.string "Tu es là pour jouer avec la\l"
	.string "Communication Sans Fil ?\p"
	.string "Tu peux attendre un petit moment ?$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "Très bien, à bientôt !$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "L'adaptateur sans fil n'est pas connecté.\n"
	.string "Reviens quand il sera branché !$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "D'accord, à quel jeu voulais-tu\n"
	.string "jouer ?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "Quel POKéMON veux-tu\n"
	.string "inscrire ?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "OK, tu es prêt.\n"
	.string "Ne laisse pas les autres te battre !$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "Tu pars déjà ?\n"
	.string "Reviens nous voir !$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "On dirait que tu n'as aucun\n"
	.string "POKéMON que tu peux inscrire…\p"
	.string "Veux-tu que je t'explique quels\n"
	.string "types de POKéMON peuvent participer ?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "« SAUT POKéMON » est\n"
	.string "ouvert aux POKéMON d'environ 71\p"
	.string "cm ou moins. Ce qui\n"
	.string "n'est pas admis, ce sont\p"
	.string "ceux qui ont évolué\n"
	.string "avec une PIERRE LUNE\p"
	.string "ou une PIERRE SOLEIL.$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "Le JEU DE CUEILLETTE DE BAIES DODRIO est un jeu\n"
	.string "auquel seul DODRIO peut participer.$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "Pourrais-tu recommencer depuis\n"
	.string "le début, s'il te plaît ?$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "Bienvenue au COIN DIRECT du CLUB\n"
	.string "SANS FIL POKéMON.\p"
	.string "Tu peux interagir directement avec\n"
	.string "tes amis ici.\p"
	.string "Dans quelle salle souhaites-tu\n"
	.string "entrer ?$"

CableClub_Text_TradePokemon:
	.string "Veux-tu échanger des POKéMON ?$"

CableClub_Text_PlayWhichBattleMode:
	.string "Quel mode de combat veux-tu\n"
	.string "jouer ?$"

CableClub_Text_AccessRecordCorner:
	.string "Voulez-vous accéder au\n"
	.string "COIN RECORDS ?$"

CableClub_Text_UseBerryCrush:
	.string "Voulez-vous utiliser le\n"
	.string "Système BROYEUR DE BAIES ?$"

CableClub_Text_ExplainBattleModes:
	.string "Il y a trois modes de combat.\p"
	.string "Le COMBAT SIMPLE oppose deux DRESSEURS\n"
	.string "avec un ou plusieurs POKéMON chacun.\p"
	.string "Chaque DRESSEUR peut avoir un POKéMON\n"
	.string "en combat à la fois.\p"
	.string "Le COMBAT DOUBLE oppose deux DRESSEURS\n"
	.string "avec deux POKéMON ou plus chacun.\p"
	.string "Chaque DRESSEUR enverra deux\n"
	.string "POKéMON en combat à la fois.\p"
	.string "Le COMBAT MULTI oppose quatre DRESSEURS\n"
	.string "avec un ou plusieurs POKéMON chacun.\p"
	.string "Chaque DRESSEUR peut avoir un POKéMON\n"
	.string "en combat à la fois.$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "Décidez lequel d'entre vous deux\n"
	.string "sera le CHEF.\p"
	.string "L'autre joueur doit ensuite choisir\n"
	.string "« REJOINDRE LE GROUPE ».$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "Décidez lequel d'entre vous quatre\n"
	.string "deviendra le CHEF DE GROUPE.\p"
	.string "Les autres joueurs doivent ensuite\n"
	.string "choisir « REJOINDRE GROUPE ».$"

CableClub_Text_ChooseGroupLeader:
	.string "Décidez qui parmi vous sera\n"
	.string "le CHEF DE GROUPE.\p"
	.string "Les autres joueurs doivent ensuite\n"
	.string "choisir « REJOINDRE LE GROUPE ».$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "Bienvenue au CLUB POKéMON SANS FIL\n"
	.string "SALLE UNION.\p"
	.string "Tu peux interagir directement avec\n"
	.string "d'autres DRESSEURS ici, dont certains\l"
	.string "que tu ne connais peut-être même pas.\p"
	.string "Veux-tu entrer dans la SALLE ?$"

CableClub_Text_UnionRoomInfo:
	.string "FLORA : C'est amusant si tu peux avoir plein de\n"
	.string "POKéMON !\l"
	.string "Je vais chercher partout parce que\p"
	.string "je veux des POKéMON différents.\n"
	.string "Si je trouve des POKéMON mignons, je les attraperai\p"
	.string "avec des POKé BALLS !\n"
	.string "Oh, et tu savais que si tu\p"
	.string "sélectionnes et utilises une BALL depuis le SAC,\n"
	.string "tu peux changer la POKé BALL\p"
	.string "qu'utilise un POKéMON ?\n"
	.string "Peut-être que je mettrai mes POKéMON dans une\p"
	.string "HONOR BALL. Elles sont si chouettes !$"

CableClub_Text_EnjoyUnionRoom:
	.string "J'espère que tu passeras un bon moment\n"
	.string "dans la SALLE UNION.$"

CableClub_Text_FirstTimeRightThisWay:
	.string "Bonjour ! Je m'appelle TEALA.\n"
	.string "Ce doit être ta première\p"
	.string "fois ici. Je vais te\n"
	.string "montrer comment fonctionne le système\p"
	.string "de communication sans fil.\n"
	.string "D'abord, je dois te\p"
	.string "montrer cet étage de\n"
	.string "notre CENTRE POKéMON. Par\p"
	.string "ici, s'il vous plaît.$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "À l'étage supérieur, il y a deux\n"
	.string "salles et le WONDERTRADE.\p"
	.string "D'abord, le système WONDERTRADE.\p"
	.string "L'homme au comptoir peut mieux\n"
	.string "l'expliquer, car il en sait\l"
	.string "plus que moi !\p"
	.string "N'hésite pas à lui parler.\p"
	.string "Ensuite, la salle au centre.\n"
	.string "C'est la SALLE UNION.\p"
	.string "Tu peux te connecter avec des DRESSEURS\n"
	.string "autour de toi qui sont aussi entrés dans\l"
	.string "la SALLE UNION.\p"
	.string "Avec eux, tu peux discuter,\n"
	.string "combattre et échanger.\p"
	.string "Enfin, la salle à l'extrême droite\n"
	.string "est le COIN DIRECT.\p"
	.string "Tu peux échanger ou combattre des POKéMON\n"
	.string "avec tes amis dans cette salle.\p"
	.string "Si l'Adaptateur Sans Fil n'est pas\n"
	.string "connecté, tu peux quand même te connecter\l"
	.string "en utilisant un câble Game Link GBA.\p"
	.string "Dans ce cas, tu dois aller\n"
	.string "au COIN DIRECT.\p"
	.string "J'espère que tu apprécieras le Système de\n"
	.string "Communication Sans Fil.$"

CableClub_Text_AskAboutLinking:
	.string "Bonjour, {PLAYER} !\p"
	.string "C'est moi, TEALA, l'hôtesse du\n"
	.string "CENTRE POKéMON 2e étage.\p"
	.string "Tu voulais me poser une question\n"
	.string "sur la connexion ?$"

CableClub_Text_ExplainWirelessClub:
	.string "Laisse-moi t'expliquer comment fonctionne le\n"
	.string "CLUB SANS FIL POKéMON.\p"
	.string "À cet étage, il y a\n"
	.string "deux salles.\p"
	.string "D'abord, la salle à gauche.\n"
	.string "C'est la SALLE UNION.\p"
	.string "Tu peux te connecter avec des DRESSEURS\n"
	.string "autour de toi qui sont aussi entrés dans\l"
	.string "la SALLE UNION.\p"
	.string "Avec eux, tu peux discuter,\n"
	.string "combattre et échanger.\p"
	.string "Ensuite, la salle à droite est\n"
	.string "le COIN DIRECT.\p"
	.string "Tu peux échanger ou combattre des POKéMON\n"
	.string "avec tes amis dans cette salle.\p"
	.string "Parfois, tu ne pourras peut-être pas\n"
	.string "trouver tes amis dans la SALLE UNION\l"
	.string "ou le COIN DIRECT.\p"
	.string "Dans ce cas, rapproche-toi\n"
	.string "de tes amis.\p"
	.string "Si l'Adaptateur Sans Fil n'est pas\n"
	.string "connecté, tu peux quand même te connecter\l"
	.string "en utilisant un câble Game Link GBA.\p"
	.string "Dans ce cas, tu dois aller\n"
	.string "au COIN DIRECT.\p"
	.string "J'espère que tu apprécieras le Système de\n"
	.string "Communication Sans Fil.$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "J'espère que tu apprécies le Système\n"
	.string "de Communication Sans Fil.$"
