Text_PictureBookShelf:
	.string "Il y a une collection de livres d'images POKéMON.$"

Text_BookShelf:
	.string "Il est rempli de toutes sortes de livres.$"

Text_PokemonCenterBookShelf:
	.string "Magazines POKéMON !\n"
	.string "AMI POKéMON…\p"
	.string "GUIDE POKéMON…\n"
	.string "POKéMON ADORABLES…$"

Text_Vase:
	.string "Ce vase a l'air cher…\n"
	.string "Regardé à l'intérieur…\p"
	.string "Mais il était vide.$"

Text_EmptyTrashCan:
	.string "C'est vide.$"

Text_ShopShelf:
	.string "Les étagères débordent de toutes sortes\n"
	.string "de produits POKéMON.$"

Text_Blueprint:
	.string "Un plan de quelque sorte ?\n"
	.string "C'est trop compliqué !$"
