@ With the exception of Link standby, none of the below texts are used

gTest_MissedTurn::
	.string "Tour manqué$"

gText_LinkStandby4::
	.string "En attente de lien !$"

gText_WinnerIsPlayersMonCongrats::
	.string "Le gagnant est {STR_VAR_1} de {STR_VAR_2} !\n"
	.string "Félicitations !$"

gText_WinnerIsPlayersMon::
	.string "Le gagnant est {STR_VAR_1} de {STR_VAR_2} !{PAUSE_UNTIL_PRESS}$"

gText_PrimaryJudgingNumX::
	.string "Jugement principal : N  {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SecondaryJudgingNumX::
	.string "Jugement secondaire : N  {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX::
	.string "Événement défini : N  {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MoveUsedMostOften::
	.string "La capacité la plus utilisée :\n"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MostImpressiveMon::
	.string "Le POKéMON le plus impressionnant :\n"
	.string "{STR_VAR_1} de {STR_VAR_2}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX2::
	.string "Événement défini : N  {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_LinkTVProgramWillNotBeMadeTrainerLost::
	.string "Une émission TV en liaison ne sera pas réalisée\n"
	.string "car le DRESSEUR a perdu.{PAUSE_UNTIL_PRESS}$"
