@ Contest move effect descriptions

gText_HighlyAppealingMove::
	.string "Une capacité très attrayante.$"

gText_UserMoreEasilyStartled::
	.string "Après cette attaque, l'utilisateur\n"
	.string "est plus facilement surpris.$"

gText_GreatAppealButNoMoreToEnd::
	.string "Fait une superbe démonstration, mais\n"
	.string "plus rien jusqu'à la fin.$"

gText_UsedRepeatedlyWithoutBoringJudge::
	.string "Peut être utilisé à répétition\n"
	.string "sans lasser le JUGE.$"

gText_AvoidStartledByOthersOnce::
	.string "Peut éviter d'être effrayé\n"
	.string "par les autres une fois.$"

gText_AvoidStartledByOthers::
	.string "Peut éviter d'être déconcerté\n"
	.string "par les autres.$"

gText_AvoidStartledByOthersLittle::
	.string "Peut éviter d'être effrayé\n"
	.string "un peu par les autres.$"

gText_UserLessLikelyStartled::
	.string "Après cette capacité, l'utilisateur est\n"
	.string "moins susceptible d'être surpris.$"

gText_SlightlyStartleFrontMon::
	.string "Effraie légèrement le\n"
	.string "POKéMON devant.$"

gText_SlightlyStartleAppealed::
	.string "Effraie légèrement ceux\n"
	.string "qui ont fait des utilisations.$"

gText_StartleAppealedBeforeUser::
	.string "Surprend le POKéMON qui a\n"
	.string "démonstré avant l'utilisateur.$"

gText_StartleAllAppealed::
	.string "Surprend tous les POKéMON\n"
	.string "qui ont fait leur démonstration.$"

gText_BadlyStartleFrontMon::
	.string "Déconcerte fortement le\n"
	.string "POKéMON devant.$"

gText_BadlyStartleAppealed::
	.string "Effraie fortement ceux qui\n"
	.string "ont fait des appels.$"

gText_StartleAppealedBeforeUser2::
	.string "Surprend le POKéMON qui a\n"
	.string "démonstré avant l'utilisateur.$"

gText_StartleAllAppealed2::
	.string "Surprend tous les POKéMON\n"
	.string "qui ont fait leur démonstration.$"

gText_ShiftJudgesAttentionFromOthers::
	.string "Détourne l'attention du JUGE\n"
	.string "des autres.$"

gText_StartleMonHasJudgesAttention::
	.string "Surprend le POKéMON qui\n"
	.string "attire l'attention du JUGE.$"

gText_JamOthersMissesTurn::
	.string "Bloque les autres et rate\n"
	.string "un tour d'utilisations.$"

gText_StartleMonsMadeSameTypeAppeal::
	.string "Effraie les POKéMON ayant\n"
	.string "fait un appel du même type.$"

gText_BadlyStartleCoolAppeals::
	.string "Effraie fortement les POKéMON\n"
	.string "qui ont fait des utilisations COOL.$"

gText_BadlyStartleBeautyAppeals::
	.string "Effraie fortement les POKéMON\n"
	.string "qui ont fait des utilisations BEAUTÉ.$"

gText_BadlyStartleCuteAppeals::
	.string "Effraie fortement les POKéMON\n"
	.string "qui ont fait des utilisations MIGNON.$"

gText_BadlyStartleSmartAppeals::
	.string "Effraie fortement les POKéMON\n"
	.string "qui ont fait des utilisations INTELLIGENCE.$"

gText_BadlyStartleToughAppeals::
	.string "Effraie fortement les POKéMON\n"
	.string "qui ont fait des utilisations FORCE.$"

gText_MakeMonAfterUserNervous::
	.string "Rend nerveux un POKéMON\n"
	.string "après l'utilisateur.$"

gText_MakeAllMonsAfterUserNervous::
	.string "Rend nerveux tous les POKéMON\n"
	.string "après l'utilisateur.$"

gText_WorsenConditionOfThoseMadeAppeals::
	.string "Aggrave l'état de ceux\n"
	.string "qui ont fait des utilisations.$"

gText_BadlyStartleMonsGoodCondition::
	.string "Effraie fortement les POKéMON\n"
	.string "en bonne condition.$"

gText_AppealGreatIfPerformedFirst::
	.string "L'utilisation fonctionne bien si\n"
	.string "elle est faite en premier.$"

gText_AppealGreatIfPerformedLast::
	.string "L'utilisation fonctionne bien si\n"
	.string "elle est faite en dernier.$"

gText_AppealAsGoodAsThoseBeforeIt::
	.string "Rend l'appel aussi bon\n"
	.string "que les précédents.$"

gText_AppealAsGoodAsOneBeforeIt::
	.string "Rend l'appel aussi bon\n"
	.string "que le précédent.$"

gText_AppealBetterLaterItsPerformed::
	.string "La démonstration fonctionne mieux\n"
	.string "plus elle est effectuée tard.$"

gText_AppealVariesDependingOnTiming::
	.string "La qualité de la démonstration varie\n"
	.string "selon son timing.$"

gText_WorksWellIfSameTypeAsBefore::
	.string "Fonctionne bien si c'est le même\n"
	.string "type que celui d'avant.$"

gText_WorksWellIfDifferentTypeAsBefore::
	.string "Fonctionne bien si le type est différent\n"
	.string "de celui d'avant.$"

gText_AffectedByAppealInFront::
	.string "Influencé par la qualité de\n"
	.string "l'utilisation devant.$"

gText_UpsConditionHelpsPreventNervousness::
	.string "Améliore la condition de l'utilisateur.\n"
	.string "Aide à prévenir le trac.$"

gText_AppealWorksWellIfConditionGood::
	.string "L'appel fonctionne bien si\n"
	.string "la condition de l'utilisateur est bonne.$"

gText_NextAppealMadeEarlier::
	.string "Le prochain appel peut être\n"
	.string "fait plus tôt au tour suivant.$"

gText_NextAppealMadeLater::
	.string "Le prochain appel peut être\n"
	.string "fait plus tard au tour suivant.$"

gText_TurnOrderMoreEasilyScrambled::
	.string "Rend l'ordre du prochain tour\n"
	.string "plus facilement brouillé.$"

gText_ScrambleOrderOfNextAppeals::
	.string "Brouille l'ordre des\n"
	.string "utilisations au tour suivant.$"

gText_AppealExcitesAudienceInAnyContest::
	.string "Une démonstration qui excite\n"
	.string "le public dans tout CONCOURS.$"

gText_BadlyStartlesMonsGoodAppeals::
	.string "Surprend fortement tous les POKéMON\n"
	.string "qui ont fait de bonnes démonstrations.$"

gText_AppealBestMoreCrowdExcited::
	.string "La démonstration fonctionne mieux\n"
	.string "plus le public est excité.$"

gText_TemporarilyStopCrowdExcited::
	.string "Arrête temporairement\n"
	.string "l'enthousiasme du public.$"

@ Unused move names

gText_RainDance::
	.string "DANSE PLUIE$"

gText_Rage::
	.string "RAGE$"

gText_FocusEnergy::
	.string "PUISSANCE$"

gText_Hypnosis::
	.string "HYPNOSE$"

gText_Softboiled::
	.string "COGNOBIDON$"

gText_HornAttack::
	.string "KOUD'KORNE$"

gText_SwordsDance::
	.string "DANSE-LAMES$"

gText_Conversion::
	.string "CONVERSION$"

gText_SunnyDay::
	.string "ZÉNITH$"

gText_Rest2::
	.string "REPOS$"

gText_Vicegrip::
	.string "PINCE$"

gText_DefenseCurl::
	.string "BOUCLIER$"

gText_LockOn::
	.string "VERROUILLAGE$"

@ Contest type names

gContestMoveTypeCoolText::
	.string "COOL$"

gContestMoveTypeBeautyText::
	.string "BEAUTÉ$"

gContestMoveTypeCuteText::
	.string "GRACIEUX$"

gContestMoveTypeSmartText::
	.string "INTELLIGENCE$"

gContestMoveTypeToughText::
	.string "ROBUSTESSE$"

gText_AppealNumWhichMoveWillBePlayed::
	.string "Démonstration n  {STR_VAR_1} !\n"
	.string "Quelle attaque sera jouée ?$"

gText_AppealNumButItCantParticipate::
	.string "Utilisation nº{STR_VAR_1} !\n"
	.string "Mais il ne peut pas participer !$"

gText_MonAppealedWithMove::
	.string "{STR_VAR_1} a utilisé\n"
	.string "{STR_VAR_2} !$"

gText_MonWasWatchingOthers::
	.string "{STR_VAR_1} regardait\n"
	.string "les autres.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AllOutOfAppealTime::
	.string "On n'a plus de\n"
	.string "Temps d'Applause !{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

@ Unused appeal result texts

gText_ButAppealWasJammed::
	.string "Mais l'appel a été\n"
	.string "bloqué.$"

gText_FollowedAnotherMonsLead::
	.string "A su l'exemple d'un autre\n"
	.string "POKéMON.$"

gText_ButItMessedUp::
	.string "Mais ça a raté.$"

gText_WentBetterThanUsual::
	.string "Ça s'est mieux passé\n"
	.string "que d'habitude.$"

gText_JudgeLookedAwayForSomeReason::
	.string "Le JUGE a détourné le regard\n"
	.string "pour une raison quelconque.$"

gText_WorkedHardToBuildOnPastMistakes::
	.string "Il a travaillé dur pour corriger\n"
	.string "les erreurs passées.$"

gText_CantMakeAnyMoreMoves::
	.string "Il ne peut plus utiliser\n"
	.string "d'autres attaques.$"

gText_WorkedFrighteninglyWell::
	.string "Ça a marché de façon\n"
	.string "terrifiante.$"

gText_WorkedHardAsStandoutMon::
	.string "Il a travaillé aussi dur que\n"
	.string "le POKéMON vedette.$"

gText_JudgedLookedOnExpectantly::
	.string "Le JUGE regardait\n"
	.string "avec impatience.$"

gText_WorkedRatherWell::
	.string "Ça a plutôt bien marché.$"

gText_WorkedLittleBetterThanUsual::
	.string "Ça a un peu mieux fonctionné\n"
	.string "que d'habitude.$"

@ Round result texts

gText_MonFailedToStandOutAtAll::
	.string "{STR_VAR_1} n'a pas réussi\n"
	.string "à se distinguer du tout…{PAUSE_UNTIL_PRESS}$"

gText_MonDidntStandOutVeryMuch::
	.string "{STR_VAR_1} ne s'est pas vraiment\n"
	.string "distingué…{PAUSE_UNTIL_PRESS}$"

gText_MonCaughtALittleAttention::
	.string "{STR_VAR_1} a attiré un peu\n"
	.string "d'attention.{PAUSE_UNTIL_PRESS}$"

gText_MonAttractedALotOfAttention::
	.string "{STR_VAR_1} a attiré\n"
	.string "beaucoup d'attention.{PAUSE_UNTIL_PRESS}$"

gText_MonCommandedTotalAttention::
	.string "{STR_VAR_1} a captivé\n"
	.string "l'attention totale.{PAUSE_UNTIL_PRESS}$"

gText_MonHasntMadeItsAppeal::
	.string "{STR_VAR_1} n'a pas fait\n"
	.string "son appel.{PAUSE_UNTIL_PRESS}$"

@ Unused
gText_AnticipationSwelledForMonsAppealNext2::
	.string "L'anticipation monte pour\n"
	.string "la prochaine démonstration de {STR_VAR_1}.$"

gText_EmptyContestString::
	.string "$"

gText_JudgesViewsOnMonHeldFirm::
	.string "L'avis du JUGE sur\n"
	.string "{STR_VAR_1} est resté ferme.$"

gText_MonsXChangedPerceptions::
	.string "La {STR_VAR_1} de {STR_VAR_3}\n"
	.string "a changé les perceptions.$"

gText_MonsAppealEffectWoreOff::
	.string "L'effet de l'utilisation de {STR_VAR_1}\n"
	.string "s'est dissipé.$"

gText_SpecialAppealsEffectWoreOff::
	.string "L'effet de l'utilisation spéciale\n"
	.string "s'est dissipé.$"

gText_EveryonesAppealsMadeToLookSame::
	.string "Toutes les utilisations ont été\n"
	.string "rendues identiques.$"

gText_CheapenedMonsAppeal::
	.string "Ça a diminué le charisme\n"
	.string "de {STR_VAR_2}.$"

gText_CheapenedAppealOfThoseAhead::
	.string "Ça a dévalué l'utilisation\n"
	.string "de ceux devant.$"

gText_StoleAttentionAwayFromMon::
	.string "Ça a volé l'attention\n"
	.string "à {STR_VAR_2}.$"

gText_CheapenedMonsAppeal2::
	.string "Ça a diminué le charisme\n"
	.string "de {STR_VAR_2}.$"

gText_SeverelyCheapenedOtherAppeals::
	.string "A fortement diminué\n"
	.string "les autres charismes.$"

gText_AnticipationSwelledForMonsAppealNext::
	.string "L'anticipation monte pour\n"
	.string "la prochaine démonstration de {STR_VAR_1}.$"

gText_CheapenedAppealOfThoseAhead2::
	.string "Ça a dévalué l'utilisation\n"
	.string "de ceux devant.$"

gText_CheapenedJudgesFavoriteAppeal::
	.string "Ça a dévalué l'utilisation\n"
	.string "préférée du JUGE.$"

gText_AppealsOfOthersCheapenedByHalf::
	.string "Les appels des autres ont été\n"
	.string "réduits de moitié.$"

gText_StoodOutToMakeUpForBeingJammed::
	.string "Il s'est démarqué pour compenser\n"
	.string "le blocage.$"

gText_CantParticipateInAppealsAnyMore::
	.string "Il ne peut plus participer\n"
	.string "aux utilisations.$"

gText_TouchedJudgeForFantasticAppeal::
	.string "Ça a touché le JUGE pour\n"
	.string "un appel fantastique.$"

gText_AnticipationRoseForUpcomingAppeals::
	.string "L'anticipation a monté pour\n"
	.string "les prochaines utilisations.$"

gText_StoodOutAsMuchAsSpecialAppeals::
	.string "Il s'est démarqué autant que\n"
	.string "les utilisations spéciales.$"

gText_StoodOutAsMuchAsMon::
	.string "S'est autant démarqué que\n"
	.string "{STR_VAR_1}.$"

gText_JammedAppealsMadeEvenLessNoticeable::
	.string "Les appels bloqués sont encore\n"
	.string "moins remarquables.$"

gText_EveryonesAppealsMadeSame::
	.string "Les utilisations de tout le monde\n"
	.string "étaient identiques.$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
	.string "Il est devenu plus conscient\n"
	.string "des autres POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
	.string "{STR_VAR_1} ne peut plus faire\n"
	.string "d'applause après ça.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
	.string "Ça s'est calmé\n"
	.string "un tout petit peu.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
	.string "Ça s'est désintéressé des\n"
	.string "autres POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
	.string "Ça s'est moins intéressé des\n"
	.string "autres POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
	.string "Ça s'est beaucoup moins soucié des\n"
	.string "autres POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "Ça a tenté de surprendre les\n"
	.string "autres POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
	.string "Il a essayé d'éblouir\n"
	.string "les autres.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
	.string "Le JUGE a détourné le regard\n"
	.string "de {STR_VAR_1}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
	.string "Ça a tenté de déstabiliser le\n"
	.string "prochain POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
	.string "{STR_VAR_1} est devenu\n"
	.string "nerveux.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "L'applause a tenté de\n"
	.string "déstabiliser les POKéMON en attente.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
	.string "Il a provoqué les POKéMON\n"
	.string "qui s'en sortaient bien.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
	.string "{STR_VAR_1} a retrouvé\n"
	.string "sa forme.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
	.string "Ça a tenté de gêner les POKéMON\n"
	.string "qui allaient bien.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "Le {STR_VAR_1} en vedette\n"
	.string "s'est encore plus démené.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "Le {STR_VAR_1} largement inaperçu\n"
	.string "a travaillé dur.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
	.string "Ça a marché autant que\n"
	.string "les POKéMON précédents.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
	.string "L'applause de {STR_VAR_1} n'a pas\n"
	.string "bien marché.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "Ça a marché autant que le\n"
	.string "POKéMON précédent.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
	.string "L'applause de {STR_VAR_1} n'a pas\n"
	.string "bien marché.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
	.string "L'applause de {STR_VAR_1} n'a pas\n"
	.string "bien marché.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
	.string "L'applause de {STR_VAR_1}\n"
	.string "a plutôt bien marché.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
	.string "L'applause de {STR_VAR_1}\n"
	.string "a plutôt bien marché.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
	.string "L'applause de {STR_VAR_1}\n"
	.string "a été excellente.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
	.string "L'appel de {STR_VAR_1} a été\n"
	.string "un échec.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "L'applause de {STR_VAR_1} n'a pas\n"
	.string "très bien marché.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
	.string "L'applause de {STR_VAR_1}\n"
	.string "a plutôt bien marché.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
	.string "L'applause de {STR_VAR_1}\n"
	.string "a plutôt bien marché.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
	.string "L'applause de {STR_VAR_1}\n"
	.string "a très bien marché.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
	.string "L'applause de {STR_VAR_1}\n"
	.string "a été excellente.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
	.string "C'est le même type que le\n"
	.string "POKéMON précédent - bien !{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "Ce n'est pas le même type que\n"
	.string "le précédent - bien !{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "Il s'est beaucoup plus démarqué\n"
	.string "que le POKéMON précédent.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
	.string "Ça n'a pas marché aussi bien que\n"
	.string "le POKéMON précédent.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
	.string "La condition de {STR_VAR_1}\n"
	.string "a dépassé la normale.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "Le statut brûlant de {STR_VAR_1}\n"
	.string "a fait une superbe appel !{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "Ça a avancé dans la file pour\n"
	.string "le prochain applause.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "Il est retourné en ligne pour\n"
	.string "le prochain appel.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "Ça a bousculé l'ordre\n"
	.string "pour le prochain tour.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
	.string "Le JUGE a regardé\n"
	.string "{STR_VAR_1} avec attente.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverWell::
	.string "Le combo d'applauses est passé\n"
	.string "bien.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverVeryWell::
	.string "Le combo d'applauses est passé\n"
	.string "très bien.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverExcellently::
	.string "Le combo d'appel est passé\n"
	.string "excellemment.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvertGaze::
	.string "{STR_VAR_1} a réussi à\n"
	.string "détourner le regard.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvoidSeeingIt::
	.string "{STR_VAR_1} a réussi à\n"
	.string "ne pas le voir.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonIsntFazedByThatSortOfThing::
	.string "{STR_VAR_1} n'est pas impressionné\n"
	.string "par ce genre de chose.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonBecameALittleDistracted::
	.string "{STR_VAR_1} est devenu\n"
	.string "un peu distrait.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToStartleOtherPokemon::
	.string "Il a essayé d'effrayer les\n"
	.string "autres POKéMON.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonLookedDownOutOfDistraction::
	.string "{STR_VAR_1} a baissé les yeux\n"
	.string "par distraction.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTurnedBackOutOfDistraction::
	.string "{STR_VAR_1} s'est retourné\n"
	.string "par distraction.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpUtteringCry::
	.string "{STR_VAR_1} n'a pas pu s'empêcher\n"
	.string "de pousser un cri.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpLeapingUp::
	.string "{STR_VAR_1} n'a pas pu s'empêcher\n"
	.string "de bondir.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTrippedOutOfDistraction::
	.string "{STR_VAR_1} a trébuché\n"
	.string "par distraction.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasTooNervousToMove::
	.string "{STR_VAR_1} était trop\n"
	.string "nervieux pour bouger.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItMessedUp2::
	.string "Mais ça a raté.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeTargetNervous::
	.string "Mais ça n'a pas réussi à rendre\n"
	.string "la cible nerveuse.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "Mais ça n'a réussi à rendre\n"
	.string "personne nerveux.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItWasIgnored::
	.string "Mais cela a été ignoré…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CouldntImproveItsCondition::
	.string "Mais ça n'a pas réussi à améliorer\n"
	.string "sa condition…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BadConditionResultedInWeakAppeal::
	.string "Son mauvais état\n"
	.string "a donné une appel faible.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasUnaffected::
	.string "{STR_VAR_1} n'a pas\n"
	.string "été affecté.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_RepeatedAppeal::
	.string "{STR_VAR_1} a déçu\n"
	.string "en répétant une démonstration.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXWentOverGreat::
	.string "Le {STR_VAR_1} de {STR_VAR_3}\n"
	.string "a eu un grand succès.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXDidntGoOverWell::
	.string "{STR_VAR_1} et sa {STR_VAR_3}\n"
	.string "n'ont pas fait bonne impression ici...{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXGotTheCrowdGoing::
	.string "Le {STR_VAR_1} de {STR_VAR_3}\n"
	.string "a enflammé le public.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCantAppealNextTurn::
	.string "{STR_VAR_1} ne peut pas faire d'applause\n"
	.string "au prochain tour…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AttractedCrowdsAttention::
	.string "Ça a attiré l'attention\n"
	.string "du public.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CrowdContinuesToWatchMon::
	.string "Le public continue de\n"
	.string "regarder {STR_VAR_3}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsMoveIsIgnored::
	.string "La capacité {STR_VAR_1} de\n"
	.string "{STR_VAR_2} est ignorée.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_Contest_Shyness::
	.string "timidité$"

gText_Contest_Anxiety::
	.string "anxiété$"

gText_Contest_Laziness::
	.string "nonchalance$"

gText_Contest_Hesitancy::
	.string "hésitation$"

gText_Contest_Fear::
	.string "peur$"

gText_Contest_Coolness::
	.string "séduction$"

gText_Contest_Beauty::
	.string "beauté$"

gText_Contest_Cuteness::
	.string "grâce$"

gText_Contest_Smartness::
	.string "intelligence$"

gText_Contest_Toughness::
	.string "robustesse$"

@ Unused
gText_Tension::
	.string "TENSION$"

gText_CoolMove::
	.string "CAPACITÉ COOL$"

gText_BeautyMove::
	.string "Capacité BEAUTÉ$"

gText_CuteMove::
	.string "CAPACITÉ GRACIEUSE$"

gText_SmartMove::
	.string "CAPACITÉ INTELLIGENTE$"

gText_ToughMove::
	.string "CAPACITÉ ROBUSTE$"

gText_3QuestionMarks::
	.string "???$"
