gContestHallPaintingCaption::
	.string "{STR_VAR_1}\n"
	.string "{STR_VAR_2}'s {STR_VAR_3}$"

@ Unused
gContestPaintingContest::
	.string "CONCOURS$"

gContestRankNormal::
	.string "RANG NORMAL$"

gContestRankSuper::
	.string "RANG SUPER$"

gContestRankHyper::
	.string "RANG HYPER$"

gContestRankMaster::
	.string "RANG MAÎTRE$"

gContestLink::
	.string "CONNEXION$"

gContestCoolness::
	.string "SANG-FROID$"

gContestBeauty::
	.string "BEAUTÉ$"

gContestCuteness::
	.string "GRÂCE$"

gContestSmartness::
	.string "INTELLIGENCE$"

gContestToughness::
	.string "ROBUSTESSE$"

gContestPaintingCool1::
	.string "Super cool sans arrêt--\n"
	.string "l'inestimable {STR_VAR_1}$"

gContestPaintingCool2::
	.string "Hé, toi !\n"
	.string "Le beau POKéMON {STR_VAR_1}$"

gContestPaintingCool3::
	.string "Le merveilleux, fabuleux et\n"
	.string "très grand {STR_VAR_1}$"

gContestPaintingBeauty1::
	.string "La dernière Vénus du siècle--\n"
	.string "la belle {STR_VAR_1}$"

gContestPaintingBeauty2::
	.string "Le sourire éblouissant\n"
	.string "et scintillant de {STR_VAR_1}$"

gContestPaintingBeauty3::
	.string "L'idole du CENTRE POKéMON--\n"
	.string "l'incomparable {STR_VAR_1}$"

gContestPaintingCute1::
	.string "Le charmant et doux {STR_VAR_1}$"

gContestPaintingCute2::
	.string "Le joli portrait gagnant\n"
	.string "de {STR_VAR_1}$"

gContestPaintingCute3::
	.string "Fais-nous un clin d'œil !\n"
	.string "Le mignon POKéMON {STR_VAR_1}$"

gContestPaintingSmart1::
	.string "Le maestro de l'intelligence--\n"
	.string "le sage POKéMON {STR_VAR_1}$"

gContestPaintingSmart2::
	.string "{STR_VAR_1}--celui choisi\n"
	.string "au-dessus de tous les POKéMON$"

gContestPaintingSmart3::
	.string "L'excellent {STR_VAR_1} et\n"
	.string "son moment d'élégance$"

gContestPaintingTough1::
	.string "Le puissant et musclé\n"
	.string "{STR_VAR_1}$"

gContestPaintingTough2::
	.string "Le fort, le plus fort et\n"
	.string "le plus fort {STR_VAR_1}$"

gContestPaintingTough3::
	.string "Le super POKéMON\n"
	.string "hyper coriace {STR_VAR_1}$"
