EventTicket_Text_ShowOldSeaMap:
	.string "Le ferry pour POIVRESSELLE est…\p"
	.string "Je vous demande pardon ?\n"
	.string "Peut-on naviguer vers cet endroit sur la carte ?\p"
	.string "Je connais quelqu'un qui pourra mieux\n"
	.string "vous aider. Veuillez patienter.$"

EventTicket_Text_ThatPass:
	.string "Le ferry pour POIVRESSE est…\p"
	.string "Oh ?\n"
	.string "Ce PASSE…$"

EventTicket_Text_ShowEonTicket:
	.string "Aye, matelot, es-tu\n"
	.string "celui qui a apporté\p"
	.string "ce PASSE vraiment bizarre ?\n"
	.string "Je te le dis, tu\p"
	.string "essaies d'atteindre\n"
	.string "une île qui n'apparaît\l"
	.string "que rarement.\p"
	.string "Bonne chance !$"

EventTicket_Text_SouthernIslandSailBack:
	.string "Hé, matelot, y a rien à voir ni à faire\n"
	.string "sur cette île oubliable.\p"
	.string "Et si on levait l'ancre pour OLIVILLE ?$"

EventTicket_Text_SailHome:
	.string "Bon, d'accord !\n"
	.string "Rentrons à la maison !$"

EventTicket_Text_AsYouLike:
	.string "Oui, d'accord, comme tu veux.$"

SouthernIsland_Interior_Text_Sign:
	.string "« Tous les rêves ne sont qu'une autre réalité.\n"
	.string "N'oublie jamais… »$"

SouthernIsland_Exterior_Text_Sign:
	.string "« Ceux dont les souvenirs s'effacent cherchent à\n"
	.string "les graver dans leur cœur… »$"
