EventTicket_Text_OldSeaMapTooFar:
	.string "Quoi de neuf, gamin ?\p"
	.string "Quoi, c'est toi qui es censé avoir\n"
	.string "une vieille carte en lambeaux ?\p"
	.string "Montre-moi ça.\n"
	.string "… … … … … …\p"
	.string "Bon sang, c'est très loin.\n"
	.string "J'ai bien peur de ne pas pouvoir t'aider…$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "RIVAGE : Attends une seconde !\p"
	.string "Quelle idée de refuser\n"
	.string "quelqu'un à qui je dois tant !$"

EventTicket_Text_BrineyLetsSail:
	.string "{PLAYER}{KUN}, je suis terriblement désolé. Tu es\p"
	.string "venu me demander de l'aide, et\n"
	.string "on a failli te renvoyer. Eh\p"
	.string "bien, laisse-moi arranger les choses. On\p"
	.string "met les voiles tout de suite,\p"
	.string "bien sûr ! Trouvons cette île\n"
	.string "sur cette VIEILLE CARTE MARINE !$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "C'est toi qui as apporté\n"
	.string "ce billet étrange ? L'île\p"
	.string "où tu veux aller est\n"
	.string "très, très loin. Personne ne\p"
	.string "sait ce qui t'y attend…\p"
	.string "La simple pensée excite mon\n"
	.string "sang de marin !\p"
	.string "Monte à bord !$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "Tu veux retourner à OLIVILLE ?$"

BirthIsland_Harbor_Text_SailorReturn:
	.string "Quelle île bizarre, hein ?\n"
	.string "Tu veux retourner à OLIVILLE ?$"

EventTicket_Text_OddTicketsWhereTo:
	.string "C'est toi qui\n"
	.string "a apporté ces\p"
	.string "billets\p"
	.string "étranges ?\n"
	.string "… … …Hm.\p"
	.string "Ces billets\n"
	.string "t'emmèneront\p"
	.string "sur des îles\n"
	.string "qui n'apparaissent\p"
	.string "que rarement.\n"
	.string "Bonne chance !$"

NavelRock_Harbor_Text_SailorReturn:
	.string "Tu… Tu as entendu ça ? Ce\n"
	.string "grognement sourd venant des profondeurs. Tu es\p"
	.string "sûr que c'est sans danger ?\n"
	.string "Tu crois qu'on devrait partir ?$"

FarawayIsland_Entrance_Text_Sign:
	.string "L'écriture s'efface comme si elle\n"
	.string "avait été écrite il y a longtemps…\p"
	.string "« …bre, 6e jour\n"
	.string "Si un humain…met le pied ici…\l"
	.string "encore…ue ce soit une personne au bon cœur…\l"
	.string "…vec cet espoir, je pars… »$"

FarawayIsland_Interior_Text_Mew:
	.string "Myuu…$"
