@ Battle Tower
gText_AnabelWonSilver::
	.string "C'est très décevant…$"

gText_AnabelDefeatSilver::
	.string "OK, je comprends…$"

gText_AnabelWonGold::
	.string "Je suis vraiment désolée…$"

gText_AnabelDefeatGold::
	.string "Merci…$"

@ Battle Dome
gText_TuckerWonSilver::
	.string "Ahahaha ! Tu n'as pas honte ?\n"
	.string "Tout le monde regarde !$"

gText_TuckerDefeatSilver::
	.string "Grrr…\n"
	.string "Qu'est-ce que…$"

gText_TuckerWonGold::
	.string "Mon titre d'AS DU DÔME n'est pas que pour la forme !$"

gText_TuckerDefeatGold::
	.string "Ahahaha !\n"
	.string "Tu es inspirant !$"

@ Battle Factory
gText_NolandWonSilver::
	.string "Bien joué !\n"
	.string "C'était une bonne leçon, hein ?$"

gText_NolandDefeatSilver::
	.string "Bien joué !\n"
	.string "Tu sais ce que tu fais !$"

gText_NolandWonGold::
	.string "Hé, hé, hé !\n"
	.string "Tu as déjà fini ?$"

gText_NolandDefeatGold::
	.string "Que s'est-il passé ici ?$"

@ Battle Pike
gText_LucyWonSilver::
	.string "Pfff…$"

gText_LucyDefeatSilver::
	.string "Argh…$"

gText_LucyWonGold::
	.string "Ha !$"

gText_LucyDefeatGold::
	.string "Mince !$"

@ Battle Arena
gText_GretaWonSilver::
	.string "Oh, allez !\n"
	.string "Tu dois faire mieux que ça !$"

gText_GretaDefeatSilver::
	.string "Pas possible !\n"
	.string "Bien joué !$"

gText_GretaWonGold::
	.string "Héhé !\n"
	.string "Tu t'attendais à quoi ?$"

gText_GretaDefeatGold::
	.string "Hein ?\n"
	.string "Tu es sérieux ?!$"

@ Battle Palace
gText_SpenserWonSilver::
	.string "Tes POKéMON sont faiblots parce que\n"
	.string "tu es faiblote comme DRESSEUR !$"

gText_SpenserDefeatSilver::
	.string "Ah…\n"
	.string "Voilà qui est autre chose…$"

gText_SpenserWonGold::
	.string "Gwahahaha !\n"
	.string "Mes frères, nous n'avons rien à craindre !$"

gText_SpenserDefeatGold::
	.string "Gwah !\n"
	.string "Hahahaha !$"

@ Battle Pyramid
gText_BrandonWonSilver::
	.string "Hé ! Qu'est-ce qui ne va pas !\n"
	.string "Montre un peu d'effort ! Debout !$"

gText_BrandonDefeatSilver::
	.string "C'est ça ! Tu as été génial !\n"
	.string "Tu as travaillé dur pour ça !$"

gText_BrandonWonGold::
	.string "Hé ! N'abandonne pas maintenant !\n"
	.string "Relève-toi ! N'aie pas foi en toi !$"

gText_BrandonDefeatGold::
	.string "C'est ça ! Tu l'as fait !\n"
	.string "Tu as travaillé pour ça !$"
