LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "C'est le COIN LOTERIE POKéMON.\p"
	.string "Si le numéro du TICKET\n"
	.string "LOTO correspond à l'ID d'un\l"
	.string "de tes POKéMON, tu recevras\p"
	.string "un fabuleux cadeau. Veux-tu tirer\n"
	.string "un TICKET LOTO POKéMON ?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "Reviens demain, s'il te plaît.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "Revenez nous voir.$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "Veuillez choisir un TICKET LOTO.\n"
	.string "…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "Le numéro du TICKET LOTO est {STR_VAR_1}.\p"
	.string "Je dois vérifier ce numéro\n"
	.string "pour voir s'il correspond à l'un de tes\l"
	.string "numéros d'identification POKéMON. Patientez.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "Félicitations !\p"
	.string "Le numéro ID du {STR_VAR_1} de ton équipe\n"
	.string "correspond au numéro de ton\l"
	.string "TICKET DE LOTERIE !$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "Félicitations !\p"
	.string "Le numéro d'identification de ton\n"
	.string "{STR_VAR_1} en PC correspond à celui\l"
	.string "de ton TICKET LOTO !$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "Je suis désolé.\n"
	.string "Aucun des numéros ne correspond.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "Deux chiffres correspondent, tu gagnes le\n"
	.string "troisième prix !\l"
	.string "Tu as gagné le {STR_VAR_1} !$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "Trois chiffres correspondent, tu gagnes le\n"
	.string "deuxième prix !\l"
	.string "Tu as gagné le {STR_VAR_1} !$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "Quatre chiffres correspondent, tu gagnes le\n"
	.string "premier prix !\l"
	.string "Tu as gagné le {STR_VAR_1} !$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "Oh, mon Dieu, les cinq chiffres\n"
	.string "correspondent !\p"
	.string "Tu as gagné le gros lot !\n"
	.string "Tu as gagné {STR_VAR_1} !$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "Oh ?\n"
	.string "Tu n'as pas l'air d'avoir de place pour ça.\p"
	.string "Fais de la place dans ton SAC et\n"
	.string "fais-le moi savoir.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{PLAYER} ?\n"
	.string "Oui, je t'attendais.\p"
	.string "Voici le lot que nous gardions\n"
	.string "pour toi.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "Revenez nous voir.$"
