MatchCall_WildBattleText1::
	.string "Salut ! {PLAYER}{KUN}, bonjour !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai vu un {STR_VAR_2} il y a peu\n"
	.string "mais je n'ai pas pu l'attraper.\p"
	.string "Il était si proche !\n"
	.string "Bon, à bientôt !$"

MatchCall_WildBattleText2::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai essayé d'attraper un joli {STR_VAR_2}\n"
	.string "il y a peu.\p"
	.string "Mais il s'est échappé.\n"
	.string "J'étais vraiment déçu !\p"
	.string "OK, salut !$"

MatchCall_WildBattleText3::
	.string "Hé, {PLAYER} !\n"
	.string "C'est moi, {STR_VAR_1}.\p"
	.string "Je viens d'essayer d'attraper\n"
	.string "ce {STR_VAR_2}, mais il s'est enfui.\p"
	.string "J'étais si près, pourtant !\p"
	.string "Ça m'a gâché la journée…\n"
	.string "OK, à plus !$"

MatchCall_WildBattleText4::
	.string "Salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu connais le POKéMON {STR_VAR_2} ?\n"
	.string "J'ai failli en attraper un.\p"
	.string "C'était il n'y a pas longtemps.\n"
	.string "Je pensais l'avoir mais il s'est\p"
	.string "échappé.\n"
	.string "Si je le revois, je l'aurai à coup\p"
	.string "sûr. À plus tard.$"

MatchCall_WildBattleText5::
	.string "Salut, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1}.\l"
	.string "Tu attrapes des POKéMON en ce moment ?\p"
	.string "Il y a peu, j'ai failli en attraper un,\n"
	.string "mais il s'est échappé.\p"
	.string "Bon, à plus !$"

MatchCall_WildBattleText6::
	.string "Salut, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} à l'appareil.\l"
	.string "Tu as attrapé des POKéMON récemment ?\p"
	.string "J'ai failli en attraper un l'autre jour.\n"
	.string "Mais il m'a échappé d'une façon ou d'une autre.\p"
	.string "Prends soin de toi.$"

MatchCall_WildBattleText7::
	.string "…Euh, {PLAYER}{KUN} ?\n"
	.string "C'est moi, {STR_VAR_1}.\p"
	.string "Oh, attends ! Attends !\n"
	.string "Je peux attraper ce {STR_VAR_2}…\p"
	.string "Aaarrrgh ! Il s'est échappé !\n"
	.string "C'était moins une !$"

MatchCall_WildBattleText8::
	.string "Oh, {PLAYER}{KUN}, comment vas-tu ?\n"
	.string "C'est {STR_VAR_1} qui parle. As-tu\p"
	.string "réussi à attraper des POKéMON\n"
	.string "récemment ? J'ai failli réussir\p"
	.string "il y a peu,\n"
	.string "mais ma cible s'est\p"
	.string "échappée. Il faut que\n"
	.string "j'essaie plus fort !$"

MatchCall_WildBattleText9::
	.string "Oh, {PLAYER}{KUN}, salut !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "Alors ? Tu attrapes plus de POKéMON\n"
	.string "ensemble ?\p"
	.string "J'ai vraiment du mal !\n"
	.string "Ils m'échappent tous !\p"
	.string "À bientôt !$"

MatchCall_WildBattleText10::
	.string "Oh, {PLAYER}{KUN}, bonjour…\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Écoute, j'ai failli attraper\n"
	.string "ce {STR_VAR_2}…\p"
	.string "Mais il m'a échappé…\p"
	.string "Il faut que je redouble d'efforts.\n"
	.string "À bientôt.$"

MatchCall_WildBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\l"
	.string "Comment ça va ?\p"
	.string "J'ai essayé d'attraper un {STR_VAR_2}\n"
	.string "sauvage tout à l'heure, mais il s'est enfui.\p"
	.string "Je me sens vaincu…$"

MatchCall_WildBattleText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C'est moi, {STR_VAR_1}.\l"
	.string "Tu attrapes encore des POKéMON ?\p"
	.string "J'essaie de les attraper\n"
	.string "moi-même, mais ce n'est pas si facile.\p"
	.string "La voie des POKéMON est profonde !$"

MatchCall_WildBattleText13::
	.string "Ah, bonjour, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1} !\l"
	.string "Tu as attrapé des POKéMON ?\p"
	.string "J'essaie de les attraper\n"
	.string "moi-même, mais avec peu de succès.\p"
	.string "La voie des POKéMON est profonde !$"

MatchCall_WildBattleText14::
	.string "Oh, salut, {PLAYER}{KUN}, comment ça va ?\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tout à l'heure, j'ai essayé d'attraper un mignon\n"
	.string "{STR_VAR_2}.\p"
	.string "Il s'est enfui !\n"
	.string "Oh, j'étais tellement déçu !\p"
	.string "Salut !$"

MatchCall_WildBattleText15::
	.string "Salut, {PLAYER} ! C'est\n"
	.string "{STR_VAR_1} ! Je pensais\p"
	.string "essayer d'attraper des POKéMON.\n"
	.string "Mais je n'arrive à\p"
	.string "en trouver aucun. C'est\n"
	.string "un vrai casse-tête !\p"
	.string "Je suis à bout\n"
	.string "! À bientôt !$"

MatchCall_NegativeBattleText1::
	.string "Salut ! {PLAYER}{KUN}, bonjour !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai essayé de me battre contre un autre DRESSEUR,\n"
	.string "mais j'ai perdu.\p"
	.string "C'était vraiment décevant.\n"
	.string "Bon, à bientôt !$"

MatchCall_NegativeBattleText2::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai défié quelqu'un d'autre après\n"
	.string "notre combat.\p"
	.string "J'ai failli gagner, mais j'ai fini par\n"
	.string "perdre. Tant pis !$"

MatchCall_NegativeBattleText3::
	.string "Hé, {PLAYER} ! C'est moi,\n"
	.string "{STR_VAR_1}. Je viens de me\p"
	.string "faire écraser en combat. Je\p"
	.string "crois qu'il faut que j'entraîne\n"
	.string "encore mon équipe !$"

MatchCall_NegativeBattleText4::
	.string "Hé, {PLAYER}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai essayé un autre combat hier,\n"
	.string "mais je n'ai pas réussi à gagner.\p"
	.string "Mon équipe a besoin de plus d'entraînement.\n"
	.string "OK, à plus tard.$"

MatchCall_NegativeBattleText5::
	.string "Salut, {PLAYER} !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Comment ça va de ton côté ?\p"
	.string "Je continue à me battre,\n"
	.string "mais je ne gagne pas souvent.\p"
	.string "Je n'arrive pas à me concentrer.\n"
	.string "Bon, à plus !$"

MatchCall_NegativeBattleText6::
	.string "Hé, {PLAYER}.\n"
	.string "{STR_VAR_1} à l'appareil.\p"
	.string "Comment ça se passe pour toi ?\p"
	.string "J'ai combattu dur récemment,\n"
	.string "mais sans grand succès.\p"
	.string "Je n'arrive pas à trouver mon rythme.\n"
	.string "Prends soin de toi.$"

MatchCall_NegativeBattleText7::
	.string "{STR_VAR_1} ici.\n"
	.string "Comment ça va ces temps-ci ?\p"
	.string "J'ai perdu un combat hier,\n"
	.string "et ça me obsède.\p"
	.string "Je dois trouver un plan…\n"
	.string "À plus.$"

MatchCall_NegativeBattleText8::
	.string "Oh, {PLAYER}{KUN}, comment vas-tu ?\n"
	.string "C'est {STR_VAR_1} qui parle.\p"
	.string "Comment vont tes POKéMON ?\n"
	.string "J'ai perdu un combat l'autre jour.\p"
	.string "Je dois faire mieux !\n"
	.string "À bientôt !$"

MatchCall_NegativeBattleText9::
	.string "Oh, {PLAYER}{KUN}, salut !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "Écoute, écoute, tu dois entendre\n"
	.string "ça !\p"
	.string "J'ai eu un combat POKéMON tout à l'heure,\n"
	.string "mais j'ai perdu à la dernière seconde.\p"
	.string "Oh, ça me rend fou !$"

MatchCall_NegativeBattleText10::
	.string "Oh, {PLAYER}{KUN}, bonjour…\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Il y a peu, j'ai eu un combat.\n"
	.string "J'ai perdu, pourtant.\p"
	.string "Il faut que j'entraîne mes POKéMON davantage.\n"
	.string "À bientôt.$"

MatchCall_NegativeBattleText11::
	.string "Ah, {PLAYER}{KUN}. C'est {STR_VAR_1}.\n"
	.string "Comment vont tes POKéMON\l"
	.string "? Je viens encore\p"
	.string "de perdre un combat.\p"
	.string "Bon, à plus !$"

MatchCall_NegativeBattleText12::
	.string "Salut, {PLAYER}{KUN}.\n"
	.string "C'est moi, {STR_VAR_1}.\l"
	.string "Tu combats toujours dur ?\p"
	.string "Pour ma part, j'ai perdu récemment, alors j'ai\n"
	.string "entraîné mon équipe partout.\p"
	.string "On se revoit.$"

MatchCall_NegativeBattleText13::
	.string "Ah, bonjour, {PLAYER}{KUN} ! C'est\n"
	.string "{STR_VAR_1} ! J'espère que tu\p"
	.string "vas bien. Je me suis\p"
	.string "battu il y a\n"
	.string "un petit moment. {PLAYER}{KUN},\p"
	.string "essaie d'être actif comme\n"
	.string "moi. À bientôt !$"

MatchCall_NegativeBattleText14::
	.string "Oh, salut, {PLAYER}{KUN}. C'est\n"
	.string "{STR_VAR_1}. Tu vas bien\p"
	.string "? Tu devrais rentrer\p"
	.string "à la maison de\n"
	.string "temps en temps.\p"
	.string "À bientôt !$"

MatchCall_PositiveBattleText1::
	.string "Salut ! {PLAYER}{KUN}, bonjour !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "J'ai combattu un autre DRESSEUR tout à l'heure.\n"
	.string "J'ai gagné ! J'ai gagné !\p"
	.string "Mon {STR_VAR_2} a vraiment bien travaillé\n"
	.string "pour moi. C'est génial !$"

MatchCall_PositiveBattleText2::
	.string "Bonjour, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "J'ai eu un combat hier et\n"
	.string "j'ai gagné ! C'est génial !$"

MatchCall_PositiveBattleText3::
	.string "Salut, {PLAYER} ! C'est\n"
	.string "moi, {STR_VAR_1} ! Comment\l"
	.string "vont tes combats ?\p"
	.string "Moi, j'ai eu\n"
	.string "un combat hier.\p"
	.string "J'ai gagné !\n"
	.string "À bientôt !{STR_VAR_2}{PLAYER}$"

MatchCall_PositiveBattleText4::
	.string "Salut, {PLAYER}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai eu un combat tout à l'heure.\n"
	.string "J'ai réussi à gagner, mais c'était serré.\p"
	.string "Mon {STR_VAR_2} a fait une\n"
	.string "prestation inspirée.$"

MatchCall_PositiveBattleText5::
	.string "Salut, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1}. Comment\p"
	.string "ça va ?\n"
	.string "Tu combats beaucoup\p"
	.string "? Moi, j'ai\n"
	.string "gagné un combat\p"
	.string "hier ! À\n"
	.string "bientôt !{STR_VAR_2}$"

MatchCall_PositiveBattleText6::
	.string "Hé, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Comment ça va pour toi ?\p"
	.string "J'enchaîne les victoires.\n"
	.string "Je viens de gagner un combat.\p"
	.string "Lors de notre prochain combat,\n"
	.string "je ne compte pas perdre !$"

MatchCall_PositiveBattleText7::
	.string "{PLAYER}{KUN} ?\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Mon {STR_VAR_2} est une force !\n"
	.string "Il m'a fait gagner un autre combat !\p"
	.string "J'ai hâte d'avoir une revanche\n"
	.string "avec toi.$"

MatchCall_PositiveBattleText8::
	.string "Oh, {PLAYER}{KUN}, comment vas-tu ?\n"
	.string "C'est {STR_VAR_1} qui parle. J'espère\p"
	.string "que tu vas bien.\n"
	.string "Je voulais te dire\p"
	.string "que j'ai gagné. Mon\n"
	.string "{STR_VAR_2} a travaillé particulièrement\p"
	.string "dur. À bientôt !$"

MatchCall_PositiveBattleText9::
	.string "Oh, {PLAYER}{KUN}, salut !\n"
	.string "C'est {STR_VAR_1} ! Comment\p"
	.string "vont tes POKéMON ?\n"
	.string "Les miens se portent\p"
	.string "bien ! On\n"
	.string "se bat si\p"
	.string "tu es dans\n"
	.string "le coin !{STR_VAR_2}$"

MatchCall_PositiveBattleText10::
	.string "Oh, {PLAYER}{KUN}, bonjour…\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Comment ça va ?\p"
	.string "Mes POKéMON semblent débordants\n"
	.string "d'énergie.\p"
	.string "Je viens de gagner un combat avec eux.\n"
	.string "À bientôt.$"

MatchCall_PositiveBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu as combattu récemment ?\n"
	.string "J'en ai gagné un autre aujourd'hui !\p"
	.string "Je suis en forme ! Gahahaha !\n"
	.string "À plus !$"

MatchCall_PositiveBattleText12::
	.string "Bonjour, {PLAYER}{KUN}. C'est moi, {STR_VAR_1}. J'espère\n"
	.string "que tu vas bien ? Je\p"
	.string "suis toujours plein de vie !\n"
	.string "À l'instant même, j'ai gagné\p"
	.string "un autre match. Je ne\n"
	.string "cède pas encore ma place\l"
	.string "aux jeunes comme toi !$"

MatchCall_PositiveBattleText13::
	.string "Ah, bonjour, {PLAYER}{KUN} ! C'est\n"
	.string "{STR_VAR_1} ! J'espère que tu\p"
	.string "vas bien. J'ai encore de\n"
	.string "l'énergie ! Tiens, j'ai encore\p"
	.string "gagné un combat. Oh, je\n"
	.string "ne perdrai pas face\l"
	.string "aux jeunes si tôt\p"
	.string "! À bientôt !$"

MatchCall_PositiveBattleText14::
	.string "Oh, salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai eu un combat récemment, et mon\n"
	.string "{STR_VAR_2} était exceptionnel !\p"
	.string "J'aurais aimé que tu le voies,\n"
	.string "{PLAYER}{KUN}. Salut !$"

MatchCall_SameRouteBattleRequestText1::
	.string "Salut ! {PLAYER}, bonjour !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Hein ? Attends, tu es près de\n"
	.string "{STR_VAR_2} ?\p"
	.string "Oh, super, on doit se battre !\n"
	.string "Je t'attends ! À plus !$"

MatchCall_SameRouteBattleRequestText2::
	.string "Bonjour, {PLAYER} !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Oh ? Tu es vers\n"
	.string "{STR_VAR_2} en ce moment ?\p"
	.string "Tu veux te battre maintenant ?\n"
	.string "Je t'attends ! À bientôt !$"

MatchCall_SameRouteBattleRequestText3::
	.string "Salut, {PLAYER} !\n"
	.string "C'est moi, {STR_VAR_1}.\p"
	.string "Oh, tu es\n"
	.string "près de {STR_VAR_2}\p"
	.string "en ce moment\n"
	.string "? Viens me\p"
	.string "voir pour un\n"
	.string "combat !$"

MatchCall_SameRouteBattleRequestText4::
	.string "Hé, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Où es-tu maintenant ?\n"
	.string "Hein ? {STR_VAR_2} ?\p"
	.string "Tu veux te battre maintenant ?\n"
	.string "Je t'attends. À plus !$"

MatchCall_SameRouteBattleRequestText5::
	.string "Salut, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1}. Comment\l"
	.string "ça va ?\p"
	.string "Tu es où\n"
	.string "maintenant ? {STR_VAR_2}\p"
	.string "? Viens me\n"
	.string "voir si tu\p"
	.string "es dans le\n"
	.string "coin !$"

MatchCall_SameRouteBattleRequestText6::
	.string "Hé, {PLAYER}{KUN}. C'est {STR_VAR_1}.\n"
	.string "Comment vont tes POKéMON\l"
	.string "? Oh, c'est ça\p"
	.string "? Tu es vers\n"
	.string "{STR_VAR_2} ? Eh bien,\p"
	.string "on ferait mieux de\n"
	.string "se battre à nouveau.\p"
	.string "Je peux attendre, bien\n"
	.string "sûr. À bientôt !$"

MatchCall_SameRouteBattleRequestText7::
	.string "…Euh, {PLAYER}{KUN} ?\n"
	.string "C'est {STR_VAR_1}…\p"
	.string "Oh, tu es par hasard vers\n"
	.string "{STR_VAR_2} ?\p"
	.string "Alors, battons-nous.\n"
	.string "Tout de suite.\p"
	.string "Je vais te montrer mes POKéMON.\n"
	.string "Je t'attends.$"

MatchCall_SameRouteBattleRequestText8::
	.string "Oh, {PLAYER}{KUN}, comment vas-tu\n"
	.string "? C'est {STR_VAR_1} qui\p"
	.string "parle. J'espère que tu\n"
	.string "vas bien. Oh, tu\p"
	.string "es près de {STR_VAR_2}.\n"
	.string "Tu voudrais te battre\p"
	.string "avec moi ? Je\n"
	.string "t'attendrai. À bientôt !$"

MatchCall_SameRouteBattleRequestText9::
	.string "Oh, {PLAYER}{KUN}, salut !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "Tu progresses bien ?\n"
	.string "Oh, tu es près de {STR_VAR_2} ?\p"
	.string "Alors, tu ne crois pas qu'on\n"
	.string "devrait se battre ?\p"
	.string "Ne me fais pas attendre trop longtemps !$"

MatchCall_SameRouteBattleRequestText10::
	.string "Oh, {PLAYER}{KUN}, bonjour…\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Comment ça va ?\n"
	.string "Oh, tu es près de {STR_VAR_2}.\p"
	.string "On devrait se battre maintenant, alors.\p"
	.string "Je suis prêt et j'attends.\n"
	.string "Dépêche-toi !$"

MatchCall_SameRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}. C'est {STR_VAR_1}. Ah,\n"
	.string "donc tu es à {STR_VAR_2}\p"
	.string "maintenant ? Eh bien,\n"
	.string "il faut qu'on se\p"
	.string "batte, tu ne trouves\n"
	.string "pas ? Je t'attends\p"
	.string "sur place ! À\n"
	.string "tout de suite !$"

MatchCall_SameRouteBattleRequestText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C'est moi, {STR_VAR_1}.\l"
	.string "Où es-tu maintenant ?\p"
	.string "{STR_VAR_2} ?\n"
	.string "C'est tout près !\p"
	.string "Que dirais-tu qu'on se batte\n"
	.string "maintenant ?\p"
	.string "Je peux attendre.\n"
	.string "À bientôt !$"

MatchCall_SameRouteBattleRequestText13::
	.string "Ah, bonjour, {PLAYER}{KUN} ! C'est\n"
	.string "{STR_VAR_1} ! J'espère que tu\p"
	.string "vas bien. Oh, tu\n"
	.string "es près de {STR_VAR_2}\p"
	.string "? Comme ce n'est\n"
	.string "pas loin, viens me\p"
	.string "voir pour un combat.\n"
	.string "Je t'attendrai. À bientôt.$"

MatchCall_SameRouteBattleRequestText14::
	.string "Oh, salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu es quoi ? …{STR_VAR_2} ?\n"
	.string "C'est tout près.\p"
	.string "Tu ne crois pas qu'on devrait\n"
	.string "se battre ?\p"
	.string "Je te chercherai !\n"
	.string "Salut !$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "Salut ! {PLAYER}, bonjour\n"
	.string "! C'est {STR_VAR_1}. Tu\p"
	.string "veux te battre avec\p"
	.string "moi ? Je t'attendrai\n"
	.string "vers {STR_VAR_2} !$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "Bonjour, {PLAYER} !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu veux qu'on se batte\n"
	.string "à nouveau ?\p"
	.string "Tu peux me trouver vers\n"
	.string "{STR_VAR_2}. Je t'attends !$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "Salut, {PLAYER} !\n"
	.string "C'est moi, {STR_VAR_1}.\p"
	.string "Mes POKéMON sont devenus beaucoup\n"
	.string "plus forts depuis\p"
	.string "la dernière fois.\n"
	.string "Je veux voir à quel point ils sont\p"
	.string "forts face à tes POKéMON, {PLAYER}.\p"
	.string "Alors, combat !\n"
	.string "Je t'attends vers {STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "Salut, {PLAYER}{KUN}. C'est {STR_VAR_1}.\n"
	.string "Comment ça va ?\l"
	.string "Mes POKéMON sont devenus\p"
	.string "assez forts récemment.\n"
	.string "Hé, ça te\p"
	.string "dirait un autre\n"
	.string "combat avec moi\p"
	.string "? Retrouvons-nous vers\n"
	.string "{STR_VAR_2}, OK ?$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "Salut, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1}. Mes\p"
	.string "POKéMON grandissent bien.\n"
	.string "Je voudrais te\p"
	.string "montrer à quel\n"
	.string "point ils sont\p"
	.string "forts. Je serai\n"
	.string "vers {STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "Salut, {PLAYER}{KUN}. C'est\n"
	.string "{STR_VAR_1}. J'espère que\l"
	.string "tu tiens le\p"
	.string "coup. Je pensais\n"
	.string "à un combat\p"
	.string "avec toi. Je\n"
	.string "serai vers {STR_VAR_2}.\p"
	.string "À bientôt !$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "…Euh, {PLAYER}{KUN} ? C'est {STR_VAR_1}…\n"
	.string "Alors ? Tes POKéMON grandissent\l"
	.string "bien ? Les miens\p"
	.string "se sont sûrement renforcés.\n"
	.string "J'aimerais te le montrer.\p"
	.string "Je serai vers {STR_VAR_2}.\n"
	.string "Viens me voir pour\p"
	.string "un match. À bientôt.$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "Oh, {PLAYER}{KUN}, comment vas-tu ?\n"
	.string "C'est {STR_VAR_1} qui parle. J'espère\p"
	.string "que tu vas bien. Mes\n"
	.string "POKéMON sont très fringants.\p"
	.string "Si tu es dans\n"
	.string "le coin, donne-moi une\p"
	.string "revanche. Je serai vers\n"
	.string "{STR_VAR_2}. À bientôt !$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "Oh, {PLAYER}{KUN}, salut !\n"
	.string "C'est {STR_VAR_1} !\l"
	.string "Comment vont tes POKéMON ?\p"
	.string "Mes POKéMON s'améliorent sans\n"
	.string "cesse. J'aimerais te les montrer,\p"
	.string "{PLAYER}{KUN}.\n"
	.string "Je suis vers {STR_VAR_2} maintenant,\p"
	.string "alors combattons si tu es dans le coin. J'espère te voir bientôt !$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "Oh, {PLAYER}{KUN}, bonjour…\n"
	.string "C'est {STR_VAR_1}.\l"
	.string "Alors, comment ça va ?\p"
	.string "Mes POKéMON sont devenus bien\n"
	.string "plus forts qu'avant.\p"
	.string "J'aimerais un autre combat avec\n"
	.string "toi, {PLAYER}{KUN}.\p"
	.string "Je serai vers {STR_VAR_2}.\n"
	.string "Viens me voir si tu es dans le coin.$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}. C'est {STR_VAR_1}. Où\n"
	.string "es-tu en ce moment ?\l"
	.string "Mes POKéMON débordent de vie.\p"
	.string "Ils ont l'air d'attendre\n"
	.string "avec impatience tes POKéMON,\l"
	.string "{PLAYER}{KUN}. Je suis vers\p"
	.string "{STR_VAR_2} maintenant. J'espère que\n"
	.string "tu viendras nous voir.$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "Bonjour, {PLAYER}{KUN}. C'est moi, {STR_VAR_1}.\n"
	.string "Je dois te dire, mes\p"
	.string "POKéMON sont devenus assez robustes\n"
	.string "récemment. J'aimerais les voir\p"
	.string "en combat contre toi,\n"
	.string "{PLAYER}{KUN}. On sera vers\p"
	.string "{STR_VAR_2}. Viens nous voir\n"
	.string "quand tu veux !$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "Ah, bonjour,\n"
	.string "{PLAYER}{KUN} !\l"
	.string "C'est {STR_VAR_1} !\p"
	.string "Tes POKéMON\n"
	.string "vont bien ?\p"
	.string "Mes POKéMON ont\n"
	.string "beaucoup grandi\p"
	.string "grâce à tes conseils !\n"
	.string "Merci !{STR_VAR_2}$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "Oh, salut,\n"
	.string "{PLAYER}{KUN}.\l"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu vas bien, j'espère.\n"
	.string "Oh, oui ! Mes\p"
	.string "POKéMON sont\n"
	.string "bien plus forts\p"
	.string "maintenant.\n"
	.string "Merci pour\p"
	.string "tes conseils !{PLAYER}{KUN}{STR_VAR_2}$"

MatchCall_PersonalizedText1::
	.string "C'est moi, {STR_VAR_1} l'amoureux\n"
	.string "des montagnes ! Depuis\p"
	.string "qu'on s'est rencontrés, as-tu\n"
	.string "apprécié les montagnes ?\p"
	.string "Moi, je les\p"
	.string "adore toujours !\n"
	.string "À bientôt !{STR_VAR_2}$"

MatchCall_PersonalizedText2::
	.string "C'est {STR_VAR_1}. Bonjour. Je parlais\n"
	.string "justement d'une nouvelle DRESSEUSE à\p"
	.string "propos de toi. Je lui\n"
	.string "ai parlé d'un DRESSEUR fort\p"
	.string "qui élève ses POKéMON avec\n"
	.string "soin. J'espère que tu deviendras\p"
	.string "un DRESSEUR que tout\n"
	.string "le monde admirera. J'espère\p"
	.string "qu'on se reverra !$"

MatchCall_PersonalizedText3::
	.string "Bonjour ! C'est {STR_VAR_1}.\p"
	.string "J'adore l'endroit où je suis.\n"
	.string "C'est agréable avec de doux parfums !\p"
	.string "Je crois que quelqu'un a planté des BAIES,\n"
	.string "et elles ont fleuri.\p"
	.string "À une prochaine fois !$"

MatchCall_PersonalizedText4::
	.string "Bonjour ! Trente ans d'exploration,\n"
	.string "{STR_VAR_1} à ton service !\p"
	.string "Il semble que tu voyages avec\n"
	.string "beaucoup d'énergie.\p"
	.string "As-tu découvert de nouvelles\n"
	.string "ruines ? Dis-le-moi si c'est le cas !\p"
	.string "Maintenant, si tu veux bien\n"
	.string "m'excuser, j'ai des ruines à explorer.$"

MatchCall_PersonalizedText5::
	.string "C'est {STR_VAR_1} !\p"
	.string "Tu sais ce que je fais aujourd'hui ?\n"
	.string "Regarder les vagues depuis la plage !\p"
	.string "Soupir… Les vagues brillent.\n"
	.string "La mer est la plus belle d'ici.\l"
	.string "J'ai faim, alors au revoir !$"

MatchCall_PersonalizedText6::
	.string "Miam-miam…\n"
	.string "Oh, salut, c'est {STR_VAR_1}.\l"
	.string "J'adore manger à la plage.\p"
	.string "Mon POKéMON et moi allons très bien.\n"
	.string "On est au max !\l"
	.string "Je vais me baigner. Salut !$"

MatchCall_PersonalizedText7::
	.string "Allô, c'est {STR_VAR_1}…\p"
	.string "Je commence à en avoir assez de ce\n"
	.string "statut de TOPDRESSEUR…\p"
	.string "Tout le monde pense que je suis un\n"
	.string "DRESSEUR parfait, et ça me pousse à\l"
	.string "être à la hauteur de cette attente.\p"
	.string "Mais je suppose que ça va avec le fait\n"
	.string "d'être TOPDRESSEUR.\p"
	.string "Je vais juste devoir me ressaisir…\n"
	.string "et faire bonne figure.\p"
	.string "Tu es la seule personne à qui je peux\n"
	.string "me confier comme ça.\p"
	.string "Mais quand on se reverra,\n"
	.string "ne t'inquiète pas, je ne me plaindrai pas !$"

MatchCall_PersonalizedText8::
	.string "Yahoo, it's {STR_VAR_1}!\n"
	.string "How do you do?\p"
	.string "I've been raising my POKéMON with\n"
	.string "you as the target.\p"
	.string "I don't intend to lose when we\n"
	.string "battle again.\p"
	.string "Isn't it great to have TRAINER\n"
	.string "friends? Let's meet again!$"

MatchCall_PersonalizedText9::
	.string "C'est {STR_VAR_1}… En ce\n"
	.string "moment, derrière toi… Il\l"
	.string "n'y avait pas quelque\p"
	.string "chose… ? Le pouvoir\n"
	.string "des POKéMON qui dorment\p"
	.string "ici au MONT SÉPIA…\p"
	.string "Il me parle de\n"
	.string "toi… Tu devrais t'éloigner\p"
	.string "vite et ne jamais\n"
	.string "te retourner… Hihi… Adieu…$"

MatchCall_PersonalizedText10::
	.string "C'est {STR_VAR_1}. Comment vas-tu ?\n"
	.string "Ce n'est pas pratique qu'on\p"
	.string "puisse parler comme ça à\n"
	.string "distance ? Avant, si je\p"
	.string "voulais parler à quelqu'un, il\n"
	.string "fallait que mon père\l"
	.string "me conduise… Je devrais\p"
	.string "y aller. Je suis\n"
	.string "content qu'on ait discuté.$"

MatchCall_PersonalizedText11::
	.string "C'est {STR_VAR_1} !\n"
	.string "Tu veux bien écouter ça ?\p"
	.string "J'adore le PARC SAFARI,\n"
	.string "mais à chaque fois que j'y vais, je me perds !\p"
	.string "Toute cette haute herbe !\n"
	.string "Et c'est beaucoup trop grand !\p"
	.string "Ça fait du bien de me confier\n"
	.string "à quelqu'un !\p"
	.string "Je retourne au PARC SAFARI !\n"
	.string "À plus !$"

MatchCall_PersonalizedText12::
	.string "Bonjour, c'est {STR_VAR_1}.\n"
	.string "Oui, c'est correct, je suis riche, oui.\p"
	.string "Je devrais te dire, ma richesse a\n"
	.string "cru depuis notre dernière rencontre.\p"
	.string "De plus, mes POKéMON sont aussi\n"
	.string "devenus plus forts.\p"
	.string "Je n'arrive pas à me défaire du sentiment que\n"
	.string "ce monde existe pour moi !\p"
	.string "Oh, pas besoin de dire un mot !\n"
	.string "Tout le monde sait que c'est vrai !\p"
	.string "Oh, tu dois m'excuser, j'ai ce\n"
	.string "dîner formel à assister.$"

MatchCall_PersonalizedText13::
	.string "Ufufufufu… C'est moi, {STR_VAR_1}… Tu\n"
	.string "devines ce que je vois\p"
	.string "? Une paire de {STR_VAR_2}\n"
	.string "en combat. Je vais peut-être\p"
	.string "essayer d'attraper le gagnant…\n"
	.string "Ufufufufufu… Je… Je suis\p"
	.string "un peu occupée. Il\n"
	.string "faut que j'y aille.$"

MatchCall_PersonalizedText14::
	.string "Oh, c'est\p"
	.string "{STR_VAR_1} !\n"
	.string "Je commençais\p"
	.string "à m'ennuyer du\n"
	.string "NAVIRE ABANDONÉ.\l"
	.string "Mais puisque je\p"
	.string "suis déjà ici,\n"
	.string "et que j'ai du\p"
	.string "temps libre,\n"
	.string "je vais explorer\l"
	.string "un peu.\p"
	.string "À plus !$"

MatchCall_PersonalizedText15::
	.string "Je suis\n"
	.string "{STR_VAR_1} !\p"
	.string "L'homme de\p"
	.string "la mer !\n"
	.string "Tu sais ce\p"
	.string "que je pense ?\n"
	.string "Les DRESSEURS\p"
	.string "en mer sont\p"
	.string "les plus coriaces !\n"
	.string "À plus !$"

MatchCall_PersonalizedText16::
	.string "C'est {STR_VAR_1} !\n"
	.string "Écoute, j'ai enseigné\p"
	.string "le karaté à\n"
	.string "mes POKéMON.\p"
	.string "Mais maintenant\n"
	.string "ils sont\l"
	.string "meilleurs que moi !\p"
	.string "C'est à la fois fierté\n"
	.string "et frustration !$"

MatchCall_PersonalizedText17::
	.string "C'est moi,\n"
	.string "{STR_VAR_1}.\p"
	.string "Comment se passent\n"
	.string "tes voyages ?\p"
	.string "…Waouh,\n"
	.string "c'est vrai ?\p"
	.string "Ça a l'air super\n"
	.string "stimulant !\p"
	.string "Continue\n"
	.string "comme ça !$"

MatchCall_PersonalizedText18::
	.string "C'est {STR_VAR_1}… Écoute ma\n"
	.string "nouvelle chanson. Lalala, {STR_VAR_2},\p"
	.string "{STR_VAR_2} ! Pourquoi es-tu\n"
	.string "ce {STR_VAR_2} ? Pourquoi\l"
	.string "ne puis-je pas être\l"
	.string "toi, {STR_VAR_2} ? Lala,\l"
	.string "{STR_VAR_2} et {STR_VAR_1}, {STR_VAR_1}\p"
	.string "et {STR_VAR_2}… Refrain, fondu…$"

MatchCall_PersonalizedText19::
	.string "Je suis {STR_VAR_1},\n"
	.string "tu sais,\p"
	.string "l'expert du camping !\n"
	.string "Quand on a\p"
	.string "combattu, je\n"
	.string "n'ai pas pu\p"
	.string "m'empêcher\n"
	.string "de perdre contre toi.\p"
	.string "Mais j'ai appris\n"
	.string "de notre combat !$"

MatchCall_PersonalizedText20::
	.string "C'est moi, moi, {STR_VAR_1} !\p"
	.string "J'aimerais escalader d'autres\n"
	.string "montagnes que celle-ci, pour être\p"
	.string "honnête.\n"
	.string "Mais je ne sais pas s'il y aurait\p"
	.string "des demoiselles comme au MONT CHIMNÉE.\n"
	.string "Si tu connais une autre montagne\p"
	.string "avec des demoiselles, dis-le-moi ! Héhéhé, à bientôt !$"

MatchCall_PersonalizedText21::
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "C'est {STR_VAR_1}…\p"
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "C'est tout pour aujourd'hui…$"

MatchCall_PersonalizedText22::
	.string "C'est {STR_VAR_1}. Aujourd'hui, j'avais le sentiment\n"
	.string "que je discuterais avec toi. Mon\p"
	.string "désir de te battre grandit jour\n"
	.string "et nuit. Tu as un\p"
	.string "rival comme ça, non ?\n"
	.string "J'aimerais que ce soit moi…\p"
	.string "Je suis content que tu\n"
	.string "m'aies écouté. À bientôt !$"

MatchCall_PersonalizedText23::
	.string "C'est {STR_VAR_1}. Quand un\p"
	.string "DRESSEUR fort est proche,\n"
	.string "je peux parfois le\l"
	.string "sentir d'une certaine manière.\p"
	.string "Tu es passé tout\n"
	.string "près, {PLAYER}{KUN} ? C'était\p"
	.string "peut-être toi. J'attendrai ta\n"
	.string "visite. Salut !$"

MatchCall_PersonalizedText24::
	.string "Bonjour, c'est\n"
	.string "{STR_VAR_1}.\p"
	.string "Tu as l'air\n"
	.string "en forme,\l"
	.string "{PLAYER}{KUN}.\p"
	.string "J'ai voyagé\n"
	.string "autour du monde,\p"
	.string "mais HOENN reste\n"
	.string "mon endroit préféré.\p"
	.string "À plus !$"

MatchCall_PersonalizedText25::
	.string "Snivel… C'est…\n"
	.string "{STR_VAR_1}…\p"
	.string "…Sanglote…\n"
	.string "ROXANNE m'a\p"
	.string "grondé en classe\p"
	.string "aujourd'hui.\n"
	.string "Mais je ne la déteste\p"
	.string "pas ou quoi\n"
	.string "que ce soit.\p"
	.string "Elle est juste stricte.$"

MatchCall_PersonalizedText26::
	.string "C'est\p"
	.string "{STR_VAR_1} !\n"
	.string "ROXANNE m'a laissé\p"
	.string "combattre\n"
	.string "avec elle\p"
	.string "hier.\n"
	.string "Les résultats…\p"
	.string "Terribles, comme tu\n"
	.string "peux l'imaginer.\p"
	.string "Je dois\n"
	.string "m'entraîner plus !$"

MatchCall_PersonalizedText27::
	.string "Salut, c'est ANNA ! Je suis avec ma\n"
	.string "partenaire junior MEG encore aujourd'hui.\p"
	.string "J'adore prendre soin de MEG et\n"
	.string "des POKéMON. Ils sont si mignons !\p"
	.string "J'aimerais pouvoir m'occuper d'eux\n"
	.string "comme s'ils étaient mes frères et soeurs !\p"
	.string "Oh, salut, MEG !\n"
	.string "Tu as eu les petits pains ?\p"
	.string "Hein ? Non, non, je ne te traite pas\n"
	.string "comme mon esclave personnel !\p"
	.string "Tu as perdu le match, alors tu dois\n"
	.string "aller acheter le pain en punition !\p"
	.string "Je ne te traiterais pas comme un esclave,\n"
	.string "MEG ! Tu es trop spécial pour moi !\p"
	.string "Je dois y aller.\n"
	.string "C'est l'heure de notre goûter !$"

MatchCall_PersonalizedText28::
	.string "J'adore les\n"
	.string "POKéMON !\p"
	.string "C'est {STR_VAR_1}\n"
	.string "du FAN CLUB !\p"
	.string "Tu dois entendre ça !\n"
	.string "Mon adorable POKéMON…\l"
	.string "Snort ! Wahaha !\p"
	.string "Je ne peux pas\n"
	.string "m'empêcher de rire !\p"
	.string "Mon POKéMON\p"
	.string "est si mignon !\n"
	.string "À plus !{STR_VAR_2}{POKEBLOCK}$"

MatchCall_PersonalizedText29::
	.string "Ohoho !\p"
	.string "C'est {STR_VAR_1} ! J'ai hâte de\n"
	.string "te parler de mon\p"
	.string "adorable POKéMON !\n"
	.string "S'il te plaît, tu dois écouter ça.\p"
	.string "C'est à propos de\n"
	.string "mon cher {STR_VAR_2}.\p"
	.string "Chaque fois que quelqu'un le prend,\n"
	.string "il bondit directement dans les bras\p"
	.string "de cette personne !\p"
	.string "C'est tellement mignon !\n"
	.string "Je ne peux pas m'empêcher\p"
	.string "de le câliner !\n"
	.string "À plus !$"

MatchCall_PersonalizedText30::
	.string "I am… {STR_VAR_1}.\n"
	.string "People call me an EXPERT.\p"
	.string "But there is one thing I know.\n"
	.string "I could not be an EXPERT on my own\l"
	.string "power.\p"
	.string "Only with the help of POKéMON can\n"
	.string "a TRAINER become an EXPERT.\p"
	.string "Humph! I believe I may have said\n"
	.string "something deep and profound!\p"
	.string "I shall leave you in good spirits!$"

MatchCall_PersonalizedText31::
	.string "C'est {STR_VAR_1}.\n"
	.string "Content de discuter\p"
	.string "avec toi !\n"
	.string "Je me sens vivant\p"
	.string "et rafraîchi\n"
	.string "en profitant de\l"
	.string "cette source\p"
	.string "chaude.\n"
	.string "À plus !$"

MatchCall_PersonalizedText32::
	.string "Yay ! C'est {STR_VAR_1} !\n"
	.string "Quoi de neuf ?\p"
	.string "Je me l'imagine peut-être, mais quand\n"
	.string "je gagne des combats, mon short semble\l"
	.string "meilleur. Matériellement.\p"
	.string "Qu'est-ce que je veux dire par là ?\n"
	.string "C'est difficile à expliquer, mais…\l"
	.string "Comment dire…\l"
	.string "Mon short est plus soyeux !\p"
	.string "Et quand je t'ai combattu, {PLAYER}{KUN},\n"
	.string "mon short était gluant et rugueux.\p"
	.string "… … … … … …\n"
	.string "Tu n'y croyais pas vraiment ?\l"
	.string "Héhéhé, c'est tout ! À plus !$"

MatchCall_PersonalizedText33::
	.string "Ahoy!\n"
	.string "{STR_VAR_1} here!\p"
	.string "As always, I'm fishing with wild\n"
	.string "abandon!\p"
	.string "Are there other places I can fish\n"
	.string "than the sea and rivers?\p"
	.string "I get these powerful urges to\n"
	.string "fish just about anywhere!\p"
	.string "Oh, gosh, darn it!\n"
	.string "My line's tangled up!\p"
	.string "Gotta go!\n"
	.string "Find me some new fishing spots!$"

MatchCall_PersonalizedText34::
	.string "Hé, c'est {STR_VAR_1}.\n"
	.string "Tu prends ça tranquillement ?\p"
	.string "Depuis que j'étais enfant, tu sais,\n"
	.string "j'ai toujours été placide, hein ?\p"
	.string "Je n'ai jamais été du genre à stresser\n"
	.string "ou à me précipiter.\p"
	.string "Mais qui l'aurait cru,\n"
	.string "je suis maintenant un TRIATHLÈTE.\p"
	.string "On ne sait jamais où la vie\n"
	.string "nous mènera, tu comprends ?\p"
	.string "Tu es DRESSEUR maintenant, mais qui\n"
	.string "sait ce que l'avenir te réserve, hein ?\p"
	.string "Imagine-toi enseignant,\n"
	.string "ou peut-être artiste. Cool, hein ?\p"
	.string "Mais bon, reste cool. Prends ça tranquillement.\n"
	.string "À bientôt.$"

MatchCall_PersonalizedText35::
	.string "This is {STR_VAR_1}!\n"
	.string "I'm cycling right now.\p"
	.string "I love swimming and running,\n"
	.string "but cycling is my first love!\p"
	.string "It makes my whole body feel as if\n"
	.string "I'm one with the wind.\p"
	.string "It exhilarates me as if I were\n"
	.string "flying!\p"
	.string "Okay! Today, I'm going to set a new\n"
	.string "CYCLING ROAD record!\p"
	.string "You should make the challenge, too!\n"
	.string "See you!$"

MatchCall_PersonalizedText36::
	.string "Yo, this is {STR_VAR_1}! I'm smack\n"
	.string "in the middle of a triathlon!\p"
	.string "But, hey, I've always got time to\n"
	.string "shoot the breeze!\p"
	.string "Working out with POKéMON feels\n"
	.string "mighty good!\p"
	.string "Without exchanging words, we synch\n"
	.string "as if we shared a heart.\p"
	.string "It's inspiring!\p"
	.string "Gasp… Chatting while running…\n"
	.string "I'm getting run down…\l"
	.string "Gasp… Have…to…go…$"

MatchCall_PersonalizedText37::
	.string "Salut, c'est {STR_VAR_1}. Si tu veux\n"
	.string "améliorer ton endurance, entraîne-toi en haute\l"
	.string "altitude ! Essaie de courir au\p"
	.string "sommet d'une montagne. Tu seras à\n"
	.string "bout de souffle en un rien\p"
	.string "de temps ! Moi aussi, je\n"
	.string "manque d'oxygène ! À bientôt !$"

MatchCall_PersonalizedText38::
	.string "Oh, c'est {STR_VAR_1}, bonjour. J'ai\p"
	.string "beaucoup nagé mais je n'arrive\n"
	.string "toujours pas à atteindre ATELANTIDE.\p"
	.string "Peut-être que je tourne\p"
	.string "en rond. Non, non,\n"
	.string "ce n'est pas possible.\l"
	.string "Wahahaha. Porte-toi bien !$"

MatchCall_PersonalizedText39::
	.string "Hé, c'est {STR_VAR_1}…\n"
	.string "Oups !\p"
	.string "Plouf !\p"
	.string "Blug-blug-blug-blug…\p"
	.string "Splouf !\p"
	.string "Snif-snif ! Snif-snif !\p"
	.string "Hé ! Désolé pour ça !\n"
	.string "Je viens de mettre de l'huile bronzante.\p"
	.string "Alors mon POKéNAV est parti\n"
	.string "dans l'eau !\p"
	.string "Mais, waouh, le POKéNAV de DEVON est solide.\n"
	.string "Il a survécu à cette trempette !\p"
	.string "Bref, je suis occupé à bronzer,\n"
	.string "alors on discutera une autre fois.$"

MatchCall_PersonalizedText40::
	.string "Bonjour, c'est {STR_VAR_1}. Des trois épreuves du\p"
	.string "triathlon, j'aime le plus la natation. Mais\n"
	.string "si je reste trop longtemps en\p"
	.string "mer, est-ce que je ne vais\n"
	.string "pas ressembler à une prune ?\p"
	.string "Ooh, le triathlon est une épreuve\n"
	.string "si exigeante ! À plus !$"

MatchCall_PersonalizedText41::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} à l'appareil.\p"
	.string "Comment vont tes POKéMON ?\p"
	.string "Mes POKéMON DRAGON semblent être\n"
	.string "au sommet de leur forme. À plus !$"

MatchCall_PersonalizedText42::
	.string "{STR_VAR_1} à l'appareil.\p"
	.string "Mon {STR_VAR_2} est devenu encore plus\n"
	.string "costaud que la dernière fois.\p"
	.string "Je ne vais pas perdre contre toi à nouveau.\n"
	.string "Attends la prochaine fois !\p"
	.string "À bientôt !$"

MatchCall_PersonalizedText43::
	.string "C'est {STR_VAR_1}. J'ai continué mes\p"
	.string "études dans l'art de la\n"
	.string "dissimulation. Mais j'ai trop\p"
	.string "réussi. Personne n'a pu\n"
	.string "me trouver. Mon succès\l"
	.string "me rend seul… Comme\p"
	.string "de la fumée, je\n"
	.string "disparais ! Adieu !$"

MatchCall_PersonalizedText44::
	.string "C'est {STR_VAR_1}.\n"
	.string "J'ai continué mon entraînement depuis qu'on s'est vus.\p"
	.string "Mon {STR_VAR_2} devient vraiment\n"
	.string "costaud.\p"
	.string "S'entraîner sur une plage, c'est efficace,\n"
	.string "comme je le pensais. Salut !$"

MatchCall_PersonalizedText45::
	.string "Comment ça va ? C'est\n"
	.string "{STR_VAR_1}. Je me demande quand\p"
	.string "ces vilaines cendres volcaniques cesseront\n"
	.string "de tomber ? Si elles\p"
	.string "s'accumulent trop, elles couvriront le\n"
	.string "motif de mon parasol… Promettons\p"
	.string "de nous revoir !$"

MatchCall_PersonalizedText46::
	.string "Salut, c'est\p"
	.string "{STR_VAR_1}.\n"
	.string "Tu savais qu'il est\p"
	.string "plus facile\n"
	.string "de flotter\p"
	.string "en mer qu'en piscine ?\n"
	.string "Juste en étant dans\l"
	.string "l'eau, ton corps\p"
	.string "flotte naturellement !\n"
	.string "À plus !$"

MatchCall_PersonalizedText47::
	.string "Oh, {PLAYER}{KUN},\n"
	.string "bonjour !\l"
	.string "C'est {STR_VAR_1}.\p"
	.string "Je suis en montagne\n"
	.string "maintenant.\p"
	.string "Mais le sol\p"
	.string "est trop dur\n"
	.string "pour planter\p"
	.string "des BAIES.\n"
	.string "À plus !$"

MatchCall_PersonalizedText48::
	.string "Oh, salut, salut, c'est {STR_VAR_1} !\p"
	.string "J'élève des POKéMON avec LIV !\n"
	.string "On fait de notre mieux !\p"
	.string "Si on s'applique encore plus, on pourra\n"
	.string "devenir numéro un ? À bientôt !$"

MatchCall_PersonalizedText49::
	.string "{STR_VAR_1} ! Je suis MARIN,\p"
	.string "mais je ne suis pas\n"
	.string "sur un bateau maintenant. Ça\p"
	.string "me fait me demander--comment appelle-t-on\n"
	.string "un MARIN sur terre ?\p"
	.string "C'est ce à quoi je\n"
	.string "pense en regardant les vagues.\p"
	.string "D'accord, à la prochaine !$"

MatchCall_PersonalizedText50::
	.string "C'est {STR_VAR_1}.\n"
	.string "Alors ? Tu as attrapé d'autres POKéMON ?\p"
	.string "Si tu attrapes un nouveau POKéMON,\n"
	.string "tu dois venir me le montrer.\p"
	.string "Je ne supplierai pas, promis.\n"
	.string "Je t'attends. À plus.$"

MatchCall_PersonalizedText51::
	.string "C'est {STR_VAR_1}.\p"
	.string "Élèves-tu\n"
	.string "tes POKéMON\p"
	.string "de la manière\n"
	.string "optimale ?\l"
	.string "L'air est pur\p"
	.string "où je suis.\n"
	.string "Prends soin de\l"
	.string "tes POKéMON !{STR_VAR_2}$"

MatchCall_PersonalizedText52::
	.string "Salut, c'est {STR_VAR_1}. J'ai donné\p"
	.string "un {POKEBLOCK} à mon {STR_VAR_2}.\n"
	.string "Il semblait beaucoup l'apprécier. On\p"
	.string "dirait que les POKéMON ont\n"
	.string "leurs préférences pour les {POKEBLOCK}S.\p"
	.string "Je trouve ça fascinant.\n"
	.string "Prends soin de toi.$"

MatchCall_PersonalizedText53::
	.string "C'est {STR_VAR_1}.\p"
	.string "Si tu coopères avec les POKéMON,\n"
	.string "on peut être à l'aise dans la nature.\p"
	.string "Tout le monde devrait le réaliser\n"
	.string "et coopérer davantage avec les\p"
	.string "POKéMON.\n"
	.string "Ce serait l'idéal.\p"
	.string "Je le pense vraiment.\n"
	.string "Je crois que tu es sur la bonne voie ! À plus tard !$"

MatchCall_PersonalizedText54::
	.string "Salut, c'est\n"
	.string "{STR_VAR_1}. Tu sais,\p"
	.string "le DRESSEUR\n"
	.string "toujours préparé !\p"
	.string "{PLAYER}{KUN},\n"
	.string "as-tu assez de\l"
	.string "POKé BALLS ?\p"
	.string "N'oublie jamais\n"
	.string "de t'équiper !$"

MatchCall_PersonalizedText55::
	.string "C'est {STR_VAR_1} !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "{STR_VAR_2} est une artère très\n"
	.string "fréquentée, alors je me fais\l"
	.string "défier par toutes sortes de\p"
	.string "DRESSEURS chaque jour.\n"
	.string "Aujourd'hui, j'ai gagné cinq\p"
	.string "combats et perdu seulement trois !\n"
	.string "Comment ça s'est passé pour toi ? Raconte-moi la prochaine fois !$"

MatchCall_PersonalizedText56::
	.string "C'est moi,\p"
	.string "{STR_VAR_1}.\n"
	.string "Je suis populaire\p"
	.string "parce que\n"
	.string "j'ai plein\p"
	.string "de POKéMON\n"
	.string "INSECTE, non ?\p"
	.string "Bref, j'ai attrapé\n"
	.string "plein de\p"
	.string "nouveaux !\n"
	.string "À plus !$"

MatchCall_PersonalizedText57::
	.string "Hah ! Hah ! Hah !\p"
	.string "Hah ! Salut ! C'est {STR_VAR_1}\p"
	.string "! Hah ! Hah ! Essayer\n"
	.string "de parler… En grimpant… C'est\l"
	.string "un exercice dur… Hah !\p"
	.string "Hah ! Urgh ! Oof…\n"
	.string "C'est plus raide maintenant… On\l"
	.string "parlera… une autre fois… Hah\l"
	.string "! Hah ! Hah !$"

MatchCall_PersonalizedText58::
	.string "Oh, hi!\p"
	.string "I'm still searching for treasures\n"
	.string "with KIRA!\p"
	.string "Maybe there isn't any treasure\n"
	.string "here at all…\p"
	.string "But the important thing is for me\n"
	.string "to search alongside KIRA.\p"
	.string "Oh, hey, KIRA!\n"
	.string "Wh-why are you angry?\p"
	.string "I'm not ignoring you, honey!\n"
	.string "You're my one and only!\p"
	.string "…{PLAYER}, I have to go, bye!$"

MatchCall_PersonalizedText59::
	.string "C'est {STR_VAR_1} !\p"
	.string "Je suis retourné à l'ARÈNE de VERGONHA\n"
	.string "pour m'entraîner.\p"
	.string "BRAWLY, le CHAMPION d'ARÈNE, semble\n"
	.string "encore plus fort maintenant.\p"
	.string "Quelque chose à propos d'être endurci\n"
	.string "par les vagues sauvages…\p"
	.string "Mais il est toujours aussi cool.\n"
	.string "Les demoiselles l'adorent !\l"
	.string "Franchement, ça me rend envieux.\p"
	.string "Je me demande… Est-ce que son ami BRUNO\n"
	.string "est pareil que BRAWLY ?\p"
	.string "Tu sais, tout en sueur ou malodorant,\n"
	.string "et enclin à appeler les gens\l"
	.string "“grande vague”, ce genre de choses.\p"
	.string "Mais bon, cette jalousie n'est pas\n"
	.string "très élégante, n'est-ce pas ?\p"
	.string "Oublie cette conversation,\n"
	.string "d'accord ? À plus !$"

MatchCall_PersonalizedText60::
	.string "Oh, salut ! Toi là !\n"
	.string "Tu pourrais me masser l'épaule ?\p"
	.string "…Oui, là ! C'est ça !\n"
	.string "Aïe, aïe ! Oooh,\p"
	.string "ça fait du bien !\n"
	.string "Je m'appelle {PLAYER}.\p"
	.string "Je fais du karaté,\n"
	.string "mais mon corps\l"
	.string "n'est pas fait pour\p"
	.string "encaisser les coups.\n"
	.string "Alors j'ai besoin de\p"
	.string "massages réguliers !\n"
	.string "Merci ! Tu es un ange !{KUN}$"

MatchCall_PersonalizedText61::
	.string "Salut, c'est\n"
	.string "{STR_VAR_1} !\p"
	.string "On vient\n"
	.string "de gagner\p"
	.string "un combat !\p"
	.string "On ne gagne\n"
	.string "pas souvent,\p"
	.string "mais c'était ce\n"
	.string "cool NAGEUR.\p"
	.string "Ma soeur était\n"
	.string "si excitée !\p"
	.string "À plus !{PLAYER}{KUN}$"

MatchCall_PersonalizedText62::
	.string "C'est {STR_VAR_1}, oui.\n"
	.string "Je suis parti en mer hier.\p"
	.string "J'espérais trouver une nouvelle\n"
	.string "ruine à explorer.\p"
	.string "Mais les marées semblaient me\n"
	.string "ramener là où j'avais commencé.\p"
	.string "Je suis encore faible au combat, aussi…\n"
	.string "N'hésite pas à te moquer de moi…\l"
	.string "Mais je n'abandonnerai pas.\p"
	.string "Mon jour viendra quand je découvrirai\n"
	.string "une nouvelle ruine !\p"
	.string "C'est tout ce que j'ai à dire !\n"
	.string "Adieu pour l'instant !$"

MatchCall_PersonalizedText63::
	.string "Ahoy !\n"
	.string "C'est moi,\l"
	.string "{STR_VAR_1} !\l"
	.string "Je suis sur la ROUTE\p"
	.string "108 maintenant !\n"
	.string "En d'autres\p"
	.string "termes, là\p"
	.string "où je suis toujours !\p"
	.string "La pêche est bonne\n"
	.string "aujourd'hui !{STR_VAR_1}$"

MatchCall_PersonalizedText64::
	.string "C'est {STR_VAR_1} !\p"
	.string "Je suis un peu occupé, mais je\n"
	.string "voulais te dire que j'ai encore\l"
	.string "battu cinq DRESSEURS aujourd'hui.\p"
	.string "Si je garde ce rythme, je pourrai\n"
	.string "probablement te battre la prochaine\p"
	.string "fois.\n"
	.string "Je pense qu'on fera de bons rivaux, toi et moi. À bientôt !$"

MatchCall_BattleFrontierStreakText1::
	.string "Salut ! C'est {STR_VAR_1}.\n"
	.string "J'ai entendu la nouvelle !\p"
	.string "On dit que tu as excellé à\n"
	.string "la {STR_VAR_2}.\p"
	.string "C'est génial, {STR_VAR_3} victoires d'affilée ?\n"
	.string "À bientôt !$"

MatchCall_BattleFrontierStreakText2::
	.string "Bonjour, c'est {STR_VAR_1} !\n"
	.string "J'ai entendu parler de toi !\p"
	.string "On dit que tu as gagné {STR_VAR_3} combats d'affilée\n"
	.string "au {STR_VAR_2} ?\p"
	.string "C'est génial !\n"
	.string "À bientôt !$"

MatchCall_BattleFrontierStreakText3::
	.string "Salut, {PLAYER} ! C'est moi, {STR_VAR_1}.\n"
	.string "J'ai entendu que tu as\p"
	.string "fait un raz de marée\n"
	.string "au {STR_VAR_2} ! Une série\p"
	.string "de {STR_VAR_3} victoires… C'est un\n"
	.string "sacré record, non ? Je\p"
	.string "ferais mieux de me ressaisir\n"
	.string "aussi ! À bientôt !$"

MatchCall_BattleFrontierStreakText4::
	.string "Hé, {PLAYER}{KUN}. C'est {STR_VAR_1}. Quoi\n"
	.string "de neuf ? Une rumeur\p"
	.string "circule selon laquelle tu as\n"
	.string "enchaîné {STR_VAR_3} victoires d'affilée\l"
	.string "au {STR_VAR_2}. Il faut\p"
	.string "que je redouble d'efforts\n"
	.string "aussi. À bientôt !$"

MatchCall_BattleFrontierStreakText5::
	.string "Salut, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu étais au {STR_VAR_2}\n"
	.string "et tu as gagné {STR_VAR_3} combats d'affilée ?\l"
	.string "Pas mal, ça !\p"
	.string "Il faut que j'entraîne mieux mes POKéMON.\n"
	.string "À bientôt !$"

MatchCall_BattleFrontierStreakText6::
	.string "Salut, {PLAYER}{KUN}. C'est {STR_VAR_1}. Comment\n"
	.string "ça va ? Au fait,\p"
	.string "j'ai entendu que tu as\n"
	.string "réussi l'exploit de {STR_VAR_3} victoires\l"
	.string "d'affilée au {STR_VAR_2}. Ça m'inspire\p"
	.string "à me concentrer sur\n"
	.string "l'entraînement de mon équipe.$"

MatchCall_BattleFrontierStreakText7::
	.string "…Euh, {PLAYER}{KUN} ?\n"
	.string "C'est {STR_VAR_1}…\p"
	.string "Oh, oui, tu étais au\n"
	.string "{STR_VAR_2}, n'est-ce pas ?\p"
	.string "Et tu as gagné {STR_VAR_3} combats d'affilée.\p"
	.string "Oh, il y a un POKéMON rare !\n"
	.string "Je dois y aller !$"

MatchCall_BattleFrontierStreakText8::
	.string "Oh, {PLAYER}{KUN}, comment vas-tu ?\n"
	.string "C'est {STR_VAR_1} qui parle.\l"
	.string "J'espère que tu vas bien.\p"
	.string "Oh, mais si, tu vas bien. J'ai entendu\n"
	.string "que tu as gagné {STR_VAR_3} combats\l"
	.string "d'affilée au {STR_VAR_2}.\p"
	.string "C'est très impressionnant !\n"
	.string "J'espère que tu resteras au sommet.$"

MatchCall_BattleFrontierStreakText9::
	.string "Oh, {PLAYER}{KUN}, salut !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "J'ai entendu ! Ta série de {STR_VAR_3} victoires\n"
	.string "au {STR_VAR_2} !\p"
	.string "C'est trop cool !\n"
	.string "Il faut que je fasse mieux, moi aussi !$"

MatchCall_BattleFrontierStreakText10::
	.string "Oh, {PLAYER}{KUN}, salut…\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu as gagné {STR_VAR_3} combats d'affilée au\n"
	.string "{STR_VAR_2} ?\p"
	.string "C'est tout un exploit.\n"
	.string "Je dois redoubler d'efforts.$"

MatchCall_BattleFrontierStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "On dit que tu es le fléau\n"
	.string "du {STR_VAR_2} ?\p"
	.string "Tu as gagné, quoi, {STR_VAR_3} matchs\n"
	.string "d'affilée ?\p"
	.string "Tu es doué, toi.\n"
	.string "Je me demande combien j'en gagnerai ?$"

MatchCall_BattleFrontierStreakText12::
	.string "Bonjour, {PLAYER}{KUN}. C'est moi, {STR_VAR_1}.\n"
	.string "Tu vas bien ? Quelqu'un\l"
	.string "m'a parlé de toi.\p"
	.string "Comment tu as gagné\n"
	.string "{STR_VAR_3} combats d'affilée à\l"
	.string "un endroit appelé {STR_VAR_2}\p"
	.string "? C'est une sacrée\n"
	.string "histoire. À bientôt !$"

MatchCall_BattleFrontierStreakText13::
	.string "Ah, bonjour, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1} !\l"
	.string "J'espère que tu vas bien.\p"
	.string "On dit que tu as gagné {STR_VAR_3} combats\n"
	.string "d'affilée au {STR_VAR_2}.\p"
	.string "J'admire ton énergie !\n"
	.string "À bientôt.$"

MatchCall_BattleFrontierStreakText14::
	.string "Oh, salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai entendu parler de toi !\n"
	.string "Tu viens de gagner {STR_VAR_3} combats d'affilée\l"
	.string "au {STR_VAR_2} ?\p"
	.string "Tu es une inspiration !\n"
	.string "Salut !$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "Salut ! C'est {STR_VAR_1}.\n"
	.string "J'ai entendu la nouvelle !\p"
	.string "On dit que tu as excellé à\n"
	.string "la {STR_VAR_2}.\p"
	.string "C'est génial-{STR_VAR_3} victoires d'affilée ?\n"
	.string "À bientôt !$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "Bonjour, c'est {STR_VAR_1} !\n"
	.string "J'ai entendu parler de toi !\p"
	.string "On dit que tu as gagné {STR_VAR_3} combats d'affilée\n"
	.string "au {STR_VAR_2} ?\p"
	.string "C'est génial !\n"
	.string "À bientôt !$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "Salut, {PLAYER} ! C'est moi, {STR_VAR_1}.\n"
	.string "J'ai entendu que tu as\p"
	.string "fait un raz de marée\n"
	.string "au {STR_VAR_2} ! Une série\p"
	.string "de {STR_VAR_3} victoires… C'est un\n"
	.string "sacré record, non ? Je\p"
	.string "ferais mieux de me ressaisir\n"
	.string "aussi ! À bientôt !$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Hé, {PLAYER}{KUN}. C'est {STR_VAR_1}. Quoi\n"
	.string "de neuf ? Une rumeur\p"
	.string "circule selon laquelle tu as\n"
	.string "enchaîné {STR_VAR_3} victoires d'affilée\l"
	.string "au {STR_VAR_2}. Il faut\p"
	.string "que je redouble d'efforts\n"
	.string "aussi. À bientôt !$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "Salut, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu étais au {STR_VAR_2}\n"
	.string "et tu as gagné {STR_VAR_3} combats d'affilée ?\l"
	.string "Pas mal, ça !\p"
	.string "Moi ? Je dirais que ça avance.\n"
	.string "À bientôt !$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "Hé, {PLAYER}{KUN}. C'est {STR_VAR_1}. Comment\n"
	.string "ça va ? Au fait,\p"
	.string "j'ai entendu que tu as\n"
	.string "réussi l'exploit de {STR_VAR_3} victoires\l"
	.string "d'affilée au {STR_VAR_2}. Il faut\p"
	.string "que je redouble d'efforts\n"
	.string "! À bientôt !$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "…Euh, {PLAYER}{KUN} ?\n"
	.string "C'est {STR_VAR_1}…\p"
	.string "Oh, oui, tu étais au\n"
	.string "{STR_VAR_2}, n'est-ce pas ?\p"
	.string "Et tu as gagné {STR_VAR_3} combats d'affilée.\p"
	.string "Oh, il y a un POKéMON rare !\n"
	.string "Je dois y aller !$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "Oh, {PLAYER}{KUN}, comment vas-tu ?\n"
	.string "C'est {STR_VAR_1} qui parle.\l"
	.string "J'espère que tu vas bien.\p"
	.string "Oh, mais si, tu vas bien. J'ai entendu\n"
	.string "que tu as gagné {STR_VAR_3} combats\l"
	.string "d'affilée au {STR_VAR_2}.\p"
	.string "C'est très impressionnant !\n"
	.string "Je ferais mieux de m'entraîner aussi !$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "Oh, {PLAYER}{KUN}, salut !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "J'ai entendu ! Ta série de {STR_VAR_3} victoires\n"
	.string "au {STR_VAR_2} !\p"
	.string "C'est trop cool !\n"
	.string "Il faut que je fasse mieux, moi aussi !$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "Oh, {PLAYER}{KUN}, salut…\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu as gagné {STR_VAR_3} combats d'affilée au\n"
	.string "{STR_VAR_2} ?\p"
	.string "C'est tout un exploit.\n"
	.string "Je dois redoubler d'efforts.$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "On dit que tu es le fléau\n"
	.string "du {STR_VAR_2} ?\p"
	.string "Tu as gagné, quoi, {STR_VAR_3} matchs\n"
	.string "d'affilée ?\p"
	.string "Tu es doué, toi.\n"
	.string "Je me demande combien j'en gagnerai ?$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "Bonjour, {PLAYER}{KUN}. C'est moi, {STR_VAR_1}.\n"
	.string "Tu vas bien ? Quelqu'un\l"
	.string "m'a parlé de toi.\p"
	.string "Comment tu as gagné\n"
	.string "{STR_VAR_3} combats d'affilée à\l"
	.string "un endroit appelé {STR_VAR_2}\p"
	.string "? C'est une sacrée\n"
	.string "histoire. À bientôt !$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "Ah, bonjour, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1} !\l"
	.string "J'espère que tu vas bien.\p"
	.string "On dit que tu as gagné {STR_VAR_3} combats\n"
	.string "d'affilée au {STR_VAR_2}.\p"
	.string "J'admire ton énergie !\n"
	.string "À bientôt.$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "Oh, salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\l"
	.string "J'ai entendu parler de toi !\p"
	.string "Tu viens de gagner {STR_VAR_3} combats d'affilée\n"
	.string "au {STR_VAR_2} ?\p"
	.string "Tu es une inspiration !\n"
	.string "Salut !$"

MatchCall_BattleDomeText1::
	.string "Salut ! {PLAYER} ?\n"
	.string "Bonjour, c'est {STR_VAR_1} !\l"
	.string "J'ai entendu la nouvelle !\p"
	.string "Tu es devenu champion au\n"
	.string "{STR_VAR_2} {STR_VAR_3} fois ?\p"
	.string "C'est génial ! Il faut que je fasse mieux !\n"
	.string "À bientôt !$"

MatchCall_BattleDomeText2::
	.string "Bonjour, c'est {STR_VAR_1} !\n"
	.string "J'ai entendu parler de toi !\p"
	.string "On m'a dit que tu as remporté {STR_VAR_3} titres\n"
	.string "au {STR_VAR_2}.\p"
	.string "C'est super ! Je me demande si\n"
	.string "je peux devenir champion ?$"

MatchCall_BattleDomeText3::
	.string "Hé, {PLAYER} !\n"
	.string "C'est moi, {STR_VAR_1}.\l"
	.string "Comment ça va ?\p"
	.string "J'ai entendu dire que tu as gagné {STR_VAR_3} fois\n"
	.string "au {STR_VAR_2} !\p"
	.string "Fais-en une de plus la prochaine fois !\n"
	.string "À bientôt !$"

MatchCall_BattleDomeText4::
	.string "Hé, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai entendu dire que tu es devenu champion\n"
	.string "au {STR_VAR_2} !\p"
	.string "Félicitations !\n"
	.string "À bientôt !{STR_VAR_3}$"

MatchCall_BattleDomeText5::
	.string "Salut, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai entendu que tu as gagné {STR_VAR_3} fois\n"
	.string "d'affilée à la {STR_VAR_2}.\p"
	.string "Il faut que je me bouge aussi !\n"
	.string "À bientôt !$"

MatchCall_BattleDomeText6::
	.string "Salut, {PLAYER}{KUN} ? C'est\n"
	.string "{STR_VAR_1}. Comment ça va\p"
	.string "? Au fait, j'ai\n"
	.string "entendu que tu es\l"
	.string "devenu le champion {STR_VAR_3}\p"
	.string "fois d'affilée au {STR_VAR_2}\n"
	.string "! Félicitations !$"

MatchCall_BattleDomeText7::
	.string "{PLAYER}{KUN} ? C'est\n"
	.string "{STR_VAR_1}. Tu étais\p"
	.string "au {STR_VAR_2} et\n"
	.string "tu es devenu\p"
	.string "le champion {STR_VAR_3}\n"
	.string "fois d'affilée ?\p"
	.string "C'est incroyable !\n"
	.string "À bientôt !$"

MatchCall_BattleDomeText8::
	.string "Oh, {PLAYER}{KUN}, comment vas-tu ?\n"
	.string "C'est {STR_VAR_1} qui parle. J'espère\l"
	.string "que tu vas bien. Oh,\l"
	.string "mais si, tu vas bien.\p"
	.string "J'ai entendu que tu as\n"
	.string "gagné {STR_VAR_3} titres au {STR_VAR_2}.\p"
	.string "Je dois élever mes POKéMON\n"
	.string "comme toi. À bientôt.$"

MatchCall_BattleDomeText9::
	.string "Oh, {PLAYER}{KUN}, salut !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "J'ai entendu ! Tu as pris le titre\n"
	.string "au {STR_VAR_3} !\p"
	.string "Félicitations !\n"
	.string "À bientôt !{STR_VAR_2}$"

MatchCall_BattleDomeText10::
	.string "Oh, {PLAYER}{KUN}, salut.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu as gagné {STR_VAR_3} fois d'affilée au\n"
	.string "{STR_VAR_2} ?\p"
	.string "C'est tout un exploit.\n"
	.string "Je dois redoubler d'efforts.$"

MatchCall_BattleDomeText11::
	.string "Ah, {PLAYER}{KUN}. C'est {STR_VAR_1}.\n"
	.string "J'entends que tu es\p"
	.string "la terreur du {STR_VAR_2}\n"
	.string "? Tu as gagné,\p"
	.string "quoi, {STR_VAR_3} fois d'affilée\n"
	.string "maintenant ? Je me\p"
	.string "demande si je pourrai\n"
	.string "jamais devenir champion ?\p"
	.string "…Plutôt impossible ? Bon,\n"
	.string "à plus !$"

MatchCall_BattleDomeText12::
	.string "Salut, {PLAYER}{KUN}.\n"
	.string "C'est moi, {STR_VAR_1}.\l"
	.string "Tu vas bien ?\p"
	.string "Tu as gagné {STR_VAR_3} épreuves dans un endroit\n"
	.string "appelé {STR_VAR_2} ?\p"
	.string "C'est une sacrée histoire.\n"
	.string "À bientôt !$"

MatchCall_BattleDomeText13::
	.string "Ah, bonjour, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1} !\l"
	.string "J'espère que tu vas bien.\p"
	.string "On dit que tu as gagné {STR_VAR_3} épreuves\n"
	.string "au {STR_VAR_2} ?\p"
	.string "J'admire ton énergie !\n"
	.string "À bientôt.$"

MatchCall_BattleDomeText14::
	.string "Oh, salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\l"
	.string "J'ai entendu parler de toi !\p"
	.string "Tu n'as pas remporté {STR_VAR_3} titres\n"
	.string "au {STR_VAR_2} ?\p"
	.string "Tu es une inspiration !\n"
	.string "À bientôt !$"

MatchCall_BattlePikeText1::
	.string "Salut ! {PLAYER} ?\n"
	.string "Bonjour, c'est {STR_VAR_1} !\l"
	.string "J'ai entendu la nouvelle !\p"
	.string "Tu as franchi {STR_VAR_3} salles\n"
	.string "à la {STR_VAR_2} !\p"
	.string "C'est génial !\n"
	.string "À bientôt !$"

MatchCall_BattlePikeText2::
	.string "Bonjour, c'est {STR_VAR_1} !\n"
	.string "J'ai entendu parler de toi !\p"
	.string "On m'a dit que tu as traversé\n"
	.string "{STR_VAR_3} salles au {STR_VAR_2}.\p"
	.string "Il faut que je fasse beaucoup mieux !\n"
	.string "Salut !$"

MatchCall_BattlePikeText3::
	.string "Hé, {PLAYER} !\n"
	.string "C'est moi, {STR_VAR_1}.\l"
	.string "Comment ça va ?\p"
	.string "J'ai entendu dire que tu as gagné dans {STR_VAR_3} salles\n"
	.string "au {STR_VAR_2} !\p"
	.string "Essaie de faire encore mieux la prochaine fois !\n"
	.string "À bientôt !$"

MatchCall_BattlePikeText4::
	.string "Hé, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai entendu que tu as traversé {STR_VAR_3} salles\n"
	.string "au {STR_VAR_2}.\p"
	.string "Il faut que j'entraîne mes POKéMON et\n"
	.string "que j'essaie de suivre !$"

MatchCall_BattlePikeText5::
	.string "Salut, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai entendu que tu as franchi {STR_VAR_3} salles\n"
	.string "à la {STR_VAR_2}.\p"
	.string "Il faut que je me bouge aussi !\n"
	.string "À bientôt !$"

MatchCall_BattlePikeText6::
	.string "Hé, {PLAYER}{KUN} ? C'est {STR_VAR_1}. Comment\n"
	.string "ça va ? Au fait, j'ai\p"
	.string "entendu que tu as franchi\n"
	.string "{STR_VAR_3} salles au {STR_VAR_2}. Il\p"
	.string "faut que j'entraîne mes POKéMON\n"
	.string "avant que tu ne m'échappes.$"

MatchCall_BattlePikeText7::
	.string "{PLAYER}{KUN} ?\n"
	.string "{STR_VAR_1} à l'appareil.\p"
	.string "Tu étais au {STR_VAR_2}\n"
	.string "et tu as franchi {STR_VAR_3} salles ?\p"
	.string "C'est génial.\p"
	.string "Oh, un POKéMON rare passe !\n"
	.string "OK, salut.$"

MatchCall_BattlePikeText8::
	.string "Oh, {PLAYER}{KUN},\n"
	.string "comment vas-tu ?\l"
	.string "C'est {STR_VAR_1}\l"
	.string "qui parle.\p"
	.string "J'espère que tu vas bien.\n"
	.string "Oh, mais oui,\p"
	.string "tu vas bien.\n"
	.string "J'ai encore besoin\l"
	.string "de ton conseil !{STR_VAR_3}{STR_VAR_2}$"

MatchCall_BattlePikeText9::
	.string "Oh, {PLAYER}{KUN}, salut !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "J'ai entendu ! Tu as gagné dans {STR_VAR_3} salles\n"
	.string "au {STR_VAR_2} !\p"
	.string "C'est trop cool !\n"
	.string "Il faut que j'essaie de faire mieux aussi !$"

MatchCall_BattlePikeText10::
	.string "Oh, {PLAYER}{KUN}, bonjour.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu as gagné {STR_VAR_3} combats d'affilée\n"
	.string "au {STR_VAR_2} ?\p"
	.string "C'est génial !\n"
	.string "À bientôt !$"

MatchCall_BattlePikeText11::
	.string "Ah,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "C'est {STR_VAR_1}.\n"
	.string "J'entends que tu\p"
	.string "es la terreur du\n"
	.string "{STR_VAR_2} ?\p"
	.string "Tu as gravi les\n"
	.string "échelons\p"
	.string "rapidement !\n"
	.string "Félicitations !{STR_VAR_3}$"

MatchCall_BattlePikeText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C'est moi, {STR_VAR_1}.\l"
	.string "Tu vas bien ?\p"
	.string "Tu as gagné dans {STR_VAR_3} salles d'un\n"
	.string "endroit nommé {STR_VAR_2} ?\p"
	.string "C'est une sacrée histoire.\n"
	.string "À plus !$"

MatchCall_BattlePikeText13::
	.string "Ah, bonjour, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1} !\l"
	.string "J'espère que tu vas bien.\p"
	.string "On dit que tu as gagné dans {STR_VAR_3} salles\n"
	.string "au {STR_VAR_2} ?\p"
	.string "J'admire ton énergie !\n"
	.string "À bientôt.$"

MatchCall_BattlePikeText14::
	.string "Oh, salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\l"
	.string "J'ai entendu parler de toi !\p"
	.string "Tu n'as pas gagné {STR_VAR_3} combats d'affilée\n"
	.string "au {STR_VAR_2} ?\p"
	.string "Tu es une inspiration !\n"
	.string "À bientôt !$"

MatchCall_BattlePyramidText1::
	.string "Salut ! {PLAYER} ?\n"
	.string "Bonjour, c'est {STR_VAR_1} !\l"
	.string "J'ai entendu la nouvelle !\p"
	.string "Tu as gravi {STR_VAR_3} étages à l'intérieur\n"
	.string "du {STR_VAR_2}, n'est-ce pas ?\p"
	.string "C'est génial !\n"
	.string "Je devrais essayer ce défi.$"

MatchCall_BattlePyramidText2::
	.string "Bonjour, c'est {STR_VAR_1} !\n"
	.string "J'ai entendu parler de toi !\p"
	.string "On dit que tu as gagné sur {STR_VAR_3} étages\n"
	.string "au {STR_VAR_2}.\p"
	.string "Waouh, c'est fantastique !\n"
	.string "Il faut que j'entraîne mes POKéMON aussi !$"

MatchCall_BattlePyramidText3::
	.string "Hé, {PLAYER} !\n"
	.string "C'est moi, {STR_VAR_1}.\l"
	.string "Comment ça va ?\p"
	.string "J'ai entendu dire que tu as gravi {STR_VAR_3} étages\n"
	.string "dans le {STR_VAR_2} !\p"
	.string "Essaie de faire encore mieux la prochaine fois !\n"
	.string "À bientôt !$"

MatchCall_BattlePyramidText4::
	.string "Hé, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai entendu dire que tu as gravi {STR_VAR_3}\n"
	.string "étages dans la {STR_VAR_2}.\p"
	.string "Je ferais mieux de travailler dur pour\n"
	.string "ne pas être distancé !$"

MatchCall_BattlePyramidText5::
	.string "Salut, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "J'ai entendu que tu as gravi {STR_VAR_3} étages\n"
	.string "dans la {STR_VAR_2}.\p"
	.string "Il faut que je me bouge aussi !\n"
	.string "À bientôt !$"

MatchCall_BattlePyramidText6::
	.string "Hé, {PLAYER}{KUN} ? C'est {STR_VAR_1}. Comment\n"
	.string "ça va ? Au fait, j'ai\p"
	.string "entendu que tu as franchi {STR_VAR_3}\n"
	.string "étages dans la {STR_VAR_2}. Il\p"
	.string "faut que j'entraîne mes POKéMON\n"
	.string "avant que tu ne m'échappes.$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}{KUN} ?\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu étais au {STR_VAR_2}\n"
	.string "et tu as gravi {STR_VAR_3} étages ?\p"
	.string "Cool. Il y avait des POKéMON rares\n"
	.string "là-bas ?\p"
	.string "Non, hein ?\n"
	.string "OK, salut.$"

MatchCall_BattlePyramidText8::
	.string "Oh, {PLAYER}{KUN},\n"
	.string "comment vas-tu ?\l"
	.string "C'est {STR_VAR_1}\l"
	.string "qui parle.\p"
	.string "J'espère que\n"
	.string "tu vas bien.\p"
	.string "Oh, mais oui,\n"
	.string "tu vas bien.\l"
	.string "À plus !{STR_VAR_3}{STR_VAR_2}$"

MatchCall_BattlePyramidText9::
	.string "Oh, {PLAYER}{KUN}, salut !\n"
	.string "C'est {STR_VAR_1} !\p"
	.string "J'ai entendu ! Tu as gagné sur {STR_VAR_3} étages\n"
	.string "dans le {STR_VAR_2} !\p"
	.string "C'est trop cool !\n"
	.string "Il faut que j'essaie de faire mieux aussi !$"

MatchCall_BattlePyramidText10::
	.string "Oh, {PLAYER}{KUN}, salut.\n"
	.string "C'est {STR_VAR_1}.\p"
	.string "Tu as gravi {STR_VAR_3} étages dans\n"
	.string "le {STR_VAR_2} ?\p"
	.string "C'est tout un exploit.\n"
	.string "Je dois redoubler d'efforts.$"

MatchCall_BattlePyramidText11::
	.string "Ah,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "C'est\n"
	.string "{STR_VAR_1}.\p"
	.string "J'entends que tu\n"
	.string "es la terreur du\p"
	.string "{STR_VAR_2} ?\n"
	.string "Tu es monté en\p"
	.string "grade rapidement !\n"
	.string "Félicitations !{STR_VAR_3}$"

MatchCall_BattlePyramidText12::
	.string "Bonjour, {PLAYER}{KUN}.\n"
	.string "C'est moi, {STR_VAR_1}.\l"
	.string "Tu vas bien ?\p"
	.string "Tu as gagné sur {STR_VAR_3} étages dans\n"
	.string "un endroit nommé {STR_VAR_2} ?\p"
	.string "C'est une sacrée histoire.\n"
	.string "À plus !$"

MatchCall_BattlePyramidText13::
	.string "Ah, bonjour, {PLAYER}{KUN} !\n"
	.string "C'est {STR_VAR_1} !\l"
	.string "J'espère que tu vas bien.\p"
	.string "On dit que tu as gravi {STR_VAR_3} étages\n"
	.string "dans le {STR_VAR_2} ?\p"
	.string "J'admire ton énergie !\n"
	.string "À bientôt.$"

MatchCall_BattlePyramidText14::
	.string "Oh, salut, {PLAYER}{KUN}.\n"
	.string "C'est {STR_VAR_1}.\l"
	.string "J'ai entendu parler de toi !\p"
	.string "Tu n'as pas traversé {STR_VAR_3} étages\n"
	.string "dans le {STR_VAR_2} ?\p"
	.string "Tu es une inspiration !\n"
	.string "À bientôt !$"

MatchCall_Text_Mom1::
	.string "MAMAN : Ton père et toi…\n"
	.string "Tout le monde est captivé par les POKéMON.\p"
	.string "Quel est le charme des POKéMON ?\p"
	.string "Moi ?\n"
	.string "J'adore les POKéMON qui m'aident dans\l"
	.string "mes tâches quotidiennes.$"

MatchCall_Text_Mom2::
	.string "MAMAN : Salut, {PLAYER} !\n"
	.string "Ton père reste enfermé dans\l"
	.string "l'ARÈNE de ROSALIA.\p"
	.string "Il rentre de temps en temps.\n"
	.string "Mais il retourne à l'ARÈNE quand\l"
	.string "il a tout mangé.\p"
	.string "Je suppose que perdre contre toi\n"
	.string "a été un coup dur pour sa fierté !$"

MatchCall_Text_Mom3::
	.string "MAMAN : {PLAYER}...\n"
	.string "Ne t'inquiète pas pour moi ni pour la maison.\p"
	.string "Porte ces CHAUSSURES DE COURSE\n"
	.string "jusqu'à ce qu'elles tombent en lambeaux !$"

MatchCall_Text_Baoba1::
	.string "BAOBA : {PLAYER} !\n"
	.string "Le PARC SAFARI est presque prêt !\p"
	.string "Je t'appellerai en premier dès que\n"
	.string "ce sera terminé !$"

MatchCall_Text_Baoba2::
	.string "BAOBA : {PLAYER} !\n"
	.string "Le PARC SAFARI est ouvert ! Viens\p"
	.string "quand tu veux !$"

MatchCall_Text_Roxanne1::
	.string "ROXANNE : Oh, bonjour, {PLAYER} !\p"
	.string "Je me suis entraînée dur depuis\n"
	.string "notre rencontre. Il me faudra encore\p"
	.string "un peu de temps avant\n"
	.string "de rouvrir l'ARÈNE. Mais quand\p"
	.string "ce sera fait, viens me\n"
	.string "défier pour une revanche !$"

MatchCall_Text_Roxanne2::
	.string "ROXANNE : C'est bien {PLAYER} ?\n"
	.string "Félicitations ! J'ai beaucoup entendu parler\l"
	.string "de toi ! Pour moi, il\p"
	.string "me faut encore un peu de\n"
	.string "temps avant de rouvrir l'ARÈNE. Mais\p"
	.string "quand ce sera fait, viens à\n"
	.string "mon ARÈNE pour une revanche !$"

MatchCall_Text_Roxanne3::
	.string "ROXANNE : {PLAYER} !\n"
	.string "Mon ARÈNE est prête !\p"
	.string "Visite MEROUVILLE quand\n"
	.string "tu peux !$"

MatchCall_Text_Roxanne4::
	.string "ROXANNE : À l'ARÈNE de KANTEBLA,\n"
	.string "le fait qu'on ait combattu, {PLAYER},\l"
	.string "est une source de fierté.$"

MatchCall_Text_Brawly1::
	.string "BRAWLY: Hey, there, {PLAYER}{KUN}!\p"
	.string "I learned a lot from the battle we\n"
	.string "had together.\p"
	.string "I intend to do my training over,\n"
	.string "then reopen the GYM.\p"
	.string "It's going to take some time before\n"
	.string "I'm ready to run the GYM again.\p"
	.string "But if I can reopen the GYM,\n"
	.string "I want you to challenge us again.$"

MatchCall_Text_Brawly2::
	.string "BRAWLY: Hey, {PLAYER}{KUN}!\n"
	.string "Congratulations!\p"
	.string "Word about your exploits arrived\n"
	.string "on tidal winds!\p"
	.string "It appears as if I need to work on\n"
	.string "my training some more.\p"
	.string "It's going to take some time before\n"
	.string "I'm ready to run the GYM again.\p"
	.string "But if I can reopen the GYM,\n"
	.string "I want you to challenge us again.$"

MatchCall_Text_Brawly3::
	.string "BRAWLY : Hé, {PLAYER}{KUN} !\n"
	.string "Mon ARÈNE est prête !\p"
	.string "Reviens à POIVRESSEL quand tu veux\n"
	.string "pour un autre défi !$"

MatchCall_Text_Brawly4::
	.string "BRAWLY : {PLAYER}{KUN}, je ne pense pas\n"
	.string "que je me lasserai jamais de te combattre !$"

MatchCall_Text_Wattson1::
	.string "VOLTERE : Oh, c'est toi\p"
	.string "! Depuis ton départ, je\n"
	.string "reprends mon entraînement depuis le\p"
	.string "début. Il me faudra encore\n"
	.string "un peu de temps pour\p"
	.string "rouvrir mon ARÈNE. Tu devras\n"
	.string "attendre jusque-là ! Wahahahaha !$"

MatchCall_Text_Wattson2::
	.string "VOLTÈRE : Wahahahaha !\p"
	.string "Tu as vraiment réussi, hein ?\n"
	.string "J'ai reçu des nouvelles sur toi !\p"
	.string "Il semble que j'aie encore besoin\n"
	.string "de m'entraîner.\p"
	.string "Je dirais qu'il me faut un peu plus\n"
	.string "de temps pour rouvrir mon ARÈNE.\p"
	.string "Tu devras attendre jusque-là !\n"
	.string "Wahahahaha !$"

MatchCall_Text_Wattson3::
	.string "VOLTÈRE : Oh, c'est toi !\n"
	.string "Mon ARÈNE est prête !\p"
	.string "Visite LAVILLA quand tu veux !\n"
	.string "Wahahahaha !$"

MatchCall_Text_Wattson4::
	.string "VOLTÈRE : Wahahaha !\p"
	.string "Un combat avec toi est toujours chargé\n"
	.string "d'une puissance choquante !$"

MatchCall_Text_Flannery1::
	.string "FLORA : {PLAYER}… Quand on\p"
	.string "s'est battus, j'ai compris à\n"
	.string "quel point j'étais immature. Mais\p"
	.string "ce n'est pas fini !\p"
	.string "Je vais reprendre mon\n"
	.string "entraînement et rouvrir l'ARÈNE.\p"
	.string "Quand le moment viendra,\n"
	.string "{PLAYER}, défie-nous à nouveau.$"

MatchCall_Text_Flannery2::
	.string "FLORA : Salut, {PLAYER} ?\n"
	.string "Félicitations !\p"
	.string "La nouvelle de ta réussite nous\n"
	.string "est parvenue comme la chaleur\p"
	.string "d'un volcan !\n"
	.string "Notre entraînement avance très\p"
	.string "bien ici.\n"
	.string "Quand l'ARÈNE sera prête, une\l"
	.string "marque apparaîtra à côté de mon nom dans la liste d'APPEL.$"

MatchCall_Text_Flannery3::
	.string "FLORA : Oh, {PLAYER} ?\n"
	.string "Notre ARÈNE est prête !\p"
	.string "Viens à VERMILAVA pour un bain\n"
	.string "de source chaude et un défi !$"

MatchCall_Text_Flannery4::
	.string "ADRIENNE : {PLAYER}…\n"
	.string "Je suis sûre que tu deviens de plus en plus\l"
	.string "forte à l'entraînement.$"

MatchCall_Text_Winona1::
	.string "ALIZÉE : Bonjour, {PLAYER} !\p"
	.string "Grâce à notre combat, j'ai\n"
	.string "compris mes points faibles !\p"
	.string "Quand je rouvrirai l'ARÈNE, je ne\n"
	.string "perdrai plus !$"

MatchCall_Text_Winona2::
	.string "ALIZÉE : Tu l'as fait, {PLAYER} !\p"
	.string "La nouvelle du nouveau CHAMPION\n"
	.string "nous est parvenue à CIMETRONELLE !\p"
	.string "Mais… La prochaine fois qu'on se bat,\n"
	.string "ça ne se terminera pas de la même façon.$"

MatchCall_Text_Winona3::
	.string "ALIZÉE : C'est {PLAYER} ?\n"
	.string "Notre ARÈNE est de nouveau ouverte !\p"
	.string "On t'attend à FORGEFRAISE !$"

MatchCall_Text_Winona4::
	.string "ALIZÉE : {PLAYER}…\n"
	.string "Bien que j'aie perdu, mes ailes ne\l"
	.string "se briseront jamais.\p"
	.string "Oui, exactement de la même façon que\n"
	.string "tu n'as jamais perdu de vue ton rêve.$"

MatchCall_Text_TateLiza1::
	.string "TATE : Oh ! Tu es… LIZA\n"
	.string ": {PLAYER} ! TATE : On s'entraîne\p"
	.string "encore… LIZA : Pour rouvrir notre ARÈNE\n"
	.string "! TATE : Quand notre ARÈNE sera\p"
	.string "prête… LIZA : Quand notre ARÈNE\n"
	.string "sera prête… TATE : Une marque\p"
	.string "apparaîtra à côté de notre nom…\n"
	.string "LIZA : Sur la liste d'APPEL.$"

MatchCall_Text_TateLiza2::
	.string "TATE : {PLAYER},\n"
	.string "félicitations !\p"
	.string "LIZA : {PLAYER},\n"
	.string "félicitations !\p"
	.string "TATE : Nous deux sommes…\n"
	.string "LIZA : …très impressionnés !\p"
	.string "TATE : Continue !\n"
	.string "LIZA : Continue !$"

MatchCall_Text_TateLiza3::
	.string "LEO : {PLAYER} !\n"
	.string "LILA : {PLAYER} !\p"
	.string "LEO : Notre ARÈNE est prête !\n"
	.string "LILA : Notre ARÈNE est prête !\p"
	.string "LEO : Viens nous rendre visite…\n"
	.string "LILA : à LILYVERRE quand tu veux !$"

MatchCall_Text_TateLiza4::
	.string "LÉO : {PLAYER}, le combat qu'on a eu…\n"
	.string "LÉA : C'est une expérience précieuse.\p"
	.string "LÉO : Ce serait bien si…\n"
	.string "LÉA : On pouvait tous se battre à nouveau !$"

MatchCall_Text_Juan1::
	.string "JUAN : Hmm…\n"
	.string "{PLAYER}{KUN}… C'était bien ça ?\p"
	.string "Notre combat ensemble--il m'a rappelé\n"
	.string "le moment où j'ai rencontré ALIZÉE\l"
	.string "pour la première fois.\p"
	.string "Peut-être es-tu un génie qui pourrait\n"
	.string "un jour surpasser ALIZÉE !$"

MatchCall_Text_Juan2::
	.string "ADRIAN : Fufu… {PLAYER}{KUN}…\n"
	.string "Tu as enfin atteint\p"
	.string "ton objectif. Mon oeil\n"
	.string "pour évaluer les talents\p"
	.string "n'a pas failli. Tu\n"
	.string "es un DRESSEUR remarquable.\l"
	.string "Je te félicite.$"

MatchCall_Text_Juan3::
	.string "JUAN : Hoho… {PLAYER}{KUN}…\p"
	.string "Notre ARÈNE de ATALANOPOLIS a enfin\n"
	.string "rouvert.\p"
	.string "Si tu souhaites me voir, tu es\n"
	.string "le bienvenu à tout moment.$"

MatchCall_Text_Juan4::
	.string "JUAN : {PLAYER}{KUN}…\p"
	.string "Comme la plus belle musique, les combats\n"
	.string "que nous livrons ensemble résonnent\l"
	.string "d'inspiration dans mon coeur…\p"
	.string "Quand je ferme les yeux, je te vois\n"
	.string "planer au rythme de la mélodie…$"

MatchCall_Text_Sidney::
	.string "ARMAND : Yo, {PLAYER} !\p"
	.string "Si tu veux te battre contre moi\n"
	.string "encore, reviens quand tu veux à la\l"
	.string "LIGUE POKéMON.\p"
	.string "Je serai toujours là !\n"
	.string "Je t'attendrai !$"

MatchCall_Text_Phoebe::
	.string "GLÉCILIA : Salut, {PLAYER} !\p"
	.string "Que dirais-tu de revenir ici\n"
	.string "un de ces jours ?\p"
	.string "J'aimerais voir à quel point ton lien\n"
	.string "est devenu plus fort avec tes\l"
	.string "POKéMON.$"

MatchCall_Text_Glacia::
	.string "GLACIA : Bonjour, {PLAYER}.\p"
	.string "J'espère que tu ne t'es pas endormi\n"
	.string "sur ta puissance ?\p"
	.string "Si tu ressens le besoin de calmer un peu\n"
	.string "tes émotions brûlantes, viens\l"
	.string "à la LIGUE POKéMON…$"

MatchCall_Text_Drake::
	.string "DRAGON : Cette voix…\n"
	.string "{PLAYER}, c'est toi ?\p"
	.string "Tu as l'air en forme…\n"
	.string "Je comprends qu'il\l"
	.string "y a maintenant\l"
	.string "une installation\p"
	.string "appelée\n"
	.string "PARC DES COMBATS.\l"
	.string "Tu devrais y\p"
	.string "aller, {PLAYER} !$"

MatchCall_Text_Wallace::
	.string "ALIZA : Bonjour,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "As-tu rencontré PIERRE ?\n"
	.string "Il est…\p"
	.string "En fait\n"
	.string "incroyablement doué.\p"
	.string "Cependant, c'est\n"
	.string "une âme étrange qui\p"
	.string "préfère collectionner\n"
	.string "des pierres rares\p"
	.string "plutôt que combattre.\n"
	.string "Mais ne le sous-estime pas !$"

MatchCall_Text_MayRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … …\p"
	.string "… Bip !\p"
	.string "FLORA : Salut,\n"
	.string "{PLAYER}{KUN} !\p"
	.string "J'étais à\n"
	.string "PACIFIDLOG\p"
	.string "il y a\n"
	.string "un petit\p"
	.string "moment.\n"
	.string "C'est un\p"
	.string "endroit\n"
	.string "paisible !$"

MatchCall_Text_BrendanRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Bip !\p"
	.string "BRENDAN : Hé,\n"
	.string "{PLAYER} !\p"
	.string "J'étais à\n"
	.string "PACIFIDLOG\p"
	.string "tout à l'heure.\n"
	.string "J'ai vu cet\p"
	.string "énorme\n"
	.string "POKéMON !\p"
	.string "C'était\n"
	.string "incroyable !{PLAYER}$"

MatchCall_Text_May1::
	.string "FLORA : Salut, {PLAYER}{KUN} !\p"
	.string "M. MARIN a pris sa retraite de MARIN,\n"
	.string "mais je le vois encore en mer\l"
	.string "avec son POKéMON PECNO parfois.\p"
	.string "Il doit toujours aimer la mer.$"

MatchCall_Text_May2::
	.string "FLORA : Salut, {PLAYER}{KUN} ! Tu sais\p"
	.string "comment les petites villes comme ROSALIA et\n"
	.string "ALGATIA ont des ARÈNES ? Pour\p"
	.string "une raison quelconque, le grand port\n"
	.string "de MYOKARA n'a pas d'ARÈNE. Quand\p"
	.string "ils construiront enfin une ARÈNE là-bas,\n"
	.string "je devrais postuler pour être CHAMPIONNE.$"

MatchCall_Text_May3::
	.string "FLORA : Salut, {PLAYER}{KUN} !\p"
	.string "Tu te souviens d'un homme appelé\n"
	.string "le TAILLEUR à MÉROUVILLE ?\l"
	.string "Il avait une maison là-bas, tu te\p"
	.string "souviens ?\n"
	.string "Eh bien, j'ai découvert que son\p"
	.string "jeune frère habite à MYOKARA.\p"
	.string "Tu devines son surnom ?\n"
	.string "… … … … … …\p"
	.string "… … … … … … Le type FORCE !$"

MatchCall_Text_May4::
	.string "FLORA : {PLAYER}{KUN} ?\p"
	.string "TUNNEL RUSTURF...\n"
	.string "Ils l'ont nommé ainsi parce qu'il\l"
	.string "relie MÉROUVILLE et VERGAZON.$"

MatchCall_Text_May5::
	.string "FLORA : {PLAYER}{KUN}, comment vas-tu ?\p"
	.string "Je suis sur la ROUTE 111 maintenant.\p"
	.string "Je vais me reposer chez une\n"
	.string "vieille dame.\p"
	.string "Elle habite juste au nord du\n"
	.string "désert.$"

MatchCall_Text_May6::
	.string "FLORA : Salut, {PLAYER}{KUN} !\p"
	.string "Tu connais la TOUR MIRAGE\n"
	.string "dans le désert ?\p"
	.string "Elle apparaît et disparaît…\n"
	.string "C'est mystérieux !\p"
	.string "Tu devrais y aller !$"

MatchCall_Text_May7::
	.string "FLORA : {PLAYER}{KUN}, youhou ! Je\n"
	.string "suis sur la ROUTE 119.\p"
	.string "Il y a une grande\n"
	.string "rivière ici, et il pleut\p"
	.string "souvent. Je suis trempée !$"

MatchCall_Text_May8::
	.string "FLORA : {PLAYER}{KUN}, salut.\p"
	.string "Le MONT PYRE est un mémorial aux POKéMON\n"
	.string "dont la vie s'est achevée.\p"
	.string "Peut-être à cause de ça, il est infesté\n"
	.string "de nombreux POKéMON de type SPECTRE !$"

MatchCall_Text_May9::
	.string "FLORA : Salut, {PLAYER}{KUN} !\p"
	.string "Je pensais aller aux sources chaudes\n"
	.string "de LAVARIDGE.\p"
	.string "Mais en chemin, vers le COL TOURMENTÉ,\n"
	.string "j'ai croisé des personnages louches.\l"
	.string "L'ambiance était mauvaise !$"

MatchCall_Text_May10::
	.string "FLORA : Salut, {PLAYER}{KUN} !\n"
	.string "Tu as vu les infos ?\p"
	.string "On dit que le CAPT. STERN a découvert\n"
	.string "la CAVERNE MARINE lors de son\l"
	.string "expédition en sous-marin.$"

MatchCall_Text_May11::
	.string "FLORA : Salut, {PLAYER}{KUN} ! Tu\n"
	.string "ne trouves pas ça génial ?\p"
	.string "Même sans bateau, tu peux traverser\n"
	.string "la mer avec une capacité de\l"
	.string "POKéMON. Tu savais qu'il y a\p"
	.string "plus ? Il y a une\p"
	.string "capacité qui te permet d'aller\n"
	.string "au fond de la mer.$"

MatchCall_Text_May12::
	.string "FLORA : Salut, {PLAYER}{KUN} !\n"
	.string "J'espère que tout va bien !\p"
	.string "Tu es allé en mer et le passage\n"
	.string "de l'autre côté était bloqué ?\l"
	.string "Essaie de plonger au fond et de\p"
	.string "suivre les fosses.\n"
	.string "Quand tu arrives\p"
	.string "de l'autre côté,\n"
	.string "remonte à la surface. Facile !$"

MatchCall_Text_May13::
	.string "FLORA : Salut, {PLAYER}{KUN}\p"
	.string "! Comment ça va\n"
	.string "? Tu remplis ton\p"
	.string "POKéDEX ? J'ai entendu\n"
	.string "une rumeur sur des\l"
	.string "POKéMON super-anciens. J'adorerais en\p"
	.string "attraper un !$"

MatchCall_Text_May14::
	.string "FLORA : {PLAYER}{KUN} !\n"
	.string "J'ai entendu les rumeurs !\p"
	.string "Tu as battu le CHAMPION\n"
	.string "de l'ARÈNE d'ATALANOPOLIS ?\p"
	.string "Ça veut dire que tu n'as plus\n"
	.string "beaucoup de chemin, hein ?$"

MatchCall_Text_May15::
	.string "FLORA : Il n'y a plus un seul DRESSEUR\n"
	.string "en HOENN qui ne te connaît pas,\l"
	.string "{PLAYER}{KUN} !\p"
	.string "Quand je dis aux gens que je suis amie\n"
	.string "avec toi, {PLAYER}{KUN}, ils sont tous\l"
	.string "surpris !$"

MatchCall_Text_Brendan1::
	.string "BRICE : Hé, {PLAYER} !\p"
	.string "M. MARIN a pris sa retraite de MARIN,\n"
	.string "mais je le vois encore en mer\l"
	.string "avec son POKéMON PECNO parfois.\p"
	.string "Je suppose qu'il doit toujours\n"
	.string "aimer la mer.$"

MatchCall_Text_Brendan2::
	.string "BRENDAN : Salut, {PLAYER} ! Je ne\p"
	.string "comprends pas comment de petites villes\n"
	.string "comme ROSALIA et ALGATIA ont des\p"
	.string "ARÈNES. Alors que le grand port\n"
	.string "de MYOKARA n'a pas d'ARÈNE. Quand\p"
	.string "ils construiront enfin une ARÈNE là-bas,\n"
	.string "je devrais postuler pour être CHAMPION.$"

MatchCall_Text_Brendan3::
	.string "BRENDAN : Yo, {PLAYER} !\p"
	.string "Tu te souviens d'un type appelé\n"
	.string "le TAILLEUR à MÉROUVILLE ?\l"
	.string "Il avait une maison là-bas, non ?\p"
	.string "Eh bien, son petit frère habite\n"
	.string "à MYOKARA.\p"
	.string "Tu devines son surnom ?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Le type FORCE !$"

MatchCall_Text_Brendan4::
	.string "BRENDAN : Cette voix… {PLAYER} ?\p"
	.string "Ils ont donné son nom au TUNNEL RUSTURF\n"
	.string "parce qu'il relie MYOKARA et\l"
	.string "VERGOYON.\p"
	.string "Tu le savais ?$"

MatchCall_Text_Brendan5::
	.string "BRICE : {PLAYER}, quoi de neuf ?\p"
	.string "Hé, je suis sur la ROUTE 111 maintenant.\p"
	.string "Je vais me reposer chez une vieille\n"
	.string "dame au nord du désert.\p"
	.string "Si tu es dans le coin, tu\n"
	.string "devrais aller la voir aussi.$"

MatchCall_Text_Brendan6::
	.string "BRICE : Hé, {PLAYER} !\p"
	.string "Tu connais la TOUR MIRAGE\n"
	.string "dans le désert ?\p"
	.string "On dit que, comme un mirage, on ne\n"
	.string "la voit que parfois.\p"
	.string "J'aimerais bien la voir !$"

MatchCall_Text_Brendan7::
	.string "BRICE : C'est qui ? Oh, {PLAYER} ?\n"
	.string "Tu sais quoi ? Je suis sur la ROUTE 119.\p"
	.string "Il y a une grande rivière ici, et\n"
	.string "il pleut tout le temps.\p"
	.string "J'ai été trempé jusqu'aux os !$"

MatchCall_Text_Brendan8::
	.string "BRICE : {PLAYER} !\p"
	.string "Le MONT PYRE est un mémorial aux POKéMON\n"
	.string "dont la vie s'est achevée.\p"
	.string "C'est probablement pour ça qu'il est infesté\n"
	.string "de nombreux POKéMON de type SPECTRE !$"

MatchCall_Text_Brendan9::
	.string "BRENDAN : Salut, {PLAYER}.\p"
	.string "Je retournais aux\n"
	.string "sources chaudes de\p"
	.string "VERMILAVA. Mais j'ai\n"
	.string "entendu parler de\p"
	.string "toi, alors je\n"
	.string "t'ai appelé !$"

MatchCall_Text_Brendan10::
	.string "BRICE : Salut, {PLAYER} !\n"
	.string "Tu as vu les infos ?\p"
	.string "On dit que le CAPT. STERN a découvert\n"
	.string "la CAVERNE MARINE lors de son\l"
	.string "expédition en sous-marin.$"

MatchCall_Text_Brendan11::
	.string "BRENDAN : Salut, {PLAYER} !\n"
	.string "Tu ne trouves pas ça génial ?\p"
	.string "Même sans bateau, tu peux\n"
	.string "traverser la mer avec une\l"
	.string "capacité de POKéMON.\p"
	.string "Et il y a une capacité qui te\n"
	.string "permet d'aller au fond de la mer.\p"
	.string "Les POKéMON peuvent tout faire !$"

MatchCall_Text_Brendan12::
	.string "BRENDAN : Salut, {PLAYER} !\n"
	.string "Comment tu te sens ?\p"
	.string "Tu as déjà eu le passage de l'autre\n"
	.string "côté bloqué en mer ?\p"
	.string "Essaie de plonger au fond et de\n"
	.string "suivre les fosses du fond marin.\p"
	.string "Quand tu arrives de l'autre côté,\n"
	.string "remonte à la surface. C'est simple !$"

MatchCall_Text_Brendan13::
	.string "BRENDAN : Salut, {PLAYER} ! Comment\p"
	.string "ça va ? Tu remplis\n"
	.string "ton POKéDEX avec succès ?\p"
	.string "J'ai entendu une rumeur qu'il\n"
	.string "y a des POKéMON super-anciens\l"
	.string "dehors. Et pas un seul--trois\p"
	.string "! J'adorerais en attraper un…$"

MatchCall_Text_Brendan14::
	.string "BRICE : {PLAYER} ! J'ai entendu\n"
	.string "les rumeurs ! Tu as battu\p"
	.string "le CHAMPION de l'ARÈNE d'ATALANOPOLIS\n"
	.string "? Génial ! Tu n'es\p"
	.string "plus qu'à deux doigts !$"

MatchCall_Text_Brendan15::
	.string "BRICE : Il n'y a pas un seul DRESSEUR\n"
	.string "en HOENN qui ne te connaisse pas,\l"
	.string "{PLAYER} !\p"
	.string "Quand je dis aux gens que je suis ami\n"
	.string "avec toi, {PLAYER}, ils sont assez\l"
	.string "envieux !$"

MatchCall_Text_Wally1::
	.string "TIMMY : Oh, {PLAYER} !\p"
	.string "Je vais de mieux en mieux\n"
	.string "et je suis plus en forme.\p"
	.string "J'espère devenir un DRESSEUR comme\n"
	.string "toi bientôt, {PLAYER} !$"

MatchCall_Text_Wally2::
	.string "WALLY : {PLAYER}, salut !\p"
	.string "Depuis que le TUNNEL RUSTURF a été\n"
	.string "percé, WANDA est très heureuse !$"

MatchCall_Text_Wally3::
	.string "ALAIN : Oh, {PLAYER} !\p"
	.string "Je… j'ai quitté la maison de mon oncle à\n"
	.string "VERGOUILLETTE sans prévenir personne.\p"
	.string "Je me demande s'il est furieux contre moi…\p"
	.string "{PLAYER}, tu comprends ce que\n"
	.string "je ressens, n'est-ce pas ?$"

MatchCall_Text_Wally4::
	.string "POPI : {PLAYER} ? C'est moi,\n"
	.string "POPI ! Le monde des DRESSEURS\p"
	.string "est incroyable ! Quand j'ai mon\p"
	.string "POKéMON avec moi, toutes sortes de\n"
	.string "gens me saluent ! C'est comme\p"
	.string "si tout le monde se connectait\n"
	.string "à travers les POKéMON !$"

MatchCall_Text_Wally5::
	.string "TIMMY : {PLAYER} ? C'est génial\n"
	.string "! Le TARSAL qu'on a attrapé\l"
	.string "ensemble ? Il a évolué, {PLAYER}\p"
	.string "! Peut-être que j'ai du talent…\p"
	.string "Oh, mais je ne devrais\n"
	.string "pas me la porter !\p"
	.string "Après tout, ce sont les\n"
	.string "POKéMON qu'il faut féliciter !$"

MatchCall_Text_Wally6::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "WALLY semble être hors de\n"
	.string "la zone de service du POKéNAV…$"

MatchCall_Text_Wally7::
	.string "PETER : Oh, {PLAYER} !\p"
	.string "Avant de te rencontrer, je sortais à peine\n"
	.string "de chez moi…\p"
	.string "Mais maintenant, je suis en aventure avec\n"
	.string "mon propre POKéMON…\p"
	.string "{PLAYER}…\n"
	.string "Merci…$"

MatchCall_Text_Scott1::
	.string "SCOTT : Comment ça\p"
	.string "va, {PLAYER}{KUN} !\n"
	.string "Tu sais que les POKéMON\p"
	.string "peuvent être trouvés\n"
	.string "partout ?\p"
	.string "Comme dans\n"
	.string "les montagnes,\p"
	.string "la mer, les grottes…\n"
	.string "Explore partout !$"

MatchCall_Text_Scott2::
	.string "SCOTT : Je suis sur la ROUTE 119 en ce moment.\n"
	.string "Elle grouille de DRESSEURS !\p"
	.string "Elle est aussi envahie de hautes herbes\n"
	.string "partout, on dirait.\p"
	.string "Marcher en short ici\n"
	.string "me chatouille partout !$"

MatchCall_Text_Scott3::
	.string "SCOTT : Salut, salut,\p"
	.string "{PLAYER}{KUN} ! Tu\n"
	.string "as eu l'occasion\p"
	.string "de grimper au\n"
	.string "MONT SÉPIA ?\p"
	.string "L'endroit est sacré.\n"
	.string "Traite-le avec respect.$"

MatchCall_Text_Scott4::
	.string "SCOTT : Salut, {PLAYER}{KUN} !\p"
	.string "J'ai entendu parler de ces\n"
	.string "bandes étranges qui posent problème.\p"
	.string "La TEAM MAGMA et la\n"
	.string "TEAM AQUA, je crois. Je\p"
	.string "pense qu'il y a des\n"
	.string "DRESSEURS habiles parmi eux. …Mais\p"
	.string "s'ils sont des voyous…$"

MatchCall_Text_Scott5::
	.string "SCOTT : Oh, salut, {PLAYER}{KUN}.\p"
	.string "Y aurait-il des DRESSEURS costauds\n"
	.string "au fond de la mer ?\p"
	.string "Je ne peux pas aller vérifier moi-même.\n"
	.string "Je ne sais pas nager, pour commencer.\l"
	.string "Et je n'élève pas de POKéMON…$"

MatchCall_Text_Scott6::
	.string "SCOTT : Salut, salut, {PLAYER}{KUN} !\p"
	.string "Tu sais que tu peux défier\n"
	.string "la LIGUE POKéMON quand tu as\l"
	.string "collecté tous les BADGES d'ARÈNE ?\p"
	.string "Avec ton talent, devenir\n"
	.string "CHAMPION n'est pas un rêve impossible.\p"
	.string "Mais tu savais ?\n"
	.string "Il y a un endroit encore meilleur.\p"
	.string "Mais, c'est tout ce\n"
	.string "que je suis prêt à dire\p"
	.string "pour le moment.\n"
	.string "C'est quelque chose à\p"
	.string "attendre avec impatience.\n"
	.string "Quand tu auras gagné ta place à la\l"
	.string "LIGUE POKéMON dans le PANTHÉON !$"

MatchCall_Text_Scott7::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "SCOTT semble être hors de\n"
	.string "la zone de service du POKéNAV…$"

MatchCall_Text_Norman1::
	.string "PAPA : À MYOKARA, il y a un homme\n"
	.string "qu'on appelle bizarrement\l"
	.string "le COUPEUR.\p"
	.string "Si tu es dans le coin, tu devrais\n"
	.string "lui rendre visite.$"

MatchCall_Text_Norman2::
	.string "PAPA : Hm… Petit à\n"
	.string "petit, mais aussi très sûrement,\l"
	.string "tu deviens plus fort, {PLAYER}.\p"
	.string "Plus tu deviens fort, plus\n"
	.string "tu t'envoles loin de Maman\l"
	.string "et moi… C'est un\p"
	.string "sentiment difficile à expliquer.$"

MatchCall_Text_Norman3::
	.string "PAPA : Je vois…\n"
	.string "Tu as collecté quatre BADGES D'ARENE…\p"
	.string "On ne peut plus l'éviter maintenant.\n"
	.string "On se battra comme je l'ai promis.\p"
	.string "Viens quand tu veux.\n"
	.string "On t'attendra tous !$"

MatchCall_Text_Norman4::
	.string "PAPA : {PLAYER} ! Tu ferais mieux d'aller voir\n"
	.string "Maman de temps en temps.\p"
	.string "Je vais rester ici et\n"
	.string "intensifier mon entraînement.\p"
	.string "La voie du combat est profonde\n"
	.string "et impitoyable !$"

MatchCall_Text_Norman5::
	.string "PAPA : Oh, salut, {PLAYER} !\p"
	.string "C'est quoi ? L'EMBLÈME MAGMA ?\n"
	.string "Je ne sais pas de quoi il s'agit.\p"
	.string "Mais avec un nom comme ça, ça pourrait\n"
	.string "être lié à un volcan d'une façon ou d'une autre !$"

MatchCall_Text_Norman6::
	.string "PAPA : Hiyah ! Haah ! Dwah !\p"
	.string "...Oh ? {PLAYER} !\p"
	.string "Tu m'as surpris en plein\n"
	.string "entraînement POKéMON !$"

MatchCall_Text_Norman7::
	.string "PAPA : {PLAYER} ! Qui\p"
	.string "aurait cru que tu deviendrais\n"
	.string "CHAMPION de la LIGUE POKéMON…\p"
	.string "OK ! Je ne vais\n"
	.string "pas rester en arrière !$"

MatchCall_Text_Norman8::
	.string "PAPA : Hm ? {PLAYER} ?\n"
	.string "Quel timing !\p"
	.string "Cette fois, je vais te défier\n"
	.string "en combat.\p"
	.string "Je t'attends à l'ARENE de CLÉMENTI-VILLE.\n"
	.string "Accepte mon défi quand tu veux !$"

MatchCall_Text_Norman9::
	.string "PAPA : …Tu m'étonnes, {PLAYER}.\n"
	.string "Jusqu'où iras-tu voler ?$"

MatchCall_Text_Steven1::
	.string "PIERRE : Salut, {PLAYER}{KUN} !\p"
	.string "Tu es déjà allé\n"
	.string "à MYOKARA ? Tu\p"
	.string "devrais visiter le MAGASIN\n"
	.string "DE VÉLOS et prendre\p"
	.string "un VÉLO CROSS. Ensuite,\n"
	.string "explore bien la GROTTE\p"
	.string "GRANITE. Tu pourrais faire\n"
	.string "une nouvelle découverte là-bas.$"

MatchCall_Text_Steven2::
	.string "PIERRE : Salut, {PLAYER}{KUN} !\p"
	.string "J'ai rencontré plein de\n"
	.string "DRESSEURS différents jusqu'ici.\p"
	.string "Mais tu es unique.\n"
	.string "Tu n'es comme personne d'autre.$"

MatchCall_Text_Steven3::
	.string "PIERRE : Salut,\p"
	.string "{PLAYER}{KUN} !\n"
	.string "Quand tu es en aventure avec\p"
	.string "tes POKéMON, à\n"
	.string "quoi penses-tu ?\p"
	.string "Penses-tu à devenir plus fort ?\n"
	.string "Ou à découvrir de\p"
	.string "nouveaux endroits ?\n"
	.string "Les deux sont merveilleux.$"

MatchCall_Text_Steven4::
	.string "PIERRE : Allô ?\n"
	.string "{PLAYER}{KUN} ?\p"
	.string "Je suis pris dans une petite\n"
	.string "galère au CENTRE SPATIAL.\p"
	.string "Je suis désolé, mais je ne peux pas parler maintenant.\n"
	.string "Salut !$"

MatchCall_Text_Steven5::
	.string "PIERRE : Oh !\n"
	.string "{PLAYER}{KUN} !\p"
	.string "Pas besoin de parler.\n"
	.string "Il est temps d'agir, pas de parler.\p"
	.string "Tu dois croire en toi\n"
	.string "et faire ce qui est juste.$"

MatchCall_Text_Steven6::
	.string "… … … … … …\p"
	.string "PIERRE ne semble pas recevoir\n"
	.string "l'appel…$"

MatchCall_Text_Steven7::
	.string "PIERRE : {PLAYER}{KUN}… Félicitations\n"
	.string "pour ton entrée au PANTHÉON.\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "J'espère qu'on se reverra\n"
	.string "quelque part !$"

MatchCall_Text_BirchRegisterCall:
	.string "PROF. SEKO : Oh, {PLAYER}{KUN} !\n"
	.string "J'ai déjà entendu parler de toi !\p"
	.string "Il semble que ton POKéNAV ait été\n"
	.string "amélioré avec l'APPEL.\p"
	.string "Eh bien, je devrais m'enregistrer\p"
	.string "aussi !\n"
	.string "Comme ça, je pourrais consulter\l"
	.string "ton POKéDEX même quand tu es\p"
	.string "en pleine exploration. … … … … … …$"

MatchCall_Text_RegisteredBirch:
	.string "PROF. SEKO enregistré\n"
	.string "dans le POKéNAV.$"

MatchCall_Text_UnusedProfBirch:
	.string "PROF. SEKO : Quand on a à la fois\n"
	.string "le POKéDEX et le POKéNAV, étudier\l"
	.string "les POKéMON devient plus amusant, non ?$"

MatchCall_Text_MrStone1::
	.string "M. PIERRE : Oh ?\p"
	.string "{PLAYER}{KUN} !\n"
	.string "Puisque tu m'as\p"
	.string "appelé, le POKéNAV\n"
	.string "doit fonctionner\p"
	.string "correctement !\n"
	.string "D'autres personnes\p"
	.string "seront enregistrées\n"
	.string "automatiquement\p"
	.string "quand\n"
	.string "tu les rencontreras.\p"
	.string "C'est pratique, non ?\n"
	.string "Utilise-le bien !$"

MatchCall_Text_MrStone2::
	.string "MR. STONE: Oh? {PLAYER}{KUN}!\p"
	.string "What's wrong? Have you forgotten\n"
	.string "about that little errand of mine?\p"
	.string "I need you to deliver my letter\n"
	.string "to STEVEN in DEWFORD.\p"
	.string "After that, deliver our parcel to\n"
	.string "CAPT. STERN in SLATEPORT.\p"
	.string "You remember, don't you?\p"
	.string "Now, since I am a busy PRESIDENT,\n"
	.string "I have to go! Bye-bye!$"

MatchCall_Text_MrStone3::
	.string "M. PIERRE : Oh ! {PLAYER}{KUN} !\p"
	.string "Ah, tu as rencontré PIERRE !\n"
	.string "Je ferais mieux de te récompenser !\p"
	.string "Quand tu reviendras à MEROUVILLE,\n"
	.string "viens me voir à mon bureau.\p"
	.string "Je t'attendrai !$"

MatchCall_Text_MrStone4::
	.string "MR. STONE: Oh! {PLAYER}{KUN}!\p"
	.string "Did you know that DEVON was\n"
	.string "digging the RUSTURF TUNNEL?\p"
	.string "But we shut down the operation to\n"
	.string "protect the POKéMON in the area.\p"
	.string "It's a no-brainer, really.\p"
	.string "It's more important to let POKéMON\n"
	.string "live in peace than worry about our\l"
	.string "own convenience.$"

MatchCall_Text_MrStone5::
	.string "M. PIERRE : Bonjour, bonjour, {PLAYER}{KUN} !\p"
	.string "J'ai entendu dire par quelqu'un à POIVRESSEL\n"
	.string "que tu es l'enfant de NORMAN !\p"
	.string "Pas étonnant que tu sois si\n"
	.string "capable !$"

MatchCall_Text_MrStone6::
	.string "M. PIERRE : Quoi ?\p"
	.string "Tu t'es battu contre ton propre père\n"
	.string "et tu l'as battu ?\p"
	.string "C'est stupéfiant !\p"
	.string "Je ne savais pas que j'étais devenu\n"
	.string "ami avec quelqu'un d'aussi spécial ! Wahaha !$"

MatchCall_Text_MrStone7::
	.string "Allô !\n"
	.string "Ici DEVON CORPORATI…\l"
	.string "Oh, bonjour, {PLAYER} !\p"
	.string "Notre PRÉSIDENT était là il y a\n"
	.string "un moment, mais il est sorti.\p"
	.string "Notre PRÉSIDENT est occupé, mais tu\n"
	.string "semblais tout aussi occupé, {PLAYER}.$"

MatchCall_Text_MrStone8::
	.string "…Hein ? …Qu'est-ce que c'est ?\p"
	.string "GROU… Oui ? …DON ?\p"
	.string "Tu coupes…\n"
	.string "…j'entends pas…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone9::
	.string "…Hein ? …Qu'est-ce que c'est ?\p"
	.string "Mer pro… Oui ? …Grot… ?\p"
	.string "Tu coupes…\n"
	.string "…j'entends pas…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone10::
	.string "M. ROCHARD : {PLAYER}{KUN} ! C'est moi !\p"
	.string "Tu as apparemment été mêlé à\n"
	.string "toutes sortes d'affaires, mais moi, occupé,\l"
	.string "je n'en sais rien de précis !\p"
	.string "Cependant, je t'encourage à suivre\n"
	.string "la voie en laquelle tu crois.\p"
	.string "Je serai toujours de ton côté !\n"
	.string "Prends soin de toi !$"

MatchCall_Text_MrStone11::
	.string "M. PIERRE : … … … … … …\n"
	.string "C'est peut-être {PLAYER}{KUN} ?\p"
	.string "Ta voix est si pleine de confiance,\n"
	.string "je ne t'ai pas reconnu tout de suite !\p"
	.string "Hm ! Tu dois venir nous voir chez DEVON\n"
	.string "un de ces jours !$"
