@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string " si joli !$"

GiddyText_SoDarling::
	.string " si adorable !$"

GiddyText_SoRelaxed::
	.string " si détendu !$"

GiddyText_SoSunny::
	.string " si ensoleillé !$"

GiddyText_SoDesirable::
	.string " si désirable !$"

GiddyText_SoExciting::
	.string " si excitant !$"

GiddyText_SoAmusing::
	.string " si amusant !$"

GiddyText_SoMagical::
	.string " si magique !$"

GiddyText_Is::
	.string " est$"

GiddyText_DontYouAgree::
	.string "\n"
	.string "Tu n'es pas d'accord ?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "J'ai tellement envie de partir en vacances.\n"
	.string "Tu connaîtrais un bel endroit ?$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "J'ai acheté des crayons avec 120 couleurs !\n"
	.string "Tu ne trouves pas ça sympa ?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "Ce ne serait pas bien de flotter\n"
	.string "sur un nuage de bulles ?$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "Quand tu écris sur une plage de sable,\n"
	.string "ça s'efface. Ça me rend triste.$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "C'est comment le fond de la mer ?\n"
	.string "Juste une fois, j'aimerais tellement y aller !$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "Quand tu vois le soleil se coucher,\n"
	.string "ça te donne envie de rentrer ?$"

GiddyText_LyingBackInTheGreenGrass::
	.string "Allongé dans l'herbe verte…\n"
	.string "Oh, c'est tellement, tellement bien !$"

GiddyText_SecretBasesAreSoWonderful::
	.string "Les BASES SECRÈTES sont merveilleuses !\n"
	.string "Tu ne sens pas l'excitation ?$"
