MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "Es-tu prêt à apprendre cette capacité ?$Ça te coûtera 5.000¥.$"

MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnceFinite:
	.string "Cette attaque ne peut être apprise\n"
	.string "qu'une fois. Ça te va ?$"

MoveTutor_Text_SwaggerTeach:
	.string "Heh ! Mon POKéMON\n"
	.string "règne totalement !\p"
	.string "Il est plus cool que\n"
	.string "n'importe quel POKéMON !\l"
	.string "Je me suis vanté\p"
	.string "avec un swagger dans\p"
	.string "la rue et tout le\n"
	.string "monde m'a regardé !$"

MoveTutor_Text_SwaggerDeclined:
	.string "Quoi, non ? Tu ne peux pas entrer\n"
	.string "dans l'esprit des choses ?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "Très bien, quel POKéMON veut\n"
	.string "apprendre GOUHARD ?$"

MoveTutor_Text_SwaggerTaught:
	.string "Je vais juste féliciter mes POKéMON\n"
	.string "désormais sans fanfaronner.$"

MoveTutor_Text_RolloutTeach:
	.string "Tu savais qu'on peut aller très\n"
	.string "loin dans cette direction sans\l"
	.string "changer de direction ?\p"
	.string "Je pourrais même rouler comme\n"
	.string "ça.\p"
	.string "Tu crois que tes POKéMON\n"
	.string "auront envie de rouler aussi ?\p"
	.string "Je peux apprendre ROULADE à\n"
	.string "l'un d'eux si tu veux.$"

MoveTutor_Text_RolloutDeclined:
	.string "Pas besoin d'être timide.\n"
	.string "Roule !$"

MoveTutor_Text_RolloutWhichMon:
	.string "Héhé, bien sûr ! Ce serait génial si\n"
	.string "le POKéMON me ressemblait.$"

MoveTutor_Text_RolloutTaught:
	.string "Rouler dans l'herbe me rend heureux.\n"
	.string "Allez, roulons !$"

MoveTutor_Text_FuryCutterTeach:
	.string "Il y a une attaque qui devient plus forte\n"
	.string "quand tu l'utilises plusieurs fois de suite.\p"
	.string "C'est une attaque de type INSECTE, et elle est\n"
	.string "sacrément cool.\p"
	.string "Elle s'appelle TAILLADE.\n"
	.string "Tu veux que je l'apprenne à un POKéMON ?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "On n'est pas sur la même longueur d'onde.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Yay !\n"
	.string "Montre-moi quel POKéMON je dois apprendre.$"

MoveTutor_Text_FuryCutterTaught:
	.string "J'adore regarder si la capacité\n"
	.string "continue de toucher en succession !$"

MoveTutor_MimicTeach:
	.string "Ah, jeune homme ! Je\p"
	.string "suis aussi jeune, mais j'imite\n"
	.string "les styles et le langage\l"
	.string "des vieillards de cette ville.\p"
	.string "Qu'en dis-tu, jeune homme ?\n"
	.string "Accepterais-tu que je t'apprenne\l"
	.string "la capacité COPIE ?$"

MoveTutor_MimicDeclined:
	.string "Oh, mince ! Je voulais enseigner\n"
	.string "COPIE à ton POKéMON !$"

MoveTutor_Text_MimicWhichMon:
	.string "Fwofwo ! Et ainsi je le ferai !\n"
	.string "Montre-moi le POKéMON\l"
	.string "que tu veux que j'enseigne.$"

MoveTutor_Text_MimicTaught:
	.string "MIMIQUE est une capacité de grande profondeur.\p"
	.string "Pourrais-tu l'exécuter à la perfection\n"
	.string "comme moi… ?$"

MoveTutor_Text_MetronomeTeach:
	.string "Je veux plein\n"
	.string "de choses !\p"
	.string "Mais j'ai épuisé\n"
	.string "mon argent de poche…\l"
	.string "Ne serait-ce pas\p"
	.string "bien s'il y avait\n"
	.string "un sort pour faire\p"
	.string "apparaître de l'argent ?\n"
	.string "Héhéhé…$"

MoveTutor_Text_MetronomeDeclined:
	.string "D'accord. Je serai là si tu changes\n"
	.string "d'avis.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "OK ! Je vais l'enseigner !\n"
	.string "À quel POKéMON dois-je l'apprendre ?$"

MoveTutor_Text_MetronomeTaught:
	.string "Quand un POKéMON agite le doigt\n"
	.string "comme une MÉTRONOME, toutes sortes de\l"
	.string "choses bien se produisent.\p"
	.string "Ce serait génial si nous pouvions\n"
	.string "l'utiliser aussi, non ?$"

MoveTutor_Text_SleepTalkTeach:
	.string "Humph ! Ma femme compte sur FORCE CACHÉE\n"
	.string "pour rester éveillée.\p"
	.string "Elle devrait juste faire une sieste comme moi,\n"
	.string "et BAVARDER.\p"
	.string "Je peux apprendre à ton POKéMON à\n"
	.string "BAVARDER à la place. Intéressé ?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Oh, d'accord, d'accord. Tu veux rester éveillé\n"
	.string "avec FORCE CACHÉE, aussi…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, un enfant reconnaissant !\n"
	.string "Quel POKéMON dois-je enseigner ?$"

MoveTutor_Text_SleepTalkTaught:
	.string "Je n'ai jamais réussi le tour\n"
	.string "de pièces de ma femme.\p"
	.string "Je serais heureux de réussir\n"
	.string "même en PARLANT EN DORMANT…$"

MoveTutor_Text_SubstituteTeach:
	.string "Quand je voyage\p"
	.string "autour du monde…\n"
	.string "Je pense à quel\l"
	.string "point ce serait bien\p"
	.string "s'il y avait plus\n"
	.string "que des POKéMON\p"
	.string "dans ce monde.\n"
	.string "C'est un beau rêve.$"

MoveTutor_Text_SubstituteDeclined:
	.string "Oh, non ?\p"
	.string "Un POKéMON peut en faire une copie\n"
	.string "en l'utilisant, tu sais.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Hihi…\n"
	.string "Quel POKéMON veux-tu que j'enseigne\l"
	.string "CLONAGE ?$"

MoveTutor_Text_SubstituteTaught:
	.string "Nous, les êtres humains, devrions profiter de nos\n"
	.string "propres vies au maximum !\p"
	.string "J'espère que tu en feras autant !$"

MoveTutor_Text_DynamicPunchTeach:
	.string "I can't do this anymore!\p"
	.string "It's utterly hopeless!\p"
	.string "I'm a FIGHTING-type TRAINER,\n"
	.string "so I can't win at the SAFFRON GYM\l"
	.string "no matter how hard I try!\p"
	.string "Argh! Punch! Punch! Punch!\n"
	.string "Punch! Punch! Punch!\p"
	.string "What, don't look at me that way!\n"
	.string "I'm only hitting the ground!\p"
	.string "Or do you want me to teach your\n"
	.string "POKéMON DYNAMICPUNCH?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Mince ! Tu te moques de moi aussi ?\n"
	.string "Coup de poing ! Coup de poing ! Coup de poing !$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "Quoi ? Tu le fais ? Tu es quelqu'un de bien !\n"
	.string "Quel POKéMON dois-je enseigner ?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "Je veux que tu gagnes à l'ARÈNE de SAFRANIA\n"
	.string "en utilisant cette DYNAMOPOING !$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Soupir…\p"
	.string "Le CHAMPION d'ARÈNE d'ARGENTA\n"
	.string "est vraiment adorable.\p"
	.string "Mais ça veut dire que j'ai beaucoup\n"
	.string "de rivales pour son attention.\p"
	.string "Il a du charme avec DAMOCLES.\n"
	.string "Je n'ai même pas réussi à attirer\p"
	.string "son regard.\n"
	.string "S'il te plaît, laisse-moi apprendre DAMOCLES à ton POKéMON !$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh…\n"
	.string "Même toi, tu m'as rejeté…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "OK, quel POKéMON dois-je enseigner\n"
	.string "DAMOCLES ?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "Je ne vivrai plus pour l'amour !\n"
	.string "Je vais devenir dur !$"

MoveTutor_Text_ExplosionTeach:
	.string "I don't intend to be going nowhere\n"
	.string "fast in the sticks like this forever.\p"
	.string "You watch me, I'll get out to the city\n"
	.string "and become a huge hit.\p"
	.string "Seriously, I'm going to cause\n"
	.string "a huge EXPLOSION of popularity!\p"
	.string "If you overheard that, I'll happily\n"
	.string "teach EXPLOSION to your POKéMON!$"

MoveTutor_Text_ExplosionDeclined:
	.string "Gaah ! Tu me refuses parce que\n"
	.string "je vis à la campagne ?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Très bien ! Une EXPLOSION, ça sera !\n"
	.string "Quel POKéMON veut exploser ?$"

MoveTutor_Text_ExplosionTaught:
	.string "Depuis longtemps, j'apprends aux POKéMON\n"
	.string "à utiliser EXPLOSION, mais je n'ai pas encore\l"
	.string "déclenché ma propre EXPLOSION…\p"
	.string "Peut-être que au fond de moi,\n"
	.string "je préfère rester ici…$"
