gText_ObtainedTheItem::
	.string "Tu as obtenu {STR_VAR_2} !$"

gText_TheBagIsFull::
	.string "Le SAC est plein…$"

gText_PutItemInPocket::
	.string "{PLAYER} a rangé {STR_VAR_2}\n"
	.string "dans la POCHE {STR_VAR_3}.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} a trouvé {STR_VAR_2} !$"

gText_TooBadBagIsFull::
	.string "Dommage !\n"
	.string "Le SAC est plein…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} a rangé {STR_VAR_2}\n"
	.string "dans le SAC.$"

gText_ObtainedTheDecor::
	.string "Tu as obtenu {STR_VAR_2} !$"

gText_NoRoomLeftForAnother::
	.string "Dommage ! Il n'y a plus de place pour\n"
	.string "un autre {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "Le {STR_VAR_2} a été transféré\n"
	.string "au PC.$"

gText_PutItemInPC::
	.string "{PLAYER} a rangé {STR_VAR_2}\n"
	.string "dans le PC car le Sac est plein.$"

gText_TooBadBagAndPCAreFull::
	.string "Dommage !\n"
	.string "Le SAC et le PC sont pleins…$"
