gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} a été envoyé sur\n"
	.string "le PC de QUELQU'UN.\p"
	.string "Il a été placé dans le\n"
	.string "BOÎTE « {STR_VAR_1} ».$"

gText_PkmnTransferredBillsPC::
	.string "{STR_VAR_2} a été envoyé sur\n"
	.string "le PC de PIERRE.\p"
	.string "Il a été placé dans le\n"
	.string "BOÎTE « {STR_VAR_1} ».$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "La BOÎTE « {STR_VAR_3} » sur le PC de\n"
	.string "QUELQU'UN était pleine.\p"
	.string "{STR_VAR_2} a été transféré dans la\n"
	.string "BOÎTE « {STR_VAR_1} ».$"

gText_PkmnTransferredBillsPCBoxFull::
	.string "La BOÎTE « {STR_VAR_3} » sur le PC de\n"
	.string "BILL était pleine.\p"
	.string "{STR_VAR_2} a été transféré dans la\n"
	.string "BOÎTE « {STR_VAR_1} ».$"

gText_NoMoreRoomForPokemon::
	.string "Il n'y a plus de place pour les POKéMON !\p"
	.string "Les BOÎTES POKéMON sont pleines et\n"
	.string "ne peuvent plus en accepter !$"

gText_NicknameThisPokemon::
	.string "Veux-tu donner un surnom\n"
	.string "à ce {STR_VAR_1} ?$"
