gText_WouldYouLikeToRestYourPkmn::
	.string "Bonjour et bienvenue au\n"
	.string "CENTRE POKéMON.\p"
	.string "Nous restaurons tes POKéMON fatigués\n"
	.string "à pleine santé.\p"
	.string "Veux-tu faire reposer tes POKéMON ?$"

gText_IllTakeYourPkmn::
	.string "OK, je prends ton POKéMON\n"
	.string "quelques secondes.$"

gText_RestoredPkmnToFullHealth::
	.string "Merci d'avoir patienté.\p"
	.string "Nous avons soigné tes POKéMON\n"
	.string "à fond.$"

gText_WeHopeToSeeYouAgain::
	.string "Nous espérons te revoir bientôt !$"

gText_WelcomeCutShort::
	.string "Bonjour, et bienvenue au\n"
	.string "CENTRE POKéMON. Nous\p"
	.string "restaurons tes POKéMON\n"
	.string "fatigués en pleine\p"
	.string "forme. Tu veux…$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several TRAINERS with\n"
	.string "a SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first TRAINER I've ever\l"
	.string "seen with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your POKéMON!$"

gText_YouWantTheUsual::
	.string "Je suis ravie de te voir, {PLAYER} !\n"
	.string "Tu veux comme d'habitude, n'est-ce pas ?$"

gText_IllTakeYourPkmn2::
	.string "OK, je prends ton POKéMON\n"
	.string "quelques secondes.$"

gText_ThankYouForWaiting::
	.string "Merci d'avoir attendu.$"

gText_WeHopeToSeeYouAgain2::
	.string "Nous espérons te revoir bientôt !$"

gText_PkmnCenterChallenge_NoVisitsLeft:: @ tx_difficulty_challenge
    .string "Sorry, but you are playing with\n"
    .string "the POKéCENTER challenge!\p"
    .string "Good luck!{PAUSE_UNTIL_PRESS}$"
