gText_WouldYouLikeToRestYourPkmn::
	.string "Bonjour et bienvenue au\n"
	.string "CENTRE POKéMON.\p"
	.string "Nous restaurons tes POKéMON fatigués\n"
	.string "à pleine santé.\p"
	.string "Veux-tu faire reposer tes POKéMON ?$"

gText_IllTakeYourPkmn::
	.string "OK, je prends ton POKéMON\n"
	.string "quelques secondes.$"

gText_RestoredPkmnToFullHealth::
	.string "Merci d'avoir patienté.\p"
	.string "Nous avons soigné tes POKéMON\n"
	.string "à fond.$"

gText_WeHopeToSeeYouAgain::
	.string "Nous espérons te revoir bientôt !$"

gText_WelcomeCutShort::
	.string "Bonjour, et bienvenue au\n"
	.string "CENTRE POKéMON. Nous\p"
	.string "restaurons tes POKéMON\n"
	.string "fatigués en pleine\p"
	.string "forme. Tu veux…$"

gText_NoticesGoldCard::
	.string "Th-th-cette carte…\n"
	.string "Pourrait-ce être…\p"
	.string "La CARTE OR ?!\n"
	.string "Oh, la couleur dorée\p"
	.string "est brillante !\n"
	.string "Les quatre étoiles\l"
	.string "semblent scintiller !\l"
	.string "Je n'en ai vu qu'une\p"
	.string "poignée de ma vie !\n"
	.string "Tu es vraiment chanceux !$"

gText_YouWantTheUsual::
	.string "Je suis ravie de te voir, {PLAYER} !\n"
	.string "Tu veux comme d'habitude, n'est-ce pas ?$"

gText_IllTakeYourPkmn2::
	.string "OK, je prends ton POKéMON\n"
	.string "quelques secondes.$"

gText_ThankYouForWaiting::
	.string "Merci d'avoir attendu.$"

gText_WeHopeToSeeYouAgain2::
	.string "Nous espérons te revoir bientôt !$"

gText_PkmnCenterChallenge_NoVisitsLeft:: @ tx_difficulty_challenge
    .string "Sorry, but you are playing with\n"
    .string "the POKéCENTER challenge!\p"
    .string "Good luck!{PAUSE_UNTIL_PRESS}$"
