gBirchDexRatingText_GoFindMrPokemon::
	.string "PROF.ORME : Ah, {PLAYER}{KUN} !\p"
	.string "As-tu trouvé la maison de M. POKéMON ?\n"
	.string "Elle est sur la ROUTE 30,\p"
	.string "tu ne peux pas la rater !$"

gBirchDexRatingText_Robbery::
	.string "PROF. ORME : {PLAYER}{KUN} !\p"
	.string "Viens vite ! Quelque chose\n"
	.string "de terrible s'est passé !$"

gBirchDexRatingText_AreYouCurious::
	.string "PROF.ORME : Ah, {PLAYER}{KUN} !\p"
	.string "Tu es curieux de savoir comment ton\n"
	.string "POKéDEX progresse ?$"

gBirchDexRatingText_Cancel::
	.string "Hm ? Oh, tu n'as pas attrapé assez\n"
	.string "de POKéMON pour que ça en vaille la peine.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm…\p"
	.string "Alors, tu as vu {STR_VAR_1} POKéMON,\n"
	.string "et tu en as attrapé {STR_VAR_2}…$"

gBirchDexRatingText_LessThan10::
	.string "Va davantage dans les herbes hautes et cherche\n"
	.string "les POKéMON plus attentivement.$"

gBirchDexRatingText_LessThan20::
	.string "Je suppose que tu commences à comprendre.\n"
	.string "Mais ça devient plus dur à partir d'ici.$"

gBirchDexRatingText_LessThan30::
	.string "Certains POKéMON n'apparaissent que dans\n"
	.string "certaines zones.\l"
	.string "Il faut être persévérant.$"

gBirchDexRatingText_LessThan40::
	.string "Eh bien, il pourrait y en avoir plus,\n"
	.string "mais ça ressemble de plus en plus à\l"
	.string "un POKéDEX maintenant.$"

gBirchDexRatingText_LessThan50::
	.string "Ça avance plutôt bien.\n"
	.string "Continue tes efforts.$"

gBirchDexRatingText_LessThan60::
	.string "Tu utilises des CANNES ?\n"
	.string "Il y a beaucoup de POKéMON dans la mer.$"

gBirchDexRatingText_LessThan70::
	.string "Au lieu de juste attraper des POKéMON,\n"
	.string "pourquoi ne pas aussi les faire évoluer ?$"

gBirchDexRatingText_LessThan80::
	.string "Ça va être un\n"
	.string "fantastique POKéDEX.\l"
	.string "C'est le sentiment que j'ai.$"

gBirchDexRatingText_LessThan90::
	.string "Tu en as collecté autant…\n"
	.string "Ton talent est remarquable !$"

gBirchDexRatingText_LessThan100::
	.string "Tu es déjà allé au PARC SAFARI ?\p"
	.string "On dit qu'il y a des POKéMON qu'on\n"
	.string "ne peut attraper que là-bas.$"

gBirchDexRatingText_LessThan110::
	.string "Tu as enfin atteint\n"
	.string "la barre des 100 espèces.\p"
	.string "C'est un POKéDEX impressionnant !$"

gBirchDexRatingText_LessThan120::
	.string "Il pourrait y avoir des POKéMON qu'on peut\n"
	.string "trouver avec FORCE.$"

gBirchDexRatingText_LessThan130::
	.string "J'ai entendu parler de POKéMON qui évoluent\n"
	.string "quand ils aiment vraiment leur\l"
	.string "DRESSEUR.$"

gBirchDexRatingText_LessThan140::
	.string "J'ai entendu parler de POKéMON qui évoluent\n"
	.string "quand ils aiment vraiment leur\l"
	.string "DRESSEUR.$"

gBirchDexRatingText_LessThan150::
	.string "Je n'avais aucune idée qu'il y avait autant\n"
	.string "d'espèces de POKéMON dans la région\l"
	.string "de JOHTO.$"

gBirchDexRatingText_LessThan160::
	.string "À l'occasion, des POKéMON apparaissent\n"
	.string "en grand nombre, comme des épidémies.\p"
	.string "Ne rate pas des occasions\n"
	.string "comme celles-là.$"

gBirchDexRatingText_LessThan170::
	.string "On peut avoir une très bonne idée des\n"
	.string "POKéMON de la région de JOHTO\l"
	.string "en parcourant ton POKéDEX.$"

gBirchDexRatingText_LessThan180::
	.string "Je dirais que tu qualifies déjà comme\n"
	.string "PROFESSEUR POKéMON, et un bon\l"
	.string "en plus !$"

gBirchDexRatingText_LessThan190::
	.string "Avec un POKéDEX aussi complet,\n"
	.string "tu es un vrai professionnel !$"

gBirchDexRatingText_LessThan200::
	.string "Tu es tout près de compléter\n"
	.string "ce POKéDEX.\l"
	.string "Je le sens dans mes os !$"

gBirchDexRatingText_DexCompleted::
	.string "Félicitations !\n"
	.string "Ton POKéDEX est complet !$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmhm...\n"
	.string "À l'échelle nationale...\p"
	.string "Tu as vu {STR_VAR_1} POKéMON,\n"
	.string "et tu en as attrapé {STR_VAR_2}...$"

gBirchDexRatingText_CaughtAllNational::
	.string "Hmhm… À l'échelle nationale…\n"
	.string "Tu as vu {STR_VAR_1}\p"
	.string "POKéMON, et tu en\n"
	.string "as attrapé {STR_VAR_2}… C'est\p"
	.string "incroyable, {PLAYER} ! Tu\p"
	.string "as complété le POKéDEX\n"
	.string "NATIONAL ! Félicitations !$"
