Questionnaire_Text_FillOut::
	.string "Il y a un questionnaire.\n"
	.string "Veux-tu le remplir ?$"

Questionnaire_Text_ThankYou::
	.string "Merci d'avoir pris le\n"
	.string "temps de remplir notre\p"
	.string "questionnaire. Vos commentaires serviront\n"
	.string "de référence future.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "Oh, bonjour !\n"
	.string "Tu connais ces mots ?\p"
	.string "Ça veut dire que tu dois connaître\n"
	.string "le CADEAU MYSTÈRE.\p"
	.string "À partir de maintenant, tu devrais\n"
	.string "recevoir des CADEAUX MYSTÈRE !$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "Une fois la partie sauvegardée, tu peux\n"
	.string "accéder au CADEAU MYSTÈRE.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "Oh, bonjour !\n"
	.string "Tu connais ces mots ?\p"
	.string "Ça veut dire que tu connais\n"
	.string "l'ÉVÉNEMENT MYSTÈRE.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "Une fois la partie sauvegardée, tu peux\n"
	.string "accéder à l'ÉVÉNEMENT MYSTÈRE.$"

MysteryGift_Text_TheresATicketForYou::
	.string "Merci d'utiliser le système\n"
	.string "ÉVÉNEMENT MYSTÈRE.\p"
	.string "Tu dois être {PLAYER}.\n"
	.string "Il y a un ticket pour toi.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "Il semble être destiné au\n"
	.string "port de NÉNUCRIQUE.\p"
	.string "Pourquoi ne pas essayer pour voir\n"
	.string "de quoi il s'agit ?$"
