	.align 2
gText_ConfirmSave::
	.string "Veux-tu sauvegarder la partie ?$"

gText_AlreadySavedFile::
	.string "Il y a déjà une sauvegarde.\n"
	.string "Est-il acceptable de l'écraser ?$"

gText_SavingDontTurnOff::
	.string "SAUVEGARDE…\n"
	.string "NE PAS ÉTEINDRE.$"

gText_PlayerSavedGame::
	.string "{PLAYER} a sauvegardé la partie.$"

gText_DifferentSaveFile::
	.string "ATTENTION !\p"
	.string "Il y a une autre sauvegarde de\n"
	.string "partie déjà enregistrée.\p"
	.string "Si tu sauvegardes maintenant,\n"
	.string "l'aventure de l'autre fichier,\l"
	.string "y compris les objets et les\p"
	.string "POKéMON, sera entièrement perdue.\n"
	.string "Es-tu sûr de vouloir sauvegarder et écraser l'autre fichier ?$"

gText_SaveError::
	.string "Erreur de sauvegarde.\p"
	.string "Veuillez changer la\n"
	.string "mémoire de secours.$"

gText_SavingDontTurnOffPower::
	.string "SAUVEGARDE…\n"
	.string "NE PAS ÉTEINDRE.$"
