SecretBase_Text_Trainer0Intro:
	.string "Tu as déjà créé une BASE SECRÈTE ?\p"
	.string "Je suis allé partout avant de\n"
	.string "choisir cet endroit.\p"
	.string "Puisque tu es déjà là,\n"
	.string "veux-tu te battre ?$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "OK !\n"
	.string "On arrive !$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "Hein ?\n"
	.string "Oh, tu ne peux pas maintenant…$"

SecretBase_Text_Trainer0Defeated::
	.string "Aaaargh ! Tu es trop fort !\n"
	.string "Pour ce qui est de ma défaite… Garde le secret, s'il te plaît !$"

SecretBase_Text_Trainer0PostBattle:
	.string "Qu'est-ce que tu penses de ma BASE SECRETE ?\n"
	.string "Reviens me voir demain.$"

SecretBase_Text_Trainer0PreChampion:
	.string "Tu as déjà créé une BASE\p"
	.string "SECRÈTE ? J'ai cherché partout avant\n"
	.string "de choisir cet endroit. N'hésite\p"
	.string "pas à traîner ici !$"

SecretBase_Text_Trainer5Intro:
	.string "Il y a plein d'endroits où\n"
	.string "tu peux créer une BASE SECRÈTE.\p"
	.string "Mais j'aime le mieux cet endroit.\n"
	.string "Tu ne trouves pas qu'il est sympa ?\p"
	.string "Oh, veux-tu te battre ?$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "Allez, c'est parti !$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "Oh…\n"
	.string "Tu ne peux pas maintenant, d'accord.$"

SecretBase_Text_Trainer5Defeated::
	.string "Hmmm… C'est notre défaite…\n"
	.string "Mais ne le dis à personne !\l"
	.string "C'est un secret confidentiel !$"

SecretBase_Text_Trainer5PostBattle:
	.string "Si tu es de nouveau dans le coin,\n"
	.string "j'espère que tu me rendras visite.$"

SecretBase_Text_Trainer5PreChampion:
	.string "Il y a plein d'endroits pour\n"
	.string "faire une BASE SECRÈTE. Mais je\p"
	.string "préfère cet endroit. Tu ne trouves\n"
	.string "pas qu'il est sympa ?$"

SecretBase_Text_Trainer1Intro:
	.string "C'est un endroit populaire.\n"
	.string "Il est toujours pris.\p"
	.string "Oh ! Tu pensais aussi\n"
	.string "prendre cette place ?\p"
	.string "Je te dis quoi, tu peux avoir cette\n"
	.string "place si tu arrives à me battre.$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "D'accord !\n"
	.string "Je vais défendre ma BASE SECRÈTE !$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "Hein ? C'est ça ?\n"
	.string "Cet endroit ne t'intéresse pas ?$"

SecretBase_Text_Trainer1Defeated::
	.string "Je ne peux plus continuer !\n"
	.string "Je me rends !$"

SecretBase_Text_Trainer1PostBattle:
	.string "OK, quand je déménagerai un jour,\n"
	.string "ce lieu sera à toi !$"

SecretBase_Text_Trainer1PreChampion:
	.string "C'est un endroit populaire.\n"
	.string "Il est toujours occupé.\p"
	.string "J'ai attendu longtemps qu'il se libère.\n"
	.string "J'ai enfin pu l'utiliser !$"

SecretBase_Text_Trainer6Intro:
	.string "Bienvenue dans mon LABORATOIRE POKéMON. Je\p"
	.string "mène des recherches sur les combats\n"
	.string "en secret. Tu veux voir à\p"
	.string "quel point je suis fort ?$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "Je vais tout donner !$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "Oh.\n"
	.string "Une autre fois, alors !$"

SecretBase_Text_Trainer6Defeated::
	.string "Hmm… J'ai encore beaucoup à apprendre.\n"
	.string "Il faut que j'étudie davantage.$"

SecretBase_Text_Trainer6PostBattle:
	.string "Merci d'avoir combattu avec moi.\n"
	.string "Reviens demain, s'il te plaît.$"

SecretBase_Text_Trainer6PreChampion:
	.string "Bienvenue dans mon LABORATOIRE POKéMON.\p"
	.string "Je mène des recherches sur les combats\n"
	.string "en secret.$"

SecretBase_Text_Trainer2Intro:
	.string "Une grande demeure, c'est bien, mais j'aime\n"
	.string "ce genre d'endroit davantage.\p"
	.string "J'aime ça parce que toutes sortes de gens\n"
	.string "viennent me voir.\p"
	.string "Alors, tu veux un combat ?$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "C'est ça !$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "Quand tu seras prêt, fais-moi signe !$"

SecretBase_Text_Trainer2Defeated::
	.string "Snif ! Battu !\n"
	.string "Mais c'est toujours amusant de se battre !$"

SecretBase_Text_Trainer2PostBattle:
	.string "Bon, bref, je vais acheter des\n"
	.string "décorations et du mobilier.\p"
	.string "Je veux que ma BASE SECRÈTE soit\n"
	.string "un endroit où les autres prennent plaisir.$"

SecretBase_Text_Trainer2PreChampion:
	.string "Un grand manoir, c'est bien, mais\n"
	.string "je préfère ce genre d'endroit. J'aime\p"
	.string "ça parce que toutes sortes\n"
	.string "de gens viennent me voir.$"

SecretBase_Text_Trainer7Intro:
	.string "J'adore faire du shopping pour des\n"
	.string "décorations et des meubles.\p"
	.string "J'aime aussi élever des POKéMON\n"
	.string "tout autant.\p"
	.string "Si tu veux bien, veux-tu te battre\n"
	.string "contre mes POKéMON ?$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "Merci.\n"
	.string "On commence ?$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "Oh.\n"
	.string "Comme c'est décevant…$"

SecretBase_Text_Trainer7Defeated::
	.string "J'abandonne…$"

SecretBase_Text_Trainer7PostBattle:
	.string "C'était pour le plaisir !\n"
	.string "Je vais faire du shopping maintenant.$"

SecretBase_Text_Trainer7PreChampion:
	.string "J'adore acheter des décorations\n"
	.string "et des meubles.\p"
	.string "J'aime aussi élever des POKéMON\n"
	.string "tout autant.$"

SecretBase_Text_Trainer3Intro:
	.string "Certaines personnes font leurs BASES SECRÈTES dans\n"
	.string "des endroits difficiles à trouver.\l"
	.string "Veulent-elles juste rester discrètes ?\p"
	.string "Mais puisque tu m'as trouvé, que dirais-tu d'un\n"
	.string "combat ?$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "Je ne vais pas tomber facilement !$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "Oh… Tu es peut-être fatigué d'avoir\n"
	.string "cherché cet endroit ?$"

SecretBase_Text_Trainer3Defeated::
	.string "J'ai été battu…$"

SecretBase_Text_Trainer3PostBattle:
	.string "Où est ta BASE SECRÈTE ?\n"
	.string "Je devrais venir te rendre visite.$"

SecretBase_Text_Trainer3PreChampion:
	.string "Certaines personnes font leurs BASES SECRÈTES dans\n"
	.string "des endroits difficiles à trouver.\l"
	.string "Veulent-elles juste rester discrètes ?$"

SecretBase_Text_Trainer8Intro:
	.string "Les gens m'ont dit qu'on peut obtenir\n"
	.string "des décorations de plusieurs façons.\p"
	.string "On devrait faire une course pour voir qui\n"
	.string "peut obtenir les plus belles décorations et meubles !\p"
	.string "En attendant, tu veux te battre ?$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "C'est ma BASE SECRÈTE.\n"
	.string "Je ne peux pas perdre !$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "Je me battrai avec toi quand tu veux.$"

SecretBase_Text_Trainer8Defeated::
	.string "Hein ?\n"
	.string "Je viens de perdre ?$"

SecretBase_Text_Trainer8PostBattle:
	.string "Je ne perdrai pas au niveau des\n"
	.string "décorations. Reviens me voir !$"

SecretBase_Text_Trainer8PreChampion:
	.string "On m'a dit qu'on peut obtenir des\n"
	.string "décorations de plusieurs façons.\p"
	.string "On devrait faire une course pour voir\n"
	.string "qui peut obtenir les plus beaux décorations et meubles !$"

SecretBase_Text_Trainer4Intro:
	.string "J'ai trouvé un endroit que j'aimais, et je l'ai\n"
	.string "aménagé avec mes décorations préférées.\p"
	.string "J'élève mon POKéMON préféré et je\n"
	.string "deviens plus fort avec lui.\p"
	.string "C'est ce que je fais.\n"
	.string "Tu veux te battre avec moi ?$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "Montre-moi de quoi tu es capable !$"

SecretBase_Text_Trainer4DeclineBattle:
	.string "Je suppose qu'il y a des moments\n"
	.string "où on n'est pas d'humeur.$"

SecretBase_Text_Trainer4Defeated::
	.string "Je sais exactement de quoi tu es fait maintenant.$"

SecretBase_Text_Trainer4PostBattle:
	.string "On peut tous devenir plus forts.\n"
	.string "Continuons comme ça !$"

SecretBase_Text_Trainer4PreChampion:
	.string "J'ai trouvé un endroit qui me plaisait,\n"
	.string "et je l'ai décoré avec mes décorations préférées.\p"
	.string "J'élève mes POKéMON préférés et je\n"
	.string "me renforce avec eux.\p"
	.string "Chaque jour est un grand jour.$"

SecretBase_Text_Trainer9Intro:
	.string "On peut apprendre beaucoup sur le\n"
	.string "goût et le sens des gens\l"
	.string "par les décorations qu'ils ont et\l"
	.string "comment ils les exposent. Que penses-tu\p"
	.string "de mon goût ? Tu es\n"
	.string "sans voix ? Tu veux voir\p"
	.string "mon goût en combat ?$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "Pas de retenue !$"

SecretBase_Text_Trainer9DeclineBattle:
	.string "Je serai heureux de démontrer mon style\n"
	.string "à tout moment.$"

SecretBase_Text_Trainer9Defeated::
	.string "Tu es suprêmement talentueux !\n"
	.string "Ta puissance semble illimitée…$"

SecretBase_Text_Trainer9PostBattle:
	.string "Qu'as-tu pensé de mon style ?\n"
	.string "Je vais continuer à le peaufiner !$"

SecretBase_Text_Trainer9PreChampion:
	.string "On peut en apprendre beaucoup sur le goût\n"
	.string "et le sens des gens par les types de\l"
	.string "décorations qu'ils ont, et comment ils\l"
	.string "les disposent.\p"
	.string "Que penses-tu de mon goût ?\n"
	.string "Tu es sans voix ?$"
