ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "Tu comptes aller au fond\n"
	.string "là-dedans ?\p"
	.string "Tu pourrais m'apporter du\n"
	.string "SEL TRÉFONDS et des COQUILLETRÉFONDS ?\p"
	.string "Je peux te fabriquer quelque chose de bien si\n"
	.string "tu m'apportes les ingrédients.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "Si tu m'apportes quatre SELS TREFONDS et quatre\n"
	.string "COQUES TREFONDS chacun,\l"
	.string "je peux te fabriquer une GRELOTZOCO…\p"
	.string "Tu peux obtenir ces ingrédients\n"
	.string "chaque jour.$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "Oh, hé ! SEL AMARYLLE et\n"
	.string "COQUILLAMARYLLE ! Et en quantité !\p"
	.string "Tu veux que je te\n"
	.string "fasse une CLOCHETTE avec ?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "Très bien ! Je te fabrique une\n"
	.string "GRELLOTTE COQUE tout de suite.\p"
	.string "... ... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ... ...\p"
	.string "Voilà ! C'est fini !$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "Fais tenir ça à un POKéMON.\n"
	.string "Il va adorer, c'est certain.\p"
	.string "Le carillon du GRELOT COQUE…\n"
	.string "C'est tout simplement sublime !\p"
	.string "Tu peux en trouver les ingrédients chaque jour,\n"
	.string "alors je peux t'en fabriquer d'autres.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "Oh… C'est ça…\n"
	.string "Je voulais fabriquer une GRELOTZOCO…$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "Tu n'as pas de place dans\n"
	.string "ton SAC pour que je la\p"
	.string "fabrique. Fais de la place\n"
	.string "et reviens pour une CLOCHETTE.$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "Il y avait du SEL ROCHE ici.\n"
	.string "Mais il n'y a plus rien maintenant.$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "Il y avait un COQUILLEGROT ici.\n"
	.string "Mais il n'y a plus rien maintenant.$"
