Route102_Text_CalvinIntro:
	.string "Si tu as des POKéMON avec toi, tu es\n"
	.string "un DRESSEUR POKéMON officiel !\l"
	.string "Tu ne peux pas refuser mon défi !$"

Route102_Text_CalvinDefeated:
	.string "Arrgh, j'ai perdu…\n"
	.string "J'aurais dû mieux les entraîner…$"

Route102_Text_CalvinPostBattle:
	.string "Écoute-moi. Si tu es fort,\n"
	.string "tu aurais dû me le dire avant !$"

Route102_Text_CalvinRegister:
	.string "Je me suis entraîné dur depuis\n"
	.string "la dernière fois qu'on s'est vus.\p"
	.string "J'aimerais te combattre à nouveau, alors peux-tu\n"
	.string "m'enregistrer dans ton POKéNAV ?$"

Route102_Text_CalvinRegisterShort:
	.string "J'aimerais te combattre à nouveau, alors\n"
	.string "peux-tu m'enregistrer dans ton POKéNAV ?$"

Route102_Text_CalvinRematchIntro:
	.string "Depuis que tu m'as battu, j'ai désespérément\n"
	.string "entraîné mes POKéMON.\l"
	.string "Tu ne peux pas refuser mon défi !$"

Route102_Text_CalvinRematchDefeated:
	.string "Arrgh, j'ai perdu…\n"
	.string "Ma méthode d'entraînement n'est-elle pas bonne ?$"

Route102_Text_CalvinRematchPostBattle:
	.string "Si tu vas devenir plus fort,\n"
	.string "je deviendrai plus fort aussi.$"

Route102_Text_AllenIntro:
	.string "Tu viens de devenir DRESSEUR ?\n"
	.string "On est tous les deux débutants !$"

Route102_Text_AllenDefeated:
	.string "Je t'ai appelé parce que je pensais\n"
	.string "pouvoir te battre…$"

Route102_Text_AllenPostBattle:
	.string "Je n'ai pas encore gagné une seule fois…\n"
	.string "J'aimerais bien gagner bientôt…$"

Route102_Text_RickIntro:
	.string "Hahah ! Nos regards se sont croisés !\n"
	.string "Je t'affronte avec mes POKéMON INSECTE !$"

Route102_Text_RickDefeated:
	.string "Aïe ! À terre !$"

Route102_Text_RickPostBattle:
	.string "Si tu croises le regard d'un DRESSEUR,\n"
	.string "tu dois le défier ! C'est la règle !$"

Route102_Text_TianaIntro:
	.string "Je vais continuer à gagner et viser\n"
	.string "à devenir le meilleur DRESSEUR.\p"
	.string "Aide-moi à faire avancer ma carrière !$"

Route102_Text_TianaDefeated:
	.string "J'ai fini par faire avancer ta carrière…$"

Route102_Text_TianaPostBattle:
	.string "Pour continuer à monter victorieusement,\n"
	.string "je vois qu'il faut que j'attrape plus de POKéMON.$"

Route103_Text_DaisyIntro:
	.string "As-tu senti l'attrait de notre\n"
	.string "parfum apaisant pour l'âme ?$"

Route103_Text_DaisyDefeated:
	.string "Tu n'as pas été égaré par notre parfum…$"

Route103_Text_DaisyPostBattle:
	.string "L'aromathérapie est une forme de guérison\n"
	.string "mentale par les fragrances.$"

Route103_Text_AmyIntro:
	.string "AMY : Je suis AMY.\n"
	.string "Et voici ma petite sœur LIV.\l"
	.string "On combat ensemble !$"

Route103_Text_AmyDefeated:
	.string "AMY : Oh-oh, on a perdu.$"

Route103_Text_AmyPostBattle:
	.string "AMY : Il faut penser à toutes\n"
	.string "sortes de choses quand on combat\l"
	.string "contre deux DRESSEURS.$"

Route103_Text_AmyNotEnoughPokemon:
	.string "AMY : Oh-oh, tu n'as qu'un seul\n"
	.string "POKéMON avec toi.\l"
	.string "Tu ne peux pas nous combattre comme ça.$"

Route103_Text_LivIntro:
	.string "LIV : On se bat ensemble comme\n"
	.string "une seule équipe.$"

Route103_Text_LivDefeated:
	.string "LIV : Oh, on a perdu, grande sœur…$"

Route103_Text_LivPostBattle:
	.string "LIV : On travaille parfaitement ensemble,\n"
	.string "ma grande sœur et moi…\p"
	.string "Mais on a quand même perdu…$"

Route103_Text_AmyLivRegister:
	.string "LIV : Vraiment, on est bien meilleurs…\n"
	.string "C'est vrai ! On te montrera la prochaine fois !$"

Route103_Text_LivNotEnoughPokemon:
	.string "LIV : Si tu veux nous combattre,\n"
	.string "tu dois avoir deux POKéMON !\l"
	.string "Ce ne serait pas juste sinon !$"

Route103_Text_AmyRematchIntro:
	.string "AMY : Je suis AMY.\n"
	.string "Et voici ma petite sœur LIV.\l"
	.string "On combat ensemble !$"

Route103_Text_AmyRematchDefeated:
	.string "AMY : Aww, mince !\n"
	.string "On n'a pas pu gagner encore…$"

Route103_Text_AmyRematchPostBattle:
	.string "AMY : Il faut penser à toutes\n"
	.string "sortes de choses quand on combat\l"
	.string "contre deux DRESSEURS.$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "AMY : Oh-oh, tu n'as qu'un seul\n"
	.string "POKéMON avec toi.\l"
	.string "Tu ne peux pas nous combattre comme ça.$"

Route103_Text_LivRematchIntro:
	.string "LIV : On se bat ensemble comme\n"
	.string "une seule équipe.$"

Route103_Text_LivRematchDefeated:
	.string "LIV : Awww, on a encore perdu…\n"
	.string "Grande sœur…$"

Route103_Text_LivRematchPostBattle:
	.string "LIV : On travaille parfaitement ensemble,\n"
	.string "moi et ma grande sœur…\p"
	.string "Mais pourquoi on a encore perdu ?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "LIV : Si tu veux nous combattre, tu\n"
	.string "dois avoir deux POKéMON !\l"
	.string "Ce ne serait pas juste sinon !$"

Route103_Text_AndrewIntro:
	.string "Argh ! Ma ligne de pêche est tout emmêlée !\n"
	.string "Je commence à m'énerver !\l"
	.string "Ça y est ! Battons-nous !$"

Route103_Text_AndrewDefeated:
	.string "Gah ! Perdu !\n"
	.string "Je suis encore plus énervé maintenant !$"

Route103_Text_AndrewPostBattle:
	.string "Gah, je bouillonne encore…\n"
	.string "Grrrrr…$"

Route103_Text_MiguelIntro:
	.string "Mon POKéMON est délicieusement adorable !\n"
	.string "Ne sois pas timide—je vais te le montrer !$"

Route103_Text_MiguelDefeated:
	.string "Oh, mon Dieu !\n"
	.string "Mes chers POKéMON !$"

Route103_Text_MiguelPostBattle:
	.string "Mon adorable POKéMON est mignon\n"
	.string "même quand il est K.O. !$"

Route103_Text_MiguelRegister:
	.string "Je te ferai revenir voir\n"
	.string "mes adorables POKéMON !$"

Route103_Text_MiguelRematchIntro:
	.string "Salut, toi ! Mon adorable POKéMON\n"
	.string "est devenu encore plus mignon !$"

Route103_Text_MiguelRematchDefeated:
	.string "Oh !\n"
	.string "Mon cher POKéMON !$"

Route103_Text_MiguelRematchPostBattle:
	.string "Plus je passe du temps avec lui,\n"
	.string "plus mon POKéMON devient adorable.$"

Route103_Text_PeteIntro:
	.string "À cette distance…\n"
	.string "Tu devrais juste nager !$"

Route103_Text_PeteDefeated:
	.string "Oh, pas mal du tout !$"

Route103_Text_PetePostBattle:
	.string "Oh, je comprends maintenant d'où\n"
	.string "tu viens. Si j'avais un\p"
	.string "POKéMON aussi fidèle, je voudrais\n"
	.string "SURF dessus aussi !$"

Route103_Text_IsabelleIntro:
	.string "Regarde où tu vas !\n"
	.string "On va se cogner !$"

Route103_Text_IsabelleDefeated:
	.string "Ouille…$"

Route103_Text_IsabellePostBattle:
	.string "Je suis un mauvais nageur alors je m'entraînais…\n"
	.string "Désolé d'avoir failli te percuter.$"

Route103_Text_RhettIntro:
	.string "Whoa !\n"
	.string "Comment es-tu entré dans un si petit espace ?$"

Route103_Text_RhettDefeated:
	.string "Ouah !\n"
	.string "Ce gamin assure !$"

Route103_Text_RhettPostBattle:
	.string "Tu aimes les espaces exigus\n"
	.string "comme celui-ci ?$"

Route103_Text_MarcosIntro:
	.string "Mon solo de guitare t'a attiré ?$"

Route103_Text_MarcosDefeated:
	.string "Mon one-man show est gâché…$"

Route103_Text_MarcosPostBattle:
	.string "Je jouais de la guitare là où\n"
	.string "il y avait peu de monde, mais\l"
	.string "plein de fans se sont rassemblés. Hé,\p"
	.string "peut-être que je devrais passer pro.$"

Route104_Text_GinaIntro:
	.string "GINA : D'accord, combattons avec\n"
	.string "nos POKéMON !$"

Route104_Text_GinaDefeat:
	.string "GINA : Perdre me contrarie !$"

Route104_Text_GinaPostBattle:
	.string "GINA : Tu es fort !\n"
	.string "On doit encore bien s'entraîner !$"

Route104_Text_GinaNotEnoughMons:
	.string "Oh ? Un seul POKéMON ?\n"
	.string "Alors, on ne se bat pas avec toi.\p"
	.string "Avec un seul POKéMON, il serait\n"
	.string "seul. Ce n'est pas sympa.$"

Route104_Text_MiaIntro:
	.string "MIA : Nous sommes jumelles, alors nous\n"
	.string "combattons ensemble.$"

Route104_Text_MiaDefeat:
	.string "MIA : On s'est battus ensemble, mais\n"
	.string "on a tous les deux perdu…$"

Route104_Text_MiaPostBattle:
	.string "MIA : Nous allons entraîner nos POKéMON\n"
	.string "et devenir forts comme toi.$"

Route104_Text_MiaNotEnoughMons:
	.string "MIA : Tu veux te battre avec\p"
	.string "nous ? C'est non si tu n'as\n"
	.string "pas deux POKéMON avec toi. On\l"
	.string "est trop forts pour toi !$"

Route104_Text_IvanIntro:
	.string "Pourquoi garder le secret ?\n"
	.string "Je suis l'expert des POKéMON EAU !\p"
	.string "Hein ?\n"
	.string "Tu ne me connais pas ?$"

Route104_Text_IvanDefeat:
	.string "Je pensais ne pas être si mauvais, si je\n"
	.string "puis me permettre… Bof…$"

Route104_Text_IvanPostBattle:
	.string "Je me suis trop pris à la pêche.\n"
	.string "J'ai oublié d'entraîner mes POKéMON…$"

Route104_Text_BillyIntro:
	.string "Laisser des empreintes dans le sable,\n"
	.string "c'est tellement amusant !$"

Route104_Text_BillyDefeat:
	.string "Waah ! J'ai du sable dans mes baskets !\n"
	.string "Elles sont toutes granuleuses !$"

Route104_Text_BillyPostBattle:
	.string "Je veux laisser mes empreintes dans\n"
	.string "le sable partout, mais elles\l"
	.string "disparaissent vite…$"

Route104_Text_HaleyIntro:
	.string "Est-ce que je devrais…\n"
	.string "Ou pas ?\p"
	.string "OK, d'accord, je me bats !$"

Route104_Text_HaleyDefeat:
	.string "Je n'aurais pas dû me battre…$"

Route104_Text_HaleyPostBattle:
	.string "Si tu fais face à une\n"
	.string "décision et que tu laisses quelqu'un\l"
	.string "d'autre choisir pour toi, tu le\l"
	.string "regretteras, quel que soit le résultat.$"

Route104_Text_HaleyRegister1:
	.string "T'es fort, mais je devrais t'enregistrer\n"
	.string "dans mon POKéNAV ?\l"
	.string "Peut-être pas...\p"
	.string "OK, d'accord, je t'enregistre !$"

Route104_Text_HaleyRegister2:
	.string "T'es fort, mais je devrais t'enregistrer\n"
	.string "dans mon POKéNAV ?\l"
	.string "Peut-être pas...\p"
	.string "OK, d'accord, je t'enregistre !$"

Route104_Text_HaleyRematchIntro:
	.string "Allez, bats-toi avec moi !$"

Route104_Text_HaleyRematchDefeat:
	.string "Ohh…\n"
	.string "Je pensais pouvoir gagner…$"

Route104_Text_HaleyPostRematch:
	.string "J'ai décidé de me battre, alors\n"
	.string "je peux accepter cette défaite avec grâce.\p"
	.string "Je suis quand même contrariée d'avoir perdu !$"

Route104_Text_WinstonIntro:
	.string "Oh, bien sûr, j'accepte ton défi.\n"
	.string "J'ai beaucoup d'argent.$"

Route104_Text_WinstonDefeat:
	.string "Pourquoi n'ai-je pas pu gagner ?$"

Route104_Text_WinstonPostBattle:
	.string "Il y a des choses que l'argent ne peut pas acheter.\n"
	.string "Ce sont les POKéMON…$"

Route104_Text_WinstonRegister1:
	.string "Hum ?\n"
	.string "Ah, tu as un POKéNAV.\p"
	.string "Je vais t'enregistrer volontiers.\n"
	.string "Après tout, j'ai plein d'argent.$"

Route104_Text_WinstonRegister2:
	.string "Hum ?\n"
	.string "Ah, tu as un POKéNAV.\p"
	.string "Je vais t'enregistrer volontiers.\n"
	.string "Après tout, j'ai plein d'argent.$"

Route104_Text_WinstonRematchIntro:
	.string "Après ma défaite contre toi, j'ai appris\n"
	.string "plein de choses sur les POKéMON.$"

Route104_Text_WinstonRematchDefeat:
	.string "J'ai encore perdu ?\n"
	.string "Pourquoi je n'ai pas pu gagner ?$"

Route104_Text_WinstonPostRematch:
	.string "Je suis fabuleusement riche, mais je n'arrive pas\n"
	.string "à gagner aux POKéMON...\p"
	.string "C'est si profond, le monde des POKéMON...$"

Route104_Text_CindyIntro:
	.string "Nous étions destinés à nous rencontrer.\n"
	.string "Puis-je te demander un combat ?$"

Route104_Text_CindyDefeat:
	.string "Oh là là !$"

Route104_Text_CindyPostBattle:
	.string "« Bonjour » est le début de « au revoir ».\n"
	.string "J'espère qu'on se reverra.$"

Route104_Text_CindyRegister1:
	.string "Bonjour, on se retrouve.\p"
	.string "On dirait qu'on est faits pour se croiser. Enregistrons-\n"
	.string "nous mutuellement dans nos POKéNAVS.$"

Route104_Text_CindyRegister2:
	.string "On devrait commémorer le fait qu'on\n"
	.string "semble attirés l'un vers l'autre.\p"
	.string "Enregistrons-nous mutuellement\n"
	.string "dans nos POKéNAVS.$"

Route104_Text_CindyRematchIntro:
	.string "Bonjour, on se revoit.\n"
	.string "Puis-je te demander un combat ?$"

Route104_Text_CindyRematchDefeat:
	.string "Oh là…\n"
	.string "J'ai fait de mon mieux…$"

Route104_Text_CindyPostRematch:
	.string "« Bonjour » est le début de « au revoir ».\n"
	.string "J'espère qu'on se reverra.$"

Route104_Text_DarianIntro:
	.string "J'ai pêché un POKéMON au look costaud !\p"
	.string "Il a quelque chose de magique !\n"
	.string "Il a l'air vraiment costaud, oui !$"

Route104_Text_DarianDefeat:
	.string "Qu'est-ce que…$"

Route104_Text_DarianPostBattle:
	.string "Hé ! MAGICARPE, tu ne portes vraiment pas\n"
	.string "ton nom, n'est-ce pas ?$"

Route105_Text_FosterIntro:
	.string "Il est censé y avoir un rocher\n"
	.string "mystique par ici.\l"
	.string "Tu sais quelque chose à ce sujet ?$"

Route105_Text_FosterDefeated:
	.string "Je pensais trop à cette pierre,\n"
	.string "alors que mes POKéMON restaient faibles…$"

Route105_Text_FosterPostBattle:
	.string "Je peux passer des heures à regarder\n"
	.string "une belle pierre sans m'ennuyer.$"

Route105_Text_LuisIntro:
	.string "Ouf ! J'ai cru qu'un gamin\n"
	.string "se noyait en te voyant. Tu\p"
	.string "as l'air d'aller bien, alors qu'est-ce\n"
	.string "que tu dis d'un combat ?$"

Route105_Text_LuisDefeated:
	.string "Gloub… Gloub…$"

Route105_Text_LuisPostBattle:
	.string "Si tu te noies, le signal est de\n"
	.string "agiter un bras vers la plage.$"

Route105_Text_DominikIntro:
	.string "Nager dans la mer profonde…\n"
	.string "C'est le top !$"

Route105_Text_DominikDefeated:
	.string "J'ai perdu…\n"
	.string "Je me sens tout bleu…$"

Route105_Text_DominikPostBattle:
	.string "Pourquoi la mer est-elle bleue ?\p"
	.string "J'ai appris ça au MUSÉE de\n"
	.string "POIVRESSE, mais j'ai oublié.$"

Route105_Text_BeverlyIntro:
	.string "Mon corps est plus léger dans l'eau.\n"
	.string "C'est comme si j'avais maigri !$"

Route105_Text_BeverlyDefeated:
	.string "Je flotte…$"

Route105_Text_PostBattle:
	.string "Ton poids corporel est réduit à\n"
	.string "un dixième dans l'eau. Ça ferait\p"
	.string "de moi… Oups ! Je ne\n"
	.string "te dirai pas mon poids !$"

Route105_Text_ImaniIntro:
	.string "Le ciel bleu, bleu…\n"
	.string "La vaste mer…\l"
	.string "C'est si paisible…$"

Route105_Text_ImaniDefeated:
	.string "J'ai perdu pendant que je me prélassais !$"

Route105_Text_ImaniPostBattle:
	.string "Je veux qu'on me dise que c'est relaxant\n"
	.string "d'être avec moi. Hi hi.$"

Route105_Text_AndresIntro:
	.string "Je suis convaincu que la mer nous\n"
	.string "cache des secrets.$"

Route105_Text_AndresDefeated:
	.string "Oui…\n"
	.string "Je ne suis pas doué pour le combat…$"

Route105_Text_AndresPostBattle:
	.string "Je suis sûr qu'il y a plein de secrets à\n"
	.string "découvrir dans les mers du monde.\p"
	.string "Je compte bien tous les trouver !$"

Route105_Text_AndresRegister:
	.string "Hein ? Je suis si faible, mais tu veux\n"
	.string "quand même m'enregistrer dans ton POKéNAV ?$"

Route105_Text_AndresRematchIntro:
	.string "Je t'ai dit que je suis faible…\n"
	.string "Tu es sûr de vouloir faire ça ?$"

Route105_Text_AndresRematchDefeated:
	.string "Oui…\n"
	.string "Je ne pensais pas pouvoir gagner.$"

Route105_Text_AndresRematchPostBattle:
	.string "Je suis faible au combat,\n"
	.string "mais ma soif d'exploration est\p"
	.string "inégalée. Je parcourrai les mers\n"
	.string "du monde entier !$"

Route105_Text_JosueIntro:
	.string "Je suis épuisé de nager.\n"
	.string "Je n'y suis pas habitué.\p"
	.string "J'ai besoin d'un combat pour changer d'air !$"

Route105_Text_JosueDefeated:
	.string "J'ai perdu parce que j'ai combattu en mer.$"

Route105_Text_JosuePostBattle:
	.string "Ouais, pour moi, le ciel convient\n"
	.string "mieux que la mer.$"

Route106_Text_ElliotIntro:
	.string "Tu préfères pêcher dans\n"
	.string "la mer ou dans une rivière ?$"

Route106_Text_ElliotDefeated:
	.string "Comme en pêche en haute mer,\n"
	.string "j'ai perdu de façon spectaculaire !$"

Route106_Text_ElliotPostBattle:
	.string "La pêche, c'est le meilleur que ce soit\n"
	.string "en mer ou en rivière.\l"
	.string "Tu es d'accord avec moi, non ?$"

Route106_Text_ElliotRegister:
	.string "La pêche, c'est génial, mais les combats aussi.\n"
	.string "Si ça ne te dérange pas, on se revoit ?$"

Route106_Text_ElliotRematchIntro:
	.string "J'ai attrapé plein de POKéMON en pêchant.\n"
	.string "Je vais te montrer un combat impressionnant !$"

Route106_Text_ElliotRematchDefeated:
	.string "J'ai encore perdu de façon spectaculaire !$"

Route106_Text_ElliotRematchPostBattle:
	.string "Gagner ou perdre, les POKéMON sont les plus grands !\n"
	.string "Tu es d'accord avec moi, non ?$"

Route106_Text_NedIntro:
	.string "Que font les gens s'ils ont besoin\n"
	.string "d'aller aux toilettes ?\p"
	.string "Et si ma CANNE accroche un gros poisson pendant\n"
	.string "que je suis aux toilettes ? Je ne peux pas y aller…$"

Route106_Text_NedDefeated:
	.string "J'ai perdu parce que j'essaie de ne pas\n"
	.string "aller aux toilettes…$"

Route106_Text_NedPostBattle:
	.string "Oh, non ! J'ai le sentiment que je vais\n"
	.string "attraper un gros !$"

Route106_Text_DouglasIntro:
	.string "Hahahah ! Je cours mal, mais dans\n"
	.string "l'eau tu ne peux pas m'attraper !$"

Route106_Text_DouglasDefeated:
	.string "Je me rends !$"

Route106_Text_DouglasPostBattle:
	.string "Je ne perdrais pas une course de natation…$"

Route106_Text_KylaIntro:
	.string "La mer, c'est mon jardin. Je ne vais pas faire\n"
	.string "de cadeau juste parce que tu es un gamin !$"

Route106_Text_KylaDefeated:
	.string "Tu t'es retenu avec moi\n"
	.string "par hasard ?$"

Route106_Text_KylaPostBattle:
	.string "Dériver avec les vagues…\n"
	.string "J'adore ça ! Pourquoi tu n'essaies pas ?$"

Route107_Text_DarrinIntro:
	.string "Bâillement…\p"
	.string "J'ai dû m'endormir en\n"
	.string "dérivant sur les vagues.$"

Route107_Text_DarrinDefeated:
	.string "Ahaha, j'ai perdu…\n"
	.string "Je vais faire une sieste, je crois…$"

Route107_Text_DarrinPostBattle:
	.string "Flotter et être bercé par\n"
	.string "les vagues, c'est comme dormir dans\l"
	.string "un lit moelleux et confortable.$"

Route107_Text_TonyIntro:
	.string "La mer, c'est comme mon jardin.\n"
	.string "Combattons !$"

Route107_Text_TonyDefeated:
	.string "J'ai perdu sur mon propre terrain…\n"
	.string "Je suis sous le choc !$"

Route107_Text_TonyPostBattle:
	.string "Je parcours les mers avec un cœur plein de\n"
	.string "rêves…\p"
	.string "C'est une chanson !\n"
	.string "Bref, je continue à nager.$"

Route107_Text_TonyRegister:
	.string "Tu m'as choqué jusqu'aux os !\n"
	.string "Bon, pour que tu ne m'oublies pas…$"

Route107_Text_TonyRematchIntro:
	.string "En nageant dans la grande mer,\n"
	.string "mon POKéMON est devenu plus fort !$"

Route107_Text_TonyRematchDefeated:
	.string "Quel choc !\p"
	.string "Mon POKéMON est devenu plus fort, mais\n"
	.string "je suis resté faible comme DRESSEUR !$"

Route107_Text_TonyRematchPostBattle:
	.string "Ce que tu apprends au combat te rend\n"
	.string "un DRESSEUR plus fort.\l"
	.string "Les vagues m'ont appris ça.$"

Route107_Text_DeniseIntro:
	.string "Tu connais une petite ville\n"
	.string "appelée MYSTIBURG ?$"

Route107_Text_DeniseDefeated:
	.string "Je déteste ça !$"

Route107_Text_DenisePostBattle:
	.string "Une expression bizarre devient vraiment\n"
	.string "à la mode à la HALLE d'ALGATIA.$"

Route107_Text_BethIntro:
	.string "Tu voulais te battre contre moi ?\n"
	.string "Bien sûr, je suis partant !$"

Route107_Text_BethDefeated:
	.string "Je n'étais pas assez fort pour toi.$"

Route107_Text_BethPostBattle:
	.string "Je pense que tu vas continuer à t'améliorer.\n"
	.string "Je vais essayer aussi !$"

Route107_Text_LisaIntro:
	.string "LISA : Nous te défions en tant que\n"
	.string "frère et sœur !$"

Route107_Text_LisaDefeated:
	.string "LISA : Génial.\n"
	.string "Tu es d'une autre catégorie de coriace.$"

Route107_Text_LisaPostBattle:
	.string "LISA : As-tu des amis qui\n"
	.string "iraient à la plage avec toi ?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "LISA : Si tu veux combattre avec nous,\n"
	.string "ramène plus de POKéMON.$"

Route107_Text_RayIntro:
	.string "RAY : On combat toujours des POKéMON,\n"
	.string "ma sœur et moi.\p"
	.string "Je perds toujours, mais on peut te battre\n"
	.string "en 2 contre 2 !$"

Route107_Text_RayDefeated:
	.string "RAY : Waouh, tu es à un niveau\n"
	.string "supérieur au nôtre !$"

Route107_Text_RayPostBattle:
	.string "RAY : Ma sœur m'a donné mon POKéMON.\n"
	.string "Je l'ai élevé, et maintenant c'est mon\l"
	.string "partenaire important !$"

Route107_Text_RayNotEnoughPokemon:
	.string "RAY : Si tu veux nous combattre,\n"
	.string "ramène plus de POKéMON !$"

Route107_Text_CamronIntro:
	.string "Je suis au milieu d'un triathlon,\n"
	.string "mais je ne suis pas du tout fatigué !$"

Route107_Text_CamronDefeated:
	.string "Ça m'a épuisé…$"

Route107_Text_CamronPostBattle:
	.string "Il me reste encore la natation et la course à\n"
	.string "faire après ça.\p"
	.string "Est-ce que ça va aller ?$"

Route108_Text_JeromeIntro:
	.string "Mon rêve est de nager sur les sept\n"
	.string "mers du monde !$"

Route108_Text_JeromeDefeated:
	.string "Je ne pourrai pas parcourir les sept mers\n"
	.string "comme ça…$"

Route108_Text_JeromePostBattle:
	.string "Jouer avec des POKéMON marins est l'un\n"
	.string "des plaisirs de la nage !$"

Route108_Text_MatthewIntro:
	.string "Ahoy ! Tu vas aussi vers\n"
	.string "le CARGO ABANDONNÉ ?$"

Route108_Text_MatthewDefeated:
	.string "Je coule !\n"
	.string "Glou… Glou…$"

Route108_Text_MatthewPostBattle:
	.string "Certaines personnes entrent même\n"
	.string "dans ce NAVIRE ABANDONNÉ.$"

Route108_Text_TaraIntro:
	.string "Mon petit ami menteur m'a dit\n"
	.string "que j'étais super en bikini…$"

Route108_Text_TaraDefeated:
	.string "Oh, mince !$"

Route108_Text_TaraPostBattle:
	.string "Même si c'est un mensonge, j'adore qu'on me dise\n"
	.string "que j'ai l'air géniale…\l"
	.string "Nous les filles, on est complexes…$"

Route108_Text_MissyIntro:
	.string "J'adore la mer !\n"
	.string "J'oublie tous mes soucis quand je nage !$"

Route108_Text_MissyDefeated:
	.string "Quand je perds un combat, je suis\n"
	.string "très stressé !$"

Route108_Text_MissyPostBattle:
	.string "Évacue ton stress en nageant !\n"
	.string "C'est tellement sain !$"

Route108_Text_CoryIntro:
	.string "J'adore les POKéMON de type EAU.\n"
	.string "J'adore les autres POKéMON aussi !$"

Route108_Text_CoryDefeated:
	.string "Waaah ! J'ai perdu !\n"
	.string "Waaah ! Waaah !$"

Route108_Text_CoryPostBattle:
	.string "Crier, c'est bon pour moi !\n"
	.string "Ça me remonte le moral !$"

Route108_Text_CoryRegister:
	.string "J'adore les DRESSEURS coriaces aussi !\n"
	.string "Enregistre-moi dans ton POKéNAV !$"

Route108_Text_CoryRematchIntro:
	.string "Gagné ou perdu, j'adore combattre en mer !$"

Route108_Text_CoryRematchDefeated:
	.string "Waaah ! J'ai encore perdu !\n"
	.string "Waaah ! Waaah !$"

Route108_Text_CoryRematchPostBattle:
	.string "Si tu fais face à un défi,\n"
	.string "essaie de crier vers la mer !$"

Route108_Text_CarolinaIntro:
	.string "Je suis très fier de mes POKéMON.\n"
	.string "On va te montrer un combat fulgurant !$"

Route108_Text_CarolinaDefeated:
	.string "Ce n'était pas mignon du tout.$"

Route108_Text_CarolinaPostBattle:
	.string "Comme je suis en mer comme ça, je n'aurais pas\n"
	.string "contre de mettre un maillot rose à froufrous…$"

Route109_Text_DavidIntro:
	.string "Hiyah ! Regarde mes abdos sculptés !\n"
	.string "C'est ce qu'on appelle « musclé » !$"

Route109_Text_DavidDefeated:
	.string "Aiyah !\n"
	.string "Raté !$"

Route109_Text_DavidPostBattle:
	.string "Hiyah !\p"
	.string "Mes abdos sculptés n'ont rien à voir\n"
	.string "avec les combats POKéMON !$"

Route109_Text_AliceIntro:
	.string "Es-tu bien protégé contre\n"
	.string "le soleil ?$"

Route109_Text_AliceDefeated:
	.string "Aïe, aïe, aïe !$"

Route109_Text_AlicePostBattle:
	.string "Les joues sont les plus sujettes aux brûlures !$"

Route109_Text_HueyIntro:
	.string "J'ai mouillé l'ancre dans des ports du monde\n"
	.string "entier, mais POIVRESSE est la meilleure.$"

Route109_Text_HueyDefeated:
	.string "Tu es le meilleur !$"

Route109_Text_HueyPostBattle:
	.string "Dans le meilleur port se trouvait\n"
	.string "le meilleur DRESSEUR…$"

Route109_Text_EdmondIntro:
	.string "Brrrruuuup…\n"
	.string "Un combat ? Avec moi ?$"

Route109_Text_EdmondDefeated:
	.string "Beurk… Ooooooohhhhhh…\n"
	.string "Brrrrrruuuup…$"

Route109_Text_EdmondPostBattle:
	.string "Je suis normalement plus fort que ça !\n"
	.string "Je suis juste malade comme un chien en mer !\p"
	.string "Je suis un MARIN, mais…$"

Route109_Text_RickyIntro:
	.string "J'ai soif… Je prendrais bien une SODA COOL\n"
	.string "à la MAISON BORD DE MER…$"

Route109_Text_RickyDefeated:
	.string "Ouille…$"

Route109_Text_RickyPostBattle:
	.string "Je commence à avoir faim… Ma bouée\n"
	.string "a l'air d'un donut géant…$"

Route109_Text_RickyRegister:
	.string "Tu veux un autre combat avec moi\n"
	.string "quand je n'aurai plus soif ?$"

Route109_Text_RickyRematchIntro:
	.string "J'ai faim, mais j'ai assez d'énergie\n"
	.string "pour un combat !$"

Route109_Text_RickyRematchDefeated:
	.string "J'ai perdu…\n"
	.string "C'est parce que j'ai faim…$"

Route109_Text_RickyRematchPostBattle:
	.string "Quand on mange sur une plage, tout\n"
	.string "a l'air d'avoir meilleur goût.$"

Route109_Text_LolaIntro:
	.string "Un parasol de plage ne ressemble-t-il pas\n"
	.string "à une fleur géante ?$"

Route109_Text_LolaDefeated:
	.string "Maman !$"

Route109_Text_LolaPostBattle:
	.string "Si tu regardes la plage depuis le ciel,\n"
	.string "elle ressemble à un grand jardin de fleurs !$"

Route109_Text_LolaRegister:
	.string "Moi ?\n"
	.string "Je suis là tous les jours !$"

Route109_Text_LolaRematchIntro:
	.string "Je ne perdrai plus contre toi !\n"
	.string "C'est pour ça que j'ai ma bouée !$"

Route109_Text_LolaRematchDefeated:
	.string "Maman !$"

Route109_Text_LolaRematchPostBattle:
	.string "Avec une bouée, la mignonnerie de mes\n"
	.string "POKéMON et moi monte en flèche !$"

Route109_Text_AustinaIntro:
	.string "Je ne sais pas nager sans ma bouée,\n"
	.string "mais je ne perdrai pas aux POKéMON !$"

Route109_Text_AustinaDefeated:
	.string "J'ai perdu parce que j'avais une\n"
	.string "bouée ?$"

Route109_Text_AustinaPostBattle:
	.string "Ma bouée est un accessoire de mode.\n"
	.string "Je ne peux pas être vue sans elle.$"

Route109_Text_GwenIntro:
	.string "Salut, grand DRESSEUR.\n"
	.string "Tu veux combattre avec moi ?$"

Route109_Text_GwenDefeated:
	.string "Oh, tu es fort.$"

Route109_Text_GwenPostBattle:
	.string "Comment es-tu devenu si fort ?$"

Route109_Text_CarterIntro:
	.string "Wahahah ! Ce type va attraper\n"
	.string "un sacré poisson !$"

Route109_Text_CarterDefeated:
	.string "Ce type vient d'en perdre un…$"

Route109_Text_CarterPostBattle:
	.string "Ce type pense que tu es un grand.\n"
	.string "Non, tu seras un grand !$"

Route109_Text_PaulIntro:
	.string "PAUL : Bon, c'est un tue-l'amour.\p"
	.string "J'aimerais que tu ne déranges pas\n"
	.string "notre précieux moment à deux.$"

Route109_Text_PaulDefeated:
	.string "PAUL : Bon, j'abandonne.$"

Route109_Text_PaulPostBattle:
	.string "PAUL : Bon, ne dis à personne qu'on\n"
	.string "est ici.\l"
	.string "C'est juste notre monde privé à deux !$"

Route109_Text_PaulNotEnoughPokemon:
	.string "PAUL : On est totalement, profondément amoureux.\n"
	.string "C'est pour ça qu'on fait combattre nos POKéMON\l"
	.string "ensemble.$"

Route109_Text_MelIntro:
	.string "MEL : On est, genre, totalement amoureux.\n"
	.string "Notre romance embrase tout HOENN !$"

Route109_Text_MelDefeated:
	.string "MEL : On a perdu, et c'est ma faute !\n"
	.string "PAUL va me détester !$"

Route109_Text_MelPostBattle:
	.string "MEL : Euh, PAUL, tu es en colère contre moi ?\n"
	.string "Ne sois pas en colère, s'il te plaît.$"

Route109_Text_MelNotEnoughPokemon:
	.string "MEL : On est, genre, profondément et vraiment amoureux.\n"
	.string "C'est pour ça qu'on fait combattre nos POKéMON\l"
	.string "ensemble.$"

Route109_Text_ChandlerIntro:
	.string "Tadaah ! Tu vois ?\n"
	.string "Ma bouée est ronde !$"

Route109_Text_ChandlerDefeated:
	.string "Oh, oh !\n"
	.string "Dommage !$"

Route109_Text_ChandlerPostBattle:
	.string "Après t'avoir montré ma bouée\n"
	.string "rondouillarde…$"

Route109_Text_HaileyIntro:
	.string "Je ne sais pas nager, alors je fais\n"
	.string "semblant de nager.$"

Route109_Text_HaileyDefeated:
	.string "Je le savais !\n"
	.string "Je ne pensais pas qu'on pouvait gagner.$"

Route109_Text_HaileyPostBattle:
	.string "Quand j'apprendrai à nager, je pense\n"
	.string "que mes POKéMON deviendront plus forts.$"

Route109_Text_ElijahIntro:
	.string "Pour un type costaud comme moi, ce genre\n"
	.string "de POKéMON est le partenaire idéal !$"

Route109_Text_ElijahDefeated:
	.string "Je reste cool même en défaite, hein ?$"

Route109_Text_ElijahPostBattle:
	.string "Pour un mec aussi viril que moi, un port\n"
	.string "est le cadre parfait !\p"
	.string "Je vais me diriger vers POIVRESSE.$"

Route110_Text_JacobIntro:
	.string "Whoa ! Attention !\n"
	.string "Tu n'as pas l'habitude des courses à VÉLO.$"

Route110_Text_JacobDefeated:
	.string "Ouah !\n"
	.string "Mes freins ont lâché !$"

Route110_Text_JacobPostBattle:
	.string "Les pneus crevés et les problèmes de freins peuvent\n"
	.string "causer de graves blessures !\l"
	.string "Inspecte ta BICYCLETTE régulièrement !$"

Route110_Text_AnthonyIntro:
	.string "Yo, toi !\n"
	.string "Tu peux suivre ma vitesse ?$"

Route110_Text_AnthonyDefeated:
	.string "Carambouille !$"

Route110_Text_AnthonyPostBattle:
	.string "La vitesse seule ne me fera pas gagner aux POKéMON.\n"
	.string "Je dois y réfléchir…$"

Route110_Text_BenjaminIntro:
	.string "Ne panique pas si ton VELO va vite !$"

Route110_Text_BenjaminDefeated:
	.string "Je ne devrais pas paniquer pendant\n"
	.string "les combats POKéMON…$"

Route110_Text_BenjaminPostBattle:
	.string "Pas besoin de paniquer ou de stresser.\n"
	.string "Prends ton temps. Il y a largement le temps.$"

Route110_Text_BenjaminRegister:
	.string "Je vais continuer à avancer sans stresser.\n"
	.string "Fais-moi signe si tu es partant.$"

Route110_Text_BenjaminRematchIntro:
	.string "Tu ne vas pas un peu trop vite ?\n"
	.string "Ralentis et combattons.$"

Route110_Text_BenjaminRematchDefeated:
	.string "Je n'ai pas paniqué, mais j'ai quand même perdu…$"

Route110_Text_BenjaminRematchPostBattle:
	.string "Pas besoin de paniquer ou de stresser.\n"
	.string "Prends ton temps. Il y a largement le temps.$"

Route110_Text_AbigailIntro:
	.string "Le triathlon est extrêmement difficile. Il\p"
	.string "faut compléter les trois épreuves\n"
	.string "de natation, cyclisme et course.$"

Route110_Text_AbigailDefeated:
	.string "Les combats POKéMON, c'est dur aussi !$"

Route110_Text_AbigailPostBattle:
	.string "Je suis épuisé, j'ai besoin d'une pause.\n"
	.string "Il est important de bien se reposer.$"

Route110_Text_AbigailRegister:
	.string "Tu sais, je t'aime bien !\n"
	.string "Revanche sur la PISTE CYCLABLE.$"

Route110_Text_AbigailRematchIntro:
	.string "Ce n'est pas génial de se battre\n"
	.string "en faisant du vélo ?$"

Route110_Text_AbigailRematchDefeated:
	.string "Ouah…\n"
	.string "Comment peux-tu être si fort ?$"

Route110_Text_AbigailRematchPostBattle:
	.string "Tu visais un record ?\p"
	.string "Désolé si je t'ai retenu !$"

Route110_Text_JasmineIntro:
	.string "Je roule sans m'arrêter.\n"
	.string "Mes cuisses sont comme du roc !$"

Route110_Text_JasmineDefeated:
	.string "Je m'inquiète des crampes musculaires…$"

Route110_Text_JasminePostBattle:
	.string "Oh, tu as des BADGES d'ARÈNE ?\n"
	.string "Pas étonnant que tu sois si fort !$"

Route110_Text_EdwardIntro:
	.string "J'ai prévu tes intentions !\n"
	.string "Je ne peux pas perdre !$"

Route110_Text_EdwardDefeated:
	.string "Je n'ai pas su prédire ma propre défaite !$"

Route110_Text_EdwardPostBattle:
	.string "Je vois ton avenir…\p"
	.string "Hmm…\n"
	.string "Je vois une lumière brillante…$"

Route110_Text_JaclynIntro:
	.string "Ahahahaha !\n"
	.string "Je vais t'éblouir avec mes merveilles !$"

Route110_Text_JaclynDefeated:
	.string "J'ai perdu merveilleusement !$"

Route110_Text_JaclynPostBattle:
	.string "Tu as gagné seulement parce que c'était\n"
	.string "un miracle ! Oui, un miracle !\l"
	.string "Ne crois pas que tu gagneras tout le temps !$"

Route110_Text_EdwinIntro:
	.string "Pourrais-je voir ton POKéMON ?\n"
	.string "Juste un coup d'œil, s'il te plaît ?$"

Route110_Text_EdwinDefeated:
	.string "Je voulais compléter\n"
	.string "ma collection…$"

Route110_Text_EdwinPostBattle:
	.string "Quand je vois un POKéMON que je ne connais pas,\n"
	.string "ma passion de collectionneur s'enflamme !$"

Route110_Text_EdwinRegister:
	.string "J'aime aussi collectionner\n"
	.string "les inscriptions MATCH CALL…$"

Route110_Text_EdwinRematchIntro:
	.string "Salut, as-tu attrapé de nouveaux POKéMON ?\p"
	.string "Je peux voir ton POKéMON ?\n"
	.string "Juste un coup d'œil, s'il te plaît ?$"

Route110_Text_EdwinRematchDefeated:
	.string "Tes POKéMON…\n"
	.string "Je t'envie.$"

Route110_Text_EdwinRematchPostBattle:
	.string "Oh, j'aimerais tant posséder tous\n"
	.string "les POKéMON rares !$"

Route110_Text_DaleIntro:
	.string "Hé !\n"
	.string "Ne me surprends pas par derrière !$"

Route110_Text_DaleDefeated:
	.string "J'ai perdu !\n"
	.string "Zut !$"

Route110_Text_DalePostBattle:
	.string "La pêche, c'est une question de concentration.\n"
	.string "Il faut se concentrer sur le flotteur.$"

Route110_Text_IsabelIntro:
	.string "Ahahaha ! J'irais n'importe où pour\n"
	.string "montrer mes adorables POKéMON.$"

Route110_Text_IsabelDefeated:
	.string "Oh, là là, ça ne va pas.$"

Route110_Text_IsabelPostBattle:
	.string "Plutôt que de combattre, je devrais peut-être\n"
	.string "montrer mes POKéMON au FAN CLUB.$"

Route110_Text_IsabelRegister:
	.string "Ce n'était pas du tout ce\n"
	.string "que je pouvais faire pour montrer\p"
	.string "mes POKéMON. Tu seras mon public\n"
	.string "captif autant que possible !$"

Route110_Text_IsabelRematchIntro:
	.string "Ahahahaha ! Je serais ravi de montrer\n"
	.string "mes POKéMON aussi souvent que tu veux !$"

Route110_Text_IsabelRematchDefeated:
	.string "Oh, là là, ça ne va pas.$"

Route110_Text_IsabelRematchPostBattle:
	.string "Je ne pense pas pouvoir arrêter de\n"
	.string "montrer mes POKéMON.\p"
	.string "Mais j'aime aussi combattre !$"

Route110_Text_TimmyIntro:
	.string "J'ai trouvé des POKéMON cool dans l'herbe\n"
	.string "par ici !$"

Route110_Text_TimmyDefeated:
	.string "Être cool ne suffit pas pour gagner…$"

Route110_Text_TimmyPostBattle:
	.string "C'est dur de combattre avec des\n"
	.string "POKéMON que tu viens de capturer.$"

Route110_Text_AlyssaIntro:
	.string "Je suis tombé de la PISTE CYCLABLE…\p"
	.string "Je vais surmonter ma gêne en\n"
	.string "combattant avec toi !$"

Route110_Text_AlyssaDefeated:
	.string "Oups !\n"
	.string "J'ai fini par perdre !$"

Route110_Text_AlyssaPostBattle:
	.string "Tomber… Perdre…\n"
	.string "C'est si humiliant pour moi !$"

Route110_Text_JosephIntro:
	.string "OK ! À fond les gaz ! Si tu ne suis pas le rythme,\n"
	.string "tu restes sur le bord du chemin !$"

Route110_Text_JosephDefeated:
	.string "Tu as trouvé le rythme, c'est sûr…$"

Route110_Text_JosephPostBattle:
	.string "Ça ne va pas me faire baisser les bras !\n"
	.string "La défaite m'a rendu meilleur !$"

Route110_Text_KalebIntro:
	.string "Quand des POKéMON mignons s'entraident…\n"
	.string "On ne voit rien de plus adorable !$"

Route110_Text_KalebDefeated:
	.string "Tu n'as ni compassion ni pitié ?$"

Route110_Text_KalebPostBattle:
	.string "D'accord, d'accord, vous avez fait\n"
	.string "de votre mieux, mes chéris.$"

Route111_Text_DrewIntro:
	.string "Oh, hé ! Ces LUNET. SABLE te vont bien.\n"
	.string "Mais je pense qu'elles me vont mieux.\p"
	.string "Décidons à qui elles vont le mieux\n"
	.string "avec un combat !$"

Route111_Text_DrewDefeat:
	.string "Je ne voyais pas ce qui se passait sur les côtés\n"
	.string "à cause des LUNET. SABLE.$"

Route111_Text_DrewPostBattle:
	.string "Les LUNETTES SABLE rendent possible de\n"
	.string "traverser les tempêtes de sable.\l"
	.string "Ça me rend heureux !$"

Route111_Text_HeidiIntro:
	.string "Je fais un pique-nique dans le désert.\p"
	.string "On trouve toujours des DRESSEURS,\n"
	.string "alors je peux aussi me battre ici !$"

Route111_Text_HeidiDefeat:
	.string "Ohhh ! Tu es méchant !$"

Route111_Text_HeidiPostBattle:
	.string "En combattant dans une tempête de\n"
	.string "sable, surveille les PV de ton\p"
	.string "POKéMON. Il peut s'évanouir si tu\n"
	.string "ne fais pas attention !$"

Route111_Text_BeauIntro:
	.string "Porter ces LUNET. SABLE me fait me sentir\n"
	.string "comme un super-héros.\l"
	.string "En ce moment, personne ne peut me battre !$"

Route111_Text_BeauDefeat:
	.string "Je ne peux pas gagner sur le seul courage…$"

Route111_Text_BeauPostBattle:
	.string "Je vais devenir un vrai héros un jour.\n"
	.string "Je vais travailler plus dur pour rendre\l"
	.string "moi et mes POKéMON plus forts.$"

Route111_Text_BeckyIntro:
	.string "J'ai entendu qu'il y a des fossiles\n"
	.string "dans le désert. Où peuvent-ils être ?$"

Route111_Text_BeckyDefeat:
	.string "Pas la forme…$"

Route111_Text_BeckyPostBattle:
	.string "S'il y a des fossiles dans le désert,\n"
	.string "c'était sûrement une mer avant.$"

Route111_Text_DustyIntro:
	.string "Depuis trente ans, je cherche des\n"
	.string "ruines anciennes !\l"
	.string "Je dois être défié ?$"

Route111_Text_DustyDefeat:
	.string "Pendant que je cherchais des ruines,\n"
	.string "je n'ai pas cherché de POKéMON forts.$"

Route111_Text_DustyPostBattle:
	.string "Depuis trente ans, je cherche des\n"
	.string "ruines antiques !\p"
	.string "Non, attends, c'était quarante ans ?\n"
	.string "Lequel était-ce déjà ?$"

Route111_Text_DustyRegister:
	.string "Je ne cherchais pas de POKéMON\n"
	.string "costauds.\p"
	.string "Mais pour une raison quelconque,\n"
	.string "j'adore vraiment les POKéNAVS.$"

Route111_Text_DustyRematchIntro:
	.string "Depuis trente ans, je cherche\n"
	.string "des ruines anciennes ! Non,\p"
	.string "attends, c'était quarante ans ?\n"
	.string "Bref, dois-je être défié ?$"

Route111_Text_DustyRematchDefeat:
	.string "Je n'ai trouvé ni ruines, ni de\n"
	.string "POKéMON forts…$"

Route111_Text_DustyPostRematch:
	.string "Depuis trente ans, je cherche des ruines antiques !\n"
	.string "Non, attends, est-ce que ça fait quarante ans\p"
	.string "que je cherche ?\n"
	.string "Hmm… Ça pourrait même être cinquante…\p"
	.string "Depuis combien de temps je fais ça ?\n"
	.string "Combien de temps ça fait ?$"

Route111_Text_TravisIntro:
	.string "Je suis plein d'énergie !\n"
	.string "Et mon POKéMON aussi !$"

Route111_Text_TravisDefeat:
	.string "Mon POKéMON a perdu son entrain…$"

Route111_Text_TravisPostBattle:
	.string "Quand je vois un DRESSEUR plein d'énergie,\n"
	.string "je ne peux m'empêcher de regarder.$"

Route111_Text_IreneIntro:
	.string "Je ne sais pas où tu vas,\n"
	.string "mais veux-tu combattre ?$"

Route111_Text_IreneDefeat:
	.string "Oh, tu es dégoûtamment fort !$"

Route111_Text_IrenePostBattle:
	.string "Je pense que je devrais aller au\n"
	.string "MONT CHIMNÉE, mais la vue autour\l"
	.string "d'ici est très belle aussi.$"

Route111_Text_DaisukeIntro:
	.string "Pour m'entraîner, je défie tous\n"
	.string "ceux que je croise !$"

Route111_Text_DaisukeDefeat:
	.string "J'abandonne !$"

Route111_Text_DaisukePostBattle:
	.string "Je ne peux que continuer à m'entraîner jusqu'à\n"
	.string "battre des DRESSEURS forts\l"
	.string "comme toi.$"

Route111_Text_WiltonIntro:
	.string "Montre-moi à quel point tu as\n"
	.string "endurci tes POKéMON.$"

Route111_Text_WiltonDefeat:
	.string "Je vois, tu les as considérablement\n"
	.string "endurcis.$"

Route111_Text_WiltonPostBattle:
	.string "Les POKéMON et les DRESSEURS apprennent\n"
	.string "beaucoup en combattant.\p"
	.string "L'important, c'est de ne jamais abandonner\n"
	.string "même si tu perds.$"

Route111_Text_WiltonRegister:
	.string "Ton style d'entraînement m'a beaucoup à\n"
	.string "apprendre.\p"
	.string "Je te demande une revanche si\n"
	.string "cela te convient.$"

Route111_Text_WiltonRematchIntro:
	.string "On s'entraîne ici pour monter notre\n"
	.string "niveau au suivant.\l"
	.string "Reste et entraîne-toi avec nous !$"

Route111_Text_WiltonRematchDefeat:
	.string "Ooh, tu es pas mal !$"

Route111_Text_WiltonPostRematch:
	.string "Puisque tu es si fort, tu devrais\n"
	.string "viser la LIGUE POKéMON.$"

Route111_Text_BrookeIntro:
	.string "Oh, tes POKéMON ont l'air de vrais\n"
	.string "acteurs.\l"
	.string "Je dois te demander un engagement.$"

Route111_Text_BrookeDefeat:
	.string "Ils avaient l'air forts,\n"
	.string "et ils le sont vraiment !$"

Route111_Text_BrookePostBattle:
	.string "Je pensais élever mes POKéMON\n"
	.string "avec diligence, mais oh non, il reste\l"
	.string "encore beaucoup à faire.$"

Route111_Text_BrookeRegister:
	.string "J'aimerais devenir ami avec\n"
	.string "plus de gens forts comme toi !$"

Route111_Text_BrookeRematchIntro:
	.string "Tu peux rendre un POKéMON plus fort ou\n"
	.string "plus faible selon les attaques que tu\l"
	.string "ui apprends.\p"
	.string "Quelles attaques connaissent\n"
	.string "tes POKéMON ?$"

Route111_Text_BrookeRematchDefeat:
	.string "Tu leur as appris de bonnes attaques !$"

Route111_Text_BrookePostRematch:
	.string "Peut-être que j'aurais dû empêcher mes\n"
	.string "POKéMON d'évoluer jusqu'à ce qu'ils\l"
	.string "apprennent de meilleures capacités…$"

Route111_Text_CeliaIntro:
	.string "Je n'aurais pas dû venir pique-niquer\n"
	.string "dans un endroit comme ça !$"

Route111_Text_CeliaDefeat:
	.string "Snif !\n"
	.string "Je n'aurais pas dû venir !$"

Route111_Text_CeliaPostBattle:
	.string "Dans une tempête de sable comme celle-ci, je ne peux pas\n"
	.string "installer un pique-nique même avec mes\l"
	.string "LUNET. SABLE…$"

Route111_Text_BryanIntro:
	.string "À quel point es-tu fort ?\n"
	.string "On va révéler ce secret !$"

Route111_Text_BryanDefeat:
	.string "Oh ! Ta force !\n"
	.string "Elle est enveloppée de mystère !$"

Route111_Text_BryanPostBattle:
	.string "Ce désert recèle des mystères\n"
	.string "dans ses sables mouvants !$"

Route111_Text_BrandenIntro:
	.string "Je te donnerai de mon sandwich\n"
	.string "si tu perds.$"

Route111_Text_BrandenDefeat:
	.string "Tch ! Je pensais qu'un sandwich\n"
	.string "suffirait comme pot-de-vin…$"

Route111_Text_BrandenPostBattle:
	.string "Mon SABELETTE adore manger\n"
	.string "mes sandwichs.$"

Route111_Text_TyronIntro:
	.string "C'est mon type de POKéMON préféré !$"

Route111_Text_TyronDefeat:
	.string "Attends !\n"
	.string "Tu as bien regardé mes POKéMON ?$"

Route111_Text_TyronPostBattle:
	.string "En combat, j'adore montrer\n"
	.string "mes POKéMON.\p"
	.string "Je parie que tout le monde ressent\n"
	.string "la même chose en entrant en combat !$"

Route111_Text_CelinaIntro:
	.string "Montre-moi comment mettre un peu\n"
	.string "d'excitation dans ma vie.$"

Route111_Text_CelinaDefeat:
	.string "Oh… Mon…\n"
	.string "C'était trop d'excitation.$"

Route111_Text_CelinaPostBattle:
	.string "Mon pouls bat encore la chamade.\n"
	.string "Tu es un DRESSEUR fabuleux.$"

Route111_Text_HaydenIntro:
	.string "Quand on a aussi faim que moi,\n"
	.string "il n'y a pas de place pour la pitié !$"

Route111_Text_HaydenDefeat:
	.string "Ouille…$"

Route111_Text_HaydenPostBattle:
	.string "Mon ventre gargouille !\n"
	.string "Je pourrais peut-être griller des BAIES…$"

Route111_Text_BiancaIntro:
	.string "Tu viens de LAVELLAGE ?\n"
	.string "Alors tu dois être plein d'énergie !$"

Route111_Text_BiancaDefeat:
	.string "Ooh lala !\n"
	.string "C'est beaucoup à encaisser !$"

Route111_Text_BiancaPostBattle:
	.string "Cette route ici…\n"
	.string "Tu as encore loin à voyager.$"

Route112_Text_BriceIntro:
	.string "Hahahaha !\n"
	.string "Que dirais-tu d'un combat ?\l"
	.string "Toi et moi !\l"
	.string "Hahahaha !$"

Route112_Text_BriceDefeat:
	.string "J'ai perdu !\n"
	.string "Hahahaha !$"

Route112_Text_BricePostBattle:
	.string "Hahahahaha ! Quelque chose m'est monté au nez !\n"
	.string "Hahahaha-atchoom !$"

Route112_Text_TrentIntro:
	.string "Mes jambes sont solides grâce aux montées\n"
	.string "et descentes en montagne.\p"
	.string "Elles ne fléchiront pas facilement,\n"
	.string "mon ami !$"

Route112_Text_TrentDefeat:
	.string "Aïe ! J'ai eu des crampes aux jambes !$"

Route112_Text_TrentPostBattle:
	.string "Essaie la randonnée, et je veux dire vraiment\n"
	.string "cogner sur ces sentiers de montagne\l"
	.string "avec un sac lourd de plusieurs\l"
	.string "dizaines de kilos.\p"
	.string "Ça, mon ami, mettra ton corps\n"
	.string "en pleine forme.$"

Route112_Text_TrentRegister:
	.string "Aïe, j'ai des crampes aux jambes.\n"
	.string "Tu peux me prendre des bandages dans\l"
	.string "mon sac à dos ?\p"
	.string "Non, c'est mon POKéNAV !\n"
	.string "Bon, d'accord, je t'enregistre.$"

Route112_Text_TrentRematchIntro:
	.string "Je me suis entraîné en randonnée.\n"
	.string "J'ai de la force à revendre !$"

Route112_Text_TrentRematchDefeat:
	.string "J'ai été surpassé en puissance ?$"

Route112_Text_TrentRematchPostBattle:
	.string "On dit qu'il y a des DRESSEURS\n"
	.string "très coriaces au sommet du\n"
	.string "MONT CHIMNEY.\p"
	.string "Je compte y monter et les défier !$"

Route112_Text_LarryIntro:
	.string "Je suis fort.\n"
	.string "Je ne pleurerai pas si je perds.$"

Route112_Text_LarryDefeat:
	.string "Waaaah !$"

Route112_Text_LarryPostBattle:
	.string "Je ne pleure pas parce que maman me manque !\n"
	.string "Snif…$"

Route112_Text_CarolIntro:
	.string "Quand on fait un pique-nique, il faut\n"
	.string "chanter !\l"
	.string "Allez, chante avec moi !$"

Route112_Text_CarolDefeat:
	.string "Oh, tu es si fort !$"

Route112_Text_CarolPostBattle:
	.string "Peu importe si tu es bon ou mauvais\n"
	.string "en chant ou en POKéMON.\p"
	.string "Si tu t'amuses le plus, tu gagnes !$"

Route112_Text_BryantIntro:
	.string "J'ai attrapé des POKéMON brûlants\n"
	.string "dans le SENTIER BRÛLANT ! Regarde !$"

Route112_Text_BryantDefeat:
	.string "Quel trajet cahoteux !$"

Route112_Text_BryantPostBattle:
	.string "J'aime ta façon de combattre.\n"
	.string "Ça a un certain style.$"

Route112_Text_ShaylaIntro:
	.string "Oh, tu es un DRESSEUR adorable !\n"
	.string "S'il te plaît, j'ai besoin d'un combat romantique !\l"
	.string "Je suis plutôt douée !$"

Route112_Text_ShaylaDefeat:
	.string "Oh, comme tu es fort !\n"
	.string "Tu m'as donné un sacré choc !$"

Route112_Text_ShaylaPostBattle:
	.string "Tu es occupé en ce moment ?\n"
	.string "Je pensais qu'on pourrait avoir une revanche\l"
	.string "tout de suite… Mais ce n'est\l"
	.string "pas grave si tu es occupé.$"

Route113_Text_JaylenIntro:
	.string "Tu devines pourquoi il fait si frais\n"
	.string "par ici ?$"

Route113_Text_JaylenDefeat:
	.string "Peeuuw !\n"
	.string "Ça pue !$"

Route113_Text_JaylenPostBattle:
	.string "Les cendres volcaniques bloquent le soleil,\n"
	.string "alors il ne fait pas très chaud.\p"
	.string "Tant mieux pour moi... je ne supporte pas la chaleur !$"

Route113_Text_DillonIntro:
	.string "L'éruption du volcan prouve que\n"
	.string "la terre est vivante.$"

Route113_Text_DillonDefeat:
	.string "Tu es d'une force incroyable !$"

Route113_Text_DillonPostBattle:
	.string "Aïe ! Aïe ! Je ne vois\n"
	.string "rien ! J'ai de la cendre dans\p"
	.string "les cils ! Tu vois ? Cendre\p"
	.string "et cils ? OK, c'était nul, désolé…$"

Route113_Text_MadelineIntro:
	.string "J'utilise ce parasol pour protéger\n"
	.string "mon cher CHAMALLOT de cette\l"
	.string "vilaine cendre volcanique.$"

Route113_Text_MadelineDefeat:
	.string "Huff, huff…\n"
	.string "Je suis épuisé…$"

Route113_Text_MadelinePostBattle:
	.string "Tu es très doué pour ça.\n"
	.string "Je dois dire que je suis impressionné !$"

Route113_Text_MadelineRegister:
	.string "Ici, glisse-toi sous mon parasol.\n"
	.string "Laisse-moi t'enregistrer dans mon POKéNAV.$"

Route113_Text_MadelineRematchIntro:
	.string "Oh, bonjour, ça fait un moment, non ?\n"
	.string "Puis-je t'inviter à combattre ?$"

Route113_Text_MadelineRematchDefeat:
	.string "Oh, c'est super !$"

Route113_Text_MadelinePostRematch:
	.string "Tu es resté très bon à ça.\n"
	.string "Je dois dire que je suis impressionné !$"

Route113_Text_LaoIntro:
	.string "Des cendres, je bondis ! Hiyah !\n"
	.string "Je te défie !$"

Route113_Text_LaoDefeat:
	.string "Avec honneur, j'admets ma défaite !$"

Route113_Text_LaoPostBattle:
	.string "Je dois perfectionner l'art de la dissimulation.\n"
	.string "Je te dis adieu.$"

Route113_Text_LaoRegister:
	.string "Yiiyaah ! Admire la technique ninja ancestrale\n"
	.string "d'enregistrement POKéNAV !$"

Route113_Text_LaoRematchIntro:
	.string "Des cendres, je bondis ! Hiyah !\n"
	.string "Je te défie !$"

Route113_Text_LaoRematchDefeat:
	.string "Avec honneur, j'admets ma défaite !$"

Route113_Text_LaoPostRematch:
	.string "Ma dissimulation parfaite a été trahie\n"
	.string "par mes compétences de combat immatures…\p"
	.string "Je te dis adieu.$"

Route113_Text_LungIntro:
	.string "Merci de m'avoir trouvé !\n"
	.string "Mais on doit quand même se battre !$"

Route113_Text_LungDefeat:
	.string "Je vais utiliser mon ninjutsu sur toi…\n"
	.string "« MANTEAU DE CENDRES VOLCANIQUES » !\p"
	.string "…Quoi ?\n"
	.string "C'est déjà fini ?$"

Route113_Text_LungPostBattle:
	.string "Tu sais ce qui est nul avec se cacher ?\n"
	.string "C'est solitaire si personne ne passe.$"

Route113_Text_ToriIntro:
	.string "TORI : Tous les deux, on collecte des cendres.\n"
	.string "On combatte aussi des POKéMON.$"

Route113_Text_ToriDefeat:
	.string "TORI : On a perdu… C'est ennuyeux, alors\n"
	.string "je vais chercher plus de cendres.$"

Route113_Text_ToriPostBattle:
	.string "TORI : Combien de cendres avons-nous ?\n"
	.string "Assez pour une FLÛTE BLANCHE, j'espère.$"

Route113_Text_ToriNotEnoughMons:
	.string "TORI : On veut combattre en 2 contre 2.\n"
	.string "Sinon, on perdrait !$"

Route113_Text_TiaIntro:
	.string "TIA : Tous les deux, on collecte des cendres.\n"
	.string "On combatte aussi des POKéMON.$"

Route113_Text_TiaDefeat:
	.string "TIA : On n'a pas pu gagner… C'est ennuyeux,\n"
	.string "alors je vais chercher plus de cendres.$"

Route113_Text_TiaPostBattle:
	.string "TIA : On a beaucoup de cendres !\n"
	.string "Je crois qu'il y en a assez pour une FLÛTE BLANCHE !$"

Route113_Text_TiaNotEnoughMons:
	.string "TIA : On veut combattre en 2 contre 2.\n"
	.string "Sinon, on ne gagnera pas !$"

Route113_Text_CobyIntro:
	.string "Pfft, avec ces ailes je peux\n"
	.string "te balayer !$"

Route113_Text_CobyDefeat:
	.string "Un… Quoi ?$"

Route113_Text_CobyPostBattle:
	.string "Je ne sais pas quoi dire quand je suis\n"
	.string "battu si facilement…$"

Route113_Text_SophieIntro:
	.string "La chaleur ici me rend somnolent.\n"
	.string "Combats avec moi pour que je reste éveillé.$"

Route113_Text_SophieDefeat:
	.string "C'est un rêve.\n"
	.string "J'en suis sûr…$"

Route113_Text_SophiePostBattle:
	.string "Perdre me rend fou…\n"
	.string "Je vais dormir ici même !\l"
	.string "Zzz !$"

Route113_Text_LawrenceIntro:
	.string "Tu étais peut-être en train\n"
	.string "de ramasser des cendres volcaniques ?$"

Route113_Text_LawrenceDefeat:
	.string "Héhé.\n"
	.string "On s'est fait battre nettement.$"

Route113_Text_LawrencePostBattle:
	.string "Je devrais moi aussi me cacher sous les cendres.$"

Route113_Text_WyattIntro:
	.string "T-tu veux combattre avec moi ?\n"
	.string "Alors que je viens juste d'attraper mon POKéMON ?$"

Route113_Text_WyattDefeat:
	.string "V-vous êtes tous contents de gagner ?\n"
	.string "Même si c'est seulement moi ?$"

Route113_Text_WyattPostBattle:
	.string "Oh, tu veux dire un mot au\n"
	.string "perdant maintenant ?\p"
	.string "Tu te crois trop cool ?\n"
	.string "Humph !$"

Route114_Text_LennyIntro:
	.string "Yodelayhihoo !\p"
	.string "… …\p"
	.string "Tu es censé crier\n"
	.string "« yodelayhihoo » car il n'y a pas\l"
	.string "d'écho ici !$"

Route114_Text_LennyDefeat:
	.string "Yodelayhihoo !$"

Route114_Text_LennyPostBattle:
	.string "Quand j'étais petit, je croyais qu'il y avait\n"
	.string "quelqu'un qui me copiait et criait\l"
	.string "« Yodelayhihoo » en retour.$"

Route114_Text_LucasIntro:
	.string "Si tu n'es pas préparé, tu ne devrais pas\n"
	.string "être en montagne !$"

Route114_Text_LucasDefeat:
	.string "Les montagnes sont impitoyables…$"

Route114_Text_LucasPostBattle:
	.string "En hiver, les montagnes deviennent mortelles\n"
	.string "à cause des blizzards et des avalanches.$"

Route114_Text_ShaneIntro:
	.string "Le camping, c'est super ! Tu peux\n"
	.string "pêcher, faire griller des guimauves et raconter\p"
	.string "des histoires d'horreur ! Mais le meilleur,\n"
	.string "ce sont les combats de POKéMON !$"

Route114_Text_ShaneDefeat:
	.string "Beaucoup trop fort !$"

Route114_Text_ShanePostBattle:
	.string "Je trouve ça génial de pouvoir camper\n"
	.string "avec mes POKéMON.$"

Route114_Text_NancyIntro:
	.string "J'ai besoin de faire de l'exercice après un repas.\n"
	.string "Faisons un combat !$"

Route114_Text_NancyDefeat:
	.string "Oh non !$"

Route114_Text_NancyPostBattle:
	.string "Je viens de faire un bon repas.\n"
	.string "Je commence à somnoler…$"

Route114_Text_SteveIntro:
	.string "Ufufufufufu…\n"
	.string "Veux-tu combattre contre mes POKéMON ?$"

Route114_Text_SteveDefeat:
	.string "M-Mes POKéMON…$"

Route114_Text_StevePostBattle:
	.string "Un gros corps tout bosselé\n"
	.string "et dur, d'énormes cornes et\p"
	.string "des crocs vicieux… Ufufufufu… J'aimerais\n"
	.string "avoir un POKéMON comme ça…$"

Route114_Text_SteveRegister:
	.string "N'oublie pas ce que tu m'as fait !\n"
	.string "Je ferai en sorte que tu ne puisses pas oublier !$"

Route114_Text_SteveRematchIntro:
	.string "Ufufufufufu…\n"
	.string "Allez, combats mes POKéMON…$"

Route114_Text_SteveRematchDefeat:
	.string "J'ai de la chance de voir tes\n"
	.string "POKéMON…$"

Route114_Text_StevePostRematch:
	.string "Ufufufufufu…\p"
	.string "Quand je vois des POKéMON combattre,\n"
	.string "je frémis de partout…$"

Route114_Text_BernieIntro:
	.string "Si tu fais un feu de camp,\n"
	.string "assure-toi d'avoir de l'eau à portée de main.$"

Route114_Text_BernieDefeat:
	.string "Merci d'avoir éteint mon feu !$"

Route114_Text_BerniePostBattle:
	.string "Il faut vraiment faire attention\n"
	.string "à tout feu dans une\p"
	.string "forêt. Ne sous-estime jamais\n"
	.string "le pouvoir du feu.$"

Route114_Text_BernieRegister:
	.string "Tu as enflammé mon esprit.\n"
	.string "Enregistrons-nous mutuellement !$"

Route114_Text_BernieRematchIntro:
	.string "As-tu appris à garder de l'eau à portée\n"
	.string "pour les feux de camp ?$"

Route114_Text_BernieRematchDefeat:
	.string "On m'a arrosé avant que je puisse\n"
	.string "m'embraser, je suppose.$"

Route114_Text_BerniePostRematch:
	.string "Il faut vraiment faire attention\n"
	.string "à tout feu dans une\p"
	.string "forêt. Ne sous-estime jamais\n"
	.string "le pouvoir du feu.$"

Route114_Text_ClaudeIntro:
	.string "Si on pêchait, tu n'aurais aucune chance\n"
	.string "contre moi.\l"
	.string "Alors, envoie tes POKéMON !$"

Route114_Text_ClaudeDefeat:
	.string "Si on pêchait, j'aurais gagné…$"

Route114_Text_ClaudePostBattle:
	.string "Je vais tenter ma chance pour\n"
	.string "attraper un gros aux CHUTES MÉTÉORES.\p"
	.string "Il doit y avoir quelque\n"
	.string "chose là-dedans. J'en suis sûr.$"

Route114_Text_NolanIntro:
	.string "J'aime pêcher. Mais j'aime aussi\n"
	.string "me battre !\p"
	.string "Si quelqu'un me défie, j'y vais,\n"
	.string "même si je suis en train de pêcher.$"

Route114_Text_NolanDefeat:
	.string "J'aime combattre, mais ça ne veut pas\n"
	.string "dire que je suis doué…$"

Route114_Text_NolanPostBattle:
	.string "Cette fois, je vais y arriver !\p"
	.string "Je me dis toujours ça, alors je ne peux pas m'éloigner\n"
	.string "de la pêche ou des POKéMON.$"

Route114_Text_TyraIntro:
	.string "TYRA : Eh bien, d'accord.\n"
	.string "J'en ai envie.\l"
	.string "Je vais t'apprendre un peu sur les POKéMON.$"

Route114_Text_TyraDefeat:
	.string "TYRA : Quel style de combat incroyable !$"

Route114_Text_TyraPostBattle:
	.string "TYRA : J'enseignais à ma cadette IVY\n"
	.string "les POKéMON.$"

Route114_Text_TyraNotEnoughMons:
	.string "TYRA : Hihi…\n"
	.string "Si tu veux combattre avec nous, un seul\l"
	.string "POKéMON ne suffit pas !$"

Route114_Text_IvyIntro:
	.string "IVY : Qui t'a appris les POKéMON ?$"

Route114_Text_IvyDefeat:
	.string "IVY : Quel style de combat incroyable !$"

Route114_Text_IvyPostBattle:
	.string "IVY : J'ai commencé à entraîner des POKéMON\n"
	.string "parce que TYRA, mon mentor,\l"
	.string "m'a appris !$"

Route114_Text_IvyNotEnoughMons:
	.string "IVY : Tu n'as qu'un seul POKéMON ?\n"
	.string "Je pense qu'il doit se sentir seul.$"

Route114_Text_KaiIntro:
	.string "J'ai attrapé un gros !\n"
	.string "Un énorme, je te le dis !$"

Route114_Text_KaiDefeat:
	.string "C'était quoi ça ?\n"
	.string "Le mien a perdu en taille ?$"

Route114_Text_KaiPostBattle:
	.string "D'accord !\n"
	.string "Je vais pêcher un plus gros !$"

Route114_Text_CharlotteIntro:
	.string "Moi !\n"
	.string "Je ne suis pas qu'un joli minois !$"

Route114_Text_CharlotteDefeat:
	.string "Ce n'était pas mignon du tout !$"

Route114_Text_CharlottePostBattle:
	.string "Je ne veux pas un POKéMON\n"
	.string "juste mignon.\p"
	.string "J'adore les mignons qui ont une\n"
	.string "petite particularité !$"

Route114_Text_AngelinaIntro:
	.string "As-tu fait évoluer tes\n"
	.string "POKéMON souvent ?$"

Route114_Text_AngelinaDefeat:
	.string "Oh, je vois.\n"
	.string "C'est bon à savoir.$"

Route114_Text_AngelinaPostBattle:
	.string "Certains POKéMON changent tellement en\n"
	.string "évoluant, c'est surprenant !$"

Route115_Text_TimothyIntro:
	.string "Hm…\n"
	.string "Tu sembles plutôt capable…\l"
	.string "Laisse-moi te tenir compagnie !$"

Route115_Text_TimothyDefeat:
	.string "Tu es bien plus fort que\n"
	.string "ce que j'imaginais !$"

Route115_Text_TimothyPostBattle:
	.string "Il n'y a pas de génie né.\n"
	.string "Tout dépend des efforts !\l"
	.string "C'est ce en quoi je crois…$"

Route115_Text_TimothyRegister:
	.string "Hmm… Une défaite aussi cuisante,\n"
	.string "c'est loin dans mes souvenirs.\p"
	.string "Si tu le permets, je souhaiterais\n"
	.string "une nouvelle occasion de combattre.$"

Route115_Text_TimothyRematchIntro:
	.string "Hm… Comme toujours, ton agilité\n"
	.string "parle d'elle-même.\l"
	.string "Viens, tiens-moi compagnie !$"

Route115_Text_TimothyRematchDefeat:
	.string "Aussi fort que jamais !$"

Route115_Text_TimothyPostRematch:
	.string "Tout est question d'efforts !\p"
	.string "J'ai perdu parce que je n'ai pas\n"
	.string "assez travaillé !$"

Route115_Text_KoichiIntro:
	.string "Toi !\p"
	.string "Mon MACHOPEUR !\p"
	.string "Exige un combat !$"

Route115_Text_KoichiDefeat:
	.string "Aïe, aïe, aïe !$"

Route115_Text_KoichiPostBattle:
	.string "Mon équipe de MACHOCOP !\p"
	.string "Tant qu'ils cherchent la puissance,\n"
	.string "je deviendrai fort avec eux !$"

Route115_Text_NobIntro:
	.string "Ma plus grande force, c'est de casser des briques\n"
	.string "avec mon front !$"

Route115_Text_NobDefeat:
	.string "Ouuaaaah !\n"
	.string "J'ai la tête qui éclate !$"

Route115_Text_NobPostBattle:
	.string "J'enseigne le karaté à mes POKéMON.\p"
	.string "On dirait qu'ils vont devenir bien\n"
	.string "meilleurs que moi. Ça m'enthousiasme.$"

Route115_Text_NobRegister:
	.string "Tu m'impressionnes ! Propose-moi une revanche\n"
	.string "après que j'aurai refait mon entraînement !$"

Route115_Text_NobRematchIntro:
	.string "Après m'avoir battu, on s'est entraînés dur pour\n"
	.string "améliorer nos compétences.\l"
	.string "Allez, une revanche !$"

Route115_Text_NobRematchDefeat:
	.string "Ugwaaah !\n"
	.string "On a encore perdu !$"

Route115_Text_NobPostRematch:
	.string "Mes POKéMON deviendront plus forts !\n"
	.string "Je redoublerai d'entraînement !$"

Route115_Text_CyndyIntro:
	.string "Cette plage est mon lieu d'entraînement secret !\n"
	.string "Ne viens pas t'immiscer !$"

Route115_Text_CyndyDefeat:
	.string "Je ne me suis pas assez entraîné !$"

Route115_Text_CyndyPostBattle:
	.string "Le sable sert de coussin pour réduire\n"
	.string "les chocs et prévenir les blessures.\l"
	.string "C'est l'endroit idéal pour s'entraîner.$"

Route115_Text_CyndyRegister:
	.string "D'accord, très bien, tu es libre de venir ici.\n"
	.string "En échange, j'aimerais te combattre à nouveau.$"

Route115_Text_CyndyRematchIntro:
	.string "OK, que le combat commence !$"

Route115_Text_CyndyRematchDefeat:
	.string "Je peux me battre mais mes POKéMON…$"

Route115_Text_CyndyPostRematch:
	.string "Même quand je perds, j'en tire quand même\n"
	.string "du plaisir.\l"
	.string "Ça doit vouloir dire que j'aime les POKéMON.$"

Route115_Text_HectorIntro:
	.string "J'ai un POKéMON rare !\n"
	.string "Veux-tu que je te le montre ?$"

Route115_Text_HectorDefeat:
	.string "Toi…\n"
	.string "Tu veux mes POKéMON, pas vrai ?$"

Route115_Text_HectorPostBattle:
	.string "J'ai ce POKéMON rare.\n"
	.string "Ça suffit à me satisfaire.$"

Route115_Text_KyraIntro:
	.string "Je combattrai en courant !\n"
	.string "Essaie de me suivre !$"

Route115_Text_KyraDefeat:
	.string "Haleine, haleine…$"

Route115_Text_KyraPostBattle:
	.string "J'ai fait l'erreur de combattre\n"
	.string "en courant !\p"
	.string "Je devrais courir pour me calmer…$"

Route115_Text_JaidenIntro:
	.string "Prends ça !\n"
	.string "Attaque ninja ultra POKéMON !$"

Route115_Text_JaidenDefeat:
	.string "Waaah !\n"
	.string "Notre stratégie a échoué !$"

Route115_Text_JaidenPostBattle:
	.string "Mais mes POKéMON étaient ultra,\n"
	.string "n'est-ce pas ?$"

Route115_Text_HeleneIntro:
	.string "Mes POKéMON ont une force\n"
	.string "de ceinture noire !$"

Route115_Text_HeleneDefeat:
	.string "C'est trop humiliant !$"

Route115_Text_HelenePostBattle:
	.string "Je rencontre rarement quelqu'un de meilleur\n"
	.string "que moi…\p"
	.string "Je comprends maintenant !\n"
	.string "Tu es un CHAMPION D'ARÈNE, n'est-ce pas ?$"

Route115_Text_AlixIntro:
	.string "Nos regards se sont croisés !\n"
	.string "Tu ne peux plus t'échapper !$"

Route115_Text_AlixDefeat:
	.string "Argh !\n"
	.string "Pas mal !$"

Route115_Text_AlixPostBattle:
	.string "Oh, bon.\n"
	.string "Je pense que je vais me TÉLÉPORTER chez moi.$"

Route115_Text_MarleneIntro:
	.string "Tu as perturbé ma méditation…\n"
	.string "Tu seras puni pour ça.$"

Route115_Text_MarleneDefeat:
	.string "Tu as brisé ma concentration !$"

Route115_Text_MarlenePostBattle:
	.string "Je méditais avec mes POKéMON.\n"
	.string "Mais cet endroit n'est pas très paisible…$"

Route116_Text_ClarkIntro:
	.string "Si le tunnel ne passe pas, alors\n"
	.string "je passerai par-dessus.$"

Route116_Text_ClarkDefeat:
	.string "Halète… Halète…\n"
	.string "La défaite m'a fatigué…$"

Route116_Text_ClarkPostBattle:
	.string "Pas de tunnel, pas grave.\n"
	.string "Pour un MONTAGNARD, les montagnes sont des routes !$"

Route116_Text_JoeyIntro:
	.string "Mes POKéMON règnent !\n"
	.string "Regarde-les !$"

Route116_Text_JoeyDefeat:
	.string "Aïe ! Une égratignure !\n"
	.string "Il faut que je mette un pansement !$"

Route116_Text_JoeyPostBattle:
	.string "Les bandages sont signes de robustesse !\n"
	.string "J'en ai un autre !$"

Route116_Text_JoseIntro:
	.string "Mes POKéMON INSECTE sont coriaces !\n"
	.string "Combattons !$"

Route116_Text_JoseDefeat:
	.string "J'ai perdu !\n"
	.string "Je pensais t'avoir !$"

Route116_Text_JosePostBattle:
	.string "Les POKéMON INSECTE évoluent vite.\n"
	.string "Ils deviennent donc forts vite aussi.$"

Route116_Text_JaniceIntro:
	.string "Laisse-moi te montrer à quel point\n"
	.string "mon adorable POKéMON est fort !$"

Route116_Text_JaniceDefeat:
	.string "Tu es un cran au-dessus de moi…$"

Route116_Text_JanicePostBattle:
	.string "Des POKéMON à la fois mignons et\n"
	.string "puissants, c'est l'idéal, je pense.$"

Route116_Text_JerryIntro:
	.string "On apprend plein de choses à l'\n"
	.string "ÉCOLE DE DRESSEURS.\p"
	.string "Je veux tester tout ça pour de vrai !$"

Route116_Text_JerryDefeat:
	.string "J'ai bavé en cours…\n"
	.string "C'est pour ça que j'ai perdu.$"

Route116_Text_JerryPostBattle:
	.string "Je vais devoir reprendre des cours à\n"
	.string "l'ÉCOLE DE DRESSEURS.\l"
	.string "Sinon, ROXANNE va être furieuse.$"

Route116_Text_JerryRegister1:
	.string "J'ai appris à l'ÉCOLE DE DRESSEURS\n"
	.string "qu'un POKéNAV peut enregistrer des DRESSEURS.\p"
	.string "Je ne comprends pas vraiment ce que ça veut dire,\n"
	.string "alors je peux essayer ?$"

Route116_Text_JerryRegister2:
	.string "J'ai appris à l'ÉCOLE DE DRESSEURS\n"
	.string "qu'un POKéNAV peut enregistrer des DRESSEURS.\p"
	.string "Je ne comprends pas vraiment ce que ça veut dire,\n"
	.string "alors je peux essayer ?$"

Route116_Text_JerryRematchIntro:
	.string "J'ai étudié sérieusement à l'\n"
	.string "ÉCOLE DE DRESSEURS.\l"
	.string "Je ne perdrai pas comme la dernière fois.$"

Route116_Text_JerryRematchDefeat:
	.string "Hein ?\n"
	.string "J'ai étudié avec application.$"

Route116_Text_JerryPostRematch:
	.string "Je vais devoir reprendre des cours à\n"
	.string "l'ÉCOLE DE DRESSEURS.\l"
	.string "Sinon, ROXANNE va être furieuse.$"

Route116_Text_KarenIntro:
	.string "J'étudie à l'école, et j'étudie aussi\n"
	.string "en rentrant à la maison !$"

Route116_Text_KarenDefeat:
	.string "Je suis sous le choc… j'ai perdu ?$"

Route116_Text_KarenPostBattle:
	.string "Aïe… Je ne deviendrai jamais un DRESSEUR\n"
	.string "élégant comme ROXANNE de cette façon !$"

Route116_Text_KarenRegister1:
	.string "Oh, waouh ! Ce n'est pas un POKéNAV ?\n"
	.string "J'en ai un aussi ! Enregistre-moi, s'il te plaît !$"

Route116_Text_KarenRegister2:
	.string "Oh, waouh ! Ce n'est pas un POKéNAV ?\n"
	.string "J'en ai un aussi ! Enregistre-moi, s'il te plaît !$"

Route116_Text_KarenRematchIntro:
	.string "J'ai beaucoup étudié depuis qu'on s'est vus.\n"
	.string "Tu dois voir mes progrès !$"

Route116_Text_KarenRematchDefeat:
	.string "Je suis sous le choc.\n"
	.string "J'ai encore perdu ?$"

Route116_Text_KarenPostRematch:
	.string "Tu as battu ROXANNE ?\n"
	.string "Je ne peux pas te battre, pas encore.$"

Route116_Text_SarahIntro:
	.string "Pour info, je n'ai jamais été battu\n"
	.string "par quiconque à quoi que ce soit.$"

Route116_Text_SarahDefeat:
	.string "Oh, mon Dieu.\n"
	.string "C'est une nouvelle expérience pour moi.$"

Route116_Text_SarahPostBattle:
	.string "Ma vie de luxe m'offre tout ce\n"
	.string "que je pourrais désirer.\p"
	.string "Cependant, quand il s'agit de POKéMON,\n"
	.string "ma richesse n'a aucun sens.$"

Route116_Text_DawsonIntro:
	.string "Quand tu poses les yeux sur la fourrure magnifique\n"
	.string "de mon POKéMON, sa beauté te rendra\l"
	.string "totalement sans défense !$"

Route116_Text_DawsonDefeat:
	.string "Oh, non, dis que ce n'est pas vrai !$"

Route116_Text_DawsonPostBattle:
	.string "Oh, non, non, non ! Tu as\n"
	.string "chiffonné la fourrure de mon POKéMON !\l"
	.string "Tu as aussi gâché ma coiffure !\l"
	.string "Il faut que j'appelle mon coiffeur !$"

Route116_Text_DevanIntro:
	.string "On va te secouer !$"

Route116_Text_DevanDefeat:
	.string "Aïe aïe aïe !\n"
	.string "Pas de concurrence du tout !$"

Route116_Text_DevanPostBattle:
	.string "Je devrais essayer différents types\n"
	.string "de POKéMON, c'est ce que je devrais faire.$"

Route116_Text_JohnsonIntro:
	.string "C'est une impasse ici.\n"
	.string "Je m'ennuie, on peut combattre ?$"

Route116_Text_JohnsonDefeat:
	.string "C'était amusant même si j'ai perdu.$"

Route116_Text_JohnsonPostBattle:
	.string "Tu veux rester ici et me\n"
	.string "tenir compagnie ?$"

Route117_Text_IsaacIntro:
	.string "Écoute, pourrais-tu combattre\n"
	.string "les POKéMON que j'élève ?$"

Route117_Text_IsaacDefeat:
	.string "Tu as élevé les tiens de façon remarquable…$"

Route117_Text_IsaacPostBattle:
	.string "Les POKéMON, ce n'est pas que\p"
	.string "la puissance. Polir un aspect unique\n"
	.string "de son caractère est une\l"
	.string "autre façon d'apprécier les POKéMON.$"

Route117_Text_IsaacRegister:
	.string "Je vais redoubler d'entraînement.\n"
	.string "Tu viendras nous voir ?$"

Route117_Text_IsaacRematchIntro:
	.string "Les POKéMON que j'élève sont en forme,\n"
	.string "comme avant.$"

Route117_Text_IsaacRematchDefeat:
	.string "Tu sais bien les élever.\n"
	.string "Tu as peut-être le talent de la PENSION…$"

Route117_Text_IsaacPostRematch:
	.string "Tes POKéMON grandissent bien !\n"
	.string "Tu devrais les inscrire aux CONCOURS.$"

Route117_Text_LydiaIntro:
	.string "S'il te plaît, laisse-moi évaluer si tu as\n"
	.string "bien élevé tes POKéMON.$"

Route117_Text_LydiaDefeat:
	.string "Oui, ils poussent correctement.$"

Route117_Text_LydiaPostBattle:
	.string "Essaie d'élever des POKéMON en accordant\n"
	.string "plus d'attention à leur caractère.$"

Route117_Text_LydiaRegister:
	.string "Je suis content d'avoir rencontré un superbe\n"
	.string "DRESSEUR comme toi. J'espère te revoir.$"

Route117_Text_LydiaRematchIntro:
	.string "Laisse-moi réévaluer si tu as\n"
	.string "bien élevé tes POKéMON.$"

Route117_Text_LydiaRematchDefeat:
	.string "Ils poussent admirablement.$"

Route117_Text_LydiaPostRematch:
	.string "Les POKéMON semblent aimer différents types\n"
	.string "de {POKEBLOCK}S, selon leur nature.$"

Route117_Text_DylanIntro:
	.string "Je suis au milieu d'un triathlon, mais\n"
	.string "bon, combattons !$"

Route117_Text_DylanDefeat:
	.string "Je n'ai plus d'énergie !$"

Route117_Text_DylanPostBattle:
	.string "J'ai peut-être raté…\p"
	.string "Je suis peut-être tombé dernier\n"
	.string "pendant ce combat…$"

Route117_Text_DylanRegister:
	.string "Les POKéMON doivent être forts, aussi ?\n"
	.string "J'aimerais que tu m'entraînes !$"

Route117_Text_DylanRematchIntro:
	.string "Je suis en plein triathlon,\n"
	.string "mais j'ai une bonne avance.\l"
	.string "Faisons vite ce combat !$"

Route117_Text_DylanRematchDefeat:
	.string "Je n'ai plus d'énergie !$"

Route117_Text_DylanPostRematch:
	.string "J'étais la meilleure en natation et en cyclisme,\n"
	.string "mais je ne suis pas encore aussi confiante avec\l"
	.string "les POKéMON.$"

Route117_Text_MariaIntro:
	.string "Je m'entraîne au triathlon avec mes POKéMON,\n"
	.string "alors je suis assez confiant dans ma vitesse.$"

Route117_Text_MariaDefeat:
	.string "Il faut que je m'entraîne davantage,\n"
	.string "je suppose.$"

Route117_Text_MariaPostBattle:
	.string "L'entraînement n'a de sens que si on le\n"
	.string "pratique régulièrement.\p"
	.string "OK ! Je reprends mon entraînement !\n"
	.string "Demain !$"

Route117_Text_MariaRegister:
	.string "Tu as l'air de t'entraîner correctement…\n"
	.string "Si tu veux, on se battra plus tard !$"

Route117_Text_MariaRematchIntro:
	.string "Tu continues ton entraînement ?\n"
	.string "Moi, oui !\l"
	.string "Laisse-moi te montrer la preuve !$"

Route117_Text_MariaRematchDefeat:
	.string "Il faut que je m'entraîne davantage,\n"
	.string "je suppose.$"

Route117_Text_MariaPostRematch:
	.string "Je reprendrai l'entraînement demain.\n"
	.string "Combattons à nouveau un jour !$"

Route117_Text_DerekIntro:
	.string "Autrefois ATTRAPEUR D'INSECTES !\n"
	.string "Et maintenant MANIAQUE D'INSECTES !\p"
	.string "Mais mon amour pour les POKéMON reste\n"
	.string "inchangé !$"

Route117_Text_DerekDefeat:
	.string "Mon ineptie reste également\n"
	.string "inchangée…$"

Route117_Text_DerekPostBattle:
	.string "J'ai seulement suivi mon cœur, et maintenant\n"
	.string "on m'appelle MANIAQUE DES INSECTES…\p"
	.string "Pourtant, je suis un expert des POKéMON INSECTE,\n"
	.string "alors c'est tout à fait normal qu'on m'appelle\l"
	.string "MANIAQUE DES INSECTES.$"

Route117_Text_AnnaIntro:
	.string "ANNA : Je suis avec ma jolie partenaire\n"
	.string "élève junior. Je dois bien me débrouiller !$"

Route117_Text_AnnaDefeat:
	.string "ANNA : Je suis avec ma jolie partenaire élève !\n"
	.string "Laisse-moi gagner !$"

Route117_Text_AnnaPostBattle:
	.string "ANNA : Tes POKéMON ont de bonnes\n"
	.string "combinaisons.\p"
	.string "Je dirais que tu es juste derrière nous !$"

Route117_Text_AnnaAndMegRegister:
	.string "ANNA : On ne peut pas laisser passer ça !\n"
	.string "Tu reviendras, n'est-ce pas ?$"

Route117_Text_AnnaNotEnoughMons:
	.string "ANNA : Si tu veux nous combattre,\n"
	.string "ramène deux POKéMON avec toi.$"

Route117_Text_MegIntro:
	.string "MEG : Je vais faire équipe avec mon super\n"
	.string "partenaire senior et te battre !$"

Route117_Text_MegDefeat:
	.string "MEG : Oh, non !\n"
	.string "Désolée, ANNA ! Je t'ai laissée tomber…$"

Route117_Text_MegPostBattle:
	.string "MEG : J'ai entraîné ANNA vers le bas…\n"
	.string "Sans moi, elle aurait gagné !$"

Route117_Text_MegNotEnoughMons:
	.string "MEG : Tu n'as qu'un seul POKéMON ?\n"
	.string "On ne peut pas se battre avec toi.\p"
	.string "On veut un combat 2 contre 2.$"

Route117_Text_AnnaRematchIntro:
	.string "ANNA : Je ne peux pas continuer à perdre\n"
	.string "devant ma partenaire junior, n'est-ce pas ?$"

Route117_Text_AnnaRematchDefeat:
	.string "ANNA : Je n'ai pas trouvé le rythme.$"

Route117_Text_AnnaPostRematch:
	.string "ANNA : Tes POKéMON ont de bonnes\n"
	.string "combinaisons.\p"
	.string "Je dirais que tu es juste derrière nous !$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "ANNA : Si tu veux nous combattre,\n"
	.string "ramène deux POKéMON avec toi.$"

Route117_Text_MegRematchIntro:
	.string "MEG : Je vais faire équipe avec ma partenaire\n"
	.string "aînée et gagner cette fois !$"

Route117_Text_MegRematchDefeat:
	.string "MEG : Trop fort !$"

Route117_Text_MegPostRematch:
	.string "MEG : J'ai combattu avec mon\n"
	.string "partenaire senior, mais on a perdu…\p"
	.string "C'est tellement décourageant…$"

Route117_Text_MegRematchNotEnoughMons:
	.string "MEG : Tu n'as qu'un seul POKéMON ?\n"
	.string "On ne peut pas se battre avec toi.\p"
	.string "On veut un combat 2 contre 2.$"

Route117_Text_MelinaIntro:
	.string "C'est agréable, non ? De combattre en\n"
	.string "admirant de jolies fleurs ?$"

Route117_Text_MelinaDefeat:
	.string "Oh, c'est tout à fait impressionnant !$"

Route117_Text_MelinaPostBattle:
	.string "C'est merveilleux de faire un jogging\n"
	.string "en regardant les fleurs.$"

Route117_Text_BrandiIntro:
	.string "Laisse-moi te montrer la puissance\n"
	.string "cachée d'un POKéMON PSY !$"

Route117_Text_BrandiDefeat:
	.string "Étonnant !$"

Route117_Text_BrandiPostBattle:
	.string "Les POKéMON PSY sont complexes.\n"
	.string "Tu devrais essayer d'en attraper.$"

Route117_Text_AishaIntro:
	.string "Concentre-toi sur la victoire.\n"
	.string "C'est comme ça que je me bats !$"

Route117_Text_AishaDefeat:
	.string "Je ne perds pas de temps à être en colère\n"
	.string "après une défaite--je préfère m'entraîner.$"

Route117_Text_AishaPostBattle:
	.string "Je pense que si tu crains de perdre,\n"
	.string "tu es plus susceptible de perdre.$"

Route118_Text_RoseIntro:
	.string "L'arôme des fleurs a un pouvoir magique.\n"
	.string "Il nous purifie corps et âme.$"

Route118_Text_RoseDefeat:
	.string "Oh, mon Dieu.\n"
	.string "Il semble que j'ai perdu.$"

Route118_Text_RosePostBattle:
	.string "Les fleurs, les POKéMON…\n"
	.string "J'adore tout ce qui sent bon.\p"
	.string "Les trucs qui puent…\n"
	.string "Passe ton chemin.$"

Route118_Text_RoseRegister:
	.string "Sniff… Cette odeur… c'est un POKéNAV !\n"
	.string "Il faut qu'on s'enregistre mutuellement !$"

Route118_Text_RoseRematchIntro:
	.string "Es-tu venu ici attiré par le doux\n"
	.string "arôme ?$"

Route118_Text_RoseRematchDefeat:
	.string "Le pouvoir de l'arôme…\n"
	.string "Ça n'a pas l'air d'avoir fait grand-chose.$"

Route118_Text_RosePostRematch:
	.string "Si tu utilises correctement un doux parfum,\n"
	.string "les POKéMON seront attirés.$"

Route118_Text_PerryIntro:
	.string "Les POKéMON Oiseau qui VOLENT avec élégance\n"
	.string "dans le ciel… Ce sont les meilleurs !$"

Route118_Text_PerryDefeat:
	.string "Urgh…\n"
	.string "J'ai crashé…$"

Route118_Text_PerryPostBattle:
	.string "Tu as de super POKéMON.\n"
	.string "Je vais devoir mieux entraîner les miens.$"

Route118_Text_ChesterIntro:
	.string "Envol !\n"
	.string "Mes POKéMON OISEAUX !$"

Route118_Text_ChesterDefeat:
	.string "Ils ont bien pris leur envol…$"

Route118_Text_ChesterPostBattle:
	.string "S'ils devenaient plus forts, ils pourraient\n"
	.string "voler plus librement…$"

Route118_Text_BarnyIntro:
	.string "Je suis PÊCHEUR, mais aussi DRESSEUR.\n"
	.string "J'élève les POKéMON que j'attrape.$"

Route118_Text_BarnyDefeat:
	.string "Je pensais m'en sortir pas mal\n"
	.string "dans mon entraînement…$"

Route118_Text_BarnyPostBattle:
	.string "Je n'ai pas pu gagner en entraînant des POKéMON\n"
	.string "en pêchant…\p"
	.string "Est-ce que je faisais les choses à moitié ?$"

Route118_Text_WadeIntro:
	.string "Pour les PÊCHEURS, l'équipement est la clé. Mais\p"
	.string "pour les DRESSEURS, les ingrédients clés sont les\n"
	.string "POKéMON et le cœur, bien sûr !$"

Route118_Text_WadeDefeat:
	.string "J'ai été battu dans mon cœur ?$"

Route118_Text_WadePostBattle:
	.string "En y réfléchissant, la pêche est un combat\n"
	.string "entre un PÊCHEUR et un POKéMON.$"

Route118_Text_DaltonIntro:
	.string "Que ma mélodie ébranle ton âme !$"

Route118_Text_DaltonDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostBattle:
	.string "Une guitare électrique n'a\n"
	.string "pas toujours besoin d'être\p"
	.string "bruyante… On peut en\n"
	.string "tirer une mélodie touchante…$"

Route118_Text_DaltonRegister:
	.string "Quand j'aurai composé de meilleures mélodies,\n"
	.string "tu devras venir écouter, d'accord ?$"

Route118_Text_DaltonRematchIntro:
	.string "Une mélodie de mes POKéMON et moi…\n"
	.string "Laisse-nous la porter jusqu'à ton âme.$"

Route118_Text_DaltonRematchDefeat:
	.string "La-lalala…$"

Route118_Text_DaltonPostRematch:
	.string "Quand je joue, mes émotions devraient\n"
	.string "te parvenir à travers ma guitare électrique…$"

Route118_Text_DeandreIntro:
	.string "Allez, allez, allez !\n"
	.string "POKéMON 1, 2 et 3 !$"

Route118_Text_DeandreDefeat:
	.string "Réponds, POKéMON ! Ça va ?\n"
	.string "POKéMON 1, 2 et 3 ?!$"

Route118_Text_DeandrePostBattle:
	.string "C'est pas cool que j'aie une équipe de combat\n"
	.string "POKéMON ?\p"
	.string "Tu peux m'imiter, je t'en prie !$"

Route119_Text_BrentIntro:
	.string "Nous sommes le CERCLE MIMIQUE !\n"
	.string "On imite tout ce que tu fais !$"

Route119_Text_BrentDefeat:
	.string "Oups !\n"
	.string "J'ai perdu !$"

Route119_Text_BrentPostBattle:
	.string "Quel intérêt à la mimétique ?\p"
	.string "Fufufu…\n"
	.string "Tu ne comprendras jamais…$"

Route119_Text_DonaldIntro:
	.string "Enfin, on se rencontre !\n"
	.string "Mes POKéMON INSECTE te tiendront compagnie !$"

Route119_Text_DonaldDefeat:
	.string "J'aurais préféré qu'on ne se soit jamais rencontrés…$"

Route119_Text_DonaldPostBattle:
	.string "Je veux encore te COPIER.\n"
	.string "Tu peux te dépêcher de bouger ?$"

Route119_Text_TaylorIntro:
	.string "Si tu avances, on avance.\p"
	.string "Si tu tournes à droite, on tourne aussi…$"

Route119_Text_TaylorDefeat:
	.string "Mais si tu gagnes, je perds…$"

Route119_Text_TaylorPostBattle:
	.string "Je ne peux pas te MIMIQUER en gagnant le match.\n"
	.string "C'est tout simplement impossible…\l"
	.string "Ça me brûle…$"

Route119_Text_DougIntro:
	.string "Oui, tu m'as enfin rattrapé !\n"
	.string "Ou tu essayais de m'éviter ?$"

Route119_Text_DougDefeat:
	.string "Youpi, c'était un super match !$"

Route119_Text_DougPostBattle:
	.string "Nous sommes le CERCLE DES MIMES !\n"
	.string "J'espère que tu as aimé notre spectacle.$"

Route119_Text_GregIntro:
	.string "Tu ne sais pas qui je suis, n'est-ce pas ?\p"
	.string "Mais moi non plus, je ne te connais pas.\n"
	.string "Alors, combattons !$"

Route119_Text_GregDefeat:
	.string "Tu es assez fort !$"

Route119_Text_GregPostBattle:
	.string "Tant que tu ne pars pas, on continuera\n"
	.string "à imiter tous tes mouvements.$"

Route119_Text_KentIntro:
	.string "Le CERCLE MIMIQUE a été formé par des gens\n"
	.string "qui aiment IMITER.\p"
	.string "Un combat commence dès qu'on se rencontre !$"

Route119_Text_KentDefeat:
	.string "Je me rends !$"

Route119_Text_KentPostBattle:
	.string "Tu ne veux pas rejoindre notre CERCLE MIMIQUE ?$"

Route119_Text_JacksonIntro:
	.string "Qui a le savoir et\n"
	.string "la technique pour survivre ?\p"
	.string "Les RANGERS POKéMON, c'est eux !$"

Route119_Text_JacksonDefeat:
	.string "Je n'avais pas assez de connaissances\n"
	.string "sur les POKéMON…$"

Route119_Text_JacksonPostBattle:
	.string "Se libérer de la civilisation et\n"
	.string "réveiller l'esprit sauvage en nous !\p"
	.string "C'est notre vision.$"

Route119_Text_JacksonRegister:
	.string "J'espère que tu me donneras une revanche\n"
	.string "sans te moquer de mon manque de connaissances.$"

Route119_Text_JacksonRematchIntro:
	.string "Je vais retrouver mon esprit sauvage\n"
	.string "en restant avec mes POKéMON.$"

Route119_Text_JacksonRematchDefeat:
	.string "Tu es resté fort !$"

Route119_Text_JacksonPostRematch:
	.string "Crois en tes POKéMON.\n"
	.string "Crois en toi.\p"
	.string "Le chemin te sera révélé.$"

Route119_Text_CatherineIntro:
	.string "Oh ? Regarde-toi.\p"
	.string "Pour quelqu'un en aventure,\n"
	.string "tu voyages bien léger.$"

Route119_Text_CatherineDefeat:
	.string "Les accidents arrivent quand on n'est\n"
	.string "pas préparé !$"

Route119_Text_CatherinePostBattle:
	.string "Tu voyages léger mais tu\n"
	.string "as tout ce qu'il faut.\p"
	.string "Tu es au top\n"
	.string "mentalement et physiquement aussi.$"

Route119_Text_CatherineRegister:
	.string "Tu as un POKéNAV ? C'est\n"
	.string "un outil indispensable pour tout DRESSEUR.\p"
	.string "Oh, tu en as un\n"
	.string "! Enregistrons-nous mutuellement, alors !$"

Route119_Text_CatherineRematchIntro:
	.string "Comment se passe ton voyage\n"
	.string "avec les POKéMON ?$"

Route119_Text_CatherineRematchDefeat:
	.string "Il me manque encore quelque chose…$"

Route119_Text_CatherinePostRematch:
	.string "De la même façon que toi, en tant que DRESSEUR,\n"
	.string "tu comptes sur tes POKéMON, tes POKéMON\l"
	.string "comptent sur toi.$"

Route119_Text_HughIntro:
	.string "Le vaste ciel recèle des promesses infinies !\p"
	.string "Rien ne vaut l'exaltation pure\n"
	.string "du vol !$"

Route119_Text_HughDefeat:
	.string "À plat ventre !$"

Route119_Text_HughPostBattle:
	.string "Mon POKéMON OISEAU a réalisé\n"
	.string "mes rêves de voler !$"

Route119_Text_PhilIntro:
	.string "Je vais te montrer le vrai potentiel de moi\n"
	.string "et de mes POKéMON Oiseau !$"

Route119_Text_PhilDefeat:
	.string "Il nous manquait du potentiel…$"

Route119_Text_PhilPostBattle:
	.string "Depuis que je suis petit, j'ai toujours\n"
	.string "admire les POKéMON Oiseau…$"

Route119_Text_YasuIntro:
	.string "Rôder dans l'ombre, vivre dans\n"
	.string "les ténèbres… C'est mon destin.\p"
	.string "Je sors pour te défier !$"

Route119_Text_YasuDefeat:
	.string "Je reconnais ma défaite !$"

Route119_Text_YasuPostBattle:
	.string "Ceux qui sont battus en combat retournent\n"
	.string "discrètement dans l'ombre.\l"
	.string "C'est aussi le destin…$"

Route119_Text_TakashiIntro:
	.string "Si tu ne restes pas sur tes gardes,\n"
	.string "tu vas avoir mal !$"

Route119_Text_TakashiDefeat:
	.string "Tu es étonnamment fort !$"

Route119_Text_TakashiPostBattle:
	.string "Mon attaque surprise s'est soldée par\n"
	.string "un échec…$"

Route119_Text_HideoIntro:
	.string "Pour cacher un arbre, utilise une forêt !$"

Route119_Text_HideoDefeat:
	.string "Je m'incline devant ta supériorité.$"

Route119_Text_HideoPostBattle:
	.string "Pour cacher un arbre, utilise une forêt !\n"
	.string "Pour cacher un POKéMON, utilise un POKéMON !\p"
	.string "Il n'y a pas de sens profond\n"
	.string "caché là-dedans.$"

Route119_Text_ChrisIntro:
	.string "Tu m'as parlé...\n"
	.string "Alors tu veux me défier !\p"
	.string "D'accord ! Je vais tester les POKéMON\n"
	.string "que j'ai attrapés en SURFANT !$"

Route119_Text_ChrisDefeat:
	.string "Je n'ai aucune idée de ce qu'il\n"
	.string "faut pour gagner.$"

Route119_Text_ChrisPostBattle:
	.string "Fais du SURF sur mon POKéMON…\p"
	.string "Puis pêche depuis son dos…\p"
	.string "C'est un moment de luxe indescriptible !$"

Route119_Text_FabianIntro:
	.string "Frappe-moi un power chord !\n"
	.string "La victoire est à moi !\l"
	.string "C'est notre moment de briller, whoa, yeah !$"

Route119_Text_FabianDefeat:
	.string "Tu m'as montré qui est le patron !\n"
	.string "On va devoir accepter la défaite, oh non !$"

Route119_Text_FabianPostBattle:
	.string "Frappe-moi un autre power chord !\n"
	.string "Laisse-moi tranquille !\l"
	.string "Ta victoire, tu dois l'expier !$"

Route119_Text_DaytonIntro:
	.string "Hohoho !\n"
	.string "J'aime les jeunes DRESSEURS !\l"
	.string "Faisons un bon combat !$"

Route119_Text_DaytonDefeat:
	.string "Tu es vraiment incroyable !\n"
	.string "Hohoho !$"

Route119_Text_DaytonPostBattle:
	.string "Hohoho !\n"
	.string "Je vais essayer d'imiter l'énergie des jeunes\l"
	.string "DRESSEURS comme toi !$"

Route119_Text_RachelIntro:
	.string "Où que je sois et quand que ce soit,\n"
	.string "j'ai toujours mon parasol à la main.$"

Route119_Text_RachelDefeat:
	.string "Oh, mais…\n"
	.string "Ce n'est pas juste.$"

Route119_Text_RachelPostBattle:
	.string "Tu demandes si mon parasol est lourd ?\n"
	.string "Ton SAC est rempli de plus de bric-à-brac\l"
	.string "que je n'en porte jamais.$"

Route120_Text_ColinIntro:
	.string "As-tu des capacités qui peuvent toucher\n"
	.string "un POKéMON volant ?$"

Route120_Text_ColinDefeat:
	.string "Tu m'as dépassé !$"

Route120_Text_ColinPostBattle:
	.string "L'attaque VOL est pratique,\n"
	.string "n'est-ce pas ?\p"
	.string "Pendant que le POKéMON vole,\n"
	.string "quasiment aucune attaque ne peut le toucher.$"

Route120_Text_RobertIntro:
	.string "Mon POKéMON est fort !\n"
	.string "Et le tien ?$"

Route120_Text_RobertDefeat:
	.string "Tes POKéMON étaient plus forts…$"

Route120_Text_RobertPostBattle:
	.string "Un POKéMON qui grandit régulièrement\n"
	.string "est un POKéMON sur qui on peut compter.$"

Route120_Text_RobertRegister:
	.string "On peut compter sur toi pour t'améliorer.\n"
	.string "J'aimerais t'enregistrer dans mon POKéNAV !$"

Route120_Text_RobertRematchIntro:
	.string "Un POKéMON qui grandit régulièrement\n"
	.string "est un POKéMON sur qui on peut compter.$"

Route120_Text_RobertRematchDefeat:
	.string "Tes POKéMON sont vraiment forts.$"

Route120_Text_RobertPostRematch:
	.string "Mes POKéMON deviennent plus forts.\n"
	.string "Il faut que je devienne plus fort aussi.$"

Route120_Text_LorenzoIntro:
	.string "Je vais examiner tes POKéMON et voir\n"
	.string "s'ils sont aptes pour l'extérieur.$"

Route120_Text_LorenzoDefeat:
	.string "Avec des POKéMON aussi forts, tu n'as\n"
	.string "pas besoin d'être secouru !$"

Route120_Text_LorenzoPostBattle:
	.string "Voyager où ton cœur te mène\n"
	.string "avec des POKéMON…\l"
	.string "C'est la joie d'être DRESSEUR.$"

Route120_Text_JennaIntro:
	.string "Comment va ta condition physique ?\n"
	.string "Si tu n'es pas en forme, tu pourrais avoir\l"
	.string "du mal dans les situations critiques.$"

Route120_Text_JennaDefeat:
	.string "Je suis en pleine forme, mais…$"

Route120_Text_JennaPostBattle:
	.string "L'entraînement physique fait partie\n"
	.string "de ma routine. Je cours toujours avec mes POKéMON.$"

Route120_Text_JeffreyIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Tu veux combattre ?$"

Route120_Text_JeffreyDefeat:
	.string "Perdu…$"

Route120_Text_JeffreyPostBattle:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Je vais essayer plus fort…$"

Route120_Text_JeffreyRegister:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "As-tu un POKéNAV… ?$"

Route120_Text_JeffreyRematchIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Tu veux te battre encore ?$"

Route120_Text_JeffreyRematchDefeat:
	.string "… … … … … …\n"
	.string "J'ai encore perdu…$"

Route120_Text_JeffreyPostRematch:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Je vais essayer plus fort…\l"
	.string "Pour mes précieux POKéMON INSECTE…$"

Route120_Text_JenniferIntro:
	.string "Les POKéMON ont de nombreuses capacités spéciales.\n"
	.string "Si tu veux devenir un DRESSEUR de premier ordre,\l"
	.string "en apprends sur elles.$"

Route120_Text_JenniferDefeat:
	.string "Tu réfléchis visiblement.$"

Route120_Text_JenniferPostBattle:
	.string "Les capacités spéciales des POKéMON\n"
	.string "changeront les styles de combat.$"

Route120_Text_ChipIntro:
	.string "Qui es-tu ? Tu cherches\p"
	.string "peut-être des ruines anciennes dont\n"
	.string "on dit qu'elles existeraient\l"
	.string "selon la légende ?$"

Route120_Text_ChipDefeat:
	.string "Quel revers humiliant…$"

Route120_Text_ChipPostBattle:
	.string "Ce rocher géant... J'aimerais croire\n"
	.string "qu'il contient peut-être des ruines\l"
	.string "anciennes. Mais je ne vois pas d'entrée.$"

Route120_Text_ClarissaIntro:
	.string "Pourquoi je porte ce parasol ?\p"
	.string "Je te le dirai si tu peux me battre.$"

Route120_Text_ClarissaDefeat:
	.string "Un parasol ne peut pas repousser\n"
	.string "les attaques POKéMON…$"

Route120_Text_ClarissaPostBattle:
	.string "Je ne pense pas que le soleil fort soit bon\n"
	.string "pour mes POKéMON.\l"
	.string "Alors je les protège avec mon parasol.$"

Route120_Text_AngelicaIntro:
	.string "Moi, mes POKéMON et mon parasol...\p"
	.string "Si l'un d'eux manque,\n"
	.string "le tableau de beauté sera gâché.$"

Route120_Text_AngelicaDefeat:
	.string "Tu as complètement gâché ma beauté…$"

Route120_Text_AngelicaPostBattle:
	.string "Un parasol ne te conviendrait pas du tout.\p"
	.string "Quelque chose comme ça ne ferait\n"
	.string "que t'embarrasser.$"

Route120_Text_KeigoIntro:
	.string "Je vais adopter les mouvements des POKéMON\n"
	.string "et créer de nouvelles techniques ninja.$"

Route120_Text_KeigoDefeat:
	.string "La création de nouvelles techniques ninja\n"
	.string "n'est qu'un rêve lointain…$"

Route120_Text_KeigoPostBattle:
	.string "Peut-être que je devrais devenir apprenti\n"
	.string "chez un maître ninja.$"

Route120_Text_RileyIntro:
	.string "Nous, les ninjas, nous cachons sous nos\n"
	.string "capes de camouflage.\l"
	.string "Je parie que tu ne savais pas où j'étais !$"

Route120_Text_RileyDefeat:
	.string "J'ai perdu !\n"
	.string "Je devrais camoufler ma honte !$"

Route120_Text_RileyPostBattle:
	.string "Nos capes de camouflage sont toutes\n"
	.string "faites à la main.$"

Route120_Text_CallieIntro:
	.string "Si tu ne fais pas attention,\n"
	.string "tu pourrais te blesser !$"

Route120_Text_CallieDefeat:
	.string "Aïe !\n"
	.string "C'est moi qui ai été blessé.$"

Route120_Text_CalliePostBattle:
	.string "Je me demande… Est-ce que je devrais faire évoluer mes POKéMON ?\n"
	.string "Ils sont mignons comme ils sont, pourtant.$"

Route120_Text_LeonelIntro:
	.string "Tes POKéMON d'équipe…\n"
	.string "As-tu des types différents ?$"

Route120_Text_LeonelDefeat:
	.string "J'ai vu ta politique en action !$"

Route120_Text_LeonelPostBattle:
	.string "Je trouve génial que tu sois si fort\n"
	.string "en combattant avec tes POKéMON préférés.$"

Route121_Text_VanessaIntro:
	.string "Tu veux jouer avec mes POKéMON\n"
	.string "délicieusement jolis ?$"

Route121_Text_VanessaDefeat:
	.string "Ce n'est pas ce que je voulais !$"

Route121_Text_VanessaPostBattle:
	.string "Je vais à un CONCOURS à NÉNUCRIQUE.\p"
	.string "Mes POKéMON ne devraient avoir aucun problème\n"
	.string "à balayer la CLASSE MAÎTRE.$"

Route121_Text_WalterIntro:
	.string "Avec mes POKéMON, j'ai voyagé\n"
	.string "aux quatre coins du monde.\p"
	.string "On pourrait dire que j'ai\n"
	.string "confiance en mes capacités.$"

Route121_Text_WalterDefeat:
	.string "Ah, bien joué.$"

Route121_Text_WalterPostBattle:
	.string "J'aimerais faire le tour du monde une fois\n"
	.string "de plus avec mes POKéMON.$"

Route121_Text_WalterRegister:
	.string "Ta maîtrise des POKéMON est remarquable.\n"
	.string "Permets-moi de t'enregistrer en souvenir.$"

Route121_Text_WalterRematchIntro:
	.string "Avec mes POKéMON, j'ai voyagé\n"
	.string "aux quatre coins du monde.\p"
	.string "On pourrait dire que j'ai\n"
	.string "confiance en mes capacités.$"

Route121_Text_WalterRematchDefeat:
	.string "Ah, bien joué.$"

Route121_Text_WalterPostRematch:
	.string "Tes POKéMON et toi…\p"
	.string "Votre prouesse ensemble sera\n"
	.string "considérée comme forte, même à l'étranger.$"

Route121_Text_TammyIntro:
	.string "Il existe des pouvoirs au-delà de\n"
	.string "notre compréhension dans ce monde…$"

Route121_Text_TammyDefeat:
	.string "J'ai perdu…$"

Route121_Text_TammyPostBattle:
	.string "MONT PYRE…\n"
	.string "Une puissance mystérieuse\l"
	.string "œuvre là-bas…$"

Route121_Text_KateIntro:
	.string "KATE : Ensemble, nous n'avons pas peur !\n"
	.string "On va montrer à quel point on est coriaces !$"

Route121_Text_KateDefeat:
	.string "KATE : J'ai tout raté devant mon partenaire\n"
	.string "élève junior…$"

Route121_Text_KatePostBattle:
	.string "KATE : Quand quelqu'un compte sur moi,\n"
	.string "j'ai envie d'avoir l'air cool devant\l"
	.string "eux…$"

Route121_Text_KateNotEnoughMons:
	.string "KATE : Si tu n'as qu'un seul POKéMON,\n"
	.string "on ne peut pas combattre avec toi.\p"
	.string "Ce serait du harcèlement.$"

Route121_Text_JoyIntro:
	.string "JOY : Ensemble, nous n'avons pas peur !\n"
	.string "On va montrer à quel point on est coriaces !$"

Route121_Text_JoyDefeat:
	.string "JOY : Pardonne-moi, KATE !$"

Route121_Text_JoyPostBattle:
	.string "JOY : Ehehe, je vais devoir m'entraîner avec KATE,\n"
	.string "mon partenaire senior, à nouveau.$"

Route121_Text_JoyNotEnoughMons:
	.string "JOY : Il te faut au moins deux POKéMON\n"
	.string "si tu veux nous défier !$"

Route121_Text_JessicaIntro:
	.string "Stop ! Regarde bien mes\n"
	.string "précieux POKéMON !$"

Route121_Text_JessicaDefeat:
	.string "Oh, comment oses-tu !\n"
	.string "Ne le prends pas si au sérieux !$"

Route121_Text_JessicaPostBattle:
	.string "Peut-être que j'irai attraper plus de POKéMON\n"
	.string "au SAFARI.$"

Route121_Text_JessicaRegister:
	.string "Je t'ai laissé gagner cette fois !\n"
	.string "Ce ne sera pas pareil la prochaine fois !$"

Route121_Text_JessicaRematchIntro:
	.string "Mon précieux POKéMON a grandi !\n"
	.string "Regarde bien !$"

Route121_Text_JessicaRematchDefeat:
	.string "Oh, comment oses-tu !\n"
	.string "Tu ne te retiens toujours pas !$"

Route121_Text_JessicaPostRematch:
	.string "Peut-être que j'irai attraper plus de POKéMON\n"
	.string "au SAFARI.$"

Route121_Text_CristinIntro:
	.string "J'ai cette routine.\n"
	.string "Battre cinq DRESSEURS par jour.\l"
	.string "Devine quoi ? Tu es le cinquième !$"

Route121_Text_CristinDefeat:
	.string "Non !\n"
	.string "Tu es méchant !$"

Route121_Text_CristinPostBattle:
	.string "Je ne pensais pas perdre si facilement…\n"
	.string "Je gagnerai la prochaine fois !$"

Route121_Text_CristinRegister:
	.string "C'était une humiliation totale !\n"
	.string "Je ne t'oublierai pas…\l"
	.string "Donne-moi ton POKéNAV !$"

Route121_Text_CristinRematchIntro:
	.string "J'ai une nouvelle routine.\n"
	.string "Battre dix DRESSEURS par jour.\l"
	.string "Devine quoi ? Tu es le dixième !$"

Route121_Text_CristinRematchDefeat:
	.string "Attends ! C'est méchant !\n"
	.string "Je réclame une revanche !$"

Route121_Text_CristinPostRematch:
	.string "Un adversaire que je n'arrive pas à battre…\n"
	.string "Snif…\l"
	.string "Je n'arrive pas à y croire…$"

Route121_Text_CaleIntro:
	.string "Tu ne vois pas que j'ai plein de\n"
	.string "affaires sur moi ?\p"
	.string "Malgré ça, tu insistes pour\n"
	.string "qu'on se batte ?$"

Route121_Text_CaleDefeat:
	.string "Bien sûr que j'ai perdu !\n"
	.string "J'ai des trucs dans les deux mains !$"

Route121_Text_CalePostBattle:
	.string "J'ai trop acheté au GRAND MAGASIN\n"
	.string "de NÉNUCRIQUE. C'est en haut\p"
	.string "de la route. J'aimerais avoir\n"
	.string "un SAC comme le tien.$"

Route121_Text_MylesIntro:
	.string "Il n'y a rien que j'aime plus que\n"
	.string "regarder les POKéMON des autres !$"

Route121_Text_MylesDefeat:
	.string "Super génial !$"

Route121_Text_MylesPostBattle:
	.string "Ils sont super, tes POKéMON !\n"
	.string "Comment tu les élèves ?$"

Route121_Text_PatIntro:
	.string "Je veux que tout le monde voie\n"
	.string "les POKéMON que j'ai élevés !$"

Route121_Text_PatDefeat:
	.string "Ouah !\n"
	.string "Spectaculaire !$"

Route121_Text_PatPostBattle:
	.string "J'élève chaque POKéMON avec le même\n"
	.string "amour et les mêmes soins--je n'en favorise aucun.$"

Route121_Text_MarcelIntro:
	.string "Mes POKéMON n'ont jamais goûté la défaite !\n"
	.string "À leur prochaine victoire, je les inscris\l"
	.string "à des CONCOURS.$"

Route121_Text_MarcelDefeat:
	.string "Oh, qu'est-ce qui s'est passé ici ?$"

Route121_Text_MarcelPostBattle:
	.string "Il faudra peut-être que j'entraîne mon équipe\n"
	.string "avant de participer à un CONCOURS.$"

Route123_Text_WendyIntro:
	.string "Tu veux mesurer ta force ?\n"
	.string "Je serai le test !$"

Route123_Text_WendyDefeat:
	.string "Tu as réussi haut la main !$"

Route123_Text_WendyPostBattle:
	.string "Me battre à moi…\n"
	.string "Ta force est merveilleuse !$"

Route123_Text_BraxtonIntro:
	.string "Tu sembles avoir une belle collection\n"
	.string "de BADGES D'ARÈNE.\p"
	.string "Voyons si tu mérites vraiment\n"
	.string "ces BADGES !$"

Route123_Text_BraxtonDefeat:
	.string "Oh, tu es digne, c'est sûr !$"

Route123_Text_BraxtonPostBattle:
	.string "Tu as honoré tes BADGES\n"
	.string "dans ce match !$"

Route123_Text_VioletIntro:
	.string "On dit que les bons moments\n"
	.string "sont remplis de bonnes odeurs.$"

Route123_Text_VioletDefeat:
	.string "Oh…\n"
	.string "Je sens l'âcre parfum du malheur…$"

Route123_Text_VioletPostBattle:
	.string "Le jardin du MAÎTRE DES BAIES est rempli\n"
	.string "de parfums revigorants.$"

Route123_Text_CameronIntro:
	.string "Être un psy, c'est une question de volonté.\p"
	.string "Je me suis imposé de ne perdre contre\n"
	.string "personne. Ça me rend fort !$"

Route123_Text_CameronDefeat:
	.string "Je suis triste…$"

Route123_Text_CameronPostBattle:
	.string "Être psychique, c'est une question de volonté.\n"
	.string "Je pensais ne pas perdre contre toi…$"

Route123_Text_CameronRegister:
	.string "Je le sens !\n"
	.string "Toi et moi, on se battra encore !\l"
	.string "Je ne sais pas si je gagnerai...\p"
	.string "Montre-moi ton POKéNAV.$"

Route123_Text_CameronRematchIntro:
	.string "Je me suis convaincu que je ne perdrai plus.\n"
	.string "Ça me rend fort !$"

Route123_Text_CameronRematchDefeat:
	.string "Je suis triste…$"

Route123_Text_CameronPostRematch:
	.string "Je devrais m'entraîner au MONT PYRE…\n"
	.string "Je ne te battrai jamais comme ça…$"

Route123_Text_JackiIntro:
	.string "Ne te réjouis pas trop si\n"
	.string "ton POKéMON développe des pouvoirs psychiques.\p"
	.string "Il faut affiner ces pouvoirs\n"
	.string "pour les rendre vraiment utiles.$"

Route123_Text_JackiDefeat:
	.string "Submergé !$"

Route123_Text_JackiPostBattle:
	.string "Nous avons tous des pouvoirs psychiques.\n"
	.string "Nous avons juste oublié comment les utiliser.$"

Route123_Text_JackiRegister:
	.string "J'aimerais t'affronter à nouveau.\n"
	.string "Ça te va ?$"

Route123_Text_JackiRematchIntro:
	.string "As-tu éveillé les pouvoirs psychiques\n"
	.string "en toi ?$"

Route123_Text_JackiRematchDefeat:
	.string "Stupéfiant !$"

Route123_Text_JackiPostRematch:
	.string "Ta force avec les POKéMON…\n"
	.string "Ça pourrait être un pouvoir psychique aussi.$"

Route123_Text_MiuIntro:
	.string "MIU : Bonjour, DRESSEUR. J'espère que tes\n"
	.string "POKéMON ne pleureront pas en perdant.$"

Route123_Text_MiuDefeat:
	.string "MIU : Oh-oh, on a perdu.$"

Route123_Text_MiuPostBattle:
	.string "MIU : DRESSEUR, tes POKéMON sont\n"
	.string "forts parce que vous êtes amis.$"

Route123_Text_MiuNotEnoughMons:
	.string "MIU : Ce n'est pas amusant de combattre\n"
	.string "si tu n'as pas deux POKéMON.$"

Route123_Text_YukiIntro:
	.string "YUKI : OK !\n"
	.string "On bat les POKéMON du DRESSEUR !$"

Route123_Text_YukiDefeat:
	.string "YUKI : Oh-oh, on a perdu.$"

Route123_Text_YukiPostBattle:
	.string "YUKI : Pourquoi es-tu si fort ?\n"
	.string "On n'avait jamais perdu avant.$"

Route123_Text_YukiNotEnoughMons:
	.string "YUKI : Ce n'est pas amusant de combattre si\n"
	.string "tu n'as pas deux POKéMON.$"

Route123_Text_KindraIntro:
	.string "MONT PYRÉ…\n"
	.string "Où dorment les esprits des POKéMON…\l"
	.string "Tes POKéMON vont-ils dormir ?$"

Route123_Text_KindraDefeat:
	.string "Débordant de vitalité…$"

Route123_Text_KindraPostBattle:
	.string "MONT SÉLÉNITE...\n"
	.string "Où dorment les esprits des POKéMON...\p"
	.string "Il doit déborder d'un pouvoir\n"
	.string "qui apaise les esprits...$"

Route123_Text_FernandoIntro:
	.string "Je vais t'éteindre pendant que\n"
	.string "je déchire cette mélodie !$"

Route123_Text_FernandoDefeat:
	.string "Hé, attends !\n"
	.string "Je jouais encore l'intro !$"

Route123_Text_FernandoPostBattle:
	.string "Tu es solide comme un roc.\n"
	.string "J'aimerais écrire une chanson sur toi.$"

Route123_Text_FernandoRegister:
	.string "La prochaine fois, écoute la mélodie\n"
	.string "entière, d'accord ?$"

Route123_Text_FernandoRematchIntro:
	.string "Aujourd'hui, c'est le jour !\n"
	.string "Je vais t'éteindre avant\l"
	.string "d'avoir fini ma chanson !$"

Route123_Text_FernandoRematchDefeat:
	.string "Hé, attends !\n"
	.string "Je n'ai même pas atteint le refrain !$"

Route123_Text_FernandoPostRematch:
	.string "Je pensais que tu serais tellement captivé\n"
	.string "par ma mélodie que tu perdrais.$"

Route123_Text_DavisIntro:
	.string "Voici mon super POKéMON INSECTE !\n"
	.string "Mon grand frère me l'a offert.$"

Route123_Text_DavisDefeat:
	.string "Waaaah !\n"
	.string "Méchant !$"

Route123_Text_DavisPostBattle:
	.string "Ne dis pas à mon frère que j'ai perdu.\n"
	.string "Tu dois garder le secret !$"

Route123_Text_JazmynIntro:
	.string "Ma confiance va monter en\n"
	.string "battant quelqu'un de manifestement fort !$"

Route123_Text_JazmynDefeat:
	.string "Là s'en va ma confiance…$"

Route123_Text_JazmynPostBattle:
	.string "On dit qu'il ne faut pas juger quelqu'un\n"
	.string "à son apparence.\p"
	.string "Mais souvent, les apparences ne trompent pas…$"

Route123_Text_FrederickIntro:
	.string "Bonjour, mon enfant !\n"
	.string "Tu as un peu de temps ?$"

Route123_Text_FrederickDefeat:
	.string "Ah, un enfant bien capable !\n"
	.string "Laisse-moi contribuer à tes économies.$"

Route123_Text_FrederickPostBattle:
	.string "Contribuer à ton argent de poche ?\n"
	.string "L'argent du prix ne suffisait pas ?$"

Route123_Text_AlbertoIntro:
	.string "Je dois te dire, les POKéMON Oiseau\n"
	.string "sont mon obsession !\p"
	.string "Les oiseaux, c'est cool !\n"
	.string "C'est les meilleurs !$"

Route123_Text_AlbertoDefeat:
	.string "Même en défaite, les POKéMON OISEAU sont cool !$"

Route123_Text_AlbertoPostBattle:
	.string "Je collectionne les plumes de\n"
	.string "POKéMON OISEAU qui s'envolent pendant\p"
	.string "les combats. Je vais faire\n"
	.string "un chapeau avec ces plumes.$"

Route123_Text_EdIntro:
	.string "Quand il n'y a pas de DRESSEURS,\n"
	.string "je fais combattre mes POKéMON entre eux.\l"
	.string "Je les regarde.$"

Route123_Text_EdDefeat:
	.string "J'aime bien tes POKéMON.$"

Route123_Text_EdPostBattle:
	.string "Héhé, je vole tes idées de combat !\n"
	.string "Je pense qu'elles vont me rendre meilleur.$"

Route123_Text_JonasIntro:
	.string "J'ai tendu une embuscade, et un DRESSEUR\n"
	.string "est tombé dans mon piège !$"

Route123_Text_JonasDefeat:
	.string "Si tu ne perds pas, comment suis-je censé\n"
	.string "m'amuser à jouer au ninja ?$"

Route123_Text_JonasPostBattle:
	.string "La prochaine fois, je vais tendre une embuscade\n"
	.string "à un DRESSEUR qui a l'air faible.$"

Route123_Text_KayleyIntro:
	.string "Je viens d'acheter ce parasol.\n"
	.string "Ma mignonnerie devrait augmenter d'un tiers !$"

Route123_Text_KayleyDefeat:
	.string "Tu es environ cinq fois\n"
	.string "meilleur que moi !$"

Route123_Text_KayleyPostBattle:
	.string "Utiliser les accessoires efficacement est\n"
	.string "le secret d'un style à la mode.$"

Route124_Text_SpencerIntro:
	.string "Hé, tu es perdu en mer ?\p"
	.string "Si tu bats mes POKéMON,\n"
	.string "je peux servir de pilote.$"

Route124_Text_SpencerDefeat:
	.string "J'ai perdu mes repères en combat !$"

Route124_Text_SpencerPostBattle:
	.string "Beaucoup de gens perdent leurs repères en mer.\p"
	.string "Si c'est ton cas, consulte\n"
	.string "la CARTE du POKéNAV.$"

Route124_Text_RolandIntro:
	.string "Hm ! Tu chevauches un POKéMON au lieu\n"
	.string "de nager toi-même…\p"
	.string "Je t'envie !$"

Route124_Text_RolandDefeat:
	.string "Oh !\n"
	.string "Je n'y arrive pas…$"

Route124_Text_RolandPostBattle:
	.string "J'ai froid…\n"
	.string "Je suis resté trop longtemps dans l'eau…\p"
	.string "J'aimerais pouvoir monter un POKéMON comme toi…$"

Route124_Text_JennyIntro:
	.string "Si tu flottes dans la mer comme\n"
	.string "ça, des POKéMON viennent jouer.$"

Route124_Text_JennyDefeat:
	.string "Oh, zut.\n"
	.string "J'ai encore perdu.$"

Route124_Text_JennyPostBattle:
	.string "En nageant, j'ai remarqué que certains\n"
	.string "POKéMON attaquent et d'autres regardent.\p"
	.string "Les POKéMON ont leur propre\n"
	.string "personnalité, j'imagine.$"

Route124_Text_JennyRegister:
	.string "C'est juste sur un coup de tête, mais peut-être que je vais\n"
	.string "te faire m'enregistrer dans mon POKéNAV.$"

Route124_Text_JennyRematchIntro:
	.string "Si tu flottes dans la mer comme ça,\n"
	.string "les DRESSEURS te défient !$"

Route124_Text_JennyRematchDefeat:
	.string "C'est bizarre…\n"
	.string "J'ai encore perdu…$"

Route124_Text_JennyPostRematch:
	.string "Ça n'a rien à voir avec tout ça,\n"
	.string "mais je vais peut-être visiter la MAISON PIKACHU.$"

Route124_Text_GraceIntro:
	.string "Je m'ennuie de nager…\n"
	.string "Et si on se battait ?$"

Route124_Text_GraceDefeat:
	.string "Je ne savais pas que tu étais\n"
	.string "si fort !$"

Route124_Text_GracePostBattle:
	.string "Tous les efforts que tu as fournis\n"
	.string "doivent t'avoir rendu si fort.$"

Route124_Text_ChadIntro:
	.string "Fufufufu… Je plonge au plus profond\n"
	.string "de l'océan pour mener une vie secrète.\l"
	.string "Sonder les abysses, c'est mon domaine !$"

Route124_Text_ChadDefeat:
	.string "Gloub, gloub, gloub…\n"
	.string "Je coule…$"

Route124_Text_ChadPostBattle:
	.string "J'ai la certitude qu'il y a un spot\n"
	.string "PLONGÉE par ici.\p"
	.string "Ça me donne envie de replonger\n"
	.string "profondément...$"

Route124_Text_LilaIntro:
	.string "LILA : Soupir… Me voilà en\p"
	.string "mer, mais qui est avec moi\n"
	.string "? Mon petit frère !\p"
	.string "Battons-nous pour que je n'aie\n"
	.string "pas à y penser !$"

Route124_Text_LilaDefeat:
	.string "LILA : ROY ! C'est de ta faute qu'on a perdu !\n"
	.string "Tu vas le payer plus tard !$"

Route124_Text_LilaPostBattle:
	.string "LILA : Soupir…\p"
	.string "Si seulement ce n'était pas mon petit frère\n"
	.string "à côté de moi, mais un gentil petit ami…$"

Route124_Text_LilaNotEnoughMons:
	.string "LILA : Tu comptes nous combattre ?\n"
	.string "Pas sans deux POKéMON.$"

Route124_Text_RoyIntro:
	.string "ROY : Ma grande sœur est coriace aux POKéMON !\p"
	.string "Ne pleure pas quand tu perdras !$"

Route124_Text_RoyDefeat:
	.string "ROY : Oh-oh…\n"
	.string "Ma grande sœur va me gronder…$"

Route124_Text_RoyPostBattle:
	.string "ROY : Ma grande sœur fait vraiment peur\n"
	.string "quand elle se met en colère.\p"
	.string "C'est pour ça qu'elle n'a pas de\n"
	.string "copain.$"

Route124_Text_LilaRoyRegister:
	.string "ROY : Tu combattras à nouveau avec nous ?\n"
	.string "Mais fais attention la prochaine fois, OK ?$"

Route124_Text_RoyNotEnoughMons:
	.string "ROY : Tu voulais nous combattre ?\n"
	.string "Ramène deux POKéMON, alors.$"

Route124_Text_LilaRematchIntro:
	.string "LILA : Soupir…\p"
	.string "Me voilà à la mer, mais qui est avec moi ?\n"
	.string "Mon petit frère !\p"
	.string "Oh, salut, ça fait un moment. Battons-nous\n"
	.string "pour que je n'aie pas à y penser !$"

Route124_Text_LilaRematchDefeat:
	.string "LILA : ROY !\n"
	.string "C'est de ta faute qu'on a encore perdu !\p"
	.string "On va s'entraîner plus tard !$"

Route124_Text_LilaPostRematch:
	.string "LILA : Soupir…\p"
	.string "Si j'avais un gentil petit ami, on battrait\n"
	.string "n'importe qui avec de belles combinaisons…$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "LILA : Tu comptes nous combattre ?\n"
	.string "Pas sans deux POKéMON.$"

Route124_Text_RoyRematchIntro:
	.string "ROY : Si on perd, je vais attraper des ennuis.\n"
	.string "Je vais tout donner !$"

Route124_Text_RoyRematchDefeat:
	.string "ROY : Oh-oh…\n"
	.string "Ma grande sœur va encore me gronder.$"

Route124_Text_RoyPostRematch:
	.string "ROY : Ma grande sœur fait\n"
	.string "vraiment peur quand elle se met\p"
	.string "en colère. Elle va me faire\n"
	.string "m'entraîner dur avec des POKéMON après…$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "ROY : Tu voulais nous combattre ?\n"
	.string "Ramène deux POKéMON, alors.$"

Route124_Text_DeclanIntro:
	.string "Me voilà à nager tout seul\n"
	.string "sur cette vaste et belle\p"
	.string "mer. Il n'y a pas\n"
	.string "d'autre mot. C'est pathétique !$"

Route124_Text_DeclanDefeat:
	.string "Je me sens triste.\n"
	.string "Bleu comme le ciel…$"

Route124_Text_DeclanPostBattle:
	.string "Je devrais draguer les nageuses\n"
	.string "et les inviter à une longue baignade.$"

Route124_Text_IsabellaIntro:
	.string "Je ne vais pas perdre contre un\n"
	.string "DRESSEUR surfeur.$"

Route124_Text_IsabellaDefeat:
	.string "J'ai juste de la sueur dans les yeux !\n"
	.string "Je ne pleure pas !$"

Route124_Text_IsabellaPostBattle:
	.string "Tu peux trouver de jolies éclats\n"
	.string "de couleur par ici.$"

Route125_Text_NolenIntro:
	.string "Je t'ai entendu approcher, alors\n"
	.string "je suis resté pour toi !$"

Route125_Text_NolenDefeat:
	.string "Je me rends !$"

Route125_Text_NolenPostBattle:
	.string "Le son se propage plus vite dans l'eau\n"
	.string "que dans l'air.$"

Route125_Text_StanIntro:
	.string "Hé, toi !\n"
	.string "Regarde mes super POKéMON !$"

Route125_Text_StanDefeat:
	.string "J'ai pataugé…$"

Route125_Text_StanPostBattle:
	.string "J'ai été emporté par le charme d'HYPOTREMPE,\n"
	.string "alors j'ai commencé à nager aussi.$"

Route125_Text_TanyaIntro:
	.string "J'en ai assez de nager.\n"
	.string "Tu veux te battre avec moi ?$"

Route125_Text_TanyaDefeat:
	.string "Tu es trop fort !$"

Route125_Text_TanyaPostBattle:
	.string "Ouf…\n"
	.string "Dans quelle direction est MOSSDEEP ?$"

Route125_Text_SharonIntro:
	.string "Que dirais-tu d'affronter les\n"
	.string "POKéMON de type EAU que j'ai élevés ?$"

Route125_Text_SharonDefeat:
	.string "Perdu…$"

Route125_Text_SharonPostBattle:
	.string "Ta puissance… Tu es du vrai calibre.\n"
	.string "Je suis impressionné !$"

Route125_Text_ErnestIntro:
	.string "Ahoy ! Je suis un MARIN costaud et musclé !\n"
	.string "J'ai bravé les mers du monde entier !$"

Route125_Text_ErnestDefeat:
	.string "Gwrroooar !\n"
	.string "Je n'ai pas réussi à gagner !$"

Route125_Text_ErnestPostBattle:
	.string "La marée monte et descend dans la\n"
	.string "GROTTE AMARYLLE.\p"
	.string "Au fait, il faut environ six heures de\n"
	.string "marée haute à basse. Tu le savais ?$"

Route125_Text_ErnestRegister:
	.string "Enregistre-moi dans ton POKéNAV,\n"
	.string "et je te dirai quelque chose de bien.$"

Route125_Text_ErnestRematchIntro:
	.string "Il est temps que je me venge de toi !\n"
	.string "Allez, on se bat !$"

Route125_Text_ErnestRematchDefeat:
	.string "Je n'ai pas pu gagner !\n"
	.string "Je n'ai vraiment pas pu gagner !$"

Route125_Text_ErnestRematchPostBattle:
	.string "La GROTTE AMARRE…\p"
	.string "Il y a des endroits accessibles ou non\n"
	.string "selon la montée et la descente\l"
	.string "des marées.\p"
	.string "Au fait, il faut environ six heures entre\n"
	.string "marée haute et marée basse. N'oublie pas !$"

Route125_Text_KimIntro:
	.string "KIM : Un drôle de vieux monsieur habite dans la\n"
	.string "GROTTE D'AMONITAIRE. Quelqu'un m'a dit.\l"
	.string "Tu vas le voir, toi aussi ?$"

Route125_Text_KimDefeat:
	.string "KIM : Je pensais qu'on allait gagner.$"

Route125_Text_KimPostBattle:
	.string "KIM : Un drôle de vieil homme vit dans\n"
	.string "la GROTTE AMPOULE, non ?\p"
	.string "Allons le voir, IRIS !$"

Route125_Text_KimNotEnoughMons:
	.string "KIM : Non, non, non ! Il te faut deux POKéMON,\n"
	.string "sinon ça ne sert à rien !$"

Route125_Text_IrisIntro:
	.string "IRIS : KIM, tu peux me dire ce qu'on\n"
	.string "cherche ici ?$"

Route125_Text_IrisDefeat:
	.string "IRIS : Oh, on s'en est approchés.$"

Route125_Text_IrisPostBattle:
	.string "IRIS : KIM, on va vraiment entrer\n"
	.string "dans la GROTTE AMONITAIRE ?\l"
	.string "On va être trempés.$"

Route125_Text_IrisNotEnoughMons:
	.string "IRIS : Oh, on ne pourrait jamais, jamais\n"
	.string "faire quelque chose comme un combat 2 contre 1.$"

Route125_Text_PresleyIntro:
	.string "Pourquoi un ÉLEVEUR D'OISEAUX comme moi\n"
	.string "viendrait en mer ?$"

Route125_Text_PresleyDefeat:
	.string "OK.\n"
	.string "Je vais te dire pourquoi je suis ici.$"

Route125_Text_PresleyPostBattle:
	.string "J'ai mis un message dans une bouteille et je l'ai\n"
	.string "jetée à la mer.\p"
	.string "Je suis sûr qu'une NAGEUSE va\n"
	.string "la trouver !$"

Route125_Text_AuronIntro:
	.string "Hé ! C'était toi qui jetait des déchets\n"
	.string "dans la mer ?$"

Route125_Text_AuronDefeat:
	.string "Oh, tu ne jetais pas de déchets\n"
	.string "dans la mer.$"

Route125_Text_AuronPostBattle:
	.string "J'ai trouvé une vilaine bouteille qui\n"
	.string "flottait dans les vagues tout à l'heure.\p"
	.string "Ça m'énerve que quelqu'un pollue\n"
	.string "la mer !$"

Route126_Text_BarryIntro:
	.string "La natation, c'est un entraînement complet !\n"
	.string "Tu vas te mettre en forme !$"

Route126_Text_BarryDefeat:
	.string "J'avoue !\n"
	.string "Tu gagnes !$"

Route126_Text_BarryPostBattle:
	.string "Grâce à ma routine de natation quotidienne…\n"
	.string "Regarde ! Contemple ce physique !$"

Route126_Text_DeanIntro:
	.string "Cette montagne blanche imposante de roche\n"
	.string "est la ville d'ATALANOPOLIS.$"

Route126_Text_DeanDefeat:
	.string "J'ai été battu ?$"

Route126_Text_DeanPostBattle:
	.string "Je ne trouve pas l'entrée d'\n"
	.string "ATALANOPOLIS. Où est-elle ?$"

Route126_Text_NikkiIntro:
	.string "Ufufufufu !\n"
	.string "Je suis une sirène !$"

Route126_Text_NikkiDefeat:
	.string "Mon fantasme a éclaté comme une bulle !\n"
	.string "Blub, blub, blub…$"

Route126_Text_NikkiPostBattle:
	.string "Tu m'as écrasé… Je veux\n"
	.string "disparaître dans un océan de désespoir…$"

Route126_Text_BrendaIntro:
	.string "Salut, gamin !\n"
	.string "Tu veux te battre avec moi ?$"

Route126_Text_BrendaDefeat:
	.string "Oh, noooooon !$"

Route126_Text_BrendaPostBattle:
	.string "J'adore gambader avec les POKéMON\n"
	.string "dans la mer comme ça !$"

Route126_Text_PabloIntro:
	.string "Regarde ce corps sculpté !\n"
	.string "Je suis plus musclé qu'une CEINTURE NOIRE !$"

Route126_Text_PabloDefeat:
	.string "Oups ! Trop fort !\n"
	.string "Pas mal ! Pas mal du tout !$"

Route126_Text_PabloPostBattle:
	.string "Perdre contre toi a stimulé mes sens !\n"
	.string "Je vais m'entraîner plus dur, moi et mes POKéMON !$"

Route126_Text_PabloRegister:
	.string "Oui, tu n'es pas mal du tout !\n"
	.string "J'aimerais mieux te connaître !$"

Route126_Text_PabloRematchIntro:
	.string "Regarde ce beau corps !\n"
	.string "Je suis plus élancé qu'un NAGEUR !$"

Route126_Text_PabloRematchDefeat:
	.string "Oups ! Vraiment trop fort !\n"
	.string "Pas mal ! Pas mal du tout !$"

Route126_Text_PabloPostRematch:
	.string "Je vais m'entraîner encore plus fort !\n"
	.string "Tu es une super motivation !\l"
	.string "Il faut que tu reviennes !$"

Route126_Text_LeonardoIntro:
	.string "L'année dernière, je ne savais même pas nager,\n"
	.string "mais maintenant je suis un bon NAGEUR.\p"
	.string "Je crois que je suis capable de tout maintenant.$"

Route126_Text_LeonardoDefeat:
	.string "Zut, être trop gourmand\n"
	.string "ne m'a servi à rien.$"

Route126_Text_LeonardoPostBattle:
	.string "Si tu t'entraînes à quelque\n"
	.string "chose, tu t'améliores. Tu es\p"
	.string "jeune, n'aie pas peur d'essayer\n"
	.string "toutes sortes de choses !$"

Route126_Text_IsobelIntro:
	.string "Quand l'eau de mer te monte au nez,\n"
	.string "ce n'est pas horrible ?$"

Route126_Text_IsobelDefeat:
	.string "Argh ! Espèce de…\n"
	.string "Gloups !$"

Route126_Text_IsobelPostBattle:
	.string "Ooh, j'ai avalé de l'eau !\n"
	.string "C'est amer ! C'est salé !!$"

Route126_Text_SiennaIntro:
	.string "Je mets tout mon cœur\n"
	.string "dans ça !$"

Route126_Text_SiennaDefeat:
	.string "Tu avais plus de cœur !$"

Route126_Text_SiennaPostBattle:
	.string "J'ai besoin de me rafraîchir…\n"
	.string "Je crois que je vais plonger.$"

Route127_Text_CamdenIntro:
	.string "Je le vois sur ton visage.\n"
	.string "Tu veux me défier.$"

Route127_Text_CamdenDefeat:
	.string "Awawawawawa…$"

Route127_Text_CamdenPostBattle:
	.string "Un match bien joué me laisse\n"
	.string "une sensation de fraîcheur et de sérénité.$"

Route127_Text_DonnyIntro:
	.string "As-tu un rival à qui tu détesterais\n"
	.string "de perdre face ?$"

Route127_Text_DonnyDefeat:
	.string "Arrrgh !\n"
	.string "Je déteste perdre !$"

Route127_Text_DonnyPostBattle:
	.string "Si tu as un rival, tu n'as pas le sentiment\n"
	.string "qu'il faut continuer à s'améliorer\l"
	.string "?$"

Route127_Text_JonahIntro:
	.string "Grâce à la pêche, j'ai atteint un état\n"
	.string "de sérénité parfaite...\p"
	.string "Permets-moi de te le démontrer...$"

Route127_Text_JonahDefeat:
	.string "Bien que j'aie perdu, mon cœur\n"
	.string "reste calme…$"

Route127_Text_JonahPostBattle:
	.string "Peu importe que je ne prenne rien.\n"
	.string "La ligne reste dans l'eau…$"

Route127_Text_HenryIntro:
	.string "Oups ! Ne me dis pas que j'ai attrapé\n"
	.string "un POKéMON SURFEUR ?$"

Route127_Text_HenryDefeat:
	.string "Je n'arrive pas à suivre !$"

Route127_Text_HenryPostBattle:
	.string "Ce serait coriace si j'accrochais\n"
	.string "tes POKéMON costauds !$"

Route127_Text_RogerIntro:
	.string "Eh bien ! Voilà un combat entre\n"
	.string "un fan de POKéMON et un accro à la pêche !$"

Route127_Text_RogerDefeat:
	.string "Non ! Ma ligne est emmêlée !\n"
	.string "La fête est finie !$"

Route127_Text_RogerPostBattle:
	.string "Ma ligne de pêche danse !\n"
	.string "La danse des nœuds ! Hahaha, emmêlée !$"

Route127_Text_AidanIntro:
	.string "Les POKéMON OISEAU ont une excellente vision.\n"
	.string "Ils repèrent leur proie de très haut.$"

Route127_Text_AidanDefeat:
	.string "Ouf… J'abandonne.$"

Route127_Text_AidanPostBattle:
	.string "Il y a plein de spots de plongée\n"
	.string "dans la mer par ici.\p"
	.string "On les repère facilement du ciel\n"
	.string "grâce à leur couleur plus foncée.$"

Route127_Text_KojiIntro:
	.string "Cours pieds nus.\n"
	.string "Ça durcira tes plantes de pieds !$"

Route127_Text_KojiDefeat:
	.string "Aïe !\n"
	.string "J'ai un caillou sous un orteil !$"

Route127_Text_KojiPostBattle:
	.string "Marcher pieds nus, c'est génial.\n"
	.string "Mais tes CHAUSSURES DE COURSE sont cool aussi.$"

Route127_Text_KojiRegister:
	.string "C'est ce que je fais aux gens qui me battent !\n"
	.string "J'espère qu'on pourra recommencer.$"

Route127_Text_KojiRematchIntro:
	.string "Je cours encore pieds nus chaque jour.\n"
	.string "Mes plantes de pieds sont dures !$"

Route127_Text_KojiRematchDefeat:
	.string "Aïe !\n"
	.string "Des cailloux se sont logés dans mes voûtes !$"

Route127_Text_KojiPostRematch:
	.string "Tu veux marcher pieds nus un moment ?\n"
	.string "Pour que j'essaie tes CHAUSSURES DE COURSE ?$"

Route127_Text_AthenaIntro:
	.string "On devrait avoir un match lent\n"
	.string "et méthodique.$"

Route127_Text_AthenaDefeat:
	.string "Tu ne m'as pas laissé le temps\n"
	.string "de faire une stratégie.$"

Route127_Text_AthenaPostBattle:
	.string "Quand je suis entouré de la mer bleue\n"
	.string "et du ciel, on dirait que le temps ralentit.$"

Route128_Text_IsaiahIntro:
	.string "EVER GRANDE est encore\n"
	.string "loin…$"

Route128_Text_IsaiahDefeat:
	.string "Ma première victoire semble aussi\n"
	.string "loin…$"

Route128_Text_IsaiahPostBattle:
	.string "J'ai passé ma vie à perdre,\n"
	.string "mais je n'abandonnerai jamais !$"

Route128_Text_IsaiahRegister:
	.string "Je sais que je ne suis pas terrible pour l'instant,\n"
	.string "mais je finirai par gagner.\p"
	.string "Enregistre-moi dans ton POKéNAV, s'il te plaît.$"

Route128_Text_IsaiahRematchIntro:
	.string "Je me sens encore bien. Je vais continuer\n"
	.string "à nager vers ATELANTIA.$"

Route128_Text_IsaiahRematchDefeat:
	.string "Je n'ai pas encore goûté ma première victoire…$"

Route128_Text_IsaiahPostRematch:
	.string "J'atteindrai un jour ATELANTIA\n"
	.string "où je pourrai enfin gagner…$"

Route128_Text_KatelynIntro:
	.string "Il faut nager, faire du vélo,\n"
	.string "puis courir un marathon dans\p"
	.string "un triathlon. C'est une course\n"
	.string "épuisante composée de trois épreuves.$"

Route128_Text_KatelynDefeat:
	.string "Un combat POKéMON, c'est épuisant aussi…$"

Route128_Text_KatelynPostBattle:
	.string "Il faut que je prenne une BICYCLETTE ensuite, mais…\n"
	.string "Je suis sur le point d'abandonner…$"

Route128_Text_KatelynRegister:
	.string "Bon, autant en profiter.\n"
	.string "J'aimerais une revanche un de ces jours.$"

Route128_Text_KatelynRematchIntro:
	.string "Un triathlon, c'est long. Mais je suppose\n"
	.string "que la route pour devenir CHAMPION POKéMON\l"
	.string "est aussi longue et difficile.$"

Route128_Text_KatelynRematchDefeat:
	.string "Un combat POKéMON est vraiment\n"
	.string "dur et impitoyable…$"

Route128_Text_KatelynPostRematch:
	.string "Tu devrais sérieusement réfléchir aux\n"
	.string "défis de la ROUTE VICTOIRE.$"

Route128_Text_AlexaIntro:
	.string "On a travaillé dur pour monter\n"
	.string "un défi de LIGUE POKéMON…\p"
	.string "On ne peut pas se permettre de perdre maintenant !$"

Route128_Text_AlexaDefeat:
	.string "Oh !\n"
	.string "Comment est-ce possible ?!$"

Route128_Text_AlexaPostBattle:
	.string "Après tout ce que j'ai fait pour arriver ici,\n"
	.string "je n'abandonnerai pas après un revers.$"

Route128_Text_RubenIntro:
	.string "Il n'y a pas de DRESSEUR plus fort que moi !$"

Route128_Text_RubenDefeat:
	.string "C'est pas possible !$"

Route128_Text_RubenPostBattle:
	.string "Il n'y a probablement pas de DRESSEUR\n"
	.string "plus fort que toi !$"

Route128_Text_WayneIntro:
	.string "Je veux aller à ÉTERNARA, alors j'ai\n"
	.string "attrapé un POKéMON qui connaît\l"
	.string "CASCADE pour franchir les chutes.$"

Route128_Text_WayneDefeat:
	.string "Je suis abattu !$"

Route128_Text_WaynePostBattle:
	.string "Awww, mince !\p"
	.string "Mon POKéMON connaît CASCADE, mais\n"
	.string "je n'ai pas le BADGE D'ARÈNE D'ATMOPOLIS !$"

Route128_Text_HarrisonIntro:
	.string "Tu as l'air terriblement coriace.\n"
	.string "Je me demande si je peux gagner ?$"

Route128_Text_HarrisonDefeat:
	.string "Aïe !\n"
	.string "Je suppose qu'il était impossible de gagner.$"

Route128_Text_HarrisonPostBattle:
	.string "Il y a plein de DRESSEURS coriaces\n"
	.string "autour d'ATRIUM VILLE.\p"
	.string "Tu crois que je suis peut-être\n"
	.string "à la hauteur ?$"

Route128_Text_CarleeIntro:
	.string "Le soleil semble plus intense\n"
	.string "dans cette zone.$"

Route128_Text_CarleeDefeat:
	.string "Je ne voyais pas bien à cause\n"
	.string "de l'éblouissement du soleil.$"

Route128_Text_CarleePostBattle:
	.string "Je devrais rentrer bientôt.\n"
	.string "Il faut que je remette de la crème solaire.$"

Route129_Text_ChaseIntro:
	.string "C'est mon premier triathlon.\n"
	.string "Je suis tendu et nerveux !$"

Route129_Text_ChaseDefeat:
	.string "Wroooaaar !\n"
	.string "Je n'ai pas réussi à gagner !$"

Route129_Text_ChasePostBattle:
	.string "Si je suis trop tendu, je ne pourrai pas\n"
	.string "donner le meilleur de moi-même.$"

Route129_Text_AllisonIntro:
	.string "Je suis au milieu d'un triathlon,\n"
	.string "mais bon, pourquoi pas un combat ?$"

Route129_Text_AllisonDefeat:
	.string "J'étais sûr de gagner !$"

Route129_Text_AllisonPostBattle:
	.string "Tu sais ce qu'il y a de génial\n"
	.string "dans les triathlons ?\p"
	.string "Tester les limites de ta propre\n"
	.string "force et endurance face à\l"
	.string "la Mère Nature !$"

Route129_Text_ReedIntro:
	.string "Hé hé hé !\n"
	.string "Allons-y !$"

Route129_Text_ReedDefeat:
	.string "Battu, je suis battu.\n"
	.string "C'est fini !$"

Route129_Text_ReedPostBattle:
	.string "Il n'y a rien pour un perdant.\n"
	.string "Il est temps de rentrer.$"

Route129_Text_TishaIntro:
	.string "Quelle est la précipitation ?\n"
	.string "Prenons notre temps.$"

Route129_Text_TishaDefeat:
	.string "Oh, mon Dieu.\n"
	.string "Je voulais me détendre un peu plus…$"

Route129_Text_TishaPostBattle:
	.string "Tu détestes faire des erreurs quand\n"
	.string "tu es pressé ?\p"
	.string "C'est pour ça que j'essaie de prendre\n"
	.string "mon temps.$"

Route129_Text_ClarenceIntro:
	.string "Surfer n'est pas aussi facile qu'il y paraît,\n"
	.string "n'est-ce pas ?$"

Route129_Text_ClarenceDefeat:
	.string "Gagner, ce n'est vraiment pas facile.$"

Route129_Text_ClarencePostBattle:
	.string "Tu vises la LIGUE POKéMON ?\n"
	.string "Continue comme ça !$"

Route130_Text_RodneyIntro:
	.string "Quelle surprise ! Je ne m'attendais pas à\n"
	.string "voir un DRESSEUR en pleine mer.\p"
	.string "Je crois qu'on devrait se battre !$"

Route130_Text_RodneyDefeat:
	.string "Ce gamin est terriblement fort…$"

Route130_Text_RodneyPostBattle:
	.string "Tes yeux ont ce regard de quelqu'un\n"
	.string "qui a surmonté des épreuves difficiles\l"
	.string "et gagné. Ça te va bien !$"

Route130_Text_KatieIntro:
	.string "Dans la mer bleue profonde,\n"
	.string "mon cœur bleu brisé trouve\l"
	.string "du réconfort parmi les vagues.$"

Route130_Text_KatieDefeat:
	.string "Comme la vaste mer bleue,\n"
	.string "le monde des POKéMON s'étend\l"
	.string "à des profondeurs incroyables.$"

Route130_Text_KatiePostBattle:
	.string "Les enfants du monde rêvent\n"
	.string "de devenir un jour\l"
	.string "le CHAMPION POKéMON.$"

Route130_Text_SantiagoIntro:
	.string "Flotter sur la mer ouverte comme ça…\n"
	.string "C'est paisible.$"

Route130_Text_SantiagoDefeat:
	.string "J'aurais dû être un peu moins paisible !$"

Route130_Text_SantiagoPostBattle:
	.string "Nager et se battre comme ça…\n"
	.string "Je suis un type heureux…$"

Route131_Text_RichardIntro:
	.string "La mer déborde de POKéMON.\n"
	.string "Ce n'est pas facile de nager, crois-moi.$"

Route131_Text_RichardDefeat:
	.string "Les POKéMON élevés par des DRESSEURS\n"
	.string "sont vraiment costauds…$"

Route131_Text_RichardPostBattle:
	.string "Haleter… Haleter…\n"
	.string "Je suis épuisé…\p"
	.string "L'aller est facile. C'est le retour\n"
	.string "qui est difficile.\p"
	.string "Est-ce que j'aurai encore assez\n"
	.string "d'énergie pour le voyage de retour ?$"

Route131_Text_HermanIntro:
	.string "La mer... La mer... La mer...\n"
	.string "La mer à perte de vue !\l"
	.string "J'en ai marre de la mer !$"

Route131_Text_HermanDefeat:
	.string "Beurk !$"

Route131_Text_HermanPostBattle:
	.string "L'ennui me gagne près de la mer, mais nager je dois.\p"
	.string "Je suis un nageur-né !\n"
	.string "C'est ce que je suis.$"

Route131_Text_SusieIntro:
	.string "Salut, chéri, attends !\n"
	.string "On devrait se battre, toi et moi !$"

Route131_Text_SusieDefeat:
	.string "Tu es coriace malgré\n"
	.string "ton apparence !$"

Route131_Text_SusiePostBattle:
	.string "Tu as vu le type là-bas qui se plaint\n"
	.string "de s'ennuyer en mer ?\p"
	.string "Ce ne sont que des mots.\n"
	.string "Il est follement amoureux de la mer !$"

Route131_Text_KaraIntro:
	.string "Pourquoi les hommes aiment-ils tant les maillots ?\p"
	.string "Ils me dévisagent tous !$"

Route131_Text_KaraDefeat:
	.string "Je suis dépassé !$"

Route131_Text_KaraPostBattle:
	.string "C'est peut-être pas mon maillot de bain qui\n"
	.string "attire les regards. Ça doit être ma beauté !$"

Route131_Text_ReliIntro:
	.string "RELI : On va se battre ensemble,\n"
	.string "frère et sœur, contre toi !$"

Route131_Text_ReliDefeat:
	.string "RELI : On n'a pas pu gagner même\n"
	.string "en travaillant ensemble…$"

Route131_Text_ReliPostBattle:
	.string "RELI : Les gens de PACIFIVILLE vivent\n"
	.string "avec la mer et les POKéMON depuis\l"
	.string "leur naissance.$"

Route131_Text_ReliNotEnoughMons:
	.string "RELI : Tu n'as pas deux POKéMON ?\n"
	.string "On ne peut pas profiter d'un combat, alors.$"

Route131_Text_IanIntro:
	.string "IAN : Je fais de mon mieux avec\n"
	.string "ma sœur !$"

Route131_Text_IanDefeat:
	.string "IAN : J'ai fait de mon mieux avec ma sœur,\n"
	.string "mais on n'a quand même pas gagné…$"

Route131_Text_IanPostBattle:
	.string "IAN : Tu sais, EXTRAMURE est\n"
	.string "une ville flottante ? Donc, partout\p"
	.string "où il y a la mer,\n"
	.string "c'est une partie d'EXTRAMURE !$"

Route131_Text_IanNotEnoughMons:
	.string "IAN : Si tu as deux POKéMON,\n"
	.string "on t'affronte !$"

Route131_Text_TaliaIntro:
	.string "Si tu me bats, je te donnerai des\n"
	.string "infos de première classe !$"

Route131_Text_TaliaDefeat:
	.string "Oh ?\n"
	.string "J'ai perdu ?$"

Route131_Text_TaliaPostBattle:
	.string "Il y a un endroit étrange à proximité.\n"
	.string "Il y a une énorme tour là-bas.\l"
	.string "Pourquoi n'irais-tu pas jeter un œil ?$"

Route131_Text_KevinIntro:
	.string "Les gens de RELIFAC-LE-HAUT sont\n"
	.string "un peuple paisible.\p"
	.string "Ils ne se fâchent jamais.\n"
	.string "Moi non plus.$"

Route131_Text_KevinDefeat:
	.string "Oups !$"

Route131_Text_KevinPostBattle:
	.string "Tch ! …Oh, attends.\n"
	.string "Je ne suis pas en colère. Promis !\p"
	.string "Mais dis donc, tu es fort !\n"
	.string "Hahaha !$"

Route132_Text_GilbertIntro:
	.string "Quand j'étais enfant, j'attrapais tout le temps\n"
	.string "un rhume, mais je suis devenu en pleine forme\l"
	.string "après avoir commencé à nager.$"

Route132_Text_GilbertDefeat:
	.string "Je veux plus de puissance…$"

Route132_Text_GilbertPostBattle:
	.string "Les DRESSEURS parcourent champs et\n"
	.string "montagnes, ils doivent donc être en forme aussi.$"

Route132_Text_DanaIntro:
	.string "J'essaie de ne pas nager là où les courants\n"
	.string "sont trop forts.$"

Route132_Text_DanaDefeat:
	.string "Oh, s'il te plaît, non !$"

Route132_Text_DanaPostBattle:
	.string "Si je suis emporté, je perdrai tout\n"
	.string "mon sens de l'orientation…$"

Route132_Text_RonaldIntro:
	.string "Gagner ou perdre, on ne le sait qu'en\n"
	.string "essayant !$"

Route132_Text_RonaldDefeat:
	.string "Waah !\n"
	.string "J'ai coulé dans la défaite !$"

Route132_Text_RonaldPostBattle:
	.string "Je ne me bats jamais quand je sais que je vais gagner.\n"
	.string "J'aime combattre au ras du rasoir entre\l"
	.string "victoire et défaite !$"

Route132_Text_KiyoIntro:
	.string "Je médite sur les POKéMON 24 heures sur 24.\n"
	.string "Comment pourrais-tu me battre ?$"

Route132_Text_KiyoDefeat:
	.string "Je perds.\n"
	.string "J'avoue ma défaite.$"

Route132_Text_KiyoPostBattle:
	.string "Urgh...\n"
	.string "Tu es un fanatique de POKéMON, pas vrai ?\p"
	.string "Tu dois penser aux POKéMON 24 heures\n"
	.string "sur 24, non ?$"

Route132_Text_MakaylaIntro:
	.string "Je suis toujours avec mon mari,\n"
	.string "mais je peux gagner même sans lui.$"

Route132_Text_MakaylaDefeat:
	.string "Oh, je suppose que je n'étais pas assez bon.$"

Route132_Text_MakaylaPostBattle:
	.string "Ce jeune homme là-bas ressemble tellement\n"
	.string "à mon mari quand il était jeune.\p"
	.string "Il me fait rougir !$"

Route132_Text_JonathanIntro:
	.string "Quelqu'un me regardait fixement.\n"
	.string "C'était toi ?$"

Route132_Text_JonathanDefeat:
	.string "Waouh !\n"
	.string "C'est vraiment fort, en effet !$"

Route132_Text_JonathanPostBattle:
	.string "Je n'arrive pas à me débarrasser de ce sentiment\n"
	.string "que quelqu'un me regarde.\p"
	.string "Je ne peux pas me concentrer !$"

Route132_Text_PaxtonIntro:
	.string "Où est passée ma femme ?\n"
	.string "Je suis toujours avec elle.\l"
	.string "Je me demande si je peux gagner tout seul.$"

Route132_Text_PaxtonDefeat:
	.string "Ah, je vois que je n'ai pas réussi\n"
	.string "à gagner tout seul après tout.$"

Route132_Text_PaxtonPostBattle:
	.string "Ma femme doit me chercher.\n"
	.string "Je ferais mieux d'aller la retrouver.$"

Route132_Text_DarcyIntro:
	.string "J'aimais m'entraîner ici tout seul.\n"
	.string "C'est horrible que tout ce monde soit venu !$"

Route132_Text_DarcyDefeat:
	.string "D'accord ! Je ne me plaindrai pas\n"
	.string "des autres personnes ici.$"

Route132_Text_DarcyPostBattle:
	.string "Je suppose que je peux faire équipe avec ce\n"
	.string "vieil homme et défier l'autre équipe.$"

Route133_Text_FranklinIntro:
	.string "Les courants t'ont emporté ici aussi ?\n"
	.string "Ça devait être le destin.\l"
	.string "Combattons !$"

Route133_Text_FranklinDefeat:
	.string "Fort !\n"
	.string "Trop fort !$"

Route133_Text_FranklinPostBattle:
	.string "C'est ma malchance qu'un DRESSEUR coriace\n"
	.string "comme toi débarque ici…\l"
	.string "Je suis maudit…$"

Route133_Text_DebraIntro:
	.string "J'ai mené une vie de malheur et de misère…\n"
	.string "On m'a rejeté, et c'est ici que\l"
	.string "j'ai échoué…$"

Route133_Text_DebraDefeat:
	.string "Encore une défaite…$"

Route133_Text_DebraPostBattle:
	.string "Une vie à la dérive…\n"
	.string "Je n'en veux plus !$"

Route133_Text_LindaIntro:
	.string "Bienvenue !\n"
	.string "Je t'attendais !$"

Route133_Text_LindaDefeat:
	.string "Non ! S'il te plaît !$"

Route133_Text_LindaPostBattle:
	.string "Un DRESSEUR enfant fort…\n"
	.string "C'est tellement agaçant !$"

Route133_Text_WarrenIntro:
	.string "Je veux gagner comme tout le monde, mais je\n"
	.string "n'élèverai pas mes POKéMON comme tout le monde.$"

Route133_Text_WarrenDefeat:
	.string "Bon sang !\n"
	.string "Ma technique est encore trop lâche !$"

Route133_Text_WarrenPostBattle:
	.string "C'est bien plus amusant de faire les choses\n"
	.string "à ma façon que d'être comme tout le monde.\l"
	.string "C'est évident !$"

Route133_Text_BeckIntro:
	.string "Je suis venu jusqu'ici avec mes\n"
	.string "POKéMON OISEAU.$"

Route133_Text_BeckDefeat:
	.string "Toi…\n"
	.string "Tu es incroyablement cool !$"

Route133_Text_BeckPostBattle:
	.string "J'aimerais retourner à FORGEFRAISE,\n"
	.string "mais cet endroit me plaît aussi.$"

Route133_Text_MollieIntro:
	.string "J'ai dû combattre des milliers\n"
	.string "de fois. J'ai perdu le compte.$"

Route133_Text_MollieDefeat:
	.string "J'ai peut-être perdu des milliers de fois,\n"
	.string "mais une défaite fait toujours mal.$"

Route133_Text_MolliePostBattle:
	.string "Continue comme ça, jeune homme. Pour devenir\n"
	.string "comme mon mari et moi.$"

Route133_Text_ConorIntro:
	.string "Les jeunes sont trop contents de suivre\n"
	.string "le courant. Ils n'ont pas de direction.$"

Route133_Text_ConorDefeat:
	.string "Tu as un sens du but bien affirmé.$"

Route133_Text_ConorPostBattle:
	.string "Ne laisse pas les autres t'égarer.\n"
	.string "Ne perds pas ta direction en vieillissant.$"

Route134_Text_JackIntro:
	.string "Même les POKéMON qui savent nager sont\n"
	.string "entraînés par les courants rapides.$"

Route134_Text_JackDefeat:
	.string "Aiyeeeeh !$"

Route134_Text_JackPostBattle:
	.string "Je pense que les POKéMON apprécient les\n"
	.string "courants rapides de par ici.$"

Route134_Text_LaurelIntro:
	.string "Mes LOVDOU cherchent un combat\n"
	.string "amusant. Tu nous rejoins ?$"

Route134_Text_LaurelDefeat:
	.string "Oups !$"

Route134_Text_LaurelPostBattle:
	.string "Il y a un collectionneur qui recherche\n"
	.string "les ÉCAILLES de LOVDOU.$"

Route134_Text_AlexIntro:
	.string "Okeydokey ! Assez reposé, la bande !\n"
	.string "C'est l'heure d'un match !$"

Route134_Text_AlexDefeat:
	.string "À bout de forces encore…$"

Route134_Text_AlexPostBattle:
	.string "Mes POKéMON Oiseau se fatiguent vite\n"
	.string "après un long vol…$"

Route134_Text_HitoshiIntro:
	.string "Tu es un Dresseur POKéMON.\n"
	.string "Pas besoin de mots. On se bat.$"

Route134_Text_HitoshiDefeat:
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "C'est moi qui t'ai défié, et pourtant\n"
	.string "j'ai perdu. J'en ai honte…$"

Route134_Text_AaronIntro:
	.string "La marée sauvage de cette zone nous rend\n"
	.string "plus forts que jamais.$"

Route134_Text_AaronDefeat:
	.string "J'avoue volontiers ma défaite.$"

Route134_Text_AaronPostBattle:
	.string "Nous reviendrons nous entraîner aux CHUTES\n"
	.string "MÉTÉORES. Si tu veux, tu devrais\p"
	.string "y aller aussi. Ça te rendra\n"
	.string "plus fort, c'est sûr !$"

Route134_Text_KelvinIntro:
	.string "N-notre bateau !\n"
	.string "La marée l'a emporté !$"

Route134_Text_KelvinDefeat:
	.string "Awawawawah !\n"
	.string "Arrête ! S'il te plaît !$"

Route134_Text_KelvinPostBattle:
	.string "Si on ne peut pas SURF, comment rentrer\n"
	.string "chez nous ?\p"
	.string "En fait, je sais qu'un POKéMON K.O. peut\n"
	.string "encore SURF, mais ça me semble mal.$"

Route134_Text_MarleyIntro:
	.string "Tes POKéMON peuvent-ils esquiver\n"
	.string "nos attaques ultra-rapides ?$"

Route134_Text_MarleyDefeat:
	.string "Je ne savais pas qu'une telle technique existait !\n"
	.string "Tu nous as battus complètement.$"

Route134_Text_MarleyPostBattle:
	.string "Je n'ai pas perdu ma passion pour la vitesse.\n"
	.string "Je vais redoubler d'efforts.$"

Route134_Text_ReynaIntro:
	.string "Mes POKéMON ne peuvent pas être\n"
	.string "abattus facilement !$"

Route134_Text_ReynaDefeat:
	.string "Tu plaisantes !\n"
	.string "Explique-moi comment j'ai perdu !$"

Route134_Text_ReynaPostBattle:
	.string "Haha !\n"
	.string "Tu as gagné, c'est sûr !\p"
	.string "Je vais remonter la pente en affrontant\n"
	.string "les DRESSEURS que je croise !$"

Route134_Text_HudsonIntro:
	.string "Dis, as-tu vu un autre MARIN\n"
	.string "par ici ?$"

Route134_Text_HudsonDefeat:
	.string "Ça, c'est du solide !$"

Route134_Text_HudsonPostBattle:
	.string "Notre bateau a dérivé en mer.\p"
	.string "Mon copain est timide, alors\n"
	.string "je m'inquiète pour lui.$"
