LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "Oh, bonjour ! Tu étais dans un\n"
	.string "CONCOURS POKéMON, n'est-ce pas ? On le\l"
	.string "voit facilement à ton POKéMON. Je\p"
	.string "suis journaliste. Je travaille sur un\n"
	.string "article sur les CONCOURS POKéMON. Si\p"
	.string "ça ne te dérange pas, accepterais-tu\n"
	.string "de répondre à quelques questions ?$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "Oh, tu veux bien ?\n"
	.string "Merci.\p"
	.string "Brièvement, comment décrirais-tu le\n"
	.string "CONCOURS auquel tu viens de participer ?$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "Ah, je vois. C'est un commentaire\n"
	.string "très instructif. On se fait une\p"
	.string "bonne idée de ce qu'était le\n"
	.string "CONCOURS. J'ai une dernière question.\p"
	.string "Quand tu entends le mot\p"
	.string "« {STR_VAR_2} », quelle image\n"
	.string "te vient à l'esprit ?$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "Je vois !\p"
	.string "C'est ainsi que tu\n"
	.string "imagines\p"
	.string "le concept\n"
	.string "de « {STR_VAR_2} ».\p"
	.string "Merci !\n"
	.string "Tu m'as donné\p"
	.string "une nouvelle\n"
	.string "perspective,\l"
	.string "{PLAYER}{KUN} !$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "Oh, trop malchanceux…\p"
	.string "Eh bien, si tu as une bonne histoire à raconter,\n"
	.string "n'hésite pas à me la partager.$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "J'attends avec impatience ton prochain\n"
	.string "CONCOURS POKéMON.$"

gTVBravoTrainerText00::
	.string "Ouais !\n"
	.string "C'est l'heure de BRAVO DRESSEUR !\p"
	.string "Aujourd'hui, nous allons présenter un POKéMON\n"
	.string "appartenant à {STR_VAR_1}.\p"
	.string "Ce POKéMON affiche un Rang {STR_VAR_3}\n"
	.string "dans la Catégorie {STR_VAR_2}.$"

gTVBravoTrainerText01::
	.string "Voici {STR_VAR_2} le\n"
	.string "{STR_VAR_1} !\p"
	.string "Le surnom {STR_VAR_2}…\p"
	.string "Même le surnom dégage une aura qui\n"
	.string "proclame « {STR_VAR_3} » !$"

gTVBravoTrainerText02::
	.string "Quand le DRESSEUR {STR_VAR_1}\n"
	.string "a inscrit le POKéMON à un CONCOURS,\l"
	.string "nous avons obtenu quelques citations\l"
	.string "passionnées sur ce fidèle partenaire.$"

gTVBravoTrainerText03::
	.string "Interrogé sur le CONCOURS après,\n"
	.string "{STR_VAR_1} a répondu joyeusement\l"
	.string "avec un grand sourire : « {STR_VAR_2} ! »\p"
	.string "Eh bien, le POKéMON de {STR_VAR_1}\n"
	.string "est arrivé numéro {STR_VAR_3} au CONCOURS.\p"
	.string "Cette réplique lui va parfaitement\n"
	.string "en ce moment, je dirais !$"

gTVBravoTrainerText04::
	.string "Interrogé sur le CONCOURS après,\n"
	.string "{STR_VAR_1} a répondu avec une pointe\l"
	.string "d'amertume : « {STR_VAR_2}. »\p"
	.string "Eh bien, le POKéMON de {STR_VAR_1}\n"
	.string "est arrivé numéro {STR_VAR_3} au CONCOURS.\p"
	.string "La déception de {STR_VAR_1} est\n"
	.string "claire comme de l'eau de roche !$"

gTVBravoTrainerText05::
	.string "Tu voudrais aussi savoir ce que\n"
	.string "{STR_VAR_1} imagine que soit\p"
	.string "{STR_VAR_2} ?\n"
	.string "Bien sûr !\p"
	.string "Alors on a demandé !\n"
	.string "La réponse est parfaitement\p"
	.string "condensée : « {STR_VAR_3} ! »\n"
	.string "C'est ce que le concept de {STR_VAR_2} représente pour {STR_VAR_1} !$"

gTVBravoTrainerText06::
	.string "La dernière attaque {STR_VAR_2} utilisée\n"
	.string "par le {STR_VAR_1} est entièrement axée sur\l"
	.string "« {STR_VAR_3} » !$"

gTVBravoTrainerText07::
	.string "Bravo, {STR_VAR_1} !\n"
	.string "Bravo, {STR_VAR_2} !\p"
	.string "Nous espérons revoir\n"
	.string "{STR_VAR_1} atteindre des sommets encore plus hauts !\p"
	.string "C'est tout pour aujourd'hui !\n"
	.string "À la prochaine fois, au revoir !$"

gTVBravoTrainerText08::
	.string "Voici le {STR_VAR_1} du DRESSEUR !$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "Bonjour ! Tu es le DRESSEUR qui vient de\n"
	.string "combattre, n'est-ce pas ?\p"
	.string "Je recueille des interviews de DRESSEURS\n"
	.string "partout.\p"
	.string "Puis-je te poser quelques questions sur\n"
	.string "ton expérience des combats ?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "Tu veux ? Vraiment ?\n"
	.string "Merci !\l"
	.string "Alors, euh…\p"
	.string "Comment ça s'est passé aujourd'hui\n"
	.string "à la TOUR DE COMBAT ?\p"
	.string "Étais-tu satisfait du combat ?\n"
	.string "Ou es-tu mécontent ?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "Oh...\n"
	.string "Désolés de t'avoir dérangé.\p"
	.string "Donne-nous une interview la prochaine\n"
	.string "fois que tu viendras à la TOUR DE COMBAT.$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "Eh bien, bien sûr !\p"
	.string "Ce regard de satisfaction indéniable\n"
	.string "sur ton visage… C'est\p"
	.string "évident que tu as\n"
	.string "eu un superbe combat.$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "Oh, je vois…\p"
	.string "C'est vrai que c'est difficile de faire\n"
	.string "dérouler un combat exactement comme prévu.$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "Oh, oh, puis-je poser une autre question ?\p"
	.string "Si tu devais décrire tes impressions\n"
	.string "de ce combat en une seule phrase,\l"
	.string "ce serait quoi ?$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "Oh, c'est incroyablement cool ! C'est\p"
	.string "une superbe réplique ! J'espère que\n"
	.string "tu feras aussi bien la prochaine\p"
	.string "fois. J'espère te revoir !$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "Oh, je vois…\p"
	.string "Quand même, être du genre silencieux\n"
	.string "c'est cool aussi, non ?\p"
	.string "J'espère que tu me donneras l'occasion\n"
	.string "de partager à nouveau tes pensées !$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "J'attends avec impatience ton\n"
	.string "prochain combat !$"

BravoTrainerBattleTower_Text_Intro::
	.string "Ouais !\n"
	.string "C'est l'heure de BRAVO DRESSEUR !\p"
	.string "Aujourd'hui, nous allons présenter {STR_VAR_1},\n"
	.string "qui a relevé le défi de la TOUR DE COMBAT !\p"
	.string "Pour le défi, {STR_VAR_1} a inscrit\n"
	.string "un sacré {STR_VAR_2}.$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "Le duo a établi un nouveau record de {STR_VAR_2} victoires\n"
	.string "consécutives en compétition {STR_VAR_1} !\l"
	.string "Bravo, DRESSEUR !$"

BravoTrainerBattleTower_Text_Lost::
	.string "Le duo a finalement succombé à\n"
	.string "{STR_VAR_1} au match numéro {STR_VAR_2}.\l"
	.string "Bien essayé, DRESSEUR !\p"
	.string "Mais bon, c'est juste la malchance\n"
	.string "de croiser {STR_VAR_1} si tôt dans\p"
	.string "le défi.\n"
	.string "Nous avons demandé au DRESSEUR ses impressions du match contre {STR_VAR_1}.$"

BravoTrainerBattleTower_Text_Won::
	.string "Le duo a tout remporté en\n"
	.string "battant {STR_VAR_1} et son {STR_VAR_2}\l"
	.string "complètement. Bravo, DRESSEUR ! Battre\p"
	.string "même {STR_VAR_1}… C'est incroyable !\n"
	.string "Simplement époustouflant ! Nous avons\p"
	.string "demandé au DRESSEUR ses impressions\n"
	.string "sur ce moment de gloire.$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "Après une série\n"
	.string "de victoires,\l"
	.string "le duo a finalement\p"
	.string "succombé au {STR_VAR_2}\p"
	.string "de {STR_VAR_1},\n"
	.string "son dernier obstacle.\l"
	.string "Bien essayé, DRESSEUR !\p"
	.string "Mais {STR_VAR_1} était\n"
	.string "trop fort cette fois.$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "Voici ce que le\n"
	.string "DRESSEUR a dit :\p"
	.string "« Je suis\n"
	.string "satisfait ! »\p"
	.string "N'est-ce pas\n"
	.string "une réponse\p"
	.string "rafraîchissante ?\n"
	.string "Bravo, DRESSEUR !$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "Voici ce que le\n"
	.string "DRESSEUR a dit :\p"
	.string "« Je ne suis\n"
	.string "pas satisfait… »\p"
	.string "Notre DRESSEUR était\n"
	.string "évidemment un peu\p"
	.string "déprimé après sa défaite.\n"
	.string "Mais il reviendra plus fort !$"

BravoTrainerBattleTower_Text_None1::
	.string "Aucun$"

BravoTrainerBattleTower_Text_None2::
	.string "Aucun$"

BravoTrainerBattleTower_Text_None3::
	.string "Aucun$"

BravoTrainerBattleTower_Text_None4::
	.string "Aucun$"

BravoTrainerBattleTower_Text_Response::
	.string "“{STR_VAR_1}.”$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "« {STR_VAR_1}. »\n"
	.string "N'est-ce pas formidable ?\p"
	.string "Ça exprime vraiment la joie de {STR_VAR_2},\n"
	.string "je dirais.\p"
	.string "Ce combat avec {STR_VAR_3} à la\n"
	.string "fin… C'était vraiment ce qu'on appelle\l"
	.string "« {STR_VAR_1} » !$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "« {STR_VAR_1}. » N'est-ce pas approprié\n"
	.string "? Ce combat avec {STR_VAR_3} à\p"
	.string "la fin… On ne peut\n"
	.string "le décrire que comme «\l"
	.string "{STR_VAR_1} » ! La déception\p"
	.string "de {STR_VAR_2} est claire comme\n"
	.string "de l'eau de roche !$"

BravoTrainerBattleTower_Text_Outro::
	.string "Bravo, {STR_VAR_1} !\n"
	.string "Bravo, {STR_VAR_2} !\p"
	.string "Nous espérons revoir\n"
	.string "{STR_VAR_1} atteindre des sommets encore plus hauts !\p"
	.string "C'est tout pour aujourd'hui !\n"
	.string "À la prochaine fois, au revoir !$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "Waouh !\p"
	.string "On voit bien que tu chéris ton\n"
	.string "{STR_VAR_1}.\p"
	.string "D'accord, il s'appelle {STR_VAR_2}.\p"
	.string "Je peux te demander une faveur ?\p"
	.string "Je suis journaliste TV, et je mène\n"
	.string "une enquête sur les POKéMON.\p"
	.string "Accepterais-tu de répondre à\n"
	.string "quelques questions simples ?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "Super ! Merci !\p"
	.string "OK, c'est parti.\n"
	.string "J'ai juste besoin de réponses rapides, OK ?$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "Quand tu as rencontré {STR_VAR_1} pour la\n"
	.string "première fois, qu'as-tu ressenti ?\p"
	.string "Comment décrirais-tu tes sentiments\n"
	.string "à ce moment-là ?$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "Ton {STR_VAR_1} est choyé avec amour. Si\p"
	.string "tu devais le comparer à quelque chose\n"
	.string "que tu aimes, ce serait quoi ?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "Cette question concerne aussi\n"
	.string "ton cher {STR_VAR_1}.\p"
	.string "Qu'est-ce qui t'a attiré\n"
	.string "chez {STR_VAR_1} ?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "D'accord, c'est logique. La\p"
	.string "prochaine question sera peut-être\n"
	.string "un peu difficile. Alors…\p"
	.string "Que représentent les POKéMON\p"
	.string "pour toi ?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "Je vois\p"
	.string "! Hmhm…\p"
	.string "D'accord !\n"
	.string "Merci de\p"
	.string "m'avoir aidé.\n"
	.string "C'était amusant\p"
	.string "et enrichissant\n"
	.string "de discuter\p"
	.string "avec\n"
	.string "toi.$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "Oh, d'accord…\p"
	.string "Eh bien, si tu as envie de me parler\n"
	.string "de POKéMON, je serai là !$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "J'adore ce travail--on apprend beaucoup\n"
	.string "sur les POKéMON en faisant des interviews.$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "Salut, tu sembles très proche\n"
	.string "de ton {STR_VAR_1}. Tu sais\p"
	.string "quoi ? Je suis journaliste\n"
	.string "TV. Je voyage pour interviewer\p"
	.string "les gens sur les POKéMON.\n"
	.string "Je me demande si tu\p"
	.string "accepterais de me parler un\n"
	.string "peu de ton {STR_VAR_1} ?$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "Waouh, merci !\p"
	.string "D'accord, alors dis-moi tout ce que tu veux\n"
	.string "sur ton {STR_VAR_1}.$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "Waouh…\n"
	.string "C'est un\p"
	.string "compte\n"
	.string "intéressant.\p"
	.string "Tu es vraiment\n"
	.string "proche\p"
	.string "de\n"
	.string "{STR_VAR_1},\l"
	.string "n'est-ce pas ?\p"
	.string "Je comprends\n"
	.string "le lien !$"

gTVFanClubOpinionsText00::
	.string "NOUS SOMMES LE FAN CLUB POKéMON !\p"
	.string "Nous sommes à l'antenne !\p"
	.string "Dans cette émission, nous recueillons vos opinions,\n"
	.string "et je les crie à votre place !\l"
	.string "N'est-ce pas un concept d'émission fantastique ?\p"
	.string "Aujourd'hui, nous vous apportons ce reportage de\n"
	.string "notre journaliste, envoyé au\l"
	.string "FAN CLUB POKéMON.\p"
	.string "Alors, qui est le fan POKéMON vedette\n"
	.string "d'aujourd'hui ?\p"
	.string "… … … … … … … …\p"
	.string "{STR_VAR_1} !\p"
	.string "Alors, écoutons ce que {STR_VAR_1} a à\n"
	.string "dire sur {STR_VAR_3} le {STR_VAR_2}.\p"
	.string "Et, je crierai ces mots d'amour\n"
	.string "à haute voix à la télé !\p"
	.string "Houah !\p"
	.string "Crions !$"

gTVFanClubOpinionsText01::
	.string "Nous avons demandé à {STR_VAR_1} : «\n"
	.string "Quand tu as vu ton {STR_VAR_2}\l"
	.string "pour la première fois, quelle était\p"
	.string "ta première pensée ? » «\p"
	.string "{STR_VAR_3} ! » Yeahah ! Quel\p"
	.string "cri puissant ! Ça ne te\n"
	.string "rappelle pas ces jours révolus ?$"

gTVFanClubOpinionsText02::
	.string "Nous avons demandé à {STR_VAR_1} :\n"
	.string "« Si tu devais comparer ton\l"
	.string "{STR_VAR_2} à quelque chose,\p"
	.string "ce serait… »\p"
	.string "… … … … … … … …\p"
	.string "« {STR_VAR_3} ! »\p"
	.string "Waouh, voilà une idée originale !\n"
	.string "On sent vraiment l'intensité des\l"
	.string "sentiments du DRESSEUR pour {STR_VAR_2}.$"

gTVFanClubOpinionsText03::
	.string "Et voyons… Qu'est-ce qui a tant\n"
	.string "attiré {STR_VAR_1} chez ce {STR_VAR_2} ?\l"
	.string "… … … … … …\p"
	.string "… … « {STR_VAR_3} ! »\p"
	.string "Waouh ! Quelle déclaration spectaculaire\p"
	.string "! L'amour du DRESSEUR pour\p"
	.string "le {STR_VAR_2} est clair comme\n"
	.string "de l'eau de roche !$"

gTVFanClubOpinionsText04::
	.string "Hm ? Oh, il y en a encore.\n"
	.string "Vérifions !\p"
	.string "Voyons voir…\p"
	.string "Nous avons demandé à {STR_VAR_1} : « Que représentent\n"
	.string "les POKéMON pour toi ? »\p"
	.string "… … … … … …\p"
	.string "« {STR_VAR_3} ! »\p"
	.string "Bravo !\p"
	.string "C'est le meilleur cri que j'ai eu de la journée !\p"
	.string "« {STR_VAR_3} ! »\p"
	.string "Ça donne envie de le crier\n"
	.string "encore et encore !\p"
	.string "Maintenant qu'on a eu un super cri, c'est\n"
	.string "l'heure de dire au revoir jusqu'à la prochaine fois !\p"
	.string "Alors, faisons un dernier cri tous ensemble !\n"
	.string "Tous ensemble maintenant…\p"
	.string "« {STR_VAR_3} ! »$"

gTVFanClubText00::
	.string "NOUS SOMMES LE FAN CLUB POKéMON !\p"
	.string "Nous sommes à l'antenne !\p"
	.string "Aujourd'hui, on commence avec le\n"
	.string "COIN ENQUÊTE POKéMON.\p"
	.string "Parmi toutes les histoires tissées par les POKéMON\n"
	.string "et les DRESSEURS, quel nouveau drame surprenant\l"
	.string "attirera notre attention aujourd'hui ?\p"
	.string "Voyons voir…\p"
	.string "Celui-ci !\p"
	.string "On commence avec cette lettre !\p"
	.string "C'est une lettre de {STR_VAR_1} à propos d'un\n"
	.string "{STR_VAR_2} bien-aimé.\p"
	.string "Voyons avec quelle passion notre auteur\n"
	.string "peut exprimer son amour pour le {STR_VAR_2} !\l"
	.string "Hmhm…$"

gTVFanClubText01::
	.string "Ouah !\n"
	.string "Quelle lettre incroyable !$"

gTVFanClubText02::
	.string "J'ai adoré, alors le voici à nouveau !$"

gTVFanClubText03::
	.string "Une belle lettre mérite d'être\n"
	.string "relue encore et encore !$"

gTVFanClubText04::
	.string "Le passage « {STR_VAR_3} »\n"
	.string "accentue vraiment l'impact émotionnel !\p"
	.string "C'est une superbe lettre\n"
	.string "pleine de sincérité !$"

gTVFanClubText05::
	.string "Surtout ce passage « {STR_VAR_3} » !\p"
	.string "J'adore comment « {STR_VAR_3} » est utilisé !$"

gTVFanClubText06::
	.string "Au fait, ce n'est pas important,\n"
	.string "mais « {STR_VAR_3} » est une super expression.\p"
	.string "J'utilise beaucoup « {STR_VAR_3} »\n"
	.string "dans mes conversations ces temps-ci.$"

gTVFanClubText07::
	.string "Si je devais noter cette lettre, je\n"
	.string "lui donnerais {STR_VAR_3} points. La prochaine\p"
	.string "fois, j'attends une lettre encore meilleure,\n"
	.string "{STR_VAR_1} ! Oups, regarde l'heure !\p"
	.string "Il est temps de dire au\n"
	.string "revoir jusqu'à la prochaine fois !$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "Oh ? Tu aimes peut-être les\n"
	.string "POKéMON ? Je suis en mission\p"
	.string "pour la chaîne TV. Je recueille\p"
	.string "des histoires sur les POKéMON et\n"
	.string "DRESSEURS récents. Si ça ne te\p"
	.string "dérange pas, pourrais-tu me parler\n"
	.string "un peu de toi ?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "Je recueille des histoires sur les POKéMON et\n"
	.string "les DRESSEURS récents.\p"
	.string "Si ça ne te dérange pas, pourrais-tu me parler\n"
	.string "un peu de toi ?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "Oh, tu veux bien ?\n"
	.string "Merci ! Alors, raconte-moi quelque\p"
	.string "chose d'intéressant que tu\n"
	.string "as vécu récemment en\l"
	.string "rapport avec les POKéMON.$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "Oh, je vois…\p"
	.string "Eh bien, si tu as une histoire intéressante\n"
	.string "à raconter, fais-le moi savoir.$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "Oh, quelle histoire inspirante !\p"
	.string "Je vais m'assurer que ton histoire soit\n"
	.string "racontée à la télévision.\p"
	.string "Elle devrait être diffusée un jour, je pense,\n"
	.string "alors attends-la avec impatience.$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "Hmmm…\n"
	.string "J'ai une bonne histoire pour une émission TV.\p"
	.string "Je ferais mieux de l'écrire vite !$"

gTVRecentHappeningsText00::
	.string "Bonjour, c'est l'heure\p"
	.string "des DERNIÈRES NOUVELLES.\n"
	.string "Pour les DRESSEURS\p"
	.string "POKéMON, chaque jour\n"
	.string "est une histoire.\p"
	.string "Ce qu'on veut faire,\n"
	.string "c'est partager\p"
	.string "ces histoires\n"
	.string "avec vous !\p"
	.string "Restez à l'écoute !$"

gTVRecentHappeningsText01::
	.string "C'était pas instructif ?\p"
	.string "L'histoire te donne une idée claire de ce que\n"
	.string "{STR_VAR_1} a vécu récemment.\l"
	.string "C'est comme si nous y étions !$"

gTVRecentHappeningsText02::
	.string "« {STR_VAR_3} ». Cela\n"
	.string "souligne le récit et lui donne de la profondeur.$"

gTVRecentHappeningsText03::
	.string "« {STR_VAR_3}. »\n"
	.string "Ça donne un sens de lieu à l'histoire.\l"
	.string "Ça nous permet d'imaginer le cadre du récit.$"

gTVRecentHappeningsText04::
	.string "La partie « {STR_VAR_3} »\n"
	.string "de l'histoire est très expressive.$"

gTVRecentHappeningsText05::
	.string "{STR_VAR_1} a raconté une merveilleuse\n"
	.string "histoire impliquant des POKéMON.\p"
	.string "Et maintenant, l'histoire de {STR_VAR_1} est\n"
	.string "gravée à jamais dans ton âme, toi aussi.\p"
	.string "C'est tout pour aujourd'hui.\n"
	.string "Rendez-vous la prochaine fois.$"

gTVMassOutbreakText00::
	.string "Salutations !\n"
	.string "C'est l'heure des ACTUALITÉS POKéMON.\p"
	.string "Nous venons d'apprendre une occurrence\n"
	.string "très rare.\p"
	.string "On signale une épidémie massive de\n"
	.string "{STR_VAR_2} aux alentours de {STR_VAR_1}.\l"
	.string "{STR_VAR_2}, comme tu\p"
	.string "le sais probablement,\n"
	.string "est un POKéMON rare et\l"
	.string "difficile à trouver.\p"
	.string "Ça semble être une occasion rare de voir\n"
	.string "l'épidémie mystérieuse de\l"
	.string "{STR_VAR_2} à l'état sauvage.\p"
	.string "C'était les ACTUALITÉS POKéMON.$"

gTV3CheersForPokeblocksText00::
	.string "MC : Nous espérons que vous êtes\n"
	.string "de bonne humeur,\p"
	.string "« 3 CHEERS POUR LES {POKEBLOCK}S » est là !\n"
	.string "Aujourd'hui, nous examinons le\p"
	.string "{POKEBLOCK} mélangé par {STR_VAR_1} et\n"
	.string "ses associés.\p"
	.string "Sans plus attendre, laissez-moi\n"
	.string "le donner à mon POKéMON gourmet AVALTOUT. … … … … … … … … … … … …$"

gTV3CheersForPokeblocksText01::
	.string "GLOUPTI : Gubi ! Gubii !\p"
	.string "MC : Et le verdict est très {STR_VAR_1} !\n"
	.string "GLoupti dit que ça a le goût de « {STR_VAR_2} » !\p"
	.string "Merci beaucoup, {STR_VAR_3} !$"

gTV3CheersForPokeblocksText02::
	.string "La performance de mélange de {STR_VAR_1}\n"
	.string "laisse à désirer.\p"
	.string "Si ce DRESSEUR savait mieux mélanger,\n"
	.string "le {POKEBLOCK} serait bien plus savoureux.$"

gTV3CheersForPokeblocksText03::
	.string "GLOUPI : Gubi ! Gubii !\p"
	.string "MC : Hmm… C'est trop {STR_VAR_1}.\n"
	.string "GLOUPI dit que ça a un goût « {STR_VAR_2} » !\p"
	.string "On dirait que les erreurs de {STR_VAR_3}\n"
	.string "ont nui à la qualité du mélange…$"

gTV3CheersForPokeblocksText04::
	.string "C'est dommage que l'effort de tête de {STR_VAR_1}\n"
	.string "ait été gâché.\p"
	.string "Espérons que {STR_VAR_2} fera mieux\n"
	.string "la prochaine fois !$"

gTV3CheersForPokeblocksText05::
	.string "À la prochaine !\n"
	.string "Notre slogan est « 3 BRAVOS POUR LES {POKEBLOCK}S ! »$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "Salut !\p"
	.string "Je suis un grand fan de {STR_VAR_1}.\n"
	.string "Quelle est ton opinion sur {STR_VAR_1} ?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "Je vois, je vois. C'est ce que tu penses\n"
	.string "du DRESSEUR.$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "As-tu complètement oublié\n"
	.string "{STR_VAR_1} ?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "Je suis un grand fan de {STR_VAR_1}.\n"
	.string "Quelle est ton opinion sur {STR_VAR_1} ?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "À quel point évaluerais-tu {STR_VAR_1}\n"
	.string "sur une échelle de cent ?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "As-tu complètement oublié\n"
	.string "{STR_VAR_1} ?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "Oh, je vois !\n"
	.string "Tu devrais rencontrer {STR_VAR_1} un jour.\l"
	.string "Je suis sûr que tu deviendras fan aussi !$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "Je vois, je vois.\p"
	.string "Merci !\n"
	.string "C'est très utile à savoir.\p"
	.string "Je partagerai cette info avec d'autres\n"
	.string "fans de {STR_VAR_1} et on en discutera.$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "Il y aura bientôt une émission TV spéciale sur\n"
	.string "{STR_VAR_1}.\p"
	.string "J'espère que tu la verras !$"

gTVTrainerFanClubSpecialText00::
	.string "FAN CLUB DRESSEUR\n"
	.string "{STR_VAR_1} SPÉCIAL !\p"
	.string "C'est une émission spéciale pour\n"
	.string "les fans de {STR_VAR_1} partout à HOENN !\p"
	.string "Aujourd'hui, nous posons la question : « Que pensent\n"
	.string "les gens de {STR_VAR_1} ? »\p"
	.string "Nous avons posé la question à {STR_VAR_2}\n"
	.string "en tant que représentant DRESSEUR.\p"
	.string "Nous avons demandé : « En un mot, comment\n"
	.string "décririez-vous {STR_VAR_1} ? »\p"
	.string "La réponse : « {STR_VAR_3}. »\p"
	.string "Bravo à {STR_VAR_2} !\n"
	.string "Quelle opinion perspicace !\p"
	.string "« {STR_VAR_3} {STR_VAR_1}. »\n"
	.string "Ça sonne si bien !\p"
	.string "{STR_VAR_2} a aussi noté la force de {STR_VAR_1}\n"
	.string "sur une échelle de 0 à 100.$"

gTVTrainerFanClubSpecialText01::
	.string "Le score est de {STR_VAR_3} points !\n"
	.string "C'est un score très élevé !\p"
	.string "{STR_VAR_2} doit manifestement tenir\n"
	.string "{STR_VAR_1} en très haute estime.$"

gTVTrainerFanClubSpecialText02::
	.string "Le score est de {STR_VAR_3}\n"
	.string "points ! C'est un très\p"
	.string "bon score. {STR_VAR_2} doit considérer\n"
	.string "{STR_VAR_1} comme un rival.$"

gTVTrainerFanClubSpecialText03::
	.string "Le score est de {STR_VAR_3} points !\n"
	.string "C'est un score plutôt faible.\p"
	.string "{STR_VAR_2} doit considérer\n"
	.string "{STR_VAR_1} comme un simple adjoint.$"

gTVTrainerFanClubSpecialText04::
	.string "Le score est de {STR_VAR_3}\n"
	.string "point(s) ! C'est un score\p"
	.string "terrible. {STR_VAR_2} doit considérer\n"
	.string "{STR_VAR_1} comme un subordonné.$"

gTVTrainerFanClubSpecialText05::
	.string "Voilà, mesdames et messieurs !\p"
	.string "Je crois qu'on a tous appris quelque chose\n"
	.string "de nouveau sur {STR_VAR_1}.\p"
	.string "Pour finir, je vous laisse avec\n"
	.string "les mots de {STR_VAR_2}.\p"
	.string "{STR_VAR_3} {STR_VAR_1} !$"

gTVNameRaterText00::
	.string "Et maintenant,\n"
	.string "c'est l'heure de…\p"
	.string "L'ÉMISSION ÉVALUATEUR\n"
	.string "DE SURNOMS.\p"
	.string "Je prédit la fortune\n"
	.string "de ton POKéMON\p"
	.string "à partir du surnom\n"
	.string "que tu lui as donné.\l"
	.string "Conseil du jour\p"
	.string ": donne un surnom\p"
	.string "qui reflète la personnalité\n"
	.string "de ton POKéMON !$"

gTVNameRaterText01::
	.string "Un surnom qui laisse entrevoir le talent\n"
	.string "sous bien des aspects.\p"
	.string "J'encourage ce DRESSEUR à prendre\n"
	.string "courage et relever de nombreux défis.$"

gTVNameRaterText02::
	.string "Un surnom qui complète parfaitement\n"
	.string "{STR_VAR_1}, le nom du DRESSEUR.\p"
	.string "Il suggère que vous forgeriez un beau\n"
	.string "partenariat avec un timing précis.$"

gTVNameRaterText03::
	.string "Un surnom digne d'un individu unique\n"
	.string "de POKéMON !\p"
	.string "Si élevé correctement, l'unicité de ce POKéMON\n"
	.string "s'épanouira excessivement !$"

gTVNameRaterText04::
	.string "Un surnom qui nourrira le côté attentionné\n"
	.string "et compatissant des POKéMON.\p"
	.string "Si élevé correctement, ce POKéMON fera\n"
	.string "preuve d'une vraie chaleur !$"

gTVNameRaterText05::
	.string "Un très beau surnom qui laisse entrevoir\n"
	.string "une grandeur à venir.\p"
	.string "Je suis intrigué par ce que l'avenir\n"
	.string "réserve à ce POKéMON.$"

gTVNameRaterText06::
	.string "Un bon surnom qui devrait rendre le\n"
	.string "POKéMON robuste et en pleine forme !\p"
	.string "Ce POKéMON devrait rester en forme\n"
	.string "pendant longtemps, longtemps.$"

gTVNameRaterText07::
	.string "Un bon surnom qui devrait rendre le\n"
	.string "POKéMON très actif !\p"
	.string "Je pense que ce POKéMON sera\n"
	.string "un excellent combattant en bataille.$"

gTVNameRaterText08::
	.string "Un surnom attrayant qui devrait rendre\n"
	.string "le POKéMON très charmant !\p"
	.string "Je ne doute pas que ce POKéMON sera\n"
	.string "un vrai charmeur aux CONCOURS POKéMON.$"

gTVNameRaterText09::
	.string "Le surnom {STR_VAR_1} est ancré par\n"
	.string "la lettre « {STR_VAR_3} ».\p"
	.string "Cette lettre est soutenue par la première\n"
	.string "lettre « {STR_VAR_2} », ce qui lui donne une solide\l"
	.string "sensation de présence en tant que surnom.$"

gTVNameRaterText10::
	.string "Le surnom {STR_VAR_1} est très\n"
	.string "élégant d'une manière plaisante.\p"
	.string "La présence des lettres « {STR_VAR_2} » et\n"
	.string "« {STR_VAR_3} » — c'est remarquablement bien !$"

gTVNameRaterText11::
	.string "Le surnom {STR_VAR_1} — il a\n"
	.string "une sensation sublime et fluide.\p"
	.string "Le flux de la lettre initiale « {STR_VAR_2} » vers\n"
	.string "« {STR_VAR_3} » est particulièrement merveilleux.$"

gTVNameRaterText12::
	.string "Examinons d'autres exemples de\n"
	.string "surnoms remarquables, d'accord ?$"

gTVNameRaterText13::
	.string "Voici un exemple. Prends une partie du\n"
	.string "nom de DRESSEUR de {STR_VAR_1}, et tu\l"
	.string "obtiens le joli surnom {STR_VAR_2}{STR_VAR_3}.$"

gTVNameRaterText14::
	.string "Le surnom {STR_VAR_2}{STR_VAR_3} conviendrait\n"
	.string "aussi très bien.$"

gTVNameRaterText15::
	.string "Le nom d'espèce de {STR_VAR_2}\n"
	.string "pourrait servir de base pour\l"
	.string "faire le surnom {STR_VAR_1}{STR_VAR_3}.$"

gTVNameRaterText16::
	.string "{STR_VAR_1}{STR_VAR_3} serait aussi\n"
	.string "un surnom efficace.$"

gTVNameRaterText17::
	.string "Ce qu'il faut toujours éviter, c'est\n"
	.string "d'utiliser le nom d'une autre espèce\p"
	.string "de POKéMON. Par exemple, évite de\n"
	.string "prendre le nom de {STR_VAR_2} pour\l"
	.string "faire le surnom {STR_VAR_1}{STR_VAR_3}. C'est inacceptable.$"

gTVNameRaterText18::
	.string "Je dois dire que {STR_VAR_1} est un\n"
	.string "bon surnom.\p"
	.string "J'espère que le DRESSEUR continuera\n"
	.string "à traiter {STR_VAR_1} avec amour.\p"
	.string "C'est tout pour l'émission d'aujourd'hui.\n"
	.string "À une prochaine fois.$"

gTVPokemonAnglerText00::
	.string "{STR_VAR_2} ANGLER\p"
	.string "ANIMATEUR : Bonjour ! Aujourd'hui, des conseils\n"
	.string "pour pêcher le {STR_VAR_2}.\p"
	.string "GURU, quels conseils peux-tu donner pour\n"
	.string "attraper le {STR_VAR_2} ?\p"
	.string "GURU : Hein ? Attraper le {STR_VAR_2} ?\n"
	.string "Eh bien, laisse-moi te dire, sois patient et\l"
	.string "attends. C'est l'essentiel.\p"
	.string "Tu vois {STR_VAR_1} là-bas ?\n"
	.string "Ce DRESSEUR est un bon exemple.\p"
	.string "Ce DRESSEUR a déjà laissé s'échapper\n"
	.string "{STR_VAR_3} POKéMON.\p"
	.string "Mais là {STR_VAR_1} attend. Pas de renoncement.\n"
	.string "C'est la loi pour attraper le {STR_VAR_2}.\p"
	.string "ANIMATEUR : Je vois…\p"
	.string "Oh ! {STR_VAR_1} a enfin attrapé un\n"
	.string "{STR_VAR_2} insaisissable !\p"
	.string "Le DRESSEUR semble près des larmes\n"
	.string "de joie pure !\p"
	.string "En voyant ce regard exalté, j'ai aussi\n"
	.string "l'envie d'aller pêcher !\p"
	.string "Téléspectateurs, pourquoi ne pas en profiter pour\n"
	.string "essayer de pêcher le {STR_VAR_2} ?\p"
	.string "Jusqu'à notre prochaine émission, au revoir et\n"
	.string "bonne pêche à tous !$"

gTVPokemonAnglerText01::
	.string "{STR_VAR_2} ANGLER\p"
	.string "ANIMATEUR : Bonjour ! Aujourd'hui, des conseils\n"
	.string "pour pêcher le {STR_VAR_2}.\p"
	.string "GURU, quels conseils peux-tu donner pour\n"
	.string "attraper le {STR_VAR_2} ?\p"
	.string "GURU : Hein ? Attraper le {STR_VAR_2} ?\n"
	.string "Eh bien, laisse-moi te dire, utilise ta CANNE\l"
	.string "à pêche avec vigueur !\p"
	.string "Tu vois {STR_VAR_1} là-bas ?\n"
	.string "Tu vois comment la CANNE est maniée ?\p"
	.string "Ce DRESSEUR a déjà attrapé\n"
	.string "{STR_VAR_3} d'affilée.\p"
	.string "ANIMATEUR : C'est incroyable !\n"
	.string "On dirait une tempête…\p"
	.string "En voyant une technique de ce calibre, j'ai\n"
	.string "aussi envie d'aller pêcher.\p"
	.string "Téléspectateurs, pourquoi ne pas en profiter pour\n"
	.string "essayer de pêcher le {STR_VAR_2} ?\p"
	.string "Jusqu'à notre prochaine émission, au revoir et\n"
	.string "bonne pêche à tous !$"

gTVPokemonTodayFailedText00::
	.string "Bonjour ! C'est l'heure\p"
	.string "de POKéMON AUJOURD'HUI !\p"
	.string "GRANDE SŒUR : Salut\n"
	.string "! Tout le monde\p"
	.string "est en forme aujourd'hui\n"
	.string "? GRAND FRÈRE :\p"
	.string "On va présenter un\n"
	.string "POKéMON spécial !$"

gTVPokemonTodayFailedText01::
	.string "Oh !\n"
	.string "En parlant de\p"
	.string "{STR_VAR_1}…\n"
	.string "GRANDE SŒUR,\p"
	.string "j'ai vu le\p"
	.string "DRESSEUR\n"
	.string "de mes\p"
	.string "propres yeux !\n"
	.string "GRANDE SŒUR :\l"
	.string "Oh, vraiment ?$"

gTVPokemonTodayFailedText02::
	.string "Le POKéMON a réussi à s'échapper\p"
	.string "! Ça a gaspillé autant de\n"
	.string "POKé BALLS : {STR_VAR_2} ! Tu\p"
	.string "aurais dû voir l'expression de frustration\n"
	.string "sur le visage de {STR_VAR_1} quand\l"
	.string "le POKéMON s'est envolé !$"

gTVPokemonTodayFailedText03::
	.string "Mais {STR_VAR_1} a fait une bêtise\n"
	.string "et a mis le POKéMON K.O.\p"
	.string "! Ça a gaspillé autant de\n"
	.string "POKé BALLS : {STR_VAR_2} ! Tu\p"
	.string "aurais dû voir l'expression d'étonnement sur\n"
	.string "le visage de {STR_VAR_1} quand\l"
	.string "le POKéMON s'est évanoui !$"

gTVPokemonTodayFailedText04::
	.string "GRANDE SŒUR : Hé, toi !\n"
	.string "Ce n'est pas gentil !\p"
	.string "Tu ne devrais pas te moquer\n"
	.string "du malheur des autres !\p"
	.string "Oh, pauvre {STR_VAR_1}.\n"
	.string "Quel dommage !\p"
	.string "GRAND FRÈRE : C'est vrai !\n"
	.string "Désolé d'avoir ri.$"

gTVPokemonTodayFailedText05::
	.string "GRANDE SŒUR : Bufufu…\p"
	.string "GRAND FRÈRE : Hé !\n"
	.string "Toi aussi, tu as ri !\p"
	.string "GRANDE SŒUR : Hein ?!\p"
	.string "Je n'ai pas ri !\n"
	.string "Honnêtement, je n'ai pas ri !\p"
	.string "Oh, pauvre {STR_VAR_1}.\n"
	.string "Quel dommage !\p"
	.string "GRAND FRÈRE : …$"

gTVPokemonTodayFailedText06::
	.string "GRANDE SŒUR : Assez de bêtises\n"
	.string "! Regardons le POKéMON du jour…\p"
	.string "Hein ? On n'a plus de\n"
	.string "temps ? Aww ! On n'a\p"
	.string "pas pu présenter de POKéMON\n"
	.string "aujourd'hui ! GRAND FRÈRE :\p"
	.string "À la prochaine ! GRANDE\p"
	.string "SŒUR : Hé, ne termine\n"
	.string "pas l'émission sans moi !$"

gTVPokemonTodaySuccessfulText00::
	.string "Bonjour ! C'est l'heure\p"
	.string "de POKéMON AUJOURD'HUI !\p"
	.string "GRANDE SŒUR : Salut\n"
	.string "! Tout le monde\p"
	.string "est en forme aujourd'hui\n"
	.string "? GRAND FRÈRE :\p"
	.string "On va présenter un\n"
	.string "POKéMON spécial !$"

gTVPokemonTodaySuccessfulText01::
	.string "GRANDE SŒUR : {STR_VAR_1} a donné le surnom\n"
	.string "{STR_VAR_3} au {STR_VAR_2} !\p"
	.string "On dirait que {STR_VAR_3} reçoit\n"
	.string "de bons soins affectueux !$"

gTVPokemonTodaySuccessfulText02::
	.string "GRAND FRÈRE : Le DRESSEUR a dû lancer autant\n"
	.string "de POKé BALLS pour l'attraper : {STR_VAR_3} !\p"
	.string "Finalement, une seule {STR_VAR_2}\n"
	.string "a suffi pour l'attraper !$"

gTVPokemonTodaySuccessfulText03::
	.string "GRANDE SŒUR : Si c'était si facile\n"
	.string "à attraper, c'était sûrement le destin qui\l"
	.string "a réuni {STR_VAR_1} et {STR_VAR_2} !$"

gTVPokemonTodaySuccessfulText04::
	.string "GRANDE SŒUR : Wow ! C'est trop cool !\p"
	.string "Mais tu sais ce qu'on dit, un POKéMON\n"
	.string "qu'on a mis beaucoup d'efforts à attraper\l"
	.string "apprécie l'amour de son DRESSEUR !$"

gTVPokemonTodaySuccessfulText05::
	.string "GRANDE SŒUR : Le {STR_VAR_2} de {STR_VAR_1}\n"
	.string "est un POKéMON mémorable car il a\l"
	.string "fallu une précieuse MASTER BALL pour l'attraper\p"
	.string "! GRAND FRÈRE : Waouh ! C'est\p"
	.string "méga- génial ! GRANDE SŒUR : {STR_VAR_1}\n"
	.string "devait vraiment vouloir ce {STR_VAR_2} !$"

gTVPokemonTodaySuccessfulText06::
	.string "GRAND FRÈRE : Alors pour donner le surnom\n"
	.string "{STR_VAR_3} à ce {STR_VAR_2}…\p"
	.string "Tu as vraiment du goût pour\n"
	.string "choisir des surnoms !\p"
	.string "C'est un excellent choix !$"

gTVPokemonTodaySuccessfulText07::
	.string "À ta place, je donnerais ce surnom\n"
	.string "à quelque chose comme ce {STR_VAR_3} !\p"
	.string "GRAND FRÈRE : Whoa ! Ça pourrait être le début\n"
	.string "de quelque chose de nouveau !$"

gTVPokemonTodaySuccessfulText08::
	.string "{STR_VAR_2} le {STR_VAR_1} ?\n"
	.string "Ça ne sonne pas parfait ?\p"
	.string "Les lettres et tout…\n"
	.string "C'est un surnom parfait !\l"
	.string "J'espère que le DRESSEUR\p"
	.string "continuera à traiter {STR_VAR_1} avec amour.$"

gTVPokemonTodaySuccessfulText09::
	.string "Autant que je sache, aucun DRESSEUR n'a jamais\n"
	.string "donné le surnom {STR_VAR_2} à son\l"
	.string "{STR_VAR_1} !\p"
	.string "GRAND FRÈRE : Ça montre le bon goût\n"
	.string "du DRESSEUR pour choisir des\l"
	.string "surnoms !$"

gTVPokemonTodaySuccessfulText10::
	.string "La prochaine fois que j'attrape un POKéMON,\n"
	.string "je devrais lui donner le nom {STR_VAR_2}.\p"
	.string "GRAND FRÈRE : Hein ? Moi aussi !\n"
	.string "J'utiliserai aussi le surnom {STR_VAR_2} !$"

gTVPokemonTodaySuccessfulText11::
	.string "GRANDE SŒUR : Oh, non !\n"
	.string "Regarde l'heure !\p"
	.string "Bon, les amis, c'est tout pour aujourd'hui.\n"
	.string "À la prochaine fois !\p"
	.string "GRAND FRÈRE : Souvenez-vous, ce pourrait être votre\n"
	.string "POKéMON sous les projecteurs la prochaine fois !$"

SmartShopper_Text_Intro::
	.string "Bonjour !\p"
	.string "C'est l'heure de L'ACHETEUR MALIN DU JOUR.\p"
	.string "JOURNALISTE : Comment allez-vous, téléspectateurs ?\p"
	.string "Aujourd'hui, nous visitons une boutique\n"
	.string "à {STR_VAR_2}.\p"
	.string "Voyons quels sont les articles\n"
	.string "les plus vendus récemment.$"

SmartShopper_Text_ClerkNormal::
	.string "Interrogeons le vendeur pour avoir\n"
	.string "les infos.\p"
	.string "Salut, comment va le commerce ?\p"
	.string "VENDEUR : Oh, ça va très bien.\p"
	.string "Récemment, {STR_VAR_2} se vend\n"
	.string "particulièrement bien.\p"
	.string "Tiens, l'autre jour un DRESSEUR\n"
	.string "nommé {STR_VAR_1} a acheté {STR_VAR_3}.$"

SmartShopper_Text_RandomComment1::
	.string "INTERVIEWEUR : Le DRESSEUR a acheté\n"
	.string "{STR_VAR_3} {STR_VAR_2}S ? Quel stock !\p"
	.string "Si je puis me permettre, {STR_VAR_1}\n"
	.string "a dû faire des réserves pour\l"
	.string "un long voyage vers des\p"
	.string "contrées lointaines. Pour voyager, les\n"
	.string "{STR_VAR_2}S sont si importants !$"

SmartShopper_Text_RandomComment2::
	.string "REPORTER : En parlant de l'objet\n"
	.string "{STR_VAR_2}, j'en ai acheté {STR_VAR_3}\l"
	.string "récemment.\p"
	.string "Après tout, {STR_VAR_2} est un super objet !$"

SmartShopper_Text_RandomComment3::
	.string "JOURNALISTE : {STR_VAR_2} ?!\n"
	.string "Mais {STR_VAR_3} d'entre eux ?!\p"
	.string "Je ne pensais pas qu'il y en aurait\n"
	.string "autant !\p"
	.string "C'est incroyable !\n"
	.string "Quelle découverte !$"

SmartShopper_Text_RandomComment4::
	.string "INTERVIEWEUR : Une fois, j'ai\n"
	.string "acheté beaucoup de l'objet {STR_VAR_2}.\p"
	.string "Mais il s'est avéré que\n"
	.string "c'en était trop. J'ai fini\p"
	.string "par le regretter… Depuis, je\n"
	.string "n'achète que ce dont j'ai\p"
	.string "absolument besoin… Oups ! Inutile\p"
	.string "de parler de moi !$"

SmartShopper_Text_SecondItem::
	.string "VENDEUR : {STR_VAR_1} a aussi acheté l'objet\n"
	.string "{STR_VAR_2} en gros, en prenant {STR_VAR_3}.\p"
	.string "JOURNALISTE : Oh, c'est malin.\n"
	.string "{STR_VAR_2} est aussi un très bon objet.$"

SmartShopper_Text_ThirdItem::
	.string "VENDEUR : Et le DRESSEUR a aussi acheté\n"
	.string "{STR_VAR_3} de l'objet {STR_VAR_2}.$"

SmartShopper_Text_DuringSale::
	.string "EMPLOYÉ : En plus, c'était pendant les soldes.\n"
	.string "C'est du shopping malin.$"

SmartShopper_Text_OutroNormal::
	.string "INTERVIEWEUR : Hmm… {STR_VAR_1} a l'air\n"
	.string "d'un sacré chasseur de bonnes affaires\p"
	.string "! Au total, les achats de\p"
	.string "{STR_VAR_1} s'élèvent à… {STR_VAR_2} ¥ ?!\n"
	.string "Quelle somme incroyable ! Oups\p"
	.string "! Plus de temps !\n"
	.string "À la prochaine émission !$"

SmartShopper_Text_IsVIP::
	.string "EMPLOYÉ : {STR_VAR_1} est un client VIP,\n"
	.string "c'est certain.$"

SmartShopper_Text_ClerkMax::
	.string "Interrogeons le vendeur pour avoir\n"
	.string "les infos.\p"
	.string "Salut, comment va le commerce ?\p"
	.string "VENDEUR : Oh, ça va incroyablement bien.\n"
	.string "C'est presque écrasant.\p"
	.string "Récemment, un DRESSEUR nommé {STR_VAR_1}\n"
	.string "a acheté l'objet {STR_VAR_2} en gros.\p"
	.string "Le DRESSEUR a presque vidé tout\n"
	.string "notre stock de {STR_VAR_2}S.\p"
	.string "Je n'aurais jamais imaginé qu'un client\n"
	.string "aurait besoin de tant de {STR_VAR_2}S.\l"
	.string "C'est inouï !\p"
	.string "INTERVIEWEUR : Donc ça ferait genre 100\n"
	.string "ou 200 vendus ?\p"
	.string "VENDEUR : Oh, non, bien plus que ça !\p"
	.string "INTERVIEWEUR : Oh mon Dieu !\n"
	.string "{STR_VAR_1} doit être un client spécial !\p"
	.string "VENDEUR : {STR_VAR_1} est un client VIP,\n"
	.string "sans aucun doute.$"

SmartShopper_Text_OutroMax::
	.string "INTERVIEWEUR : Hmm… C'est incroyable.\n"
	.string "Mais pourquoi le DRESSEUR aurait-il\p"
	.string "besoin d'en acheter autant ?\n"
	.string "… … Le mystère s'épaissit,\p"
	.string "mais c'est tout le\p"
	.string "temps qu'on a aujourd'hui.\n"
	.string "À la prochaine émission\l"
	.string "! Quand même, {STR_VAR_1}\p"
	.string "est certainement une énigme…$"

gTVWorldOfMastersText00::
	.string "C'est un plaisir de discuter avec\p"
	.string "un jeune DRESSEUR comme toi.\p"
	.string "J'imagine que tu continueras à apprécier\n"
	.string "les POKéMON quel que soit ton âge.\p"
	.string "Ne serait-ce pas bien d'avoir\n"
	.string "un partenariat comme le nôtre ?\p"
	.string "Bien sûr, {PLAYER}{KUN}, tu profites déjà\n"
	.string "de la confiance et de la compagnie\p"
	.string "de tes POKéMON.\n"
	.string "Tu as déjà les bases de relations\p"
	.string "longues et durables !\n"
	.string "Hahaha ! Ne te décourage jamais !$"

gTVWorldOfMastersText01::
	.string "Cet exploit remarquable n'a été possible\n"
	.string "que grâce à la confiance entre\l"
	.string "le DRESSEUR et {STR_VAR_1}.$"

gTVWorldOfMastersText02::
	.string "Le maître a\n"
	.string "attrapé le dernier\p"
	.string "{STR_VAR_3} du jour\n"
	.string "près de {STR_VAR_2}.\p"
	.string "Ce POKéMON apprécie\n"
	.string "apparemment\p"
	.string "un certain type de BAIE.\n"
	.string "Intéressant !$"

gTVTodaysRivalTrainerText00::
	.string "LE DRESSEUR RIVAL DU JOUR !\p"
	.string "Bonjour, chers DRESSEURS POKéMON !\n"
	.string "Comment allez-vous aujourd'hui ?\p"
	.string "Aujourd'hui, comme chaque jour,\n"
	.string "nous allons examiner l'un de nos rivaux !$"

gTVTodaysRivalTrainerText07::
	.string "Le DRESSEUR rival du jour est {STR_VAR_1},\n"
	.string "qui est vers {STR_VAR_3} maintenant.\p"
	.string "{STR_VAR_1} a enregistré jusqu'ici\n"
	.string "{STR_VAR_2} POKéMON dans le POKéDEX.$"

gTVTodaysRivalTrainerText08::
	.string "Le DRESSEUR rival du jour est {STR_VAR_1},\n"
	.string "qui est dans une BASE SECRÈTE maintenant.\p"
	.string "{STR_VAR_1} a enregistré jusqu'ici\n"
	.string "{STR_VAR_2} POKéMON dans le POKéDEX.$"

gTVTodaysRivalTrainerText09::
	.string "Le DRESSEUR rival du jour est {STR_VAR_1}.\p"
	.string "Pour l'instant, {STR_VAR_1} a inscrit\n"
	.string "{STR_VAR_2} POKéMON dans le POKéDEX.$"

gTVTodaysRivalTrainerText10::
	.string "Le DRESSEUR rival d'aujourd'hui est {STR_VAR_1},\n"
	.string "qui est sur un ferry maintenant.\p"
	.string "{STR_VAR_1} a enregistré\n"
	.string "{STR_VAR_2} POKéMON dans le POKéDEX jusqu'ici.$"

	.string "$"

gTVTodaysRivalTrainerText01::
	.string "Et combien de BADGES notre rival\n"
	.string "a-t-il ? Le nombre est de {STR_VAR_1} !$"

gTVTodaysRivalTrainerText02::
	.string "Mais notre rival n'a pas encore obtenu\n"
	.string "le moindre BADGE !$"

gTVTodaysRivalTrainerText03::
	.string "Notre rival n'a encore obtenu aucun\n"
	.string "Symbole de la ZONE DE COMBAT.$"

gTVTodaysRivalTrainerText04::
	.string "Voyons combien de SYMBOLES de la\n"
	.string "ZONE DE COMBAT notre rival a.\p"
	.string "Symboles Or : {STR_VAR_1} !\n"
	.string "Symboles Argent : {STR_VAR_2} !$"

gTVTodaysRivalTrainerText05::
	.string "Notre rival a accumulé {STR_VAR_1}\n"
	.string "Point(s) de Combat au PARC DES COMBATS.$"

gTVTodaysRivalTrainerText06::
	.string "Alors, comment t'es-tu débrouillé face\n"
	.string "à {STR_VAR_1} ?\p"
	.string "L'aventure continue !\p"
	.string "Dresseurs, à nous tous !\p"
	.string "Continuons d'avancer\n"
	.string "et de devancer nos rivaux !$"

TrendWatcher_Text_Intro::
	.string "RÉSEAU DES TENDANCES DE VERGONHA !\p"
	.string "MC : Quoi de neuf ?\n"
	.string "On va vous donner les dernières infos sur\l"
	.string "ce qui est branché à VERGONHA.\p"
	.string "Notre invité aujourd'hui est ce vieux monsieur\n"
	.string "dont la réputation est d'être l'autorité\l"
	.string "sur tout ce qui se passe à VERGONHA.\p"
	.string "Vieux monsieur : Content d'être là.\p"
	.string "MC : Allons droit au but.\p"
	.string "Quel est ton avis sur ce qui fait vibrer\n"
	.string "les gens de VERGONHA ?\p"
	.string "Vieux monsieur : {STR_VAR_1} {STR_VAR_2}.\p"
	.string "MC : {STR_VAR_1} {STR_VAR_2},\n"
	.string "tu dis ?\p"
	.string "Vieux monsieur : Non.\p"
	.string "{STR_VAR_1} {STR_VAR_2} n'a\n"
	.string "jamais vraiment été populaire.\p"
	.string "Tu veux en entendre parler ?\p"
	.string "MC : Euh, non. Ce qu'on veut savoir, c'est\n"
	.string "ce qui est tendance en ce moment…$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTaughtMePhrase::
	.string "Vieil homme : {STR_VAR_1} {STR_VAR_2}\n"
	.string "c'est ce que {STR_VAR_3} de BOURG-EN-VOL\l"
	.string "m'a appris comme étant branché...$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "Vieil homme : {STR_VAR_1} {STR_VAR_2}\n"
	.string "c'est ce que {STR_VAR_3} de BOURG-EN-VOL\l"
	.string "m'a appris comme étant branché...$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "Mais c'était\p"
	.string "totalement désespéré.\p"
	.string "Festival {STR_VAR_1}\p"
	.string "{STR_VAR_2} !\n"
	.string "Concours {STR_VAR_1}\p"
	.string "{STR_VAR_2} !\n"
	.string "Rien n'a marché…\p"
	.string "{PLAYER}{KUN},\n"
	.string "donne-moi un conseil !$"

@ Identical to below, may have been different in other languages
TrendWatcher_Text_MaleTellMeBigger::
	.string "Vieil homme : {STR_VAR_3} !\n"
	.string "S'il te plaît, dis-moi quelque chose de plus grand que\l"
	.string "ce {STR_VAR_1} {STR_VAR_2} !$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "Vieil homme : {STR_VAR_3} !\n"
	.string "S'il te plaît, dis-moi quelque chose de plus grand que\l"
	.string "ce {STR_VAR_1} {STR_VAR_2} !$"

TrendWatcher_Text_Outro::
	.string "MC : …Euh… Voilà, tous les\n"
	.string "branchés du monde entier ! {STR_VAR_1}\p"
	.string "{STR_VAR_2}…euh… N'a pas percé à ALGATIA\n"
	.string "! Mon temps est écoulé.\p"
	.string "À la prochaine ! Vieux\p"
	.string "monsieur : {STR_VAR_1} {STR_VAR_2} !$"

gTVHoennTreasureInvestigatorsText00::
	.string "ENQUÊTEURS AU TRÉSOR DE HOENN !\p"
	.string "Salut la bande ! Vous avez\n"
	.string "trouvé des objets secrets ? Comme\p"
	.string "toujours, on examine les témoignages de\n"
	.string "secrets du monde entier ! Commençons\p"
	.string "par une lettre. Elle dit :\n"
	.string "« {STR_VAR_1} découvert ! »$"

gTVHoennTreasureInvestigatorsText01::
	.string "Waouh, on ferait mieux\n"
	.string "de lire cette lettre !\p"
	.string "Laisse-moi te la lire.\n"
	.string "…Chers ENQUÊTEURS,\p"
	.string "J'espère que vous allez bien.\n"
	.string "J'ai récemment vu\p"
	.string "{STR_VAR_2} quelque part\n"
	.string "autour de {STR_VAR_3}.\p"
	.string "Le DRESSEUR a trouvé l'objet\p"
	.string "{STR_VAR_1} dans une caverne.\n"
	.string "Je pense que c'est une piste importante.\p"
	.string "Bonne chance !\n"
	.string "Signé, un ami.$"

gTVHoennTreasureInvestigatorsText02::
	.string "TATE : Héhéhé… Tu es surpris ?\n"
	.string "LIZA : Fufufu… Tu es surpris ?\p"
	.string "TATE : Qu'il y ait deux CHAMPIONS d'ARÈNE ?\n"
	.string "LIZA : Qu'il y ait deux CHAMPIONS d'ARÈNE ?\p"
	.string "TATE : On est jumeaux !\p"
	.string "LIZA : On est jumeaux !\n"
	.string "TATE : On n'a pas besoin de parler car…\p"
	.string "LIZA : On peut chacun deviner ce que…\p"
	.string "TATE : L'autre pense…\n"
	.string "LIZA : Tout dans nos têtes !\p"
	.string "TATE : Cette combinaison…\n"
	.string "LIZA : Tu peux la battre ?$"

gTVFindThatGamerText00::
	.string "TROUVE CE JOUEUR !\p"
	.string "Hé, tous les\n"
	.string "joueurs ! Comment\p"
	.string "tourne ton {STR_VAR_2}\n"
	.string "? Comme toujours,\l"
	.string "on examine les\p"
	.string "habitudes de jeu\n"
	.string "de {STR_VAR_1} !$"

gTVFindThatGamerText01::
	.string "{STR_VAR_1} a joué au jeu {STR_VAR_2}\n"
	.string "et a gagné de rares JETONS {STR_VAR_3}.\p"
	.string "« Quand {STR_VAR_1} vient, il faut\n"
	.string "s'assurer d'avoir assez de JETONS. »\p"
	.string "C'est ce que murmurent les employés du\n"
	.string "CASINO quand notre joueur est en jeu !\p"
	.string "Téléspectateurs, il vaut mieux surveiller vos JETONS\n"
	.string "comme {STR_VAR_1} si vous visitez le\l"
	.string "CASINO et jouez au jeu {STR_VAR_2}.\p"
	.string "C'est en direct du CASINO--\n"
	.string "où vous pouvez sentir l'excitation !\p"
	.string "C'est tout pour aujourd'hui !$"

gTVFindThatGamerText02::
	.string "{STR_VAR_1} a joué au {STR_VAR_2} et\n"
	.string "a perdu {STR_VAR_3} JETONS. « Quand\p"
	.string "{STR_VAR_1} vient, nos ventes de JETONS\n"
	.string "augmentent. » C'est ce que disent\p"
	.string "les employés du CASINO quand\n"
	.string "notre joueur est là !$"

gTVFindThatGamerText03::
	.string "Téléspectateurs, surveillez vos JETONS comme\n"
	.string "{STR_VAR_1} si vous visitez le\l"
	.string "CASINO et jouez au {STR_VAR_2}.\p"
	.string "En direct du CASINO-- où\n"
	.string "l'excitation est palpable ! C'est\p"
	.string "tout pour aujourd'hui !$"

gTVBreakingNewsText00::
	.string "INFOS EN DIRECT !$"

gTVBreakingNewsText01::
	.string "Un {STR_VAR_2} rare attrapé par\n"
	.string "{STR_VAR_1} !\p"
	.string "Nous sommes en direct des environs\n"
	.string "de {STR_VAR_3} !\p"
	.string "{STR_VAR_1} a réussi à capturer\n"
	.string "un {STR_VAR_2} rare plus tôt ici !$"

gTVBreakingNewsText02::
	.string "Quand {STR_VAR_1} a rencontré le rare\n"
	.string "{STR_VAR_2}, le DRESSEUR a envoyé\l"
	.string "le POKéMON {STR_VAR_3}.$"

gTVBreakingNewsText03::
	.string "Pendant le combat, le nombre de POKé\n"
	.string "BALLS lancées par le DRESSEUR était de {STR_VAR_1}.\p"
	.string "Finalement, le POKéMON rare a été\n"
	.string "attrapé avec la {STR_VAR_2} utilisée en dernier.$"

gTVBreakingNewsText04::
	.string "À cet instant, {STR_VAR_2}\n"
	.string "a résonné des\l"
	.string "cris de joie\p"
	.string "triomphante de {STR_VAR_1}.\n"
	.string "Je dois dire\p"
	.string "que c'était un\n"
	.string "combat mémorable !$"

gTVBreakingNewsText05::
	.string "{STR_VAR_1} n'arrive pas à capturer un rare\n"
	.string "{STR_VAR_2} !\p"
	.string "Nous sommes en direct des environs\n"
	.string "du PARC SAFARI !\p"
	.string "Quelle déception !\n"
	.string "Dommage !$"

gTVBreakingNewsText06::
	.string "Quand {STR_VAR_1} a rencontré le rare\n"
	.string "{STR_VAR_2}, le DRESSEUR a envoyé\l"
	.string "le POKéMON {STR_VAR_3}.$"

gTVBreakingNewsText07::
	.string "Le DRESSEUR a fait utiliser à\n"
	.string "{STR_VAR_2} le mouvement {STR_VAR_1}. Sans\p"
	.string "le vouloir, le DRESSEUR a\n"
	.string "fait K.O. le POKéMON rare…$"

gTVBreakingNewsText12::
	.string "Cependant, {STR_VAR_1} a paniqué à la\n"
	.string "vue du rare {STR_VAR_2}. Dans\p"
	.string "la confusion, le DRESSEUR a\n"
	.string "ordonné à {STR_VAR_3} d'attaquer. Sans\p"
	.string "le vouloir, le DRESSEUR a\n"
	.string "fait s'évanouir le POKéMON rare.$"

gTVBreakingNewsText08::
	.string "À cet instant, {STR_VAR_2}\n"
	.string "a résonné des cris de frustration de {STR_VAR_1}…\l$"

gTVBreakingNewsText09::
	.string "Cependant, {STR_VAR_1} semblait manquer de\n"
	.string "POKé BALLS. Le DRESSEUR a\p"
	.string "dû interrompre le combat\n"
	.string "avec le rare {STR_VAR_2}.\p"
	.string "À cet instant, {STR_VAR_3}\n"
	.string "a résonné des cris\l"
	.string "de frustration de {STR_VAR_1}…$"

gTVBreakingNewsText10::
	.string "Cependant, le {STR_VAR_2} s'est enfui sans\n"
	.string "prévenir.\p"
	.string "À cet instant, {STR_VAR_3}\n"
	.string "a résonné des cris de frustration de\l"
	.string "{STR_VAR_1}…$"

gTVBreakingNewsText11::
	.string "Je dois avouer que je compatis pour {STR_VAR_1}.\n"
	.string "Ça me donne envie de hurler, moi aussi.\p"
	.string "…C'est la fin du direct en direct de\n"
	.string "cette scène mélancolique !$"

gTVSecretBaseVisitText00::
	.string "Bonjour à tous ! C'est\n"
	.string "l'heure d'une nouvelle VISITE\l"
	.string "DE BASE SECRÈTE. Aujourd'hui,\p"
	.string "nous visitons la BASE\n"
	.string "SECRÈTE de {STR_VAR_1}. Comment\p"
	.string "{STR_VAR_1} a-t-il personnalisé sa\n"
	.string "BASE SECRÈTE ? Allons\p"
	.string "voir ! … …\n"
	.string "… … … …$"

gTVSecretBaseVisitText01::
	.string "Oh !\n"
	.string "Voilà {STR_VAR_1} !\p"
	.string "Ce {STR_VAR_2}…\n"
	.string "Ce n'est pas ce qu'on s'attendrait à\l"
	.string "trouver ici !$"

gTVSecretBaseVisitText02::
	.string "Oh !\n"
	.string "Comme c'est\p"
	.string "remarquable !\n"
	.string "Il n'y a pas\p"
	.string "un seul meuble\n"
	.string "ou objet d'intérieur !\p"
	.string "Les simples mortels\n"
	.string "ne pourraient pas\p"
	.string "vivre ici, mais un\n"
	.string "DRESSEUR le peut !$"

gTVSecretBaseVisitText03::
	.string "Oh ! Je vois !\n"
	.string "Avec une clarté parfaite, je le vois !\p"
	.string "Ce {STR_VAR_2} placé ici...\n"
	.string "Ça envoie un message efficace !$"

gTVSecretBaseVisitText04::
	.string "Oh ! Je vois !\n"
	.string "Avec une clarté parfaite, je le vois !\p"
	.string "Cet espace est délibérément dégagé\n"
	.string "de tout objet d'intérieur !\p"
	.string "C'est un message efficace !$"

gTVSecretBaseVisitText05::
	.string "Youpi ! L'association du\p"
	.string "{STR_VAR_2} avec le {STR_VAR_3}\n"
	.string "! C'est une combinaison\p"
	.string "de rêve s'il\n"
	.string "en est !$"

gTVSecretBaseVisitText06::
	.string "Oooh !\p"
	.string "L'emplacement de ce {STR_VAR_2}\n"
	.string "juste ici...\p"
	.string "Il dégage une présence qui remplit\n"
	.string "toute la BASE SECRÈTE !$"

gTVSecretBaseVisitText07::
	.string "Oooh !\p"
	.string "Il n'y a rien ici.\p"
	.string "Cet espace vide a un effet sur\n"
	.string "toute la BASE SECRÈTE.$"

gTVSecretBaseVisitText08::
	.string "Oh !\n"
	.string "Voilà {STR_VAR_1} !\l"
	.string "Défions le DRESSEUR !\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText09::
	.string "Soupir…\n"
	.string "Il faut rendre\p"
	.string "hommage à {STR_VAR_1}.\n"
	.string "Les POKéMON\p"
	.string "du DRESSEUR\n"
	.string "étaient vraiment\p"
	.string "dignes du titre\n"
	.string "de CHAMPION.\p"
	.string "Ils ont donné un\n"
	.string "combat mémorable !\p"
	.string "Bravo, {STR_VAR_1} !$"

gTVSecretBaseVisitText10::
	.string "Aiyeeh !\n"
	.string "Il faut rendre\p"
	.string "hommage à\n"
	.string "{STR_VAR_1}.\p"
	.string "Les POKéMON du\n"
	.string "DRESSEUR étaient\p"
	.string "monstrueusement\n"
	.string "coriaces !\p"
	.string "Ils ont donné un\n"
	.string "combat\p"
	.string "mémorable !$"

gTVSecretBaseVisitText11::
	.string "Wouhou !\n"
	.string "Il faut rendre\p"
	.string "hommage à {STR_VAR_1}.\n"
	.string "Les POKéMON du DRESSEUR\p"
	.string "étaient clairement\n"
	.string "élevés de manière\p"
	.string "équilibrée.\n"
	.string "Leur coordination\p"
	.string "en combat était\n"
	.string "remarquable !\p"
	.string "Bravo, {STR_VAR_1} !$"

gTVSecretBaseVisitText12::
	.string "Eh bien, eh bien !\n"
	.string "Il faut rendre\p"
	.string "hommage à\n"
	.string "{STR_VAR_1}.\p"
	.string "Les POKéMON du\n"
	.string "DRESSEUR ont montré\p"
	.string "un grand potentiel de\n"
	.string "croissance future.\p"
	.string "Ils ont donné un\n"
	.string "combat prometteur !\p"
	.string "Bravo, {STR_VAR_1} !$"

gTVSecretBaseVisitText13::
	.string "Je dois dire, quelle superbe BASE SECRÈTE\n"
	.string "c'était !\p"
	.string "Téléspectateurs, si vous en avez l'occasion,\n"
	.string "visitez la BASE SECRÈTE de {STR_VAR_1}.\p"
	.string "Jusqu'à la prochaine fois, je vous dis adieu !$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "C'est excitant !\n"
	.string "C'est dramatique !\p"
	.string "C'est le FLASH INFO GAGNANT\n"
	.string "de la LOTERIE POKéMON !\p"
	.string "Bonjour ! Nous sommes en direct du\n"
	.string "COIN LOTERIE POKéMON au\l"
	.string "rez-de-chaussée des GRANDS MAGASINS\l"
	.string "de LILYCOVE !\p"
	.string "Comme toujours, un autre\n"
	.string "DRESSEUR chanceux est apparu aujourd'hui !\p"
	.string "Le nom de ce DRESSEUR…\n"
	.string "{STR_VAR_1} !\p"
	.string "{STR_VAR_1} a gagné le prix {STR_VAR_2}\n"
	.string "et repart avec {STR_VAR_3} !\p"
	.string "{STR_VAR_1} !\n"
	.string "Félicitations !\p"
	.string "Téléspectateurs, ne restez pas spectateurs,\n"
	.string "participez !\p"
	.string "Tous les employés des GRANDS MAGASINS\n"
	.string "de LILYCOVE attendent votre prochaine visite !\p"
	.string "C'était une émission en direct des\n"
	.string "GRANDS MAGASINS de LILYCOVE,\l"
	.string "vous offrant la plus grande sélection\l"
	.string "de tout HOENN !$"

gTVThePokemonBattleSeminarText00::
	.string "LE SÉMINAIRE DE COMBAT POKéMON\p"
	.string "! On analyse les combats\n"
	.string "pour voir quelles leçons on\p"
	.string "peut en tirer. L'étude\n"
	.string "de cas d'aujourd'hui porte\p"
	.string "sur le combat de\n"
	.string "{STR_VAR_1} contre {STR_VAR_2} !$"

gTVThePokemonBattleSeminarText01::
	.string "Et il a utilisé l'attaque {STR_VAR_3}\n"
	.string "sur le {STR_VAR_2}...\p"
	.string "Hmm... {STR_VAR_1} !\n"
	.string "C'est la mauvaise chose à faire !$"

gTVThePokemonBattleSeminarText02::
	.string "En plus de la capacité fatale,\n"
	.string "le {STR_VAR_1} du DRESSEUR connaissait aussi$"

gTVThePokemonBattleSeminarText03::
	.string "les attaques {STR_VAR_1}, {STR_VAR_2}\n"
	.string "et {STR_VAR_3}.$"

gTVThePokemonBattleSeminarText04::
	.string "les capacités {STR_VAR_1} et\n"
	.string "{STR_VAR_2}.$"

gTVThePokemonBattleSeminarText05::
	.string "la capacité {STR_VAR_2}.$"

gTVThePokemonBattleSeminarText06::
	.string "Alors, dans cette\n"
	.string "situation,\p"
	.string "que devrait\n"
	.string "utiliser le\p"
	.string "DRESSEUR ?\n"
	.string "… … … … … …\p"
	.string "La capacité\n"
	.string "{STR_VAR_1} !\p"
	.string "La bonne réponse !$"

gTVTrainerFanClubText00::
	.string "Tous ensemble maintenant !\n"
	.string "FAN CLUB DRESSEUR !\p"
	.string "MC : Comment ça\n"
	.string "groove, tout le monde ?\l"
	.string "Aujourd'hui, on a\p"
	.string "rassemblé les fans du\p"
	.string "super-populaire\p"
	.string "{STR_VAR_1} !\n"
	.string "FANS : {STR_VAR_1}\p"
	.string "! {STR_VAR_1} !\p"
	.string "MC : Quelle énergie\n"
	.string "! Merci à tous !$"

gTVTrainerFanClubText01::
	.string "FANS : Leur façon cool de lancer\n"
	.string "des POKé BALLS !$"

gTVTrainerFanClubText02::
	.string "FANS : Leur façon adorable de courir !$"

gTVTrainerFanClubText03::
	.string "FANS : Comme le DRESSEUR devient dur\n"
	.string "quand ça se complique !$"

gTVTrainerFanClubText04::
	.string "FANS : Les connaissances du DRESSEUR\n"
	.string "en POKéMON !$"

gTVTrainerFanClubText05::
	.string "FANS : La gentillesse du DRESSEUR\n"
	.string "envers tous les POKéMON !$"

gTVTrainerFanClubText06::
	.string "FANS : Les techniques incroyables\n"
	.string "de vélo du DRESSEUR !$"

gTVTrainerFanClubText07::
	.string "FANS : Le DRESSEUR achète des objets\n"
	.string "avec un style impressionnant !$"

gTVTrainerFanClubText08::
	.string "FANS : Le charmant talent du DRESSEUR\n"
	.string "pour donner des surnoms aux POKéMON !$"

gTVTrainerFanClubText09::
	.string "FANS : Le style déco de BASE SECRÈTE\n"
	.string "du DRESSEUR est génial !$"

gTVTrainerFanClubText10::
	.string "FANS : Les façons audacieuses du DRESSEUR\n"
	.string "d'utiliser les CT !$"

gTVTrainerFanClubText11::
	.string "MC : Comme vous venez de le voir, {STR_VAR_1}\n"
	.string "est chaud ! Trop chaud pour y toucher, ouille !\p"
	.string "Parmi les FANS de {STR_VAR_1}\n"
	.string "il y a un slogan spécial !\p"
	.string "MC : Quand je dis {STR_VAR_1},\n"
	.string "vous dites…\p"
	.string "FANS : {STR_VAR_2} !\p"
	.string "FANS : {STR_VAR_3} !\p"
	.string "FANS : {STR_VAR_2} !\p"
	.string "FANS : {STR_VAR_3} !\p"
	.string "MC : C'est ça, quand quelqu'un dit,\n"
	.string "« {STR_VAR_1} »…\p"
	.string "Répondez par, « {STR_VAR_2}\n"
	.string "{STR_VAR_3} ! »\p"
	.string "Ça a une sonorité si unique !\n"
	.string "Je comprends pourquoi les gens deviennent FANS\l"
	.string "de {STR_VAR_1} !\p"
	.string "OK, toi, devant la télé, rejoins-nous !\n"
	.string "Tous ensemble maintenant !\p"
	.string "MC : Quand je dis {STR_VAR_1},\n"
	.string "vous dites…\p"
	.string "FANS : {STR_VAR_2} !\p"
	.string "FANS : {STR_VAR_3} !\p"
	.string "FANS : {STR_VAR_2} !\p"
	.string "FANS : {STR_VAR_3} !\p"
	.string "MC : Merci de nous avoir rejoints, tous les\n"
	.string "FANS fous de {STR_VAR_1} !\l"
	.string "C'est la fin de l'émission ! À bientôt !\p"
	.string "MC : Quand je dis {STR_VAR_1},\n"
	.string "vous dites…\p"
	.string "FANS : {STR_VAR_2} !\p"
	.string "FANS : {STR_VAR_3} !$"

TVSpotTheCuties_Text_Intro::
	.string "REPÉREZ LES MIGNONS !\n"
	.string "POKéMON EN RUBANS !\p"
	.string "Bonjour, mes chers\p"
	.string "téléspectateurs !\n"
	.string "Je sais que\p"
	.string "vous serez\n"
	.string "d'accord, mais\l"
	.string "un POKéMON\p"
	.string "avec un RUBAN est\n"
	.string "vraiment spécial !$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "Le nombre de RUBANS que porte\n"
	.string "{STR_VAR_2} est de {STR_VAR_3}.\p"
	.string "Ça en dit long sur l'affection\n"
	.string "que {STR_VAR_1} porte à ce POKéMON.$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "{STR_VAR_2} porte d'incroyables {STR_VAR_3} RUBANS\n"
	.string "! Ça en dit long\p"
	.string "sur l'engagement de {STR_VAR_1}\n"
	.string "envers le POKéMON !$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "{STR_VAR_2} porte d'incroyables {STR_VAR_3} RUBANS\n"
	.string "! Ça montre l'engagement\p"
	.string "total de {STR_VAR_1} en\n"
	.string "tant que collectionneur !$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "Examinons de plus près les nombreux\n"
	.string "RUBANS portés par {STR_VAR_2}.$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "Le RUBAN CHAMPION est\n"
	.string "vraiment élégant. {STR_VAR_2} l'a\p"
	.string "reçu en entrant au\n"
	.string "PANthéON. Il révèle vraiment\p"
	.string "la bravoure de {STR_VAR_2}.\n"
	.string "{STR_VAR_2} et le RUBAN\p"
	.string "CHAMPION ! La combinaison\n"
	.string "est super efficace !$"

TVSpotTheCuties_Text_RibbonCool::
	.string "Le RUBAN COOL est vraiment\n"
	.string "élégant. {STR_VAR_2} l'a reçu pour\p"
	.string "avoir gagné un CONCOURS\n"
	.string "COOL. Il révèle vraiment\p"
	.string "le style de {STR_VAR_2}.\n"
	.string "{STR_VAR_2} et le RUBAN\p"
	.string "COOL ! La combinaison\n"
	.string "est super efficace !$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "Le RUBAN BEAUTÉ est vraiment\n"
	.string "élégant. {STR_VAR_2} l'a reçu pour\p"
	.string "avoir gagné un CONCOURS\n"
	.string "BEAUTÉ. Il révèle vraiment\p"
	.string "la beauté de {STR_VAR_2}.\n"
	.string "{STR_VAR_2} et le RUBAN\p"
	.string "BEAUTÉ ! La combinaison\n"
	.string "est super efficace !$"

TVSpotTheCuties_Text_RibbonCute::
	.string "Le RUBAN SÉDUCTION est vraiment\n"
	.string "élégant. {STR_VAR_2} l'a reçu pour\p"
	.string "avoir gagné un CONCOURS\n"
	.string "SÉDUCTION. Il révèle vraiment\p"
	.string "la séduction de {STR_VAR_2}.\n"
	.string "{STR_VAR_2} et le RUBAN\p"
	.string "SÉDUCTION ! La combinaison\n"
	.string "est super efficace !$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "Le RUBAN INTELLIGENCE est vraiment\n"
	.string "élégant. {STR_VAR_2} l'a reçu\p"
	.string "pour avoir gagné un\n"
	.string "CONCOURS INTELLIGENCE. Il révèle\p"
	.string "vraiment l'intelligence de {STR_VAR_2}.\n"
	.string "{STR_VAR_2} et le RUBAN\p"
	.string "INTELLIGENCE ! La combinaison\n"
	.string "est super efficace !$"

TVSpotTheCuties_Text_RibbonTough::
	.string "Le RUBAN ROBUSTESSE est vraiment\n"
	.string "élégant. {STR_VAR_2} l'a reçu pour\p"
	.string "avoir gagné un CONCOURS\n"
	.string "ROBUSTESSE. Il révèle vraiment\p"
	.string "la robustesse de {STR_VAR_2}.\n"
	.string "{STR_VAR_2} et le RUBAN\p"
	.string "ROBUSTESSE ! La combinaison\n"
	.string "est super efficace !$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "Le RUBAN VICTOIRE est vraiment\n"
	.string "élégant. {STR_VAR_2} l'a reçu pour\p"
	.string "ses exploits à la TOUR\n"
	.string "DE COMBAT. Il révèle vraiment\p"
	.string "la puissance de {STR_VAR_2}.\n"
	.string "{STR_VAR_2} et le RUBAN\p"
	.string "VICTOIRE ! La combinaison\n"
	.string "est super efficace !$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "Le RUBAN VICTOIRE est vraiment\n"
	.string "élégant.\p"
	.string "{STR_VAR_2} l'a reçu pour ses exploits\n"
	.string "à la TOUR DE COMBAT.\p"
	.string "Il révèle vraiment l'incroyable\n"
	.string "pouvoir de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} et le RUBAN VICTOIRE !\n"
	.string "La combinaison est super efficace !$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "Le RUBAN ARTISTE est vraiment\n"
	.string "élégant. {STR_VAR_2} l'a reçu pour\p"
	.string "avoir été le modèle d'un\n"
	.string "artiste. Il révèle vraiment le\p"
	.string "charme de star de {STR_VAR_2}.\n"
	.string "{STR_VAR_2} et le RUBAN\p"
	.string "ARTISTE ! La combinaison\n"
	.string "est super efficace !$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "Le RUBAN TRAVAILLEUR est\n"
	.string "vraiment élégant.\p"
	.string "{STR_VAR_2} l'a reçu pour son\n"
	.string "dévouement au travail.\p"
	.string "Il révèle vraiment la détermination\n"
	.string "de {STR_VAR_2}.\p"
	.string "{STR_VAR_2} et le RUBAN TRAVAILLEUR !\n"
	.string "La combinaison est super efficace !$"

TVSpotTheCuties_Text_Outro::
	.string "...Soupir...\p"
	.string "Les RUBANS et les POKéMON...\n"
	.string "Ils vont si bien ensemble !\p"
	.string "Avant de m'évanouir,\n"
	.string "je vous dis adieu !$"

gTVPokemonNewsBattleFrontierText00::
	.string "Bonjour !\n"
	.string "C'est l'heure des POKéMON NEWS.\p"
	.string "Nous avons de bonnes nouvelles de\n"
	.string "la ZONE DE COMBAT.$"

gTVPokemonNewsBattleFrontierText01::
	.string "Le DRESSEUR {STR_VAR_1} a établi un nouveau\n"
	.string "record de {STR_VAR_2} victoires consécutives lors du\l"
	.string "défi SALLE DE COMBAT SOLO\l"
	.string "de la TOUR DE COMBAT.\p"
	.string "Bravo à {STR_VAR_1} !$"

gTVPokemonNewsBattleFrontierText02::
	.string "Le DRESSEUR {STR_VAR_1} a établi un nouveau\n"
	.string "record de {STR_VAR_2} victoires consécutives lors du\l"
	.string "défi SALLE DE COMBAT EN DOUBLE\l"
	.string "de la TOUR DE COMBAT.\p"
	.string "Bravo à {STR_VAR_1} !$"

gTVPokemonNewsBattleFrontierText03::
	.string "Le DRESSEUR {STR_VAR_1} a établi un nouveau\n"
	.string "record de {STR_VAR_2} victoires consécutives lors du\l"
	.string "défi SALLE DE COMBAT MULTI\l"
	.string "de la TOUR DE COMBAT.\p"
	.string "Bravo à {STR_VAR_1} !$"

gTVPokemonNewsBattleFrontierText04::
	.string "Le DRESSEUR {STR_VAR_1} a établi un nouveau\n"
	.string "record de {STR_VAR_2} victoires consécutives\l"
	.string "ors du défi SALLE DE COMBATS MULTI\l"
	.string "EN LIEN de la TOUR DE COMBAT.\p"
	.string "Bravo à {STR_VAR_1} !$"

gTVPokemonNewsBattleFrontierText05::
	.string "Le DRESSEUR {STR_VAR_1} a établi un nouveau\n"
	.string "record de {STR_VAR_2} victoires consécutives\l"
	.string "en participant aux Tournois de COMBATS\l"
	.string "SIMPLES du DÔME DE COMBAT.\p"
	.string "Bravo à {STR_VAR_1} !$"

gTVPokemonNewsBattleFrontierText06::
	.string "Le DRESSEUR {STR_VAR_1} a établi un nouveau\n"
	.string "record de {STR_VAR_2} victoires consécutives\l"
	.string "en participant aux Tournois de COMBATS\l"
	.string "DOUBLES du DÔME DE COMBAT.\p"
	.string "Bravo à {STR_VAR_1} !$"

gTVPokemonNewsBattleFrontierText07::
	.string "Le DRESSEUR {STR_VAR_1} a établi un nouveau\n"
	.string "record de {STR_VAR_2} victoires consécutives lors du\l"
	.string "défi Échange Simple de l'USINE\l"
	.string "DE COMBAT.\p"
	.string "Bravo à {STR_VAR_1} !$"

gTVPokemonNewsBattleFrontierText08::
	.string "Le DRESSEUR {STR_VAR_1} a établi un nouveau\n"
	.string "record de {STR_VAR_2} victoires consécutives lors du\l"
	.string "défi Échange Double de l'USINE\l"
	.string "DE COMBAT.\p"
	.string "Bravo à {STR_VAR_1} !$"

gTVPokemonNewsBattleFrontierText09::
	.string "Le DRESSEUR {STR_VAR_1} a établi un nouveau\n"
	.string "record en franchissant {STR_VAR_2} salles\l"
	.string "lors du défi Choix de Combat\l"
	.string "de la TOUR DE COMBAT.\p"
	.string "Bravo à {STR_VAR_1} !$"

gTVPokemonNewsBattleFrontierText10::
	.string "Le DRESSEUR {STR_VAR_1} a établi un nouveau\n"
	.string "record de {STR_VAR_2} victoires consécutives en\l"
	.string "participant aux Tournois K.O. Fixe\l"
	.string "de l'ARENE DE COMBAT.\p"
	.string "Bravo à {STR_VAR_1} !$"

gTVPokemonNewsBattleFrontierText11::
	.string "Le DRESSEUR {STR_VAR_1} a établi un nouveau\n"
	.string "record de {STR_VAR_2} victoires consécutives lors du\l"
	.string "défi SALLE DE COMBAT SOLO\l"
	.string "du PALAIS DE COMBAT.\p"
	.string "Bravo à {STR_VAR_1} !$"

gTVPokemonNewsBattleFrontierText12::
	.string "Le DRESSEUR {STR_VAR_1} a établi un nouveau\n"
	.string "record de {STR_VAR_2} victoires consécutives lors du\l"
	.string "défi SALLE DE COMBAT EN DOUBLE\l"
	.string "du PALAIS DE COMBAT.\p"
	.string "Bravo à {STR_VAR_1} !$"

gTVPokemonNewsBattleFrontierText13::
	.string "Le DRESSEUR {STR_VAR_1} a établi un nouveau\n"
	.string "record en franchissant {STR_VAR_2} étages\l"
	.string "ors du défi Quête de Combat\l"
	.string "de la PYRAMIDE DE COMBAT.\p"
	.string "Bravo à {STR_VAR_1} !$"

gTVPokemonNewsBattleFrontierText14::
	.string "Et aux trois POKéMON, {STR_VAR_1},\n"
	.string "{STR_VAR_2}, et {STR_VAR_3} !\p"
	.string "Félicitations pour votre\n"
	.string "performance record !$"

gTVPokemonNewsBattleFrontierText15::
	.string "Et aux deux POKéMON, {STR_VAR_1}\n"
	.string "et {STR_VAR_2} !\p"
	.string "Félicitations pour votre\n"
	.string "performance historique !$"

gTVPokemonNewsBattleFrontierText16::
	.string "Et aux quatre POKéMON : {STR_VAR_1} !\p"
	.string "{STR_VAR_2} !\p"
	.string "{STR_VAR_3} !$"

gTVPokemonNewsBattleFrontierText17::
	.string "Et {STR_VAR_1} !\p"
	.string "Félicitations pour ta\n"
	.string "performance record !$"

gTVPokemonNewsBattleFrontierText18::
	.string "Espérons d'autres exploits record de\n"
	.string "{STR_VAR_1} et des POKéMON\l"
	.string "fidèles ! C'était l'actualité\p"
	.string "sur POKéMON NEWS !$"

gTVWhatsNo1InHoennTodayText00::
	.string "QU'EST-CE QUI EST NO 1 À HOENN\n"
	.string "AUJOURD'HUI ?\p"
	.string "Oui, c'est l'heure !\n"
	.string "Bonjour les téléspectateurs !\p"
	.string "Vous donnez le meilleur de vous-\n"
	.string "même ?\p"
	.string "Regardons le DRESSEUR qui a le\n"
	.string "mieux réussi aujourd'hui ! Le DRESSEUR no 1 d'aujourd'hui n'est autre que {STR_VAR_1} !$"

gTVWhatsNo1InHoennTodayText01::
	.string "En un jour, {STR_VAR_1} a fait\n"
	.string "tourner les MACHINES au CASINO {STR_VAR_2}\p"
	.string "fois. En jouant, on a entendu\n"
	.string "{STR_VAR_1} murmurer : « Pour moi,\l"
	.string "les rouleaux ne tournent même pas…\l"
	.string "» Ce n'est pas intéressant ?$"

gTVWhatsNo1InHoennTodayText02::
	.string "En un jour, {STR_VAR_1} a joué\n"
	.string "à la ROULETTE au CASINO {STR_VAR_2}\l"
	.string "fois. En jouant, {STR_VAR_1} a crié,\p"
	.string "« Que les billes décident\n"
	.string "! » Les yeux du\p"
	.string "DRESSEUR étaient concentrés et son\n"
	.string "visage montrait de la concentration.$"

gTVWhatsNo1InHoennTodayText03::
	.string "En un jour, {STR_VAR_1} a combattu\n"
	.string "des POKéMON sauvages {STR_VAR_2} fois !\p"
	.string "Apparemment, les POKéMON de {STR_VAR_1}\n"
	.string "sont devenus incomparablement plus forts.\p"
	.string "Ils semblent prêts à combattre\n"
	.string "partout, tout le temps !$"

gTVWhatsNo1InHoennTodayText04::
	.string "En un seul jour, {STR_VAR_1} a fait tourner\n"
	.string "le MIXEUR À BAIES {STR_VAR_2} fois !\p"
	.string "Vers la fin, même {STR_VAR_1}\n"
	.string "avait l'air d'avoir le tournis.\p"
	.string "Le DRESSEUR semblait tituber\n"
	.string "comme un SPINDA !$"

gTVWhatsNo1InHoennTodayText05::
	.string "En un seul jour, {STR_VAR_1} a planté\n"
	.string "{STR_VAR_2} BAIES !\p"
	.string "Du coup, les vêtements de\n"
	.string "{STR_VAR_1} étaient couverts de terre.\p"
	.string "Là où le DRESSEUR a planté, d'innombrables\n"
	.string "fleurs ont éclos.\p"
	.string "On dit que ces fleurs apaisent\n"
	.string "les émotions des gens.$"

gTVWhatsNo1InHoennTodayText06::
	.string "En un seul jour, {STR_VAR_1} a cueilli\n"
	.string "{STR_VAR_2} BAIES !\p"
	.string "Le SAC de {STR_VAR_1} est devenu si rempli\n"
	.string "de BAIES que le DRESSEUR avait du mal\l"
	.string "à marcher ensuite !$"

gTVWhatsNo1InHoennTodayText07::
	.string "En un seul jour,\n"
	.string "{STR_VAR_1} a obtenu\p"
	.string "{STR_VAR_2} Points\n"
	.string "de Combat !\l"
	.string "{STR_VAR_1} a ensuite été\l"
	.string "vu en train de célébrer\p"
	.string "au PARC DES COMBATS !\n"
	.string "Félicitations !$"

gTVWhatsNo1InHoennTodayText08::
	.string "Eh bien, c'est quelque chose !\p"
	.string "{STR_VAR_1} !\n"
	.string "Tu es le DRESSEUR nº1 du jour !\p"
	.string "Téléspectateurs, prenez exemple sur {STR_VAR_1} !\n"
	.string "Vous aussi, vous pouvez être nº1 chaque jour !$"

TVSecretBaseSecrets_Text_Intro::
	.string "SECRETS DE BASE SECRÈTE !\p"
	.string "Que font les DRESSEURS dans\n"
	.string "le secret des BASES SECRÈTES\p"
	.string "? Aujourd'hui, on enquête sur\n"
	.string "la BASE SECRÈTE de {STR_VAR_1}.\p"
	.string "Oh ? On dirait que\n"
	.string "{STR_VAR_2} est venu rendre visite.\p"
	.string "Jetons un œil ! Que\p"
	.string "va faire {STR_VAR_2} ?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "Que va faire {STR_VAR_2} ensuite ?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "Et maintenant, que va faire {STR_VAR_2} ?$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "Au final, {STR_VAR_2} a fait {STR_VAR_3} pas\n"
	.string "dans la BASE SECRÈTE de {STR_VAR_1} avant\l"
	.string "de partir.$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "Hmm…\p"
	.string "Il semble que la BASE SECRÈTE de {STR_VAR_1}\n"
	.string "n'ait pas intéressé {STR_VAR_2}…$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "{STR_VAR_2} semble avoir beaucoup apprécié\n"
	.string "la BASE SECRÈTE de {STR_VAR_1}.$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "{STR_VAR_2} semble être devenu un grand fan\n"
	.string "de la\l"
	.string "BASE SECRÈTE de {STR_VAR_1}.$"

TVSecretBaseSecrets_Text_Outro::
	.string "Les téléspectateurs voudront peut-être aussi\n"
	.string "visiter la BASE SECRÈTE de {STR_VAR_1}.\p"
	.string "Rendez-vous la prochaine fois pour une autre\n"
	.string "BASE SECRÈTE ! Merci de nous avoir rejoints !$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "Le visiteur s'est arrêté !\p"
	.string "Le visiteur ne bouge plus du tout !\p"
	.string "La BASE SECRÈTE de {STR_VAR_1}\n"
	.string "était si peu impressionnante ?$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "Le visiteur s'est arrêté !\p"
	.string "Le visiteur ne bouge plus du tout !\p"
	.string "Est-ce la fatigue ?\n"
	.string "Le visiteur est-il épuisé ?$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "Le visiteur s'est assis sur une chaise !\n"
	.string "Le visiteur est assis !\p"
	.string "Regarde cette expression de plaisir !\p"
	.string "Cette chaise doit être très confortable\n"
	.string "pour provoquer une telle réaction !$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "Le visiteur a foncé sur un ballon !\p"
	.string "Il a éclaté !\n"
	.string "Oh là là, il a crevé !\p"
	.string "Le visiteur semble surpris\n"
	.string "par le bruit soudain !$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "Le visiteur est entré dans une TENTE !\p"
	.string "Le visiteur court partout !\p"
	.string "Oh là là, le visiteur s'amuse !\p"
	.string "Le visiteur semble surpris par\n"
	.string "la taille de la TENTE !$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "Le visiteur examine\n"
	.string "une plante en pot !\p"
	.string "Le visiteur a des goûts\n"
	.string "étonnamment raffinés !$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "Le visiteur examine\n"
	.string "un BOUCLIER D'OR !\p"
	.string "Les yeux du visiteur semblent\n"
	.string "briller d'émerveillement !$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "Le visiteur examine\n"
	.string "un BOUCLIER ARGENTÉ !\p"
	.string "Le visiteur semble avoir les yeux écarquillés !$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "Le visiteur examine\n"
	.string "un ORNEMENT EN VERRE !\p"
	.string "Oh, non !\p"
	.string "Le visiteur le touche !\p"
	.string "Il est couvert\n"
	.string "de traces de doigts…$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "Le visiteur regarde la télévision !\p"
	.string "On dirait qu'on a un grand fan de la télé !$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "Le visiteur a écrasé une BOULE DE BOUE !\p"
	.string "Le visiteur a l'air ravi !$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "…Oh ? Le visiteur cherche\p"
	.string "dans son propre SAC et\n"
	.string "fouille dedans ! Le visiteur\p"
	.string "a sorti un {STR_VAR_2}\n"
	.string "! Regarde le visiteur\p"
	.string "sourire en tenant le\n"
	.string "{STR_VAR_2} ! C'est comme\p"
	.string "une pub TV !$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "Le visiteur attrape un coussin et…$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "…commence à le frapper !\p"
	.string "Le visiteur est-il très stressé ?$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "…le serre fort !\p"
	.string "Le visiteur serait-il content\n"
	.string "de quelque chose ?$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "Le visiteur cause avec\n"
	.string "{STR_VAR_1} !\p"
	.string "On dirait qu'ils vont\n"
	.string "se battre !\p"
	.string "Et…\p"
	.string "C'est le visiteur !\n"
	.string "Le visiteur a gagné un match à l'extérieur !\p"
	.string "Le visiteur fait\n"
	.string "une danse de la victoire !$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "Le visiteur cause avec\n"
	.string "{STR_VAR_1} !\p"
	.string "On dirait qu'ils vont\n"
	.string "se battre !\p"
	.string "Et…\p"
	.string "C'est le visiteur !\n"
	.string "Le visiteur a gagné !\p"
	.string "Le visiteur fait une danse de la victoire !$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "Le visiteur discute avec\n"
	.string "{STR_VAR_1} ! On dirait\p"
	.string "qu'ils vont se battre\n"
	.string "! Et… Non, le\p"
	.string "visiteur a refusé !\p"
	.string "Il n'y aura pas\p"
	.string "de combat finalement !\p"
	.string "Le visiteur a-t-il trouvé\n"
	.string "{STR_VAR_1} peu attrayant ?$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "Le visiteur fixe intensément\n"
	.string "une affiche !\p"
	.string "L'affiche plaît-elle\n"
	.string "au visiteur ?\p"
	.string "…Mais… Il y a quelque chose de dérangeant\n"
	.string "dans le regard du visiteur.$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "Le visiteur a marché sur un TAPIS NOTE !\p"
	.string "…Hmm…\n"
	.string "Le visiteur a composé une drôle de mélodie !$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "Le visiteur cause avec\n"
	.string "{STR_VAR_1} !\p"
	.string "On dirait qu'ils vont\n"
	.string "se battre !\p"
	.string "Et…\p"
	.string "Match nul !\n"
	.string "Rien n'est résolu !\p"
	.string "Les deux DRESSEURS semblent très\n"
	.string "déçus !$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "Le visiteur a marché sur\n"
	.string "un TAPIS TOURNANT ! On\p"
	.string "dirait que le visiteur a\p"
	.string "le vertige ! Le visiteur\n"
	.string "titube ! Attention !$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "Le visiteur tend la main vers\n"
	.string "un ORNEMENT DE SABLE !\p"
	.string "Oh !\p"
	.string "Il s'est effrité !\n"
	.string "Il est tombé en morceaux !\p"
	.string "Le visiteur a l'air penaud\n"
	.string "et coupable !$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "Le visiteur frotte un bureau\n"
	.string "avec son doigt !\p"
	.string "Apparemment, le visiteur n'approuve pas\n"
	.string "la poussière !\p"
	.string "Le visiteur est étonnamment soucieux\n"
	.string "de la propreté !$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "Le visiteur fixe une BRIQUE !\p"
	.string "Peut-être que le visiteur réfléchit\n"
	.string "à l'objet posé sur la BRIQUE.$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "Le visiteur traverse\n"
	.string "la PLANCHE SOLIDE.\p"
	.string "Le visiteur regarde constamment vers le bas.\p"
	.string "Le visiteur semble étonnamment\n"
	.string "timide et prudent !$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "Le visiteur regarde intensément\n"
	.string "une CLÔTURE !\p"
	.string "Une nouvelle idée de piège lui est-elle\n"
	.string "venue à l'esprit ?$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "Le visiteur a marché sur\n"
	.string "un TAPIS BRILLANT !\p"
	.string "Le visiteur prend toute une variété\n"
	.string "de poses !\p"
	.string "Le visiteur semble fantasmer\n"
	.string "sur le fait d'être une idole !$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "Le visiteur fixe intensément un\n"
	.string "PNEU ! Le visiteur\p"
	.string "se demande peut-être quelle\n"
	.string "voiture pourrait l'utiliser ?$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "Le visiteur a grimpé sur un SUPPORT !\p"
	.string "Le visiteur regarde la BASE\n"
	.string "de {STR_VAR_1} d'en haut !\p"
	.string "Et…\p"
	.string "Pousse un rugissement !\n"
	.string "Le visiteur rugit !$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "Le visiteur a foncé tête baissée dans\n"
	.string "une PORTE FRAGILE !\p"
	.string "Le visiteur éclate de rire !$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "Le visiteur parle à une POUPÉE !\p"
	.string "…C'est un peu flippant…$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "Le visiteur grimpe à l'échelle\n"
	.string "sur un TOBOGGAN !\p"
	.string "Et…\p"
	.string "Le visiteur est descendu en glissant !\p"
	.string "On dirait que le visiteur passe\n"
	.string "un sacré bon moment !$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "Le visiteur grimpe à l'échelle\n"
	.string "sur un TOBOGGAN !\p"
	.string "Et…\p"
	.string "Le visiteur est redescendu\n"
	.string "par l'échelle !\p"
	.string "Le visiteur a-t-il eu soudainement la trouille ?$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "Le visiteur a marché sur\n"
	.string "un TAPIS DE SAUT !\p"
	.string "Le visiteur a sauté une fois !\p"
	.string "Deux fois !\p"
	.string "Et un atterrissage réussi !\p"
	.string "Le visiteur applaudit !\n"
	.string "Quelle performance solo !$"

gTVSafariFanClubText00::
	.string "FAN CLUB SAFARI !\p"
	.string "REPORTER :\n"
	.string "D'accord, les amis !\p"
	.string "Vous lancez des\n"
	.string "SAFARI BALLS, hein ?\p"
	.string "Moi aussi\n"
	.string "j'en lance !\p"
	.string "Bonne chance dans\n"
	.string "la ZONE SAFARI !$"

gTVSafariFanClubText01::
	.string "GUIDE : Tout le monde semble s'y mettre\n"
	.string "à fond.\p"
	.string "{STR_VAR_1} s'en sort particulièrement bien.\p"
	.string "Avant, {STR_VAR_1} a attrapé\n"
	.string "{STR_VAR_2} POKéMON.$"

gTVSafariFanClubText02::
	.string "Le DRESSEUR est habile avec les {POKEBLOCK}S.\n"
	.string "Il a utilisé {STR_VAR_2} cette fois, je crois.$"

gTVSafariFanClubText03::
	.string "Le DRESSEUR n'a pas utilisé un seul\n"
	.string "{POKEBLOCK} ! Pas un seul !\p"
	.string "Voilà un expert.$"

gTVSafariFanClubText04::
	.string "JOURNALISTE : C'est vrai, alors ?\p"
	.string "On dirait que notre camarade {STR_VAR_1}\n"
	.string "est un solide DRESSEUR du PARC SAFARI !\p"
	.string "Continue comme ça !\n"
	.string "Bravo !$"

gTVSafariFanClubText05::
	.string "GUIDE : Personne ne semble s'en sortir\n"
	.string "très bien.\p"
	.string "{STR_VAR_1} a eu particulièrement du mal.\p"
	.string "Avant, le DRESSEUR n'a réussi à attraper\n"
	.string "que {STR_VAR_2} POKéMON.$"

gTVSafariFanClubText06::
	.string "GUIDE : Personne ne semble se débrouiller\n"
	.string "comme il faut.\p"
	.string "{STR_VAR_1} a eu particulièrement du mal.\p"
	.string "Avant, ce DRESSEUR n'a attrapé\n"
	.string "aucun POKéMON. Pas un seul !$"

gTVSafariFanClubText07::
	.string "Le DRESSEUR utilise des {POKEBLOCK}S.\n"
	.string "Il a utilisé {STR_VAR_2} cette fois, je crois.\p"
	.string "Mais bon, j'aimerais que le DRESSEUR\n"
	.string "s'améliore un peu.$"

gTVSafariFanClubText08::
	.string "Je pense que le DRESSEUR aurait eu plus de chance\n"
	.string "en utilisant des {POKEBLOCK}S, qui n'ont pas\l"
	.string "é été utilisés cette fois-là.$"

gTVSafariFanClubText09::
	.string "JOURNALISTE : C'est vrai, alors ?\p"
	.string "On dirait que notre camarade {STR_VAR_1}\n"
	.string "a besoin de plus de SAFARI BALLS !\p"
	.string "Les spectateurs devraient l'encourager !\n"
	.string "Allez {STR_VAR_1} !$"

gTVSafariFanClubText10::
	.string "JOURNALISTE : Tout à fait, c'est ça !\n"
	.string "Affronter les défis, c'est important !\p"
	.string "Spectateurs, continuez à soutenir\n"
	.string "{STR_VAR_1} !\p"
	.string "Courage !$"

ContestLiveUpdates_Text_Intro::
	.string "« ACTUALITÉS CONCOURS POKéMON EN DIRECT ! »\p"
	.string "MC : Merci de nous rejoindre !\p"
	.string "Nous sommes en direct du site du\n"
	.string "{STR_VAR_1} qui vient de se terminer.\p"
	.string "La salle est encore remplie d'un\n"
	.string "public qui ne veut pas partir.\p"
	.string "Spectateur : {STR_VAR_2} !\p"
	.string "Spectateur : {STR_VAR_3} !\p"
	.string "MC : Comme vous venez de l'entendre, le CONCOURS\n"
	.string "a été remporté par le POKéMON {STR_VAR_2}\l"
	.string "de {STR_VAR_3}.\p"
	.string "Spectateur : {STR_VAR_2} !\n"
	.string "Tu es le meilleur !\p"
	.string "Spectateur : {STR_VAR_3} !\n"
	.string "Bravo !\p"
	.string "MC : Écoutons ce que les fans ont à\n"
	.string "dire sur ce CONCOURS.$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "Spectateur : Le {STR_VAR_2} était au top\n"
	.string "en jugement primaire et secondaire ! Ce\p"
	.string "{STR_VAR_2} va continuer à gagner !$"

ContestLiveUpdates_Text_BetterRound2::
	.string "Spectateur : Le {STR_VAR_2} n'a pas bien\n"
	.string "réussi au jugement primaire, mais il a\l"
	.string "excelé au jugement secondaire !\p"
	.string "C'était un retour miraculeux\n"
	.string "pour ce {STR_VAR_2}. Youpi !$"

ContestLiveUpdates_Text_EqualRounds::
	.string "Spectateur : Le {STR_VAR_2} est resté\n"
	.string "constant tout au long des jugements\l"
	.string "primaire et secondaire.\p"
	.string "{STR_VAR_3} et le {STR_VAR_2},\n"
	.string "ce n'est pas un duo ordinaire !$"

ContestLiveUpdates_Text_BetterRound1::
	.string "Spectateur : En termes de {STR_VAR_1},\n"
	.string "ce {STR_VAR_2} était remarquable.\p"
	.string "J'espère qu'il fera de meilleures\n"
	.string "séquences la prochaine fois, cependant.$"

ContestLiveUpdates_Text_GotNervous::
	.string "Spectateur : Quand le {STR_VAR_2} s'est\n"
	.string "mis à stresser, je n'ai pas pu m'empêcher de\l"
	.string "crier des encouragements.\p"
	.string "J'aimerais dire ceci à ce\n"
	.string "{STR_VAR_2} : « Félicitations ! »$"

ContestLiveUpdates_Text_StartledFoes::
	.string "Spectateur : L'appel de ce {STR_VAR_2}\n"
	.string "m'a surpris moi aussi !\p"
	.string "{STR_VAR_2}, tu étais génial !$"

ContestLiveUpdates_Text_UsedCombo::
	.string "Spectateur : Le combo d'appel de ce {STR_VAR_2}\n"
	.string "était époustouflant !\p"
	.string "Ça m'a secoué jusqu'au plus profond de moi !$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "Spectateur : L'appel du {STR_VAR_2} gagnant\n"
	.string "m'a fait battre le cœur !$"

ContestLiveUpdates_Text_WasCool::
	.string "{STR_VAR_2} !\n"
	.string "Tu as été cool !$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "{STR_VAR_2} !\n"
	.string "Tu étais magnifique !$"

ContestLiveUpdates_Text_WasCute::
	.string "{STR_VAR_2} !\n"
	.string "Tu as été mignon !$"

ContestLiveUpdates_Text_WasSmart::
	.string "{STR_VAR_2} !\n"
	.string "Tu as été malin !$"

ContestLiveUpdates_Text_WasTough::
	.string "{STR_VAR_2} !\n"
	.string "Tu as été fort !$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "Spectateur : L'appel du {STR_VAR_2} gagnant\n"
	.string "me fait encore battre le cœur !$"

ContestLiveUpdates_Text_VeryCool::
	.string "{STR_VAR_2} !\n"
	.string "Tu es le summum de la classe !$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "{STR_VAR_2} !\n"
	.string "Tu es la plus belle !$"

ContestLiveUpdates_Text_VeryCute::
	.string "{STR_VAR_2} !\n"
	.string "Tu es tout simplement la plus mignonne !$"

ContestLiveUpdates_Text_VerySmart::
	.string "{STR_VAR_2} !\n"
	.string "Tu es le plus intelligent des intelligents !$"

ContestLiveUpdates_Text_VeryTough::
	.string "{STR_VAR_2} !\n"
	.string "Tu es le plus coriace des coriaces !$"

ContestLiveUpdates_Text_TookBreak::
	.string "Spectateur : Même quand {STR_VAR_2}\n"
	.string "a fait une pause dans ses charmes,\l"
	.string "je ne pouvais pas détacher mes yeux.\p"
	.string "Je suis captivé par ce {STR_VAR_2}.$"

ContestLiveUpdates_Text_GotStartled::
	.string "Spectateur : Quand {STR_VAR_2} a été\n"
	.string "surpris par le charme d'un autre POKéMON,\l"
	.string "j'étais au bord des larmes.\p"
	.string "{STR_VAR_2}, tu as tenu bon !\n"
	.string "Bravo !$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "Spectateur : Oh…\n"
	.string "Le {STR_VAR_3} de ce {STR_VAR_2} !\l"
	.string "Le {STR_VAR_3} de ce {STR_VAR_2} !\l"
	.string "Le {STR_VAR_3} de ce {STR_VAR_2} !\l"
	.string "Comment peut-il être si merveilleux ?$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "MC : Voilà, c'est tout. Cet\n"
	.string "endroit est plein de fans de\p"
	.string "{STR_VAR_1} ! Je devrais aussi mentionner\n"
	.string "qu'un autre POKéMON, le {STR_VAR_3}\l"
	.string "de {STR_VAR_2}, a attiré mon\p"
	.string "attention. Le {STR_VAR_3} de {STR_VAR_2}…$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "Il n'a pas réussi à faire une seule démonstration\n"
	.string "pendant le jugement secondaire à cause du trac.\p"
	.string "La prochaine fois, j'aimerais voir ce\n"
	.string "{STR_VAR_1} faire au moins une démonstration.$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "Il est arrivé dernier au jugement\n"
	.string "primaire et secondaire.\p"
	.string "J'espère que {STR_VAR_1} réentraînera ce\n"
	.string "{STR_VAR_2} et effacera la honte de\l"
	.string "cette dernière place indiscutable.$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "Il n'a pas su profiter de\n"
	.string "l'excitation du public et faire une\l"
	.string "démonstration appropriée. Nous espérons que\p"
	.string "{STR_VAR_1} apprendra à sentir le\n"
	.string "public et à monter l'excitation\l"
	.string "au comble la prochaine fois.$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "Après avoir fini premier au jugement\n"
	.string "principal, ses démonstrations au jugement secondaire\l"
	.string "n'ont pas convaincu. Il a\p"
	.string "subi une humiliante défaite après\n"
	.string "avoir mené. Je suis sûr\p"
	.string "que {STR_VAR_1} étudie comment faire\n"
	.string "des démonstrations plus efficaces maintenant.$"

ContestLiveUpdates_Text_NeverExciting::
	.string "Le public n'a jamais été enthousiasmé par\n"
	.string "ses actions lors du second jugement.\p"
	.string "On espère qu'il arrêtera de s'inquiéter des\n"
	.string "autres POKéMON et apprendra à mieux\l"
	.string "séduire le public.$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "Il a perdu face\n"
	.string "au {STR_VAR_2} de {STR_VAR_1}\p"
	.string "de justesse. Ça doit\n"
	.string "être déchirant de\p"
	.string "perdre si près\n"
	.string "de la victoire.$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "Il a déçu le JUGE en\n"
	.string "répétant les mêmes actions.\p"
	.string "C'est une erreur impardonnable dans tout\n"
	.string "CONCOURS, et le POKéMON en a payé le prix.\p"
	.string "{STR_VAR_1} devrait se sentir coupable de\n"
	.string "cette piètre prestation.$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{STR_VAR_1} a fourni un effort vaillant,\n"
	.string "mais…\p"
	.string "Tout cela n'a servi à rien, finissant dernier.\p"
	.string "{STR_VAR_1} devrait tirer une leçon de cette défaite\n"
	.string "et en faire bon usage.$"

ContestLiveUpdates_Text_Outro::
	.string "J'aimerais terminer cette émission\n"
	.string "avec notre salut habituel aux\p"
	.string "gagnants.\n"
	.string "Cette fois, c'est {STR_VAR_1} et\p"
	.string "le {STR_VAR_2} !\n"
	.string "MC : Tout le monde est prêt ?\p"
	.string "Ensemble maintenant !\n"
	.string "Public : {STR_VAR_1} ! {STR_VAR_2} !\l"
	.string "Félicitations ! Vous êtes les gagnants du CONCOURS !$"

gTVPokemonBattleUpdateText00::
	.string "« ACTUALITÉS COMBATS POKéMON ! »\p"
	.string "Les résultats des combats POKéMON\n"
	.string "en direct !$"

gTVPokemonBattleUpdateText01::
	.string "Les DRESSEURS {STR_VAR_1} et\n"
	.string "{STR_VAR_2} se sont affrontés dans\l"
	.string "un COMBAT {STR_VAR_3}.\p"
	.string "Ce match s'est terminé par la victoire de\n"
	.string "{STR_VAR_1} !$"

gTVPokemonBattleUpdateText02::
	.string "Dans le combat, {STR_VAR_2} de\n"
	.string "{STR_VAR_1} était une force redoutable\l"
	.string "en utilisant {STR_VAR_3} !$"

gTVPokemonBattleUpdateText03::
	.string "Le {STR_VAR_2} de {STR_VAR_1} a eu une\n"
	.string "performance décevante qui a fait mal.$"

gTVPokemonBattleUpdateText04::
	.string "Félicitations pour ta victoire,\n"
	.string "{STR_VAR_1} !\p"
	.string "Et pour le vaincu {STR_VAR_2},\n"
	.string "nous espérons un meilleur résultat la prochaine fois !\p"
	.string "C'est la fin de cet épisode de\n"
	.string "« ACTUALITÉS COMBATS POKéMON ! »$"

gTVPokemonBattleUpdateText05::
	.string "Les équipes des DRESSEURS {STR_VAR_1} et\n"
	.string "{STR_VAR_2} se sont affrontées en COMBAT MULTI.\p"
	.string "Ce match s'est terminé par la victoire de\n"
	.string "l'équipe de {STR_VAR_1}.$"

gTVPokemonBattleUpdateText06::
	.string "Pendant le combat, le {STR_VAR_2} de\n"
	.string "l'équipe de {STR_VAR_1} était une force redoutable\l"
	.string "en utilisant {STR_VAR_3}.$"

gTVPokemonBattleUpdateText07::
	.string "La faible performance\n"
	.string "du {STR_VAR_3}\p"
	.string "sur l'équipe\n"
	.string "de {STR_VAR_2}\p"
	.string "a vraiment fait mal.\n"
	.string "Félicitations pour la\p"
	.string "victoire de\n"
	.string "ton équipe !$"

GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "GABBY : Oh ! On vient de repérer un DRESSEUR\n"
	.string "coriace ici, de tous les endroits !\p"
	.string "OK, caméra !\n"
	.string "On va faire cette interview.$"

GabbyAndTy_Text_GabbyIntro:
	.string "GABBY : Oh ! C'est toi, {PLAYER} ! Salut !\n"
	.string "Tu te souviens de nous la dernière fois ?\p"
	.string "Tu peux nous montrer à quel point tu es\n"
	.string "devenu plus fort ? OK, c'est parti pour l'interview !$"

GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "GABBY : Mes yeux ne m'ont pas menti !\n"
	.string "J'ai découvert un DRESSEUR étonnant !$"

GabbyAndTy_Text_WhoAreYouInterview:
	.string "GABBY : Génial\n"
	.string "! Génial !\p"
	.string "Qui es-tu ?!\n"
	.string "Je savais qu'on était\p"
	.string "sur quelque\n"
	.string "chose de fou\l"
	.string "quand on t'a repéré !\p"
	.string "{PLAYER}, tu\n"
	.string "es une star !$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "GABBY : « {STR_VAR_1} ! »\p"
	.string "Tu te souviens ? C'est la citation que tu nous as\n"
	.string "donnée comme phrase décisive la dernière fois.\p"
	.string "Je n'oublie jamais ce genre de choses !$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "La dernière fois qu'on s'est battus, tu nous as\n"
	.string "écrasés avant qu'on puisse nous préparer…\p"
	.string "Bref, qu'en penses-tu ?\n"
	.string "Tu veux qu'on te refasse une interview ?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "La dernière fois qu'on s'est battus, tu ne\n"
	.string "nous as pas lancé une POKé BALL ?\p"
	.string "On était choqués ! Alors on l'a\n"
	.string "raconté à tout le monde, absolument tout\p"
	.string "le monde ! Bref, qu'en penses-tu ?\n"
	.string "Tu veux qu'on t'interviewe à nouveau ?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "La dernière fois qu'on s'est battus, tes talents\n"
	.string "avec les objets nous ont habilement vaincus.\p"
	.string "Bref, qu'en penses-tu ?\n"
	.string "Tu veux qu'on t'interviewe à nouveau ?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "La dernière fois qu'on s'est battus,\n"
	.string "on a réussi à avoir l'air respectable.\p"
	.string "Bon, qu'en penses-tu ?\n"
	.string "Tu veux qu'on te re-interviewe ?$"

GabbyAndTy_Text_InterviewAgain:
	.string "Bref, qu'en penses-tu ?\n"
	.string "Tu veux être interviewé à nouveau ?$"

GabbyAndTy_Text_DescribeYourFeelings:
	.string "Tu veux bien ?\n"
	.string "Merci !\p"
	.string "OK, décris-moi tes impressions\n"
	.string "sur notre combat, mais il faut que\l"
	.string "ce soit court et percutant. Vas-y !$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "GABBY : Mmm, ouais !\n"
	.string "C'est la conclusion parfaite !\p"
	.string "J'ai le sentiment que ça\n"
	.string "fera une super émission TV.\p"
	.string "Il y a une chance\n"
	.string "qu'ils diffusent ça à la\p"
	.string "TV, alors cherche-nous ! OK\n"
	.string "! On se revoit !$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "GABBY : Oh…\p"
	.string "D'accord, mais n'abandonne pas !\n"
	.string "On gardera un œil sur toi !$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
	.string "GABBY : On gardera un œil sur\n"
	.string "toi !$"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "GABBY : Y a-t-il un DRESSEUR fort\n"
	.string "quelque part avec beaucoup de POKéMON ?$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "GABBY : Waouh, tu es quelque chose !\p"
	.string "Tu es devenu beaucoup plus fort--\n"
	.string "beaucoup--depuis notre dernier\p"
	.string "combat.\n"
	.string "On avait raison de te repérer\p"
	.string "comme DRESSEUR prometteur.\n"
	.string "Alors, qu'est-ce que tu en dis ?\l"
	.string "Tu veux bien nous accorder une interview cette fois ?$"

GabbyAndTy_Text_GabbyDefeat:
	.string "GABBY : C'était un combat intense !\n"
	.string "Tu as tout filmé ?$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "TY : Hé, regarde ! Un DRESSEUR\n"
	.string "à l'air coriace, en plein milieu de nulle part !\l"
	.string "La caméra tourne !$"

GabbyAndTy_Text_TyIntro:
	.string "TY : Hé, regarde !\n"
	.string "Je me souviens de toi !\p"
	.string "Je vais filmer tout ce combat\n"
	.string "avec ma caméra !$"

GabbyAndTy_Text_TyPostBattle:
	.string "TY : Tu es un naturel !\n"
	.string "J'ai de super images ici !$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "TY : Tu n'as qu'un seul\n"
	.string "POKéMON et c'est tout ? Si\p"
	.string "tu avais plus de POKéMON, ce\n"
	.string "serait mieux pour les images, mais…$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "TY : Oui, on a repéré un DRESSEUR chaud.\n"
	.string "C'est un énorme scoop pour nous !$"

GabbyAndTy_Text_TyDefeat:
	.string "TY : Ouais, j'ai tout filmé.\n"
	.string "Tout le combat est en caméra.$"

gTVInSearchOfTrainersText00::
	.string "À LA RECHERCHE\p"
	.string "DE DRESSEURS…\n"
	.string "GABBY : Salut\p"
	.string "! Aujourd'hui\n"
	.string "je visite une zone\p"
	.string "près de {STR_VAR_1}.\n"
	.string "On essaie de repérer\p"
	.string "des DRESSEURS forts\n"
	.string "pour notre émission !$"

gTVInSearchOfTrainersText01::
	.string "On s'est déjà battus contre {PLAYER}, mais on\n"
	.string "peut attester que ce DRESSEUR s'est nettement\l"
	.string "amélioré depuis.\p"
	.string "On savait qu'on avait affaire à quelqu'un\n"
	.string "de spécial quand on a repéré ce DRESSEUR !$"

gTVInSearchOfTrainersText02::
	.string "SCOTT : Salut, {PLAYER}{KUN} !\n"
	.string "Alors tu es venu à cette TENTE DE COMBAT !\p"
	.string "Les gens de ces régions ont tendance à être\n"
	.string "décontractés et tranquilles.\p"
	.string "Mais tu vois, ce que je cherche, ce sont\p"
	.string "des gens avec…\n"
	.string "Comment dire…\p"
	.string "Quelqu'un débordant de désir\n"
	.string "et de volonté de gagner.\p"
	.string "S'il y avait un DRESSEUR comme ça,\p"
	.string "je…\n"
	.string "Oups ! Laisse tomber ! Continue comme ça !$"

gTVInSearchOfTrainersText03::
	.string "La combinaison de {STR_VAR_1} et\n"
	.string "de {STR_VAR_3} était divine !\p"
	.string "La vue d'eux--{STR_VAR_1} et\n"
	.string "{STR_VAR_3}--se soutenant\l"
	.string "mutuellement au cœur du combat…\p"
	.string "C'était un spectacle merveilleux à contempler !\p"
	.string "{STR_VAR_2} était la capacité que le DRESSEUR\n"
	.string "a utilisée en dernier dans notre combat.\p"
	.string "La capacité {STR_VAR_2} est le signe\n"
	.string "d'amitié de {STR_VAR_1} et {STR_VAR_3} !$"

gTVInSearchOfTrainersText04::
	.string "…J'ai perdu confiance en moi à\n"
	.string "suite de notre rencontre.\p"
	.string "Nous avons été battus avant même\n"
	.string "de pouvoir lancer une attaque.\l"
	.string "Ohhh… Snif…\p"
	.string "Malgré ça, les combats de {PLAYER}\n"
	.string "valent le coup d'œil.\p"
	.string "Je recommande aux DRESSEURS\n"
	.string "confiants de défier {PLAYER}.$"

gTVInSearchOfTrainersText05::
	.string "Il n'y a qu'une\n"
	.string "chose à dire.\l"
	.string "N'ose pas lancer une\p"
	.string "POKé BALL pendant\n"
	.string "un combat de\p"
	.string "DRESSEUR !\p"
	.string "{PLAYER}, tu le\n"
	.string "savais, n'est-ce pas ?$"

gTVInSearchOfTrainersText06::
	.string "{PLAYER} sait lire les actions\n"
	.string "de l'adversaire.\p"
	.string "Le timing d'utilisation des objets\n"
	.string "a été remarquablement efficace !$"

gTVInSearchOfTrainersText07::
	.string "Honnêtement, je pensais être\n"
	.string "plutôt bon. Même si\p"
	.string "on a perdu,\n"
	.string "c'était un bon\p"
	.string "combat. Tu es\n"
	.string "vraiment fort, {PLAYER}.$"

gTVInSearchOfTrainersText08::
	.string "Après notre combat, nous avons demandé à {PLAYER}\n"
	.string "un résumé succinct.\p"
	.string "Le DRESSEUR a répondu : « {STR_VAR_1} ».\p"
	.string "Les POKéMON de {PLAYER}, {STR_VAR_2} et\n"
	.string "{STR_VAR_3}…\l"
	.string "Et « {STR_VAR_1} »…\p"
	.string "Mmm ! C'est profond ! Il y a une signification\n"
	.string "profonde derrière cette citation !\p"
	.string "Pas étonnant--un bon DRESSEUR a\n"
	.string "de bonnes choses à dire.\p"
	.string "C'est tout pour aujourd'hui !\n"
	.string "À bientôt dans notre prochaine émission !$"

ContestLadyShow_Text_Intro::
	.string "ALIZA : Bienvenue, {PLAYER}{KUN}.\p"
	.string "C'est vraiment agréable de te revoir.\n"
	.string "Au premier regard, tu as l'air d'être\p"
	.string "quelqu'un d'autre. Tu\n"
	.string "es devenu plus fort ?\l"
	.string "Oui… Oui, tu l'as fait. Oh…\p"
	.string "Ce regard que tu me lances…\p"
	.string "D'accord, je vois que tu es déjà\n"
	.string "prêt pour ce combat.\p"
	.string "Voyons si tu peux\n"
	.string "danser à mon rythme.\p"
	.string "Montre-moi que tu es le plus fort\n"
	.string "dresseur POKéMON de HOENN !$"

ContestLadyShow_Text_Won::
	.string "MC : Excusez-moi !\n"
	.string "Merci de nous rejoindre en direct !\p"
	.string "Puis-je vous féliciter pour votre victoire ?\p"
	.string "Quel a été le facteur clé de votre\n"
	.string "superbe victoire aujourd'hui ?\p"
	.string "TOPDRESSEUSE : On a donné le meilleur\n"
	.string "aujourd'hui, mon {STR_VAR_2} et moi !\p"
	.string "Mais je suis sûre qu'on\n"
	.string "n'y serait pas arrivés\l"
	.string "sans toute l'aide reçue avant le CONCOURS !\p"
	.string "MC : As-tu quelqu'un de spécial\n"
	.string "avec qui tu aimerais partager ta joie ?\l"
	.string "Écoutons-le en direct !\p"
	.string "TOPDRESSEUSE : Hé, là-bas !\p"
	.string "{STR_VAR_3} ! Tu regardes ?\n"
	.string "On l'a fait !\l"
	.string "Merci !$"

ContestLadyShow_Text_Lost::
	.string "MC : Excusez-moi !\n"
	.string "Merci de nous rejoindre en direct !\p"
	.string "Vous devez être déçus par ce retournement\n"
	.string "de situation. Avez-vous des commentaires ?\p"
	.string "TOPDRESSEUSE : C'est déchirant…\n"
	.string "Mon {STR_VAR_2} et moi, on a fait de notre mieux…\p"
	.string "Mais j'ai l'impression d'avoir déçu tous\n"
	.string "ceux qui nous ont soutenus.\p"
	.string "MC : Je déteste le dire, mais la coloration\n"
	.string "du POKéMON laisse à désirer.\p"
	.string "TOPDRESSEUSE : {STR_VAR_3}, je suis désolée…\n"
	.string "Je ferai mieux la prochaine fois, je le jure…\l"
	.string "…Snif… Ouuaaaah !\p"
	.string "Spectateurs : Tu vois ça ?\n"
	.string "La pauvre !\p"
	.string "MC : Euh… Oh-oh…\p"
	.string "Euh… C'est tout le temps qu'on a aujourd'hui !\n"
	.string "Merci de nous avoir regardés !$"

ContestLadyShow_Text_LostBadly::
	.string "MC : Excusez-moi !\n"
	.string "Merci de nous rejoindre en direct !\p"
	.string "Comment s'est passée votre apparition au CONCOURS ?\p"
	.string "TOPDRESSEUSE : Rien n'a marché…\n"
	.string "Pour une raison inconnue, mon {STR_VAR_2}\l"
	.string "n'a attiré aucune popularité.\p"
	.string "MC : Je déteste le dire, mais la coloration\n"
	.string "du POKéMON laisse à désirer.\p"
	.string "TOPDRESSEUSE : … … … … … …\n"
	.string "…Snif… Ouuaaaah !\p"
	.string "Spectateurs : Tu vois ça ?\n"
	.string "La pauvre !\p"
	.string "MC : Euh… Oh-oh…\p"
	.string "Euh… C'est tout le temps qu'on a aujourd'hui !\n"
	.string "Merci de nous avoir regardés !$"
