VerdanturfTown_House_MapScripts::
	.byte 0

VerdanturfTown_House_EventScript_Woman1::
	msgbox VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague, MSGBOX_NPC
	end

VerdanturfTown_House_EventScript_Woman2::
	msgbox VerdanturfTown_House_Text_DefeatEliteFourInARow, MSGBOX_NPC
	end

VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague:
	.string "Loin, au fond d'ATALANOPOLIS,\n"
	.string "se trouve la LIGUE POKéMON.\p"
	.string "Les DRESSEURS qui s'y rassemblent sont\n"
	.string "tous effrayamment talentueux.$"

VerdanturfTown_House_Text_DefeatEliteFourInARow:
	.string "À la LIGUE POKéMON, je crois\n"
	.string "que les règles disent qu'il faut\l"
	.string "affronter le CONSEIL DES 4\p"
	.string "d'affilée. Si tu perds contre\n"
	.string "l'un d'eux, tu dois recommencer\l"
	.string "ton défi depuis le premier.$"

