VermilionCity_Mart_MapScripts::
	.byte 0

VermilionCity_Mart_EventScript_BirdMan::
	msgbox VermilionMart_Text_SuperNerd, MSGBOX_NPC
	end

VermilionCity_Mart_EventScript_Woman::
	msgbox VermilionMart_Text_Beauty, MSGBOX_NPC
	end

VermilionMart_Text_SuperNerd:
	.string "La TEAM ROCKET n'est plus à\n"
	.string "KANTO.\p"
	.string "Ça à lui seul me rend heureux.$"

VermilionMart_Text_Beauty:
	.string "Je pense aller faire du shopping\n"
	.string "à SAFRANIA.$"
