VermilionCity_House2_MapScripts::
	.byte 0

VermilionCity_House2_EventScript_PokefanF::
	msgbox VermilionCity_House2_Text_PokefanF, MSGBOX_NPC
	end

VermilionCity_House2_EventScript_Youngster::
	msgbox VermilionCity_House2_Text_Youngster, MSGBOX_NPC
	end

VermilionCity_House2_Text_PokefanF:
	.string "Tu connais le TRAIN\n"
	.string "MAGNÉT ?\p"
	.string "C'est un train qui va à\n"
	.string "DOUBLANVILLE en JOHTO.$"

VermilionCity_House2_Text_Youngster:
	.string "Je veux aller à SAFRANIA pour voir\n"
	.string "le TRAIN MAGNÉT.$"
