MahoganyTown_House1_MapScripts::
	.byte 0

MahoganyTown_House1_EventScript_BlackBelt::
	msgbox MahoganyRedGyaradosHouse_Text_BlackBelt, MSGBOX_NPC
	end

MahoganyTown_House1_EventScript_Teacher::
	goto_if_lt VAR_GOLDENROD_CITY_STATE, 6, MahoganyTown_House1_EventScript_TeacherBeforeAfter
	goto_if_lt VAR_GOLDENROD_CITY_STATE, 10, MahoganyTown_House1_EventScript_TeacherDuring
MahoganyTown_House1_EventScript_TeacherBeforeAfter::
	msgbox MahoganyRedGyaradosHouse_Text_Teacher MSGBOX_NPC
	end

MahoganyTown_House1_EventScript_TeacherDuring::
	msgbox MahoganyRedGyaradosHouse_Text_Teacher_Rockets, MSGBOX_NPC
	end


MahoganyRedGyaradosHouse_Text_BlackBelt:
    .string "J'ai entendu dire qu'un LÉVIATOR\n"
    .string "rouge est apparu au LAC.\p"
    .string "C'est bizarre, car même les\n"
    .string "LÉVIATOR ordinaires y sont rares…$"

MahoganyRedGyaradosHouse_Text_Teacher:
    .string "Mon émission radio préférée ?\n"
    .string "La MUSIQUE POKéMON.$"

MahoganyRedGyaradosHouse_Text_Teacher_Rockets:
    .string "J'entends des rires\n"
    .string "à la radio…\p"
    .string "C'est flippant.$"
