.set LOCALID_CIANWOOD_CHUCK, 1
.set LOCALID_CIANWOOD_CHUCK_ROCK_LEFT, 10
.set LOCALID_CIANWOOD_CHUCK_ROCK_RIGHT, 9

CianwoodGym_MapScripts::
	.byte 0


CianwoodGym_EventScript_Statue::
	lock
	goto_if_set FLAG_DEFEATED_CIANWOOD_GYM, CianwoodGym_EventScript_Statue2
	msgbox CianwoodGym_Text_GymStatue, MSGBOX_DEFAULT
	closemessage
	release
	end

CianwoodGym_EventScript_Statue2::
	msgbox CianwoodGym_Text_GymStatueCertified, MSGBOX_DEFAULT
	closemessage
	release
	end

CianwoodGym_Text_GymStatue:
	.string "ECORCEK ARENE POKéMON$"

CianwoodGym_Text_GymStatueCertified:
	.string "OLIVILLE ARENE POKéMON\p"
	.string "DRESSEURS CERTIFIÉS DE CHUCK :\n"
	.string "{PLAYER}$"

CianwoodGym_EventScript_Chuck::
	lock
	faceplayer
	goto_if_unset FLAG_HIDE_DOJO_CHUCK, CianwoodGym_EventScript_ChuckAtDojo
	goto_if_set FLAG_VISITED_VERMILION_CITY, CianwoodGym_EventScript_ChuckGotoDojo
	goto_if_set FLAG_DEFEATED_CIANWOOD_GYM, CianwoodGym_EventScript_Chuck_Defeated
	msgbox CianwoodGym_Text_ChuckIntro1, MSGBOX_DEFAULT
	applymovement LOCALID_CIANWOOD_CHUCK, CianwoodGym_Movement_ChuckLeft
	waitmovement 0
	message CianwoodGym_Text_ChuckIntro2
	applymovement LOCALID_CIANWOOD_CHUCK_ROCK_LEFT, Movement_SmashRock
	playse SE_M_ROCK_THROW
	waitmovement 0

	delay 20

	applymovement LOCALID_CIANWOOD_CHUCK, CianwoodGym_Movement_ChuckRight
	waitmovement 0
	applymovement LOCALID_CIANWOOD_CHUCK_ROCK_RIGHT, Movement_SmashRock
	playse SE_M_ROCK_THROW
	waitmovement 0
	waitmessage
	turnobject LOCALID_CIANWOOD_CHUCK, DIR_SOUTH
	msgbox CianwoodGym_Text_ChuckIntro3, MSGBOX_DEFAULT
	goto_if_set FLAG_DEFEATED_OLIVINE_CITY_GYM, CianwoodGym_EventScript_OlivineCheckMahog
	goto_if_set FLAG_DEFEATED_MAHOGANY_TOWN_GYM, CianwoodGym_EventScript_MahogCheckOlivine
	goto CianwoodGym_EventScript_Chuck_Battle1

CianwoodGym_EventScript_ChuckVictory::
	message CianwoodGym_Text_GetStormBadge
	waitmessage
	call Common_EventScript_PlayGymBadgeFanfare
	msgbox CianwoodGym_Text_ChuckBadgeSpeech, MSGBOX_DEFAULT
	setflag FLAG_BADGE05_GET
	setflag FLAG_DEFEATED_CIANWOOD_GYM
	addvar VAR_NUM_BADGES, 1
	setvar VAR_0x8008, 5
	call Common_EventScript_SetGymTrainers
	giveitem ITEM_TM_FOCUS_PUNCH
	msgbox CianwoodGym_Text_ChuckTMSpeech, MSGBOX_DEFAULT
	setvar VAR_GETFLY, 1
	setrespawn HEAL_LOCATION_CIANWOOD_CITY
	closemessage
	release
	end

CianwoodGym_EventScript_ChuckGotoDojo::
	msgbox CianwoodGym_Text_ChuckGotoDojo, MSGBOX_DEFAULT
	closemessage
	clearflag FLAG_HIDE_DOJO_CHUCK
	release
	end

CianwoodGym_Text_ChuckGotoDojo:
	.string "WAHAHAHA {PLAYER} ! Je suis en\n"
	.string "plein entraînement ! Si tu veux\p"
	.string "un autre match, viens au DOJO\n"
	.string "DE COMBAT à SAFRANIA !$"

CianwoodGym_EventScript_ChuckAtDojo::
	msgbox CianwoodGym_Text_ChuckAtDojo, MSGBOX_DEFAULT
	closemessage
	release
	end

CianwoodGym_Text_ChuckAtDojo:
	.string "Je te retrouverai au DOJO !\n"
	.string "WAHAHAHAHAHA$"

CianwoodGym_EventScript_OlivineCheckMahog::
	goto_if_set FLAG_DEFEATED_MAHOGANY_TOWN_GYM, CianwoodGym_EventScript_Chuck_Battle3
	goto CianwoodGym_EventScript_Chuck_Battle2

CianwoodGym_EventScript_MahogCheckOlivine::
	goto_if_set FLAG_DEFEATED_OLIVINE_CITY_GYM, CianwoodGym_EventScript_Chuck_Battle3
	goto CianwoodGym_EventScript_Chuck_Battle2
	
CianwoodGym_EventScript_Chuck_Battle1::
	trainerbattle_no_intro TRAINER_CHUCK_1, CianwoodGym_Text_ChuckIntro2
	goto CianwoodGym_EventScript_ChuckVictory

CianwoodGym_EventScript_Chuck_Battle2::
	trainerbattle_no_intro TRAINER_CHUCK_1_2, CianwoodGym_Text_ChuckIntro2
	goto CianwoodGym_EventScript_ChuckVictory

CianwoodGym_EventScript_Chuck_Battle3::
	trainerbattle_no_intro TRAINER_CHUCK_1_3, CianwoodGym_Text_ChuckIntro2
	goto CianwoodGym_EventScript_ChuckVictory

CianwoodGym_EventScript_Chuck_Defeated::
	msgbox CianwoodGym_Text_ChuckAfter, MSGBOX_DEFAULT
	closemessage
	release
	end

CianwoodGym_Movement_ChuckLeft:
	jump_in_place_left
	step_end

CianwoodGym_Movement_ChuckRight:
	jump_in_place_right
	step_end

CianwoodGym_Text_ChuckIntro1:
	.string "WAHAHAH !\p"
	.string "Alors tu es arrivé jusqu'ici !\p"
	.string "Laisse-moi te dire, je suis dur !\p"
	.string "Mes POKéMON écraseront des pierres et\n"
	.string "briseront des os !\p"
	.string "Regarde ça !$"

CianwoodGym_Text_ChuckIntro2:
	.string "CHUCK : Urgh !\n"
	.string "…\p"
	.string "Oooarrgh !$"

CianwoodGym_Text_ChuckIntro3:
	.string "Voilà ! Tu as peur\p"
	.string "maintenant, hein ? Quoi ?\n"
	.string "Ça n'a rien à voir\p"
	.string "avec les POKéMON ? C'est\p"
	.string "vrai ! Allez. Battons-nous !$"

CianwoodGym_Text_ChuckLoss:
	.string "Quoi ? Hein ? J'ai perdu ?\p"
	.string "Comme c'est bizarre !\n"
	.string "Tu mérites le BADGEFOUDRE !$"

CianwoodGym_Text_GetStormBadge:
	.string "{PLAYER} a reçu le BADGE CHOC.$"

CianwoodGym_Text_ChuckBadgeSpeech:
	.string "Le BADGE FORT permet à tous les POKéMON\n"
	.string "jusqu'au N70 d'obéir, même ceux échangés.\p"
	.string "Il permet aussi à tes POKéMON d'utiliser VOL\n"
	.string "quand tu n'es pas en combat.\p"
	.string "Tiens, prends ça aussi !$"

CianwoodGym_Text_ChuckTMSpeech:
	.string "C'est MITRA-POING.\p"
	.string "Il est lent mais inflige d'énormes\n"
	.string "dégâts. Ne te fais juste pas toucher avant !$"

CianwoodGym_Text_ChuckAfter:
	.string "WAHAHAH ! J'ai aimé me battre contre toi !\p"
	.string "Mais une défaite reste une défaite !\p"
	.string "À partir de maintenant, je vais m'entraîner\n"
	.string "24 heures sur 24 !$"

CianwoodGym_Text_ChuckRematch:
	.string "WAHAHAH ! CHAMPION DE JOHTO ! Tu es\p"
	.string "revenu pour en avoir plus ! Je vois\p"
	.string "que tes compétences se sont améliorées ! Prêt\p"
	.string "à voir qui est le plus fort ?$"

CianwoodGym_Text_ChuckRematchDefeat:
	.string "Hein ? Quoi ? J'ai perdu ?\n"
	.string "Encore ?$"

CianwoodGym_EventScript_Yoshi::
	trainerbattle_single TRAINER_YOSHI CianwoodGym_Text_BlackbeltYoshiSeen, CianwoodGym_Text_BlackbeltYoshiBeaten
	msgbox CianwoodGym_Text_BlackbeltYoshiAfter, MSGBOX_AUTOCLOSE
	end

CianwoodGym_Text_BlackbeltYoshiSeen:
	.string "Mon POKéMON et moi sommes liés\n"
	.string "par l'amitié.\p"
	.string "Notre lien ne sera jamais brisé !$"

CianwoodGym_Text_BlackbeltYoshiBeaten:
	.string "C'est pas possible !$"

CianwoodGym_Text_BlackbeltYoshiAfter:
	.string "Tu as l'air d'avoir un lien fort\n"
	.string "avec tes POKéMON aussi !$"

CianwoodGym_EventScript_Lao::
	trainerbattle_single TRAINER_LAO CianwoodGym_Text_BlackbeltLaoSeen, CianwoodGym_Text_BlackbeltLaoBeaten
	msgbox CianwoodGym_Text_BlackbeltLaoAfter, MSGBOX_AUTOCLOSE
	end

CianwoodGym_Text_BlackbeltLaoSeen:
	.string "Nous, artistes martiaux, ne craignons rien !$"

CianwoodGym_Text_BlackbeltLaoBeaten:
	.string "C'est choquant !$"

CianwoodGym_Text_BlackbeltLaoAfter:
	.string "Les POKéMON COMBAT ont peur\n"
	.string "des psys…$"


CianwoodGym_EventScript_Nob::
	trainerbattle_single TRAINER_NOB CianwoodGym_Text_BlackbeltNobSeen, CianwoodGym_Text_BlackbeltNobBeaten
	msgbox CianwoodGym_Text_BlackbeltNobAfter, MSGBOX_AUTOCLOSE
	end

CianwoodGym_Text_BlackbeltNobSeen:
	.string "Les mots sont inutiles.\n"
	.string "Laisse tes poings parler !$"

CianwoodGym_Text_BlackbeltNobBeaten:
	.string "…$"

CianwoodGym_Text_BlackbeltNobAfter:
	.string "J'ai perdu ! Je suis sans voix !$"

CianwoodGym_EventScript_Lung::
	trainerbattle_single TRAINER_LUNG CianwoodGym_Text_BlackbeltLungSeen, CianwoodGym_Text_BlackbeltLungBeaten
	msgbox CianwoodGym_Text_BlackbeltLungAfter, MSGBOX_AUTOCLOSE
	end

CianwoodGym_Text_BlackbeltLungSeen:
	.string "Mes poings enragés vont briser\n"
	.string "tes POKéMON !$"

CianwoodGym_Text_BlackbeltLungBeaten:
	.string "J'ai été pulvérisé !$"

CianwoodGym_Text_BlackbeltLungAfter:
	.string "Mon POKéMON a perdu…\n"
	.string "Ma… ma fierté est brisée…$"

