.set LOCALID_UNION_CAVE_LAPRAS, 6

UnionCave_B2F_MapScripts::
	.byte 0

UnionCave_B2F_EventScript_CooltrainerNick::
	trainerbattle_single TRAINER_NICK, UnionCave_B2F_Text_CooltrainermNickSeen, UnionCave_B2F_Text_CooltrainermNickBeaten
	msgbox UnionCave_B2F_Text_CooltrainermNickAfter, MSGBOX_AUTOCLOSE
	end

UnionCave_B2F_EventScript_CooltrainerfGwen::
	trainerbattle_single TRAINER_GWEN, UnionCave_B2F_Text_CooltrainerfGwenSeen, UnionCave_B2F_Text_CooltrainerfGwenBeaten
	msgbox UnionCave_B2F_Text_CooltrainerfGwenAfter, MSGBOX_AUTOCLOSE
	end

UnionCave_B2F_EventScript_CooltrainerfEmma::
	trainerbattle_single TRAINER_EMMA, UnionCave_B2F_Text_CooltrainerfEmmaSeen, UnionCave_B2F_Text_CooltrainerfEmmaBeaten
	msgbox UnionCave_B2F_Text_CooltrainerfEmmaAfter, MSGBOX_AUTOCLOSE
	end

UnionCave_B2F_EventScript_Lapras::
	lock
	faceplayer
	playmoncry SPECIES_LAPRAS, CRY_MODE_ENCOUNTER
	waitmoncry
	setwildbattle SPECIES_LAPRAS, 20
	dowildbattle
	specialvar VAR_RESULT, GetBattleOutcome
	goto_if_eq VAR_RESULT, B_OUTCOME_RAN, UnionCave_B2F_EventScript_LaprasRan
	fadescreenswapbuffers FADE_TO_BLACK
	removeobject LOCALID_UNION_CAVE_LAPRAS
	setflag FLAG_HIDE_UNION_CAVE_LAPRAS
	fadescreenswapbuffers FADE_FROM_BLACK
	release
	end

UnionCave_B2F_EventScript_LaprasRan::
	release
	end


UnionCave_B2F_EventScript_Item_Ether::
	finditem ITEM_ETHER
	end

UnionCave_B2F_EventScript_Item_HyperPotion::
	finditem ITEM_HYPER_POTION
	end

UnionCave_B2F_EventScript_Item_MaxRevive::
	finditem ITEM_MAX_REVIVE
	end

UnionCave_B2F_Text_CooltrainermNickSeen:
	.string "Il y a deux sortes de gens.\p"
	.string "Ceux qui ont du style, et ceux\n"
	.string "qui n'en ont pas.\p"
	.string "De quel genre es-tu ?$"

UnionCave_B2F_Text_CooltrainermNickBeaten:
	.string "Tu as un style éblouissant !$"

UnionCave_B2F_Text_CooltrainermNickAfter:
	.string "Ton style POKéMON est éblouissant et\n"
	.string "coloré, je l'admets.\p"
	.string "Tu ne feras que t'améliorer !$"

UnionCave_B2F_Text_CooltrainerfGwenSeen:
	.string "Je m'entraîne. Envie d'un round ?$"

UnionCave_B2F_Text_CooltrainerfGwenBeaten:
	.string "Snif, non ! Tu es trop fort pour moi.$"

UnionCave_B2F_Text_CooltrainerfGwenAfter:
	.string "Je vais m'entraîner seul jusqu'à\n"
	.string "m'améliorer.$"

UnionCave_B2F_Text_CooltrainerfEmmaSeen:
	.string "Si le POKéMON que j'aimais était là,\n"
	.string "j'irais n'importe où.\p"
	.string "C'est ce que fait un vrai Dresseur.$"

UnionCave_B2F_Text_CooltrainerfEmmaBeaten:
	.string "Je préfère câliner mes bébés que ça !$"

UnionCave_B2F_Text_CooltrainerfEmmaAfter:
	.string "Une fois par semaine, un POKéMON vient au\n"
	.string "bord de l'eau.\p"
	.string "Je voulais voir ce POKéMON…$"
