SlateportCity_SternsShipyard_2F_MapScripts::
	.byte 0

SlateportCity_SternsShipyard_2F_EventScript_Scientist1::
	msgbox SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_EventScript_Scientist2::
	msgbox SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding:
	.string "Concevoir un grand navire, c'est plus\n"
	.string "comme construire un grand bâtiment\l"
	.string "que d'assembler un véhicule de transport.$"

SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy:
	.string "Tu ne trouves pas bizarre\n"
	.string "qu'un navire en fer lourd\p"
	.string "flotte ? Il flotte grâce\n"
	.string "à un principe appelé flottabilité.$"

