@ Note: local IDs shared with scripts.inc for LilycoveCity_ContestLobby
.set LOCALID_MAN, 3
.set LOCALID_BOY, 9
.set LOCALID_TWIN, 10
.set LOCALID_POKEFAN_F, 15
.set LOCALID_EXPERT_M, 16
.set LOCALID_GIRL, 17

.set NUM_OPPONENTS, VAR_0x8009

BerryBlender_Text_WantToMakePokeblocks:
	.string "Oh ? Tu veux faire des {POKEBLOCK}S\n"
	.string "avec ce vieux briscard ?$"

BerryBlender_Text_Excellent:
	.string "Remarquable !$"

BerryBlender_Text_MadeOldTimerSad:
	.string "Oh…\n"
	.string "Tu as attristé ce vieux briscard…$"

BerryBlender_Text_KnowHowToMakePokeblocks:
	.string "Tu sais comment faire un {POKEBLOCK} ?$"

BerryBlender_Text_LetsBerryBlender:
	.string "C'est parti, alors !\p"
	.string "MIXEUR À BAIES !$"

BerryBlender_Text_ExplainBerryBlending:
	.string "D'accord, une petite explication. Oh, ne t'inquiète\p"
	.string "pas, c'est très simple. Quand la flèche\p"
	.string "du MIXEUR arrive sur ton marqueur, appuie\n"
	.string "sur le bouton A. C'est tout ce\p"
	.string "que tu as à faire. Tu\n"
	.string "verras comme c'est facile en essayant.$"

BerryBlender_Text_DontHaveAnyBerries:
	.string "Oh ?\n"
	.string "Tu n'as pas de BAIES ?\p"
	.string "Sans BAIES, tu ne peux pas faire\n"
	.string "de {POKEBLOCK}S.$"

BerryBlender_Text_CanHaveOneOfMyBerries:
	.string "Eh bien, ça ne fera pas l'affaire.\p"
	.string "Si les restes ne te dérangent pas, tu peux\n"
	.string "avoir une de mes BAIES.\p"
	.string "Comme ça, on pourrait faire des {POKEBLOCK}S\n"
	.string "ensemble avec le MIXEUR À BAIES.$"

BerryBlender_Text_DontHaveAnyBerriesToSpare:
	.string "S'il me restait des BAIES,\n"
	.string "je t'en donnerais volontiers une…\p"
	.string "Mais je n'en ai pas de trop aujourd'hui.\n"
	.string "On fera ça une autre fois.$"

BerryBlender_Text_PokeblockCaseIsFull:
	.string "Mais ta BOÎTE {POKEBLOCK} est pleine.\p"
	.string "Tu devrais utiliser des {POKEBLOCK}S\n"
	.string "avant de revenir me voir.$"

BerryBlender_Text_DontHavePokeblockCase:
	.string "Tu n'as pas de BOÎTE À {POKEBLOCK}S.\p"
	.string "Tu devrais obtenir une BOÎTE À {POKEBLOCK}S et\n"
	.string "revenir me voir.$"

BerryBlender_Text_LetsGetBlendingAlready:
	.string "Mélangeons déjà !$"

BerryBlender_Text_WhatKindOfPokeblockWillIGet:
	.string "Je me demande quel genre de {POKEBLOCK} je vais obtenir ?\n"
	.string "C'est tellement excitant !$"

BerryBlender_Text_WantToBlendPokeblocksWithUs:
	.string "Salut ! Tu voulais mixer des\n"
	.string "{POKEBLOCK}S avec nous ?$"

BerryBlender_Text_Okay:
	.string "D'accord !$"

BerryBlender_Text_ThatsTooBad:
	.string "C'est dommage…\p"
	.string "Mais on sera toujours là quand tu auras envie\n"
	.string "de mixer !$"

BerryBlender_Text_KnowHowToMakePokeblocks2:
	.string "Bien sûr, tu sais comment\n"
	.string "mixer des {POKEBLOCK}S, n'est-ce pas ?$"

BerryBlender_Text_LetsBerryBlender2:
	.string "C'est parti, alors !\p"
	.string "MIXEUR À BAIES !$"

BerryBlender_Text_ExplainBerryBlending2:
	.string "OK !\n"
	.string "Laisse-moi t'expliquer !\p"
	.string "Quand la flèche du MIXEUR en rotation\n"
	.string "atteint ton marqueur, appuie simplement\l"
	.string "sur le bouton A.\p"
	.string "C'est tout.\n"
	.string "Assez facile, tu ne trouves pas ?$"

BerryBlender_Text_DontHaveAnyBerries2:
	.string "Oh, mais attends une seconde…\n"
	.string "Tu n'as pas de BAIES.\p"
	.string "Tu ne peux pas faire de {POKEBLOCK}S sans\n"
	.string "BAIES…\p"
	.string "On sera toujours là quand tu\n"
	.string "auras des BAIES à mixer.$"

BerryBlender_Text_PokeblockCaseIsFull2:
	.string "Oh, attends une seconde…\n"
	.string "Ta BOÎTE POKéBLOCS est\p"
	.string "pleine. Utilise des\n"
	.string "POKéBLOCS et reviens.$"

BerryBlender_Text_DontHavePokeblockCase2:
	.string "Oh, attends une seconde… Tu\n"
	.string "n'as pas de BOÎTE\p"
	.string "POKéBLOCS. Tu devrais en\n"
	.string "obtenir une et revenir.$"

@ Unused
BerryBlender_Text_MakePokeblocksWithOurGroup:
	.string "Oh, bonjour ! Tu voulais faire des\n"
	.string "{POKEBLOCK}S avec notre petit groupe ?$"

BerryBlender_Text_OhDear:
	.string "Oh, non !$"

BerryBlender_Text_LeftUsInShock:
	.string "Oh, mon Dieu…\p"
	.string "Tu nous as laissés sous le choc !$"

BerryBlender_Text_KnowHowToMakePokeblocks3:
	.string "Naturellement, tu sais faire des\n"
	.string "{POKEBLOCK}S, n'est-ce pas ?$"

BerryBlender_Text_LetsBerryBlender3:
	.string "D'accord, chéri !\n"
	.string "C'est parti !\p"
	.string "Au MIXEUR !$"

BerryBlender_Text_ExplainBerryBlending3:
	.string "Oh, mon Dieu !\p"
	.string "Alors, je vais t'expliquer gentiment.\p"
	.string "Quand la flèche du MIXEUR pointe vers\n"
	.string "ton marqueur, appuie sur le bouton A.\p"
	.string "C'est tout ce qu'il faut faire.\n"
	.string "C'est simple, non ?$"

BerryBlender_Text_DontHaveAnyBerries3:
	.string "Tu n'as pas de\n"
	.string "BAIES, n'est-ce pas ?\p"
	.string "Sans BAIES, tu\n"
	.string "ne peux pas\p"
	.string "faire de {POKEBLOCK}S.\n"
	.string "Va en cueillir\l"
	.string "et reviens !$"

BerryBlender_Text_PokeblockCaseIsFull3:
	.string "Ton BOÎTE {POKEBLOCK} est pleine,\n"
	.string "à ce qu'il paraît.\p"
	.string "Tu devrais en utiliser et revenir\n"
	.string "ensuite.$"

BerryBlender_Text_DontHavePokeblockCase3:
	.string "Tu n'as pas encore de\n"
	.string "BOÎTE POKéBLOCS, apparemment. Il\p"
	.string "te faut une BOÎTE\n"
	.string "POKéBLOCS avant de revenir.$"

BerryBlender_Text_SetNewBlenderRecord:
	.string "D'accord ! Aujourd'hui sera le jour où\n"
	.string "je bats le record de vitesse du MIXEUR !$"

BerryBlender_Text_LookGoodAtBlendingJoinUs:
	.string "Oh, mon dieu !\n"
	.string "Tu as l'air doué pour le mixage.\l"
	.string "Tu veux nous rejoindre ?$"

BerryBlender_Text_MakeDeliciousPokeblocks:
	.string "Je vais faire de délicieux {POKEBLOCK}S\n"
	.string "et rendre mon POKéMON plus mignon.$"

BerryBlender_Text_SaveGameBeforeBerryBlenderLink:
	.string "Des {POKEBLOCK}S seront fabriqués avec tes amis\n"
	.string "à partir de BAIES dans le MIXEUR À BAIES.\p"
	.string "Est-ce que je peux sauvegarder avant\n"
	.string "de me connecter avec tes amis ?$"

BerryBlender_Text_SearchingForFriends:
	.string "Recherche de tes amis…\n"
	.string "… … Bouton B : Annuler$"

BerryBlender_Text_Player1Arrived:
	.string "{STR_VAR_1} est arrivé.$"

BerryBlender_Text_Player1And2Arrived:
	.string "{STR_VAR_1} et {STR_VAR_2} sont arrivés.$"

BerryBlender_Text_AllPlayersArrived:
	.string "{STR_VAR_1}, {STR_VAR_2} et\n"
	.string "{STR_VAR_3} sont arrivés.$"

BerryBlender_Text_NoBerriesLink:
	.string "Tu n'as pas de BAIES.\n"
	.string "Le MIXEUR ne peut pas être utilisé.$"

BerryBlender_Text_PokeblockCaseIsFullLink:
	.string "Ta BOÎTE A {POKEBLOCK}S est pleine.\n"
	.string "Le MIXEUR A BAIES ne peut pas être utilisé.$"

BerryBlender_Text_DontHavePokeblockCaseLink:
	.string "Tu n'as pas de BOÎTE A {POKEBLOCK}S.\n"
	.string "Le MIXEUR A BAIES ne peut pas être utilisé.$"

BerryBlender_Text_LoveMakingPokeblocks:
	.string "J'adore faire des {POKEBLOCK}S.\p"
	.string "J'ai toujours des BAIES avec moi.$"

BerryBlender_Text_MakePokeblocksUsingBerryBlender:
	.string "Si tu veux, on pourrait faire des\n"
	.string "{POKEBLOCK}S avec le\l"
	.string "MIXEUR DE BAIES.$"

BerryBlender_Text_DontHaveAnyBerriesHaveOne:
	.string "Oh ?\n"
	.string "Tu n'as pas de BAIES ?\p"
	.string "Eh bien, ça ne fera pas l'affaire, n'est-ce pas ?\p"
	.string "Si ça ne te dérange pas, tu peux\n"
	.string "avoir une de mes BAIES.$"

BerryBlender_Text_UseItToMakePokeblocksTogether:
	.string "On va s'en servir pour faire des {POKEBLOCK}S\n"
	.string "ensemble avec le MIXEUR A BAIES.$"

BerryBlender_Text_DontHaveAnyBerriesNoneToSpare:
	.string "Oh ?\n"
	.string "Tu n'as pas de BAIES ?\p"
	.string "S'il m'en restait, je t'en donnerais\n"
	.string "volontiers une…\p"
	.string "Mais je n'en ai pas de trop aujourd'hui.\n"
	.string "Désolé.$"

BerryBlender_EventScript_BerryBlender1::
	lockall
	goto_if_unset FLAG_GARBAGEFLAG, BerryBlender_EventScript_BlendMasterPresent
	setvar NUM_OPPONENTS, 1
	applymovement LOCALID_EXPERT_M, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_WantToMakePokeblocks, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryUseBerryBlender1
	goto BerryBlender_EventScript_DeclineBlender1
	end

BerryBlender_EventScript_DeclineBlender1:
	msgbox BerryBlender_Text_MadeOldTimerSad, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries, MSGBOX_DEFAULT
	dotimebasedevents
	goto_if_set FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY, BerryBlender_EventScript_Blender1NoSpareBerries
	goto BerryBlender_EventScript_Blender1GiveSpareBerry
	end

BerryBlender_EventScript_Blender1NoSpareBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerriesToSpare, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1GiveSpareBerry:
	msgbox BerryBlender_Text_CanHaveOneOfMyBerries, MSGBOX_DEFAULT
	giveitem ITEM_PECHA_BERRY
	setflag FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
	goto BerryBlender_EventScript_UseBerryBlender1
	end

BerryBlender_EventScript_UseBerryBlender1:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_StartBlender1
	goto BerryBlender_EventScript_ExplainBlending1
	end

BerryBlender_EventScript_StartBlender1:
	msgbox BerryBlender_Text_LetsBerryBlender, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending1:
	msgbox BerryBlender_Text_ExplainBerryBlending, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender1
	end

BerryBlender_EventScript_TryUseBerryBlender1:
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender1NoCase
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_Blender1CaseFull
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender1NoBerries
	msgbox BerryBlender_Text_Excellent, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_UseBerryBlender1
	end

BerryBlender_EventScript_DoBerryBlending:
	copyvar VAR_0x8004, NUM_OPPONENTS
	fadescreen FADE_TO_BLACK
	special DoBerryBlending
	waitstate
	releaseall
	end

BerryBlender_EventScript_Blender1CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BerryBlender2::
	lockall
	setvar NUM_OPPONENTS, 2
	applymovement LOCALID_TWIN, Common_Movement_FaceOriginalDirection
	applymovement LOCALID_MAN, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_WantToBlendPokeblocksWithUs, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryUseBerryBlender2
	goto BerryBlender_EventScript_DeclineBlender2
	end

BerryBlender_EventScript_DeclineBlender2:
	msgbox BerryBlender_Text_ThatsTooBad, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries2, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_UseBerryBlender2:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks2, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_StartBlender2
	goto BerryBlender_EventScript_ExplainBlending2
	end

BerryBlender_EventScript_StartBlender2:
	msgbox BerryBlender_Text_LetsBerryBlender2, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending2:
	msgbox BerryBlender_Text_ExplainBerryBlending2, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender2
	end

BerryBlender_EventScript_TryUseBerryBlender2:
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender2NoBerries
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender2NoCase
	msgbox BerryBlender_Text_Okay, MSGBOX_DEFAULT
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_UseBerryBlender2
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_Blender2CaseFull
	end

BerryBlender_EventScript_Blender2CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull2, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase2, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BerryBlender3::
	lockall
	setvar VAR_0x8008, LOCALID_POKEFAN_F
	setvar NUM_OPPONENTS, 3
	applymovement LOCALID_BOY, Common_Movement_FaceOriginalDirection
	applymovement LOCALID_GIRL, Common_Movement_FaceOriginalDirection
	applymovement VAR_0x8008, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_LookGoodAtBlendingJoinUs, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryUseBlender3
	goto BerryBlender_EventScript_DeclineBlender3
	end

BerryBlender_EventScript_DeclineBlender3:
	msgbox BerryBlender_Text_LeftUsInShock, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender3NoBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerries3, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_UseBerryBlender3:
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks3, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_StartBlender3
	goto BerryBlender_EventScript_ExplainBlending3
	end

BerryBlender_EventScript_StartBlender3:
	msgbox BerryBlender_Text_LetsBerryBlender3, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending3:
	msgbox BerryBlender_Text_ExplainBerryBlending3, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender3
	end

BerryBlender_EventScript_TryUseBlender3:
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender3NoBerries
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_Blender3NoCase
	msgbox BerryBlender_Text_OhDear, MSGBOX_DEFAULT
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_UseBerryBlender3
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_Blender3CaseFull
	end

BerryBlender_EventScript_Blender3CaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFull3, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender3NoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCase3, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterPresent:
	lockall
	setvar NUM_OPPONENTS, 1
	msgbox BerryBlender_Text_SeeMyMasteryInAction, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryBlendWithBlendMaster
	msgbox BerryBlender_Text_TooBusyNowIsee, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterNoBerries:
	msgbox BerryBlender_Text_BlendMasterNoBerries, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_TryBlendWithBlendMaster:
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_BlendMasterNoCase
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_BlendMasterNoBerries
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_BlendWithBlendMaster
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_BlendMasterCaseFull
	end

BerryBlender_EventScript_BlendWithBlendMaster:
	msgbox BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks, MSGBOX_YESNO
	call_if_eq VAR_RESULT, NO, BerryBlender_EventScript_BlendMasterExplainBlending
	msgbox BerryBlender_Text_BlendMasterLetsBerryBlender, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_BlendMasterExplainBlending:
	msgbox BerryBlender_Text_BlendMasterExplainBerryBlending, MSGBOX_DEFAULT
	return

BerryBlender_EventScript_BlendMasterNoCase:
	msgbox BerryBlender_Text_BlendMasterNoPokeblockCase, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterCaseFull:
	msgbox BerryBlender_Text_BlendMasterPokeblockCaseFull, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2Man::
	msgbox BerryBlender_Text_SetNewBlenderRecord, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender3PokefanF::
	msgbox BerryBlender_Text_LookGoodAtBlendingJoinUs, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender2Twin::
	msgbox BerryBlender_Text_MakeDeliciousPokeblocks, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender1ExpertM::
	setvar VAR_0x8008, 15
	goto BerryBlender_EventScript_ExpertMCheckGiveBerry
	end

BerryBlender_EventScript_ExpertMCheckGiveBerry:
	lock
	faceplayer
	msgbox BerryBlender_Text_LoveMakingPokeblocks, MSGBOX_DEFAULT
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, TRUE, BerryBlender_EventScript_ExpertMPlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_ExpertMNoBerries
	end

BerryBlender_EventScript_ExpertMPlayerHasBerries:
	msgbox BerryBlender_Text_MakePokeblocksUsingBerryBlender, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_ExpertMNoBerries:
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_ExpertMNoSpareBerries
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_ExpertMNoSpareBerries
	dotimebasedevents
	goto_if_set FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY, BerryBlender_EventScript_ExpertMNoSpareBerries
	goto BerryBlender_EventScript_ExpertMGiveBerry
	end

BerryBlender_EventScript_ExpertMNoSpareBerries:
	msgbox BerryBlender_Text_DontHaveAnyBerriesNoneToSpare, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_ExpertMGiveBerry:
	msgbox BerryBlender_Text_DontHaveAnyBerriesHaveOne, MSGBOX_DEFAULT
	giveitem ITEM_PECHA_BERRY
	setflag FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
	msgbox BerryBlender_Text_UseItToMakePokeblocksTogether, MSGBOX_DEFAULT
	release
	end

BerryBlender_Movement_BlendLeaderWalkInPlace:
	walk_in_place_faster_right
	step_end

BerryBlender_EventScript_BerryBlenderLink::
	lockall
	specialvar VAR_RESULT, PlayerHasBerries
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_LinkBlenderNoBerries
	checkitem ITEM_POKEBLOCK_CASE
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_LinkBlenderNoCase
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	goto_if_ne VAR_RESULT, 65535, BerryBlender_EventScript_LinkBlenderSaveGame
	goto_if_eq VAR_RESULT, 65535, BerryBlender_EventScript_LinkBlenderCaseFull
	end

BerryBlender_EventScript_LinkBlenderSaveGame:
	msgbox BerryBlender_Text_SaveGameBeforeBerryBlenderLink, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, BerryBlender_EventScript_TryDoLinkBlender
	goto_if_eq VAR_RESULT, NO, BerryBlender_EventScript_CancelLinkBlender
	end

BerryBlender_EventScript_LinkBlenderNoBerries:
	msgbox BerryBlender_Text_NoBerriesLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_TryDoLinkBlender:
	call Common_EventScript_SaveGame
	goto_if_eq VAR_RESULT, FALSE, BerryBlender_EventScript_CancelLinkBlender
	specialvar VAR_RESULT, IsWirelessAdapterConnected
	goto_if_eq VAR_RESULT, TRUE, BerryBlender_EventScript_StartDecideLinkLeader
	message BerryBlender_Text_SearchingForFriends
	waitmessage
	special TryBerryBlenderLinkup
	waitstate
	goto_if_eq VAR_RESULT, LINKUP_SUCCESS, BerryBlender_EventScript_SpawnLinkPartners
	goto_if_eq VAR_RESULT, LINKUP_SOMEONE_NOT_READY, BerryBlender_EventScript_CloseLinkNotReady
	goto_if_eq VAR_RESULT, LINKUP_DIFF_SELECTIONS, BerryBlender_EventScript_CloseLinkDifferentSelections
	goto_if_eq VAR_RESULT, LINKUP_FAILED, BerryBlender_EventScript_CloseLink
	goto_if_eq VAR_RESULT, LINKUP_CONNECTION_ERROR, BerryBlender_EventScript_LinkError
	end

BerryBlender_EventScript_TwoPlayerLink:
	msgbox BerryBlender_Text_Player1Arrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_ThreePlayerLink:
	msgbox BerryBlender_Text_Player1And2Arrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_FourPlayerLink:
	msgbox BerryBlender_Text_AllPlayersArrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_DoLinkBerryBlending:
	setvar VAR_0x8004, 0  @ number of opponents, 0 indicates Link
	fadescreen FADE_TO_BLACK
	removeobject 240 @ Unclear where these local IDs come from,
	removeobject 239 @ but presumably they'd be the 4 link players
	removeobject 238
	removeobject 237
	special DoBerryBlending
	waitstate
	releaseall
	end

BerryBlender_EventScript_CancelLinkBlender:
	releaseall
	end

BerryBlender_EventScript_LinkBlenderCaseFull:
	msgbox BerryBlender_Text_PokeblockCaseIsFullLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_LinkBlenderNoCase:
	msgbox BerryBlender_Text_DontHavePokeblockCaseLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLinkNotReady:
	special CloseLink
	msgbox Text_SomeoneIsNotReadyToLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLinkDifferentSelections:
	special CloseLink
	msgbox Text_PlayersMadeDifferentSelections, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLink:
	special CloseLink
	msgbox gText_PokeblockLinkCanceled, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_LinkError:
	special CloseLink
	msgbox Text_LinkErrorPleaseReset, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_SpawnLinkPartners:
	fadescreen FADE_TO_BLACK
	specialvar VAR_RESULT, GetLinkPartnerNames
	copyvar VAR_0x8008, VAR_RESULT
	copyvar VAR_0x8004, VAR_0x8008
	special SpawnLinkPartnerObjectEvent
	goto BerryBlender_EventScript_LinkPlayersArrived
	end

BerryBlender_EventScript_LinkPlayersArrived:
	fadescreen FADE_FROM_BLACK
	switch VAR_0x8008
	case 2, BerryBlender_EventScript_TwoPlayerLink
	case 3, BerryBlender_EventScript_ThreePlayerLink
	case 4, BerryBlender_EventScript_FourPlayerLink
	end

BerryBlender_EventScript_StartDecideLinkLeader:
	setvar VAR_0x8004, LINK_GROUP_BERRY_BLENDER
	goto BerryBlender_EventScript_DecideLinkLeader
	end

BerryBlender_EventScript_DecideLinkLeader:
	message LilycoveCity_ContestLobby_Text_PleaseDecideLinkLeader
	waitmessage
	multichoice 16, 6, MULTI_LINK_LEADER, FALSE
	switch VAR_RESULT
	case 0, BerryBlender_EventScript_TryJoinGroup
	case 1, BerryBlender_EventScript_TryLeadGroup
	case 2, BerryBlender_EventScript_CloseLink
	case MULTI_B_PRESSED, BerryBlender_EventScript_CloseLink
	end

BerryBlender_EventScript_TryLeadGroup:
	call BerryBlender_EventScript_TryBecomeLinkLeader
	goto_if_eq VAR_RESULT, LINKUP_SUCCESS, BerryBlender_EventScript_LinkLeaderDecided
	goto_if_eq VAR_RESULT, LINKUP_FAILED, BerryBlender_EventScript_DecideLinkLeader
	goto_if_eq VAR_RESULT, LINKUP_RETRY_ROLE_ASSIGN, BerryBlender_EventScript_TryLeadGroup
	release
	end

BerryBlender_EventScript_TryJoinGroup:
	call BerryBlender_EventScript_TryJoinLinkGroup
	goto_if_eq VAR_RESULT, LINKUP_SUCCESS, BerryBlender_EventScript_LinkLeaderDecided
	goto_if_eq VAR_RESULT, LINKUP_FAILED, BerryBlender_EventScript_DecideLinkLeader
	goto_if_eq VAR_RESULT, LINKUP_RETRY_ROLE_ASSIGN, BerryBlender_EventScript_TryJoinGroup
	release
	end

BerryBlender_EventScript_TryBecomeLinkLeader:
	special TryBecomeLinkLeader
	waitstate
	return

BerryBlender_EventScript_TryJoinLinkGroup:
	special TryJoinLinkGroup
	waitstate
	return

BerryBlender_EventScript_LinkLeaderDecided:
	goto BerryBlender_EventScript_SpawnLinkPartners
	end
