PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "Voyager, c'est merveilleux !\p"
	.string "Quand j'étais jeune, j'ai parcouru les mers\n"
	.string "et les montagnes !$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "Soupir…\p"
	.string "J'aimerais partir\n"
	.string "à l'aventure\p"
	.string "avec des POKéMON…\n"
	.string "Ramper dans\p"
	.string "l'herbe humide…\n"
	.string "Grimper des\p"
	.string "montagnes…\n"
	.string "Un jour,\p"
	.string "peut-être…$"

