MauvilleCity_House2_MapScripts::
	.byte 0

MauvilleCity_House2_EventScript_Woman::
	lock
	faceplayer
	goto_if_set FLAG_RECEIVED_COIN_CASE, MauvilleCity_House2_EventScript_ReceivedCoinCase
	msgbox MauvilleCity_House2_Text_BuyHarborMailAtSlateport, MSGBOX_DEFAULT
	checkitem ITEM_HARBOR_MAIL
	goto_if_eq VAR_RESULT, TRUE, MauvilleCity_House2_EventScript_AskToTradeForHarborMail
	release
	end

MauvilleCity_House2_EventScript_AskToTradeForHarborMail::
	playse SE_PIN
	applymovement VAR_LAST_TALKED, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement VAR_LAST_TALKED, Common_Movement_Delay48
	waitmovement 0
	msgbox MauvilleCity_House2_Text_TradeHarborMailForCoinCase, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, MauvilleCity_House2_EventScript_AcceptTrade
	goto_if_eq VAR_RESULT, NO, MauvilleCity_House2_EventScript_DeclineTrade
	end

MauvilleCity_House2_EventScript_AcceptTrade::
	msgbox MauvilleCity_House2_Text_IllTradeYouCoinCase, MSGBOX_DEFAULT
	removeitem ITEM_HARBOR_MAIL
	giveitem ITEM_COIN_CASE
	setflag FLAG_RECEIVED_COIN_CASE
	goto MauvilleCity_House2_EventScript_ReceivedCoinCase
	end

MauvilleCity_House2_EventScript_ReceivedCoinCase::
	msgbox MauvilleCity_House2_Text_UseCoinCaseAtGameCorner, MSGBOX_DEFAULT
	release
	end

MauvilleCity_House2_EventScript_DeclineTrade::
	msgbox MauvilleCity_House2_Text_ThatsDisappointing, MSGBOX_DEFAULT
	release
	end

MauvilleCity_House2_Text_BuyHarborMailAtSlateport:
	.string "Si j'avais un VÉLO, ce serait facile de pédaler\n"
	.string "jusqu'à POIVRESSELLE pour faire des courses.\p"
	.string "Je pourrais acheter des LETTRES PORT\n"
	.string "au MARCHÉ POKéMON de POIVRESSELLE…$"

MauvilleCity_House2_Text_TradeHarborMailForCoinCase:
	.string "Oh ! Tu as le COURRIER PORT ?\n"
	.string "Tu veux l'échanger contre une BOÎTE JETONS ?$"

MauvilleCity_House2_Text_IllTradeYouCoinCase:
	.string "Oh, je suis si heureux !\n"
	.string "OK, je t'échange un BOÎTE JETONS !$"

MauvilleCity_House2_Text_UseCoinCaseAtGameCorner:
	.string "Cette BOÎTE JETONS peut être utilisée\n"
	.string "au CASINO.$"

MauvilleCity_House2_Text_ThatsDisappointing:
	.string "Oh, c'est décevant.\p"
	.string "Une BOÎTE A JETONS est nécessaire pour le\n"
	.string "CASINO.$"

